import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Chemistry', 'class11-chemistry-ch09-hydrocarbons')
d = Deck('Chapter 9: Hydrocarbons', 'Class 11', ['class-11', 'chemistry', 'ch-9'])
d.description = 'Alkanes, conformations, alkenes, Markovnikov and peroxide effect, alkynes, benzene, aromaticity, electrophilic substitution, directive influence and carcinogenicity'
M = 'media/'
fig = lambda name: {'definitionImage': M + name + '.webp'}
img = lambda name: {'termImage': M + name + '.webp'}

# ---------------------------------------------------------------- intro
d.sec('9.0-intro')
d.basic('Define hydrocarbons.', 'Compounds of ' + T('carbon and hydrogen only'))
d.cloze('LPG = {{c1::liquified petroleum gas}}; CNG = {{c2::compressed natural gas}}; LNG = {{c3::liquified natural gas}}.')
d.basic('Source of petrol, diesel, kerosene vs coal gas?', 'Petrol, diesel, kerosene: ' + T('fractional distillation of petroleum') + '. Coal gas: ' + T('destructive distillation of coal') + '.')
d.basic('Least polluting domestic fuel per NCERT?', T('LPG') + ' (kerosene causes some pollution)')
d.basic('Three main classes of hydrocarbons?', T('Saturated') + ' (alkanes, cycloalkanes), ' + T('unsaturated') + ' (alkenes, alkynes) and ' + T('aromatic'))

# ---------------------------------------------------------------- 9.2 Alkanes
d.sec('9.2-alkanes')
d.basic('General formula of alkanes?', r'\( C_nH_{2n+2} \)')
d.basic('Structure of methane?', T('Tetrahedral') + ', C at centre; H–C–H = ' + N('109.5°'), **fig('fig_9_1_methane'))
d.basic('C–C and C–H bond lengths in alkanes?', N('154 pm') + ' and ' + N('112 pm'))
d.basic('Why were alkanes called paraffins?', 'Inert to acids, bases and other reagents: Latin ' + T('parum affinis') + ' = little affinity')
d.basic('Where is methane found?', 'In ' + T('coal mines') + ' and ' + T('marshy places'))
d.basic('Isomers of C₄H₁₀ and their b.p.?', T('n-Butane') + ' (273 K) and ' + T('isobutane / 2-methylpropane') + ' (261 K)')
d.basic('Isomers of C₅H₁₂ with b.p.?', 'n-Pentane ' + N('309 K') + ', isopentane (2-methylbutane) ' + N('301 K') + ', neopentane (2,2-dimethylpropane) ' + N('282.5 K'))
d.cloze('Number of structural isomers: C₆H₁₄ = {{c1::5}}, C₇H₁₆ = {{c2::9}}, C₁₀H₂₂ = {{c3::75}}.')
d.basic('Five isomers of C₆H₁₄? (Problem 9.1)', 'n-Hexane, 2-methylpentane, 3-methylpentane, 2,3-dimethylbutane, 2,2-dimethylbutane')
d.basic('Define 1°, 2°, 3°, 4° carbon.', 'Carbon bonded to ' + N('1, 2, 3, 4') + ' other carbons<br>Methane’s C is counted as primary<br>4° is also called neo/quaternary')
d.basic('IUPAC names of (CH₃)₃CCH₂C(CH₃)₃ and (CH₃)₂C(C₂H₅)₂? (Problem 9.3)', T('2,2,4,4-Tetramethylpentane') + '; ' + T('3,3-dimethylpentane'))
d.basic('Why is "2-ethylpentane" wrong? (Problem 9.5)', 'Longest chain has 6 C: ' + T('3-methylhexane'))
d.basic('Why is "5-ethyl-3-methylheptane" wrong?', 'Lower locant should go to the alphabetically first group: ' + T('3-ethyl-5-methylheptane'))
d.basic('Nomenclature examples (Table 9.1)?', 'Lowest sum, alphabetical order, sec ignored, isopropyl as one word', **fig('tab_9_1_nomenclature'))

d.sec('9.2.2-preparation-of-alkanes')
d.basic('What is hydrogenation, and which catalysts?', 'Adding H₂ to alkenes/alkynes over finely divided ' + T('Pt, Pd or Ni') + '.<br>Pt and Pd work at room T; Ni needs higher T and p')
d.basic('Alkane from alkyl halide with Zn and dil. HCl?', 'Reduction: CH₃Cl + H₂ → CH₄ + HCl (' + X('not fluorides') + ')')
d.basic('What is the Wurtz reaction?', 'Alkyl halide + ' + T('Na in dry ether') + ' → higher alkane (even number of C): 2CH₃Br + 2Na → C₂H₆ + 2NaBr')
d.basic('Why isn’t Wurtz used for odd-carbon alkanes? (Ex 9.25)', 'Two different halides give a ' + X('mixture') + ' (e.g. CH₃Br + C₂H₅Br → ethane + propane + butane), hard to separate')
d.basic('What is decarboxylation?', 'Sodium carboxylate + ' + T('soda lime') + ' (NaOH + CaO), heat → alkane with ' + T('one C less') + ' + Na₂CO₃')
d.basic('Salt needed to make propane by decarboxylation? (Problem 9.6)', T('Sodium butanoate') + ' (CH₃CH₂CH₂COONa)')
d.basic('Kolbe’s electrolytic method?', 'Electrolysis of Na/K carboxylate gives an alkane with ' + T('even C') + ' at the ' + T('anode') + '.<br>2CH₃COONa → C₂H₆ (+ CO₂, H₂ at cathode)')
d.basic('Why can’t methane be made by Kolbe’s method?', 'Two alkyl radicals couple, so the product has at least ' + X('2 carbons'))

d.sec('9.2.3-properties-of-alkanes')
d.cloze('At 298 K: C₁–C₄ are {{c1::gases}}, C₅–C₁₇ are {{c2::liquids}}, C₁₈ onwards are {{c3::solids}}.')
d.basic('Why do alkanes dissolve grease but not in water?', 'Non-polar: ' + T('like dissolves like'))
d.basic('Effect of branching on boiling point?', 'More branching → more ' + T('spherical') + ' → less surface contact → ' + X('lower b.p.') + ' (neopentane lowest)', **fig('tab_9_2_alkane_mp_bp'))
d.basic('Conditions for halogenation of alkanes?', 'High temperature (' + N('573–773 K') + ') or diffused sunlight/UV')
d.basic('Products of stepwise chlorination of methane?', 'CH₃Cl → CH₂Cl₂ → CHCl₃ → ' + T('CCl₄'))
d.basic('Reactivity of halogens and of H atoms in halogenation?', 'Halogens: F₂ > Cl₂ > Br₂ > I₂. H atoms: ' + T('3° > 2° > 1°') + '.')
d.basic('Why is iodination of alkanes done with HIO₃ or HNO₃?', 'It is slow and ' + T('reversible') + '; oxidant removes HI')
d.cloze('Free radical halogenation: {{c1::initiation}} (Cl₂ → 2Cl•), {{c2::propagation}} (CH₄ + Cl• → CH₃• + HCl; CH₃• + Cl₂ → CH₃Cl + Cl•), {{c3::termination}} (radicals combine).')
d.basic('Why does ethane form during chlorination of methane? (Ex 9.1)', 'Termination step: ' + T('CH₃• + CH₃• → C₂H₆'))
d.basic('Why is Cl–Cl broken first in initiation?', 'Cl–Cl is ' + T('weaker') + ' than C–C and C–H')
d.basic('ΔcH of methane and butane?', N('−890 kJ/mol') + ' and ' + N('−2875.84 kJ/mol'))
d.basic('General combustion equation of alkanes?', r'\( C_nH_{2n+2} + \frac{3n+1}{2} O_2 \rightarrow nCO_2 + (n+1)H_2O \)')
d.basic('Use of carbon black from incomplete combustion?', 'Ink, printer ink, black pigments, ' + T('fillers'))
table_card(d, 'Controlled oxidation', 'Product?', [
    ('CH₄ + O₂, Cu/523 K/100 atm', 'Methanol', False), ('CH₄ + O₂, Mo₂O₃', 'Methanal (HCHO)', False),
    ('C₂H₆ + O₂, (CH₃COO)₂Mn', 'Ethanoic acid', False), ('(CH₃)₃CH + KMnO₄', '2-Methylpropan-2-ol', False)], term='Controlled oxidation of alkanes')
d.basic('Isomerisation of n-hexane?', 'Anhydrous ' + T('AlCl₃ + HCl') + ' → 2-methylpentane and 3-methylpentane')
d.basic('What is aromatization (reforming)?', 'n-Alkanes (C ≥ 6) at ' + N('773 K') + ', 10–20 atm over oxides of V, Mo or Cr on alumina → benzene and homologues')
d.basic('Alkane that gives toluene by aromatization?', T('n-Heptane'))
d.basic('Methane + steam?', 'At 1273 K over Ni: CH₄ + H₂O → CO + ' + T('3H₂') + ' (industrial H₂)')
d.basic('What is pyrolysis (cracking)?', 'Heating higher alkanes to break into lower alkanes and alkenes; ' + T('free radical') + '; e.g. dodecane at 973 K (Pt/Pd/Ni) → heptane + pentene')

d.sec('9.2.4-conformations')
d.basic('Define conformations (rotamers).', 'Spatial arrangements interconvertible by ' + T('rotation about a C–C single bond'))
d.basic('What is torsional strain?', 'Repulsion between electron clouds of ' + T('adjacent bonds') + '; barrier ' + N('1–20 kJ/mol'))
d.basic('Eclipsed, staggered and skew conformations?', T('Eclipsed') + ': H atoms as close as possible. ' + T('Staggered') + ': as far apart as possible. ' + T('Skew') + ': anything in between.')
d.basic('Identify these projections.', T('Sawhorse') + ': (i) eclipsed, (ii) staggered', **img('fig_9_2_sawhorse'))
d.basic('Identify these projections.', T('Newman') + ': front C is a point, rear C a circle; (i) eclipsed, (ii) staggered', **img('fig_9_3_newman'))
d.basic('Angle between H’s on one carbon in Newman/sawhorse projections?', N('120°'))
d.basic('Which conformation of ethane is more stable, and by how much?', T('Staggered') + '; about ' + N('12.5 kJ/mol'))
d.basic('Why can’t ethane conformers be isolated?', 'The 12.5 kJ/mol barrier is crossed easily at room temperature: rotation is ' + T('almost free'))
d.basic('Do bond angles and lengths change between conformations?', X('No'))

# ---------------------------------------------------------------- 9.3 Alkenes
d.sec('9.3-alkenes')
d.basic('General formula of alkenes and why "olefins"?', r'\( C_nH_{2n} \)' + '; ethene forms an ' + T('oily liquid') + ' with chlorine (olefin = oil forming)')
d.cloze('C=C: one {{c1::σ}} bond (~397 kJ/mol, sp²–sp²) + one {{c2::π}} bond (~284 kJ/mol, sideways p–p); total {{c3::681}} kJ/mol; length {{c4::134 pm}}.')
d.basic('Why are alkenes attacked by electrophiles?', 'The π electrons are ' + T('loosely held') + ' and exposed')
d.basic('Orbital picture of ethene?', 'σ framework of sp² orbitals; π bond above and below the plane; H–C–H ≈ ' + N('116.6°'), **fig('fig_9_4_ethene_sigma'))
d.basic('Bond angles and lengths in ethene (Fig 9.5)?', 'C=C ' + N('134 pm') + ', C–H ' + N('110 pm') + ', H–C–C ' + N('121.7°'), **fig('fig_9_5_ethene_pi'))
d.basic('IUPAC names: CH₂=CHCH₂CH₃, CH₂=CH–CH=CH₂, CH₂=C(CH₃)₂.', T('But-1-ene, buta-1,3-diene, 2-methylprop-1-ene'))
d.basic('Structural isomers of C₄H₈ (alkenes)?', 'But-1-ene, but-2-ene, 2-methylprop-1-ene')
d.basic('Five alkene isomers of C₅H₁₀? (Problem 9.9)', 'Pent-1-ene, pent-2-ene, 2-methylbut-2-ene, 3-methylbut-1-ene, 2-methylbut-1-ene')
d.basic('Why does C=C show geometrical isomerism?', T('Restricted rotation') + ' about the double bond (like two cardboards nailed together)')
d.basic('Condition for cis–trans isomerism?', 'Each doubly bonded carbon must carry ' + T('two different') + ' groups (XYC=CXY, XYC=CXZ, XYC=CZW)')
d.basic('cis vs trans?', T('cis') + ': identical groups on the same side. ' + T('trans') + ': opposite sides.')
d.basic('Dipole moments of cis- and trans-but-2-ene?', 'cis ' + N('0.33 D') + '; trans ≈ ' + N('0') + ' (C–CH₃ dipoles cancel)')
d.basic('Which has higher m.p. and which higher b.p.: cis or trans?', 'm.p.: ' + T('trans') + ' (packs better). b.p.: ' + T('cis') + ' (more polar).')
d.basic('Which show cis–trans: (CH₃)₂C=CHC₂H₅, CH₂=CBr₂, C₆H₅CH=CHCH₃, CH₃CH=CClCH₃? (Problem 9.11)', 'Only ' + T('C₆H₅CH=CHCH₃ and CH₃CH=CClCH₃'))

d.sec('9.3.4-preparation-of-alkenes')
d.basic('What is Lindlar’s catalyst and its product?', 'Pd/C ' + T('poisoned') + ' with S compounds or quinoline; alkyne → ' + T('cis-alkene'))
d.basic('Alkyne + Na in liquid NH₃ gives?', T('trans-Alkene'))
d.basic('Does propene from propyne show geometrical isomerism?', X('No') + ': one carbon has two H atoms')
d.basic('Dehydrohalogenation?', 'Alkyl halide + ' + T('alcoholic KOH') + ', heat → alkene; a β-elimination')
d.basic('Rate order in dehydrohalogenation?', 'Halogen: ' + T('I > Br > Cl') + '. Alkyl: ' + T('3° > 2° > 1°') + '.')
d.basic('What is a vicinal dihalide, and dehalogenation?', 'Halogens on ' + T('adjacent') + ' carbons; with Zn → alkene + ZnX₂')
d.basic('Acidic dehydration of alcohols?', 'Heat with ' + T('conc. H₂SO₄') + ' → alkene + H₂O (β-elimination)')

d.sec('9.3.5-properties-of-alkenes')
d.basic('Physical state of alkenes?', 'First ' + N('3') + ' gases, next ' + N('14') + ' liquids, rest solids; ethene has a faint sweet smell')
d.basic('Test for unsaturation with bromine?', 'Reddish orange Br₂ in ' + T('CCl₄') + ' is decolourised')
d.basic('Does iodine add to alkenes normally?', X('No'))
d.basic('Reactivity order of HX towards alkenes?', T('HI > HBr > HCl'))
d.basic('Markovnikov’s rule (1869)?', 'The ' + T('negative part') + ' of the adding molecule goes to the carbon with ' + T('fewer H atoms'))
d.basic('Mechanism behind Markovnikov addition of HBr to propene?', 'H⁺ adds first to give the more stable ' + T('2° carbocation') + '; Br⁻ then attacks → 2-bromopropane')
d.basic('Mnemonic for Markovnikov? (intuition)', '"' + T('The rich get richer') + '": H goes to the carbon that already has more H')
d.basic('What is the peroxide (Kharasch) effect?', 'With ' + T('benzoyl peroxide') + ', HBr adds ' + T('anti-Markovnikov') + ' to propene → 1-bromopropane (free radical)')
d.basic('Correction: NCERT spells the discoverer "Kharash". Correct?', T('Morris S. Kharasch') + ' (with F.R. Mayo, 1933, Chicago)')
d.basic('Why no peroxide effect with HCl and HI?', 'H–Cl (430.5 kJ/mol) is ' + X('too strong') + ' to break; I• radicals combine to I₂ instead of adding')
d.basic('Why is 1-bromopropane the peroxide product?', 'Br• adds to C-1 giving the more stable ' + T('2° free radical'))
d.basic('Hex-1-ene + HBr without and with peroxide? (Problem 9.12)', 'Without: ' + T('2-bromohexane') + '. With: ' + T('1-bromohexane') + '.')
d.basic('Cold conc. H₂SO₄ with alkenes?', 'Markovnikov addition → ' + T('alkyl hydrogen sulphate'))
d.basic('Alkene + water?', 'With a few drops of conc. H₂SO₄ → ' + T('alcohol') + ' (Markovnikov)')
d.basic('What is Baeyer’s reagent and its product?', 'Cold dilute aqueous ' + T('KMnO₄') + ' → vicinal ' + T('glycols') + '; decolourisation = test for unsaturation')
d.basic('But-2-ene + acidic KMnO₄?', '2 CH₃COOH (' + T('ethanoic acid') + ')')
d.basic('What is ozonolysis?', 'O₃ adds to give an ' + T('ozonide') + ', cleaved by Zn–H₂O into carbonyls; locates the double bond')
d.basic('Alkene giving ethanal and pentan-3-one on ozonolysis? (Ex 9.5)', T('3-Ethylpent-2-ene') + ': CH₃CH=C(C₂H₅)₂')
d.basic('Alkene with 3 C–C σ, 8 C–H σ, 1 π that gives 2 mol of a 44 u aldehyde? (Ex 9.6)', T('But-2-ene') + ' (ozonolysis → 2 CH₃CHO)')
d.basic('Ozonolysis products of pent-2-ene? (Ex 9.4)', T('Ethanal + propanal'))
d.basic('Monomers and uses of polythene and polypropene?', 'Ethene → polythene (bags, sheets, toys, pipes). Propene → polypropene (' + T('milk crates, buckets') + ').')

# ---------------------------------------------------------------- 9.4 Alkynes
d.sec('9.4-alkynes')
d.basic('General formula of alkynes?', r'\( C_nH_{2n-2} \)')
d.basic('Use of ethyne (acetylene)?', T('Oxyacetylene flame') + ' for arc welding')
d.basic('Common names of propyne, but-1-yne, but-2-yne?', 'Methylacetylene, ethylacetylene, ' + T('dimethylacetylene'), **fig('tab_alkynes_names'))
d.basic('Isomers of C₅H₈ alkynes?', 'Pent-1-yne, pent-2-yne, 3-methylbut-1-yne')
d.basic('Seven alkyne isomers of C₆H₁₀? (Problem 9.13)', 'Hex-1-yne<br>Hex-2-yne<br>Hex-3-yne<br>3-Methylpent-1-yne<br>4-Methylpent-1-yne<br>4-Methylpent-2-yne<br>3,3-Dimethylbut-1-yne')
d.cloze('C≡C: one {{c1::σ}} (sp–sp) and two {{c2::π}} bonds; H–C–C = {{c3::180°}}; bond enthalpy {{c4::823}} kJ/mol; length {{c5::120 pm}}.')
d.basic('Shape of the electron cloud in ethyne?', T('Cylindrically symmetrical') + ' about the axis: linear molecule', **fig('fig_9_6_ethyne_orbitals'))
d.basic('Industrial preparation of ethyne?', 'CaCO₃ → CaO; CaO + 3C → ' + T('CaC₂') + ' + CO; CaC₂ + 2H₂O → Ca(OH)₂ + ' + T('C₂H₂'))
d.basic('Alkyne from vicinal dihalide?', 'Alcoholic KOH (→ vinyl halide), then ' + T('sodamide (NaNH₂)'))
d.basic('Physical state of alkynes?', 'First ' + N('3') + ' gases, next ' + N('8') + ' liquids, rest solids')
d.basic('Why are terminal alkyne H atoms acidic?', 'sp carbon (' + N('50% s') + ') is most electronegative, so C–H electrons are pulled in and H⁺ leaves easily')
d.basic('Acidity order: ethyne, ethene, ethane? And ethyne, propyne, but-2-yne?', T('HC≡CH > CH₂=CH₂ > CH₃CH₃') + '; ' + T('HC≡CH > CH₃C≡CH ≫ CH₃C≡CCH₃'))
d.basic('Ethyne + Na?', 'Monosodium ethynide, then disodium ethynide, + H₂')
d.basic('Distinguish but-1-yne from but-2-yne?', 'Only ' + T('but-1-yne') + ' (terminal H) reacts with Na/NaNH₂')
d.basic('Acidity order: benzene, n-hexane, ethyne? (Ex 9.18)', T('Ethyne > benzene > n-hexane') + ' (sp > sp² > sp³)')
d.basic('HBr adds to ethyne twice: final product?', T('1,1-Dibromoethane') + ' (a gem-dihalide)')
d.basic('Hydration of alkynes: conditions and product?', 'HgSO₄ + dil. H₂SO₄ at ' + N('333 K') + ' → ' + T('carbonyl compound') + ' (ethyne → ethanal)')
d.basic('What is polyacetylene and its use?', 'Linear polymer of ethyne; ' + T('conducts electricity') + ' (films as battery electrodes)')
d.basic('Cyclic polymerisation of ethyne?', 'Red hot iron tube, ' + N('873 K') + ': 3C₂H₂ → ' + T('benzene'))
d.basic('Ethanoic acid → benzene? (Problem 9.14)', 'CH₃COONa + soda lime → CH₄ → CH₃Cl → C₂H₆ (Wurtz) → C₂H₄Br₂ … → C₂H₂ → red hot Fe tube → benzene')

# ---------------------------------------------------------------- 9.5 Aromatic
d.sec('9.5-aromatic-hydrocarbons')
d.basic('Origin of "aromatic"? Benzenoid vs non-benzenoid?', 'Greek "aroma" (pleasant smell). ' + T('Benzenoid') + ': contain a benzene ring. ' + T('Non-benzenoid') + ': aromatic without one.')
d.basic('Who isolated benzene, and when?', T('Michael Faraday') + ', ' + N('1825'))
d.basic('Evidence for three double bonds in benzene?', 'Forms a ' + T('triozonide'))
d.basic('Kekulé structure (1865) and its problem?', 'Alternate single/double bonds in a ring.<br>Problem: it predicts ' + X('two 1,2-dibromobenzenes') + ' but only one exists → oscillating bonds')
d.basic('What does Kekulé’s structure fail to explain?', 'Benzene’s ' + T('unusual stability') + ' and preference for ' + T('substitution over addition'))
d.basic('C–C bond length in benzene vs C–C and C=C?', N('139 pm') + ' (all equal), between 154 pm and 133–134 pm')
d.basic('Orbital picture of benzene?', 'Six sp² carbons; unhybridised p orbitals overlap all around → two ' + T('"doughnut" π clouds') + ' above and below the ring', **fig('fig_9_7_aromatic_rings'))
d.cloze('Aromaticity (Hückel): {{c1::planar}} ring, {{c2::complete delocalisation}} of π electrons, and {{c3::(4n + 2)}} π electrons.')
d.basic('Aromatic examples with n = 1, 2?', 'n = 1 (6π): ' + E('benzene, cyclopentadienyl anion, cycloheptatrienyl cation') + '. n = 2 (10π): ' + E('naphthalene') + '.', **fig('fig_aromatic_polycyclic'))
d.basic('Laboratory preparations of benzene?', 'Cyclic polymerisation of ethyne; ' + T('decarboxylation') + ' of sodium benzoate (soda lime); ' + T('reduction of phenol') + ' by hot zinc dust')
d.basic('Commercial source of benzene?', T('Coal tar'))
d.basic('How do arenes burn?', 'With a ' + T('sooty flame'))
d.basic('Use of naphthalene balls?', 'Moth repellent; toilets')
d.cloze('Electrophilic substitution of benzene: nitration with {{c1::conc. HNO₃ + conc. H₂SO₄}}; halogenation with Cl₂ + {{c2::anhydrous FeCl₃/FeBr₃/AlCl₃}}; sulphonation with {{c3::oleum}}.')
d.basic('Friedel–Crafts alkylation and acylation?', 'Benzene + ' + T('R–X') + ' or ' + T('RCOCl/(RCO)₂O') + ' with anhydrous ' + T('AlCl₃') + ' → alkylbenzene / acylbenzene')
d.basic('Why does benzene + 1-chloropropane give isopropylbenzene?', 'The 1° carbocation ' + T('rearranges') + ' to the more stable 2° carbocation')
d.basic('Benzene + excess Cl₂ with AlCl₃?', T('Hexachlorobenzene') + ' (C₆Cl₆)')
d.cloze('SE mechanism: generation of {{c1::electrophile}} → formation of {{c2::σ-complex (arenium ion)}} → loss of {{c3::proton}} to restore aromaticity.')
d.basic('How is the nitronium ion formed?', 'H₂SO₄ protonates HNO₃ (HNO₃ acts as a ' + T('base') + '); loses water → ' + T('NO₂⁺'))
d.basic('Why is the arenium ion not aromatic?', 'One carbon becomes ' + T('sp³') + ', breaking delocalisation')
d.basic('Why does benzene prefer electrophilic substitution? (Ex 9.19)', 'The electron-rich π cloud attracts ' + T('electrophiles') + '.<br>Substitution keeps the ring aromatic (addition would lose it)')
d.basic('Addition reactions of benzene?', 'H₂/Ni, high T and p → ' + T('cyclohexane') + '. Cl₂ in UV → benzene hexachloride C₆H₆Cl₆.')
d.basic('Correction: NCERT says benzene hexachloride "is also called gammaxane". Accurate?', 'BHC is a mixture of isomers; only the ' + T('γ-isomer (lindane)') + ' is gammaxane, the insecticide')
d.basic('General combustion equation of a hydrocarbon?', r'\( C_xH_y + (x + \frac{y}{4})O_2 \rightarrow xCO_2 + \frac{y}{2}H_2O \)')

d.sec('9.5.6-directive-influence')
d.basic('What is directive influence?', 'The group ' + T('already present') + ' (not the incoming one) decides whether the new group goes o/p or m')
d.basic('Why is –OH ortho/para directing and activating?', 'Its +R effect raises electron density at ' + T('o and p') + '; outweighs its −I effect')
d.basic('Activating o/p directors?', E('–NH₂, –NHR, –NHCOCH₃, –OCH₃, –CH₃, –C₂H₅, –OH'))
d.basic('Why are halogens deactivating yet o/p directing?', 'Strong ' + T('−I') + ' lowers overall density (deactivating); ' + T('+R') + ' keeps o/p richer than m')
d.basic('Meta-directing (deactivating) groups?', E('–NO₂, –CN, –CHO, –COR, –COOH, –COOR, –SO₃H'))
d.basic('Why is –NO₂ meta directing?', 'Its −I and −R pull electrons from o and p; ' + T('meta') + ' is left comparatively richer')
d.basic('Ease of nitration: benzene, m-dinitrobenzene, toluene? (Ex 9.23)', T('Toluene > benzene > m-dinitrobenzene'))
d.basic('Benzene → p-nitrobromobenzene vs m-nitrochlorobenzene? (Ex 9.13)', 'p-Nitrobromobenzene: ' + T('brominate first') + ', then nitrate. m-Nitrochlorobenzene: ' + T('nitrate first') + ', then chlorinate.')
d.basic('Mnemonic for directors? (intuition)', '"' + T('Lone pair on the first atom → o/p') + '; a multiple bond to an electronegative atom → meta"')

d.sec('9.6-carcinogenicity')
d.basic('Which hydrocarbons are carcinogenic?', T('Benzene') + ' and polynuclear hydrocarbons with ' + T('more than two fused benzene rings'))
d.basic('How are carcinogenic PAHs formed and how do they harm?', 'Incomplete combustion of ' + T('tobacco, coal, petroleum') + '; they damage ' + T('DNA'))

# ---------------------------------------------------------------- summary
d.sec('summary')
table_card(d, 'Summary', 'Typical reaction?', [
    ('Alkanes', 'Free radical substitution', False), ('Alkenes', 'Electrophilic addition', False),
    ('Alkynes', 'Electrophilic addition; terminal H acidic', False), ('Arenes', 'Electrophilic substitution', False)], term='Hydrocarbon reactivity')
table_card(d, 'Summary', 'Product?', [
    ('Propene + HBr', '2-Bromopropane', False), ('Propene + HBr + peroxide', '1-Bromopropane', False),
    ('Alkyne + H₂ (Lindlar)', 'cis-Alkene', False), ('Alkyne + Na/liq. NH₃', 'trans-Alkene', False),
    ('Ethyne, red hot Fe, 873 K', 'Benzene', False)], term='Key hydrocarbon conversions')

n = d.write(os.path.join(OUT, 'deck.json'))
print(n, 'cards')
