import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Chemistry', 'class12-chemistry-ch04-d-and-f-block-elements')
d = Deck('Chapter 4: The d- and f-Block Elements', 'Class 12', ['class-12', 'chemistry', 'ch-4'])
d.description = 'Transition metal trends, oxidation states, E° values, magnetism, colour, catalysis, K₂Cr₂O₇, KMnO₄, lanthanoids and actinoids'
M = 'media/'
fig = lambda name: {'definitionImage': M + name + '.webp'}
img = lambda name: {'termImage': M + name + '.webp'}
F47 = (1001, 732)

# ---------------------------------------------------------------- intro
d.sec('4.0-introduction')
d.basic('Which groups form the d-block?', 'Groups ' + N('3–12') + '; d orbitals progressively filled in four long periods')
d.cloze('Transition series: 3d = {{c1::Sc to Zn}}; 4d = {{c2::Y to Cd}}; 5d = {{c3::La and Hf to Hg}}; 6d = {{c4::Ac and Rf to Cn}}.')
d.cloze('Inner transition series: 4f = {{c1::Ce to Lu}} ({{c2::lanthanoids}}); 5f = {{c3::Th to Lr}} ({{c4::actinoids}}).')
d.basic('IUPAC definition of transition metals?', 'Metals with an ' + T('incomplete d subshell') + ' in the neutral atom or in their ions')
d.basic('Why are Zn, Cd, Hg not regarded as transition metals?', 'Full ' + X('d¹⁰') + ' configuration in the ground state and in their common oxidation states')
d.basic('Why are Zn, Cd, Hg still studied with transition metals?', 'They are the ' + T('end members') + ' of the 3d, 4d and 5d series')
d.basic('Origin of the name "transition"?', 'Their properties were ' + T('transitional') + ' between s- and p-block elements')
d.basic('Inner transition elements used for nuclear energy?', E('Th, Pa, U'))

# ---------------------------------------------------------------- 4.2 configuration
d.sec('4.2-electronic-configurations')
d.basic('General outer configuration of d-block elements?', r'\( (n-1)d^{1-10} \, ns^{1-2} \)' + '; exception ' + X('Pd: 4d¹⁰5s⁰'))
d.basic('Why are there many exceptions in d-block configurations?', 'Very ' + T('small energy gap') + ' between (n−1)d and ns, and extra stability of ' + T('half-filled and full') + ' sets')
d.basic('Configurations of Cr and Cu?', 'Cr: ' + T('3d⁵4s¹') + ' (not 3d⁴4s²); Cu: ' + T('3d¹⁰4s¹') + ' (not 3d⁹4s²)')
d.basic('3d series configurations at a glance?', 'Table 4.1 (1st series)', **fig('tab_4_1a_3d_series'))
d.basic('4d, 5d and 6d series configurations?', 'Table 4.1 (2nd–4th series)', **fig('tab_4_1b_4d_5d_6d'))
d.basic('General configuration of Zn, Cd, Hg, Cn?', r'\( (n-1)d^{10} \, ns^2 \)')
d.basic('Sc is a transition element but Zn is not. Why? (Example 4.1)', 'Sc has ' + T('3d¹') + ' (incomplete); Zn has 3d¹⁰ in atom and ion')
d.basic('Silver is 4d¹⁰5s¹. Why is it a transition element? (Intext 4.1)', 'In its ' + T('+2 state') + ' (Ag²⁺, AgF₂) it has an incomplete 4d⁹ subshell')
d.basic('Why are d orbitals so influential in chemistry?', 'They ' + T('protrude to the periphery') + ' of the atom, so they feel and affect surroundings most')
d.basic('Characteristic properties caused by partly filled d orbitals?', 'Variable oxidation states, ' + T('coloured ions') + ', complex formation, catalysis, paramagnetism')
d.basic('Horizontal vs group similarities in d-block?', 'Greater similarity along a ' + T('horizontal row') + ' than in non-transition elements; some group similarity too')

# ---------------------------------------------------------------- 4.3 physical
d.sec('4.3.1-physical-properties')
d.basic('Typical physical properties of transition metals?', 'High tensile strength, ductility, malleability, ' + T('high thermal and electrical conductivity') + ', metallic lustre')
d.basic('Which transition metals lack typical metallic structures?', X('Zn, Cd, Hg and Mn'))
d.basic('Lattice structures of transition metals?', 'bcc, hcp, ccp (X = typical metal structure)', **fig('tab_lattice_structures'))
d.basic('Why are melting points of transition metals high?', 'Many ' + T('(n−1)d + ns electrons') + ' take part in metallic bonding')
d.basic('Trend of melting points along a series?', 'Rise to a maximum at ' + T('d⁵') + ', then fall; anomalies at ' + X('Mn and Tc'), **fig('fig_4_1_melting_points'))
d.basic('Why is enthalpy of atomisation maximum in the middle of each series?', T('One unpaired electron per d orbital') + ' favours strong interatomic interaction', **fig('fig_4_2_atomisation'))
d.basic('Metals with very high ΔaH° tend to be…?', T('Noble') + ' in their reactions (ΔaH° affects E°)')
d.basic('Why is metal–metal bonding more common in heavy transition metals?', '4d and 5d metals have ' + T('greater ΔaH°') + ' than 3d metals')
d.basic('Why do transition elements have high enthalpies of atomisation? (Example 4.2)', 'Many ' + T('unpaired electrons') + ' give stronger interatomic bonding')
d.basic('Why is ΔaH° of Zn the lowest (126 kJ/mol) in 3d? (Intext 4.2)', 'No unpaired d electrons: 3d¹⁰ does ' + X('not take part') + ' in metallic bonding')

d.sec('4.3.2-atomic-and-ionic-sizes')
d.basic('Trend of ionic radius (same charge) across a series?', T('Decreases') + ' gradually: each new d electron shields poorly as nuclear charge rises')
d.basic('Radii of 3d vs 4d vs 5d series?', '4d > 3d, but 5d ≈ 4d', **fig('fig_4_3_atomic_radii'))
d.basic('What is lanthanoid contraction?', 'Regular decrease in radii from La to Lu as ' + T('4f is filled') + ' before 5d')
d.basic('Cause of lanthanoid contraction?', T('Imperfect shielding') + ' of one 4f electron by another (poorer than d shielding)')
d.basic('Main consequence of lanthanoid contraction for 4d/5d?', 'Similar radii, e.g. ' + T('Zr 160 pm, Hf 159 pm') + ': very similar properties')
d.basic('Trend in density from Ti to Cu, and why?', T('Increases') + ': radius decreases while atomic mass increases')

d.sec('4.3.3-ionisation-enthalpies')
d.basic('Trend of ionisation enthalpy across a transition series?', 'Increases, but ' + T('less steeply') + ' than across a period of non-transition elements')
d.basic('Which electrons are lost first when d-block atoms ionise?', T('ns') + ' electrons before (n−1)d')
d.basic('Why does IE rise only slightly across 3d?', '3d electrons ' + T('shield the 4s') + ' electrons fairly well from the rising nuclear charge')
d.basic('Breaks in the steady rise of 2nd and 3rd IE occur at?', 'Mn²⁺ (2nd IE of Mn) and Fe³⁺ (3rd IE of Fe): both form ' + T('d⁵'))
d.basic('Three factors in ionisation enthalpy?', 'Attraction to nucleus, ' + T('electron–electron repulsion') + ', ' + T('exchange energy'))
d.basic('What is exchange energy?', 'Stabilisation ∝ number of ' + T('pairs of parallel spins') + ' in degenerate orbitals (Hund’s rule)')
d.basic('Why is 2nd IE of Mn lower than that of Cr?', 'Cr⁺ is d⁵ (stable, losing it costs exchange energy); Mn⁺ is 3d⁵4s¹ and loses the 4s electron')
d.basic('Why is 3rd IE of Fe lower than that of Mn?', 'Fe²⁺ (d⁶) → Fe³⁺ gives stable ' + T('d⁵') + '; Mn²⁺ (d⁵) would lose it')
d.basic('Why are 2nd IE of Cr and Cu unusually high?', 'Cr⁺ and Cu⁺ have stable ' + T('d⁵ and d¹⁰') + ' configurations')
d.basic('Why is 2nd IE of Zn low?', 'Removing the second ' + T('4s') + ' electron leaves stable d¹⁰')
d.basic('Why are oxidation states above +2 hard for Cu, Ni, Zn?', 'Their ' + X('third ionisation enthalpies') + ' are very high')
d.basic('Values: ΔiH (I, II, III) and other data for 3d metals?', 'Table 4.2', **fig('tab_4_2_first_series'))

d.sec('4.3.4-oxidation-states')
d.basic('Which 3d elements show the most oxidation states? (Intext 4.3)', T('Mn') + ': all from +2 to +7 (4s² 3d⁵: most electrons to lose or share)', **fig('tab_4_3_oxidation_states'))
d.basic('Why fewer oxidation states at the ends of the series?', 'Too ' + X('few electrons') + ' (Sc, Ti) or too ' + X('many d electrons') + ', fewer orbitals to share (Cu, Zn)')
d.basic('Maximum stable oxidation state up to Mn equals?', 'Sum of ' + T('s + d electrons') + ': TiO₂, VO₂⁺, CrO₄²⁻, MnO₄⁻')
d.basic('Typical oxidation states after Mn?', 'Fe(II, III), Co(II, III), Ni(II), Cu(I, II), Zn(II)')
d.basic('Transition vs p-block variability of oxidation states?', 'Transition: differ by ' + T('one') + ' (V²⁺, V³⁺, V⁴⁺, V⁵⁺). Non-transition: usually by ' + T('two') + '.')
d.basic('Heavier members in d-block groups favour which states?', T('Higher') + ' states (opposite of the p-block inert pair effect): Mo(VI), W(VI) more stable than Cr(VI)')
d.basic('Consequence: Cr₂O₇²⁻ vs MoO₃ and WO₃ as oxidants?', 'Dichromate is a ' + T('strong oxidant') + '; MoO₃ and WO₃ are ' + X('not'))
d.basic('When are low (zero) oxidation states found? Examples?', 'With ligands that are ' + T('π-acceptors') + ' as well as σ-donors: ' + E('Ni(CO)₄, Fe(CO)₅') + ' (oxidation state 0)')
d.basic('Transition element with no variable oxidation state? (Example 4.3)', T('Scandium') + ' (only +3)')

d.sec('4.3.5-m2-m-electrode-potentials')
d.basic('Why is E°(Cu²⁺/Cu) positive (+0.34 V)? (Intext 4.4)', 'High energy for Cu(s) → Cu²⁺(aq) (high ΔaH° + IE) is ' + X('not balanced') + ' by its hydration enthalpy')
d.basic('Consequence of E°(Cu²⁺/Cu) > 0?', 'Cu cannot liberate H₂ from acids; only ' + T('oxidising acids') + ' (HNO₃, hot conc. H₂SO₄) attack it')
d.basic('General trend of E°(M²⁺/M) across 3d, and cause?', 'Becomes ' + T('less negative') + ': sum of 1st and 2nd IE increases', **fig('fig_4_4_electrode_potentials'))
d.basic('Which metals have E°(M²⁺/M) more negative than the trend, and why?', T('Mn') + ' (stable d⁵ Mn²⁺), ' + T('Zn') + ' (stable d¹⁰ Zn²⁺), ' + T('Ni') + ' (most negative ΔhydH°)')
d.basic('Thermochemical data behind E° values?', 'ΔaH°, ΔiH°₁, ΔiH°₂, ΔhydH°', **fig('tab_4_4_thermochemical'))
d.basic('Why is Cr²⁺ reducing but Mn³⁺ oxidising (both d⁴)? (Example 4.4)', 'Cr²⁺ → Cr³⁺ gives ' + T('d³ (half-filled t₂g)') + '; Mn³⁺ → Mn²⁺ gives ' + T('d⁵ (half-filled)'))
d.basic('Why is E°(M²⁺/M) irregular for V, Cr, Mn…? (Example 4.6)', 'Irregular IE (ΔiH₁ + ΔiH₂) and low ' + T('sublimation enthalpies') + ' of Mn and V')

d.sec('4.3.6-m3-m2-electrode-potentials')
d.basic('Why is E°(Sc³⁺/Sc²⁺) low?', 'Sc³⁺ has a ' + T('noble gas configuration') + ' (very stable)')
d.basic('Why is E°(Zn³⁺/Zn²⁺) highest?', 'It would remove an electron from stable ' + X('d¹⁰') + ' Zn²⁺')
d.basic('Why is E°(Mn³⁺/Mn²⁺) high but E°(Fe³⁺/Fe²⁺) comparatively low?', 'Mn²⁺ is d⁵ (stable, resists oxidation); Fe³⁺ is d⁵ (stable, easy to form)')
d.basic('Why is E°(Mn³⁺/Mn²⁺) much more positive than Cr or Fe? (Example 4.7)', 'Very large ' + T('3rd IE of Mn') + ' (d⁵ → d⁴); so Mn(III) is of little importance')
d.basic('Why is E°(V³⁺/V²⁺) comparatively low?', 'V²⁺ is stable: ' + T('half-filled t₂g') + ' (d³)')
d.basic('Why are Mn²⁺ compounds more stable to oxidation than Fe²⁺? (Ex 4.2)', 'Mn²⁺ is already d⁵; Fe²⁺ (d⁶) gains stability by becoming Fe³⁺ (d⁵)')

d.sec('4.3.7-higher-oxidation-states')
d.basic('Highest oxidation states in 3d halides?', T('TiX₄, VF₅, CrF₆') + '; Mn(VII) only as MnO₃F', **fig('tab_4_5_halides'))
d.basic('Why does fluorine stabilise the highest oxidation states?', 'Higher ' + T('lattice energy') + ' (CoF₃) or higher ' + T('bond enthalpy') + ' of covalent compounds (VF₅, CrF₆)')
d.basic('Beyond Mn, which metals form trihalides?', 'Only ' + T('FeX₃ and CoF₃'))
d.basic('What happens to V(V) halides other than VF₅?', 'Hydrolyse to ' + T('oxohalides VOX₃'))
d.basic('Why is CuI₂ unknown?', 'Cu²⁺ ' + X('oxidises I⁻') + ': 2Cu²⁺ + 4I⁻ → Cu₂I₂ + I₂')
d.basic('Why is Cu⁺ unstable in water? (Intext 4.9)', 'It ' + T('disproportionates') + ' (2Cu⁺ → Cu²⁺ + Cu): much more negative ΔhydH° of Cu²⁺ outweighs the 2nd IE')
d.basic('Highest oxidation state in oxides equals?', 'The ' + T('group number') + ', reached in Sc₂O₃ to Mn₂O₇', **fig('tab_4_6_oxides'))
d.basic('Higher oxide of iron than Fe₂O₃?', X('None') + '; ferrate(VI) FeO₄²⁻ forms in alkali but decomposes to Fe₂O₃ + O₂')
d.basic('Oxocations that stabilise high states?', T('VO₂⁺') + ' (V), ' + T('VO²⁺') + ' (IV), ' + T('TiO²⁺') + ' (Ti IV)')
d.basic('Oxygen or fluorine: which stabilises higher states? Evidence?', T('Oxygen') + ': highest Mn fluoride is MnF₄, highest oxide Mn₂O₇')
d.basic('Why is oxygen better than fluorine here?', 'O forms ' + T('multiple bonds') + ' to metals')
d.basic('Structure of Mn₂O₇?', 'Covalent; each Mn ' + T('tetrahedral') + ', with an Mn–O–Mn bridge')
d.basic('Why is the highest oxidation state shown only in oxides or fluorides? (Intext 4.6)', 'O and F are small and highly electronegative; O also forms multiple bonds')
d.basic('Why does oxidising power rise VO₂⁺ < Cr₂O₇²⁻ < MnO₄⁻? (Example 4.5)', 'Increasing ' + T('stability of the lower species') + ' they are reduced to')

d.sec('4.3.8-chemical-reactivity')
d.basic('Which 3d metal is not oxidised by 1 M H⁺?', T('Copper'))
d.basic('Why are Ti and V passive to dilute non-oxidising acids?', 'The reaction is ' + X('kinetically slow') + ' even though feasible')
d.basic('Strongest oxidising agents among M³⁺ in water?', T('Mn³⁺ and Co³⁺'))
d.basic('Which M²⁺ ions are strong reducing agents?', T('Ti²⁺, V²⁺, Cr²⁺') + ': liberate H₂ from dilute acid (2Cr²⁺ + 2H⁺ → 2Cr³⁺ + H₂)')
d.basic('Stronger reducing agent: Cr²⁺ or Fe²⁺? (Intext 4.7)', T('Cr²⁺') + ': E°(Cr³⁺/Cr²⁺) = −0.41 V vs +0.77 V for Fe; Cr³⁺ is d³ (stable)')

# ---------------------------------------------------------------- magnetic, colour
d.sec('4.3.9-magnetic-properties')
d.basic('Diamagnetic vs paramagnetic vs ferromagnetic?', 'Dia: ' + X('repelled') + '. Para: ' + T('attracted') + '. Ferro: attracted very strongly (extreme paramagnetism).')
d.basic('Origin of paramagnetism?', T('Unpaired electrons') + ' (spin + orbital angular momentum)')
d.basic('Why only spin counts for 3d ions?', 'Orbital contribution is effectively ' + T('quenched'))
d.basic('Spin-only formula?', r'\( \mu = \sqrt{n(n+2)} \)' + ' BM (n = unpaired electrons)')
d.basic('Spin-only μ for n = 1, 2, 3, 4, 5?', N('1.73, 2.84, 3.87, 4.90, 5.92') + ' BM')
d.basic('Magnetic moment of divalent ion of Z = 25? (Example 4.8)', 'Mn²⁺, d⁵, n = 5: ' + N('5.92 BM'))
d.basic('Spin-only μ of M²⁺, Z = 27? (Intext 4.8)', 'Co²⁺, d⁷, n = 3: ' + N('3.87 BM'))
d.basic('Calculated and observed moments for 3d ions?', 'Table 4.7', **fig('tab_4_7_magnetic_moments'))
d.basic('Correction: Table 4.7 lists "Tl²⁺" as 3d². Which ion?', T('Ti²⁺') + ' (titanium); Tl is thallium, a p-block element')
d.basic('Trick: unpaired electrons from μ = 4.90 BM?', 'Solve n(n+2) = 24 → ' + N('n = 4'))

d.sec('4.3.10-coloured-ions')
d.basic('Why are transition metal ions coloured?', T('d–d transition') + ': an electron excited to a higher d orbital absorbs visible light.<br>We see the ' + T('complementary colour'))
d.basic('What decides the frequency absorbed?', 'The nature of the ' + T('ligand'))
d.basic('Identify the ions (left to right).', T('V⁴⁺, V³⁺, Mn²⁺, Fe³⁺, Co²⁺, Ni²⁺, Cu²⁺'), **img('fig_4_5_ion_colours'))
d.cloze('Aquated ion colours: Ti³⁺ {{c1::purple}}; V⁴⁺ {{c2::blue}}; V³⁺ {{c3::green}}; V²⁺ {{c4::violet}}; Cr³⁺ {{c5::violet}}.')
d.cloze('Aquated ion colours: Mn³⁺ {{c1::violet}}; Cr²⁺ {{c2::blue}}; Mn²⁺ {{c3::pink}}; Fe³⁺ {{c4::yellow}}; Fe²⁺ {{c5::green}}.')
d.cloze('Aquated ion colours: Co³⁺ {{c1::blue}}; Co²⁺ {{c2::pink}}; Ni²⁺ {{c3::green}}; Cu²⁺ {{c4::blue}}.')
d.basic('Which aquated 3d ions are colourless, and why?', T('Sc³⁺, Ti⁴⁺ (d⁰), Zn²⁺ (d¹⁰)') + ': no d–d transition possible', **fig('tab_4_8_ion_colours'))

d.sec('4.3.11-complexes-catalysis-interstitials-alloys')
d.basic('Why do transition metals form many complexes?', T('Small ion size') + ', high ionic charge, available ' + T('d orbitals'))
d.basic('Examples of complex ions (NCERT)?', E('[Fe(CN)₆]³⁻, [Fe(CN)₆]⁴⁻, [Cu(NH₃)₄]²⁺, [PtCl₄]²⁻'))
d.basic('Why are transition metals good catalysts?', 'Multiple ' + T('oxidation states') + ' and complex formation<br>Surface bonding raises reactant concentration and weakens bonds')
d.cloze('Catalysts: {{c1::V₂O₅}} in the Contact process; {{c2::finely divided Fe}} in Haber process; {{c3::Ni}} in catalytic hydrogenation.')
d.basic('How does Fe³⁺ catalyse 2I⁻ + S₂O₈²⁻ → I₂ + 2SO₄²⁻?', '2Fe³⁺ + 2I⁻ → 2Fe²⁺ + I₂; then 2Fe²⁺ + S₂O₈²⁻ → 2Fe³⁺ + 2SO₄²⁻ (Fe cycles between states)')
d.basic('Intuition: why does Fe³⁺ speed up I⁻ + S₂O₈²⁻?', 'Both reactants are ' + T('anions') + ' that repel; Fe³⁺ lets each react separately with a cation instead')
d.basic('What are interstitial compounds? Examples?', 'Small atoms (H, C, N) trapped in metal lattices; non-stoichiometric: ' + E('TiC, Mn₄N, Fe₃H, VH₀.₅₆, TiH₁.₇'))
d.cloze('Interstitial compounds: {{c1::higher}} melting points than pure metals; very {{c2::hard}} (some borides near diamond); retain {{c3::metallic conductivity}}; chemically {{c4::inert}}.')
d.basic('Condition for alloy (solid solution) formation?', 'Metallic radii within about ' + N('15%') + ' of each other')
d.basic('Metals used to make steels and stainless steel?', E('Cr, V, W, Mo, Mn'))
d.basic('Alloys of transition with non-transition metals?', T('Brass') + ' (Cu–Zn), ' + T('bronze') + ' (Cu–Sn)')

# ---------------------------------------------------------------- 4.4 compounds
d.sec('4.4-oxides-and-oxoanions')
d.basic('What is disproportionation? Example (Example 4.9)?', 'One oxidation state converts into a higher and a lower one: 3MnO₄²⁻ + 4H⁺ → 2MnO₄⁻ + MnO₂ + 2H₂O')
d.basic('Which 3d metals form ionic MO oxides?', 'All ' + X('except Sc'))
d.basic('Effect of increasing oxidation number on oxides?', 'Ionic character ' + X('decreases') + ', acidic character increases')
d.basic('Nature of Mn₂O₇? What acids from Mn₂O₇ and CrO₃?', 'Covalent ' + T('green oil') + '; Mn₂O₇ → HMnO₄; CrO₃ → H₂CrO₄ and H₂Cr₂O₇')
d.basic('Nature of V₂O₃, V₂O₄, V₂O₅?', 'Basic → less basic → ' + T('amphoteric') + ' (V₂O₅ mainly acidic; gives VO₄³⁻ and VO₂⁺ salts)')
d.basic('Nature of CrO and Cr₂O₃?', 'CrO ' + T('basic') + '; Cr₂O₃ ' + T('amphoteric'))

d.sec('4.4-potassium-dichromate')
d.basic('Uses of K₂Cr₂O₇?', T('Leather industry') + ', oxidant for azo compounds, ' + T('primary standard') + ' in volumetric analysis')
d.basic('Ore of chromium and first step to dichromate?', T('Chromite FeCr₂O₄') + ' fused with Na₂CO₃ (or K₂CO₃) in free air')
d.cloze('Step 1: 4FeCr₂O₄ + 8Na₂CO₃ + 7O₂ → {{c1::8Na₂CrO₄}} + 2Fe₂O₃ + 8CO₂ (yellow chromate).')
d.cloze('Step 2: 2Na₂CrO₄ + 2H⁺ → {{c1::Na₂Cr₂O₇}} + 2Na⁺ + H₂O (orange; acidify with {{c2::H₂SO₄}}).')
d.cloze('Step 3: Na₂Cr₂O₇ + 2KCl → {{c1::K₂Cr₂O₇}} + 2NaCl.')
d.basic('Why convert Na₂Cr₂O₇ to K₂Cr₂O₇?', 'K₂Cr₂O₇ is ' + T('less soluble') + ' and crystallises out; a non-hygroscopic primary standard')
d.basic('Chromate ⇌ dichromate: effect of pH? (Ex 4.14)', 'Acid: 2CrO₄²⁻ (yellow) + 2H⁺ → Cr₂O₇²⁻ (orange). ' + T('Raising pH') + ' (OH⁻) turns dichromate back to yellow chromate.')
d.basic('Oxidation state of Cr in chromate and dichromate?', T('+6 in both'))
d.basic('Structures of CrO₄²⁻ and Cr₂O₇²⁻?', 'Chromate ' + T('tetrahedral') + '; dichromate = two tetrahedra sharing ' + T('one corner') + ', Cr–O–Cr ' + N('126°'), **fig('fig_chromate_dichromate'))
d.basic('Dichromate half-reaction in acid and E°?', 'Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O; ' + N('1.33 V'))
d.basic('Why is Na₂Cr₂O₇ used in organic chemistry?', 'Greater ' + T('solubility') + ' in water')
d.cloze('Acidified dichromate oxidises I⁻ to {{c1::I₂}}, H₂S to {{c2::S}}, Sn²⁺ to {{c3::Sn⁴⁺}}, Fe²⁺ to {{c4::Fe³⁺}}.')
d.basic('Ionic equation: dichromate + Fe²⁺ (acid)?', 'Cr₂O₇²⁻ + 14H⁺ + 6Fe²⁺ → 2Cr³⁺ + 6Fe³⁺ + 7H₂O')

d.sec('4.4-potassium-permanganate')
d.basic('Preparation of KMnO₄ (lab fusion)?', 'Fuse MnO₂ with KOH and an oxidant (KNO₃ / air) → dark green ' + T('K₂MnO₄') + '<br>It disproportionates in neutral/acid solution')
d.cloze('2MnO₂ + 4KOH + O₂ → {{c1::2K₂MnO₄}} + 2H₂O; then 3MnO₄²⁻ + 4H⁺ → {{c2::2MnO₄⁻ + MnO₂}} + 2H₂O.')
d.basic('Commercial preparation of KMnO₄?', 'Alkaline oxidative fusion of MnO₂ → manganate, then ' + T('electrolytic oxidation') + ' in alkaline solution → permanganate')
d.basic('Lab preparation from Mn²⁺?', 'Oxidise with ' + T('peroxodisulphate') + ': 2Mn²⁺ + 5S₂O₈²⁻ + 8H₂O → 2MnO₄⁻ + 10SO₄²⁻ + 16H⁺')
d.basic('Physical properties of KMnO₄?', 'Dark purple (almost black) crystals, isostructural with ' + T('KClO₄') + '; solubility 6.4 g/100 g water at 293 K')
d.basic('Effect of heating KMnO₄ (513 K)?', '2KMnO₄ → K₂MnO₄ + MnO₂ + ' + T('O₂'))
d.basic('Shapes and magnetism of manganate and permanganate?', 'Both ' + T('tetrahedral') + '. Green MnO₄²⁻: ' + T('paramagnetic') + ' (1 unpaired e⁻). Purple MnO₄⁻: ' + T('diamagnetic') + '.')
d.basic('Identify: shape, ion and colour.', 'Tetrahedral ' + T('manganate ion MnO₄²⁻') + ', green', **img('fig_manganate'))
d.basic('Identify: shape, ion and colour.', 'Tetrahedral ' + T('permanganate ion MnO₄⁻') + ', purple', **img('fig_permanganate'))
d.basic('π-bonding in MnO₄⁻?', 'Overlap of O ' + T('p orbitals') + ' with Mn ' + T('d orbitals'))
d.basic('Unusual physical properties of KMnO₄?', 'Intense colour and diamagnetism with weak temperature-dependent paramagnetism (explained by MO theory)')
d.basic('Correction/insight: why is MnO₄⁻ intensely coloured though Mn(VII) is d⁰?', 'Not d–d: it is ' + T('charge transfer') + ' (O → Mn electron transfer absorbs strongly)')
d.cloze('E° of MnO₄⁻ reductions: to MnO₄²⁻ {{c1::+0.56 V}}; to MnO₂ (acid) {{c2::+1.69 V}}; to Mn²⁺ {{c3::+1.52 V}}.')
d.basic('Why doesn’t KMnO₄ oxidise water though E° says it should?', 'Kinetically ' + X('very slow') + ' unless Mn²⁺ is present or temperature is raised')
d.basic('Acidic KMnO₄: n-factor and product?', T('Mn²⁺') + ' (5 electrons)')
d.basic('Neutral/faintly alkaline KMnO₄: product?', T('MnO₂') + ' (3 electrons)')
d.cloze('Acidic MnO₄⁻ oxidises: I⁻ → {{c1::I₂}}; Fe²⁺ (green) → {{c2::Fe³⁺ (yellow)}}; oxalate (333 K) → {{c3::CO₂}}; H₂S → {{c4::S}}; SO₃²⁻ → {{c5::SO₄²⁻}}; NO₂⁻ → {{c6::NO₃⁻}}.')
d.basic('Ionic equation: permanganate + Fe²⁺ (acid)?', '5Fe²⁺ + MnO₄⁻ + 8H⁺ → Mn²⁺ + 4H₂O + 5Fe³⁺')
d.basic('Ionic equation: permanganate + oxalate (acid)?', '5C₂O₄²⁻ + 2MnO₄⁻ + 16H⁺ → 2Mn²⁺ + 8H₂O + 10CO₂')
d.cloze('Neutral/alkaline MnO₄⁻ oxidises: I⁻ → {{c1::IO₃⁻}}; S₂O₃²⁻ → {{c2::SO₄²⁻}}; Mn²⁺ → {{c3::MnO₂}} (catalysed by ZnSO₄/ZnO).')
d.basic('Why aren’t permanganate titrations done in HCl?', 'HCl is ' + X('oxidised to Cl₂') + ', using up extra KMnO₄')
d.basic('Uses of KMnO₄?', 'Analytical oxidant, preparative organic chemistry, ' + T('bleaching') + ' wool/cotton/silk, decolourising oils')

# ---------------------------------------------------------------- 4.5 Lanthanoids
d.sec('4.5-lanthanoids')
d.basic('Why is La included with lanthanoids (symbol Ln)?', 'La ' + T('closely resembles') + ' them')
d.basic('Lanthanoids vs actinoids: overall chemistry?', 'Lanthanoids: very similar, essentially one stable state (+3). Actinoids: ' + T('many oxidation states') + ' and radioactive: more complex.')
d.basic('General configuration of lanthanoid atoms and Ln³⁺?', 'Atoms: 6s² with variable 4f (and 5d). Ln³⁺: ' + T('4fⁿ') + ' (n = 1–14).', **fig('tab_4_9_lanthanoids'))
d.basic('Which lanthanoids have a 5d¹ electron in the atom?', T('La, Ce, Gd, Lu') + ' (Gd: 4f⁷5d¹6s², Lu: 4f¹⁴5d¹6s²)')
d.basic('Is the decrease in radii smoother for atoms or Ln³⁺ ions?', T('Ln³⁺ ions') + ' (regular); atomic radii are less regular', **fig('fig_4_6_lanthanoid_radii'))
d.basic('Why are Zr and Hf found together and hard to separate?', 'Lanthanoid contraction gives almost ' + T('identical radii') + ' (160 vs 159 pm)')
d.basic('Most common oxidation state of lanthanoids?', T('+3'))
d.basic('Correction: NCERT says "La(II) and Ln(III) compounds are predominant." Right?', T('La(III)') + ' and Ln(III): La shows only +3; "II" is a typo')
d.basic('Why do some lanthanoids show +2 or +4?', 'Extra stability of ' + T('empty, half-filled or filled') + ' f subshell')
d.basic('Ce(IV): why formed, and why a useful reagent?', 'Noble gas configuration (4f⁰)<br>E°(Ce⁴⁺/Ce³⁺) = ' + N('+1.74 V') + ' could oxidise water but ' + T('reacts slowly') + '<br>A good analytical oxidant')
d.basic('Lanthanoid well known for +4? (Example 4.10)', T('Cerium (Z = 58)'))
d.basic('Which lanthanoids show +4 only in oxides (MO₂)?', E('Pr, Nd, Tb, Dy'))
d.basic('Eu²⁺ and Yb²⁺: configurations and behaviour?', 'Eu²⁺ ' + T('f⁷') + ', Yb²⁺ ' + T('f¹⁴') + ': both ' + T('reducing agents') + ' (revert to +3)')
d.basic('Tb(IV): configuration and behaviour?', 'Half-filled ' + T('f⁷') + '; an ' + T('oxidant'))
d.basic('Which lanthanoid behaves like Eu (both +2 and +3)?', T('Samarium'))

d.sec('4.5.4-lanthanoid-properties')
d.basic('Physical nature of lanthanoids?', 'Silvery white ' + T('soft') + ' metals; tarnish rapidly in air; hardness rises with Z (Sm steel-hard)')
d.basic('Melting range of lanthanoids? Exception?', N('1000–1200 K') + '; Sm melts at ' + N('1623 K'))
d.basic('Which lanthanoids break smooth density trends?', X('Eu and Yb') + ' (sometimes Sm and Tm)')
d.basic('Why are Ln³⁺ ions coloured? Which are colourless?', 'f electrons (f–f transitions, narrow bands). ' + X('La³⁺ and Lu³⁺') + ' colourless.')
d.basic('Which lanthanoid ions are diamagnetic?', 'f⁰ (' + T('La³⁺, Ce⁴⁺') + ') and f¹⁴ (' + T('Yb²⁺, Lu³⁺') + '); the rest paramagnetic')
d.basic('First and second IE of lanthanoids?', '~' + N('600') + ' and ~' + N('1200 kJ/mol') + ' (comparable with calcium)')
d.basic('Lanthanoids with abnormally low 3rd IE?', T('La, Gd, Lu') + ' (f⁰, f⁷, f¹⁴ after ionisation)')
d.basic('Chemical behaviour along the series?', 'Early members reactive like ' + T('calcium') + '; later ones more like ' + T('aluminium'))
d.basic('E°(Ln³⁺/Ln) range?', N('−2.2 to −2.4 V') + ' (Eu −2.0 V)')
d.basic('Carbides formed by lanthanoids?', T('Ln₃C, Ln₂C₃, LnC₂') + ' on heating with carbon')
d.basic('Nature of Ln(OH)₃?', 'Definite compounds (not hydrated oxides), ' + T('basic') + ' like alkaline earth hydroxides')
d.occlusion('Figure 4.7 · Chemical reactions of the lanthanoids', M + 'fig_4_7_lanthanoid_reactions.webp', F47, [
    ('Ln₂O₃', wbox(222, 18, 315, 55, F47), True), ('H₂', wbox(744, 20, 782, 57, F47), True), ('LnX₃', wbox(906, 392, 990, 429, F47), True),
    ('Ln(OH)₃ + H₂', wbox(710, 673, 918, 710, F47), True), ('LnC₂', wbox(481, 673, 561, 710, F47), True), ('LnN', wbox(169, 670, 239, 705, F47), True),
    ('Ln₂S₃', wbox(11, 395, 99, 432, F47), True)])
d.basic('Best single use of lanthanoids?', 'Alloy ' + T('steels') + ' for plates and pipes')
d.basic('Composition and use of mischmetall?', '~' + N('95%') + ' lanthanoid + ~' + N('5%') + ' Fe + traces of S, C, Ca, Al; in Mg alloys for ' + T('bullets, shells, lighter flints'))
d.basic('Other uses of lanthanoid oxides?', 'Mixed oxides: catalysts in ' + T('petroleum cracking') + '; some as ' + T('phosphors') + ' in TV screens')

# ---------------------------------------------------------------- 4.6 Actinoids
d.sec('4.6-actinoids')
d.basic('Actinoid half-lives?', 'Early members long; later ones from a day down to ' + N('3 min') + ' (Lr); latter made only in nanogram amounts')
d.basic('General configuration of actinoids?', T('7s²') + ' with variable 5f and 6d occupancy', **fig('tab_4_10_actinoids'))
d.basic('Configurations of Am and Cm?', 'Am [Rn]5f⁷7s²; Cm [Rn]' + T('5f⁷6d¹7s²'))
d.basic('Why do 5f electrons bond more than 4f?', '5f orbitals are ' + T('less buried') + ' (less shielded inside the core)')
d.basic('Why is actinoid contraction greater per element than lanthanoid? (Intext 4.10)', T('Poorer shielding by 5f') + ' electrons')
d.basic('Why do actinoids show many oxidation states?', '5f, 6d and 7s levels have ' + T('comparable energies'), **fig('tab_4_11_actinoid_ox_states'))
d.basic('Maximum oxidation states of Th, Pa, U, Np?', N('+4, +5, +6, +7') + '; then decrease')
d.basic('Common oxidation state of actinoids?', T('+3') + ' (more compounds in +3 than +4); +3 and +4 ions tend to ' + T('hydrolyse'))
d.basic('Actinoid metals: appearance and structures?', 'All ' + T('silvery') + '; variety of structures (irregular metallic radii)')
d.basic('Reactions of actinoids with water, HCl, HNO₃, alkali?', 'Boiling water: oxide + hydride. HCl attacks all. HNO₃: ' + X('slight') + ' (protective oxide). Alkalis: ' + X('no action') + '.')
d.basic('Actinoid vs lanthanoid magnetic behaviour?', 'Actinoids more complex; lanthanoids have ' + T('higher') + ' susceptibility values')
d.basic('Why are IEs of early actinoids lower than early lanthanoids?', '5f penetrates less, is ' + T('more shielded') + ', so outer electrons are held less firmly')
d.basic('Why is lanthanoid contraction more important than actinoid contraction?', 'Chemistry of elements after actinoids is ' + X('much less known'))

# ---------------------------------------------------------------- 4.7 Applications
d.sec('4.7-applications')
d.basic('Metals added to steel?', E('Cr, Mn, Ni') + ' (plus carbon)')
d.basic('Correction: NCERT says "TiO for the pigment industry." Actual pigment?', T('TiO₂') + ' (titanium dioxide, white pigment)')
d.basic('MnO₂ and Zn, Ni/Cd used in?', T('Battery') + ' industry (MnO₂ in dry cells)')
d.basic('Why are group 11 elements called coinage metals? Modern UK coins?', 'Cu, Ag, Au; UK "copper" coins are ' + T('copper-coated steel') + ', "silver" coins ' + T('Cu/Ni alloy'))
d.cloze('Catalysts: {{c1::V₂O₅}} oxidises SO₂ (H₂SO₄); {{c2::TiCl₄ + Al(CH₃)₃}} = Ziegler catalyst (polythene); {{c3::Fe}} in Haber process; {{c4::Ni}} hydrogenates fats.')
d.basic('NCERT: Wacker process oxidises ethyne to ethanal with PdCl₂. Correction?', 'Wacker process oxidises ' + T('ethene (ethylene)') + ' to ethanal: CH₂=CH₂ + ½O₂ → CH₃CHO (PdCl₂/CuCl₂)')
d.basic('Uses of Ni complexes and AgBr?', 'Ni complexes: polymerisation of alkynes, benzene formation. AgBr: ' + T('photography') + ' (light-sensitive).')

# ---------------------------------------------------------------- summary
d.sec('summary')
table_card(d, 'Compare', 'Lanthanoids vs actinoids?', [
    ('Orbitals filled', '4f  |  5f', False), ('Common state', '+3  |  +3, many higher (to +7)', False),
    ('Radioactivity', 'Only Pm  |  All', False), ('Contraction per element', 'Smaller  |  Larger (poorer 5f shielding)', False),
    ('f electrons in bonding', 'Buried, little  |  More involved', False)], term='Lanthanoids vs actinoids')
table_card(d, 'Summary', 'Reason?', [
    ('Paramagnetism', 'Unpaired d electrons', False), ('Colour', 'd–d transitions in visible region', False),
    ('Catalysis', 'Variable oxidation states, complexes', False), ('High ΔaH°', 'Many unpaired electrons in bonding', False),
    ('Zr ≈ Hf', 'Lanthanoid contraction', False)], term='Transition metal properties and their causes')

n = d.write(os.path.join(OUT, 'deck.json'))
print(n, 'cards')
