import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch12-limits-and-derivatives')
d = Deck('Chapter 12: Limits and Derivatives', 'Class 11', ['class-11', 'mathematics', 'ch-12'])
d.description = 'Intuitive derivative, limits and their algebra, standard trigonometric limits, first principle, derivative rules and standard derivatives.'
b = d.basic

# ---------------------------------------------------------------- 12.2 Intuitive idea
d.sec('12.2-intuitive-derivative')
b('What is calculus mainly about?', 'The study of how the value of a function ' + T('changes') + ' as the point in its domain changes: rates of change (derivatives) and accumulation (integrals)')
b('Average velocity between t = t₁ and t = t₂?', r'\(\dfrac{s(t_2) - s(t_1)}{t_2 - t_1}\)' + ': distance travelled ÷ time taken')
b('A body falls s = 4.9t² metres. Average velocity over the first 2 seconds?', 's(2) = 19.6 m, so 19.6/2 = ' + N('9.8 m/s'))
b('Same body: average velocity between t = 1 and t = 2?', '(19.6 − 4.9)/1 = ' + N('14.7 m/s'))
b('Table: average velocity from t₁ to 2 for t₁ = 1.5, 1.8, 1.9, 1.99: what do the values do?', '17.15, 18.62, 19.11, 19.551: ' + T('increasing towards 19.6') + '. From the right (t = 2.5, 2.1, 2.01): 22.05, 20.58, 19.649: ' + T('decreasing towards 19.6'))
sm.secant_to_tangent(d)
b('Instantaneous velocity at t = 2 for s = 4.9t²?', N('19.6 m/s') + ' (between 19.551 and 19.649 from the tables). It is the derivative s′(2) = the slope of the tangent at t = 2')
b('Why must the left and right sequences of average velocities meet at one value?', 'Physically the body has a single velocity at t = 2. Both sequences squeeze the same number, the ' + T('limit') + ' of the average velocity as the interval → 0')

# ---------------------------------------------------------------- 12.3 Limits
d.sec('12.3-limits')
b('Explain lim x→a f(x) = l in words.', 'As x gets close to a (but ≠ a), f(x) gets close to l. l is the value f ' + T('“should take” at a') + ' judging from nearby values')
b('Left-hand and right-hand limits?', 'LHL: lim x→a⁻ f(x) (values with x < a). RHL: lim x→a⁺ f(x) (x > a). The limit exists ' + T('iff LHL = RHL') + ' (finite)')
sm.left_right_limits(d)
b('Can the limit exist at a point where f is undefined? Can f(a) and the limit differ?', E('Yes to both') + '. e.g. f(x) = (x² − 4)/(x − 2) has limit 4 at 2 but f(2) is undefined; a function can also be defined at a with f(a) ≠ limit')
sm.hole_limit(d)
b('Illustration: f(x) = x² as x → 0; g(x) = |x| as x → 0?', N('0') + ' and ' + N('0') + ' (g(0) is not needed)')
b('Illustration 1–3: lim x→5 (x + 10); lim x→1 x³; lim x→2 3x.', N('15') + ', ' + N('1') + ', ' + N('6') + ': for polynomials the limit equals the value at the point')
b('Limit of a constant function f(x) = c at any a?', N('c'))
b('Illustration 5: lim x→1 (x² + x)?', N('2') + ' (substitute; polynomial)')
b('Illustration 6–7: lim x→π/2 sin x; lim x→0 (x + cos x).', N('1') + ' and ' + N('1'))
b('Illustration 8: f(x) = 1/x² for x > 0 as x → 0. What happens?', 'f(x) grows without bound: lim = ' + N('+∞') + ' (the limit does not exist as a finite number; not needed further in this course)')
b('Illustration 9: f(x) = x − 2 for x < 0, 0 at x = 0, x + 2 for x > 0. lim at 0?', 'LHL = −2, RHL = +2 → ' + N('does not exist') + ' (even though f(0) = 0 is defined)')
b('Illustration 10: f(x) = x + 2 for x ≠ 1 and f(1) = 3?', 'x + 2 → 3 at 1: ' + N('lim = 3') + ' (here it equals f(1); in general they may differ)')
b('Theorem 1: algebra of limits (both limits exist).', T('lim (f ± g) = lim f ± lim g') + ';  ' + T('lim (fg) = lim f · lim g') + ';  ' + T('lim (f/g) = lim f / lim g') + ' if lim g ≠ 0;  lim (λf) = λ lim f')
b('Limit of a polynomial at a?', 'Just substitute: ' + T('lim x→a p(x) = p(a)'))
b('Limit of a rational function g/h at a when h(a) ≠ 0? When h(a) = 0?', 'h(a) ≠ 0: substitute, g(a)/h(a). h(a) = 0 and g(a) ≠ 0: ' + X('limit does not exist') + ' (infinite). h(a) = 0 and g(a) = 0: cancel the common factor (x − a) and try again')
b('Indeterminate form: what is 0/0 and what do you do?', 'Substituting gives 0/0, which tells nothing. ' + T('Factorise (or rationalise) and cancel the factor (x − a)') + ' that causes it (allowed because x ≠ a)')
b('Example 1: lim x→1 (x³ − x² + 1); lim x→3 (x(x + 1)); lim x→−1 (1 + x + x² + … + x¹⁰).', N('1') + ';  ' + N('12') + ';  ' + N('1') + ' (alternating 1 − 1 + 1 … eleven terms)')
b('Example 2: lim x→1 (x² + 1)/(x + 100).', '2/101 → ' + N('2/101'))
b('Example 2: lim x→2 (x³ − 4x² + 4x)/(x² − 4)?', 'x(x − 2)²/((x − 2)(x + 2)) = x(x − 2)/(x + 2) → ' + N('0'))
b('Example 2 (iii): lim x→2 (x³ − 4x² + 4x)/(x² − 5x + 6).', 'x(x − 2)²/((x − 2)(x − 3)) = x(x − 2)/(x − 3): as x → 2 this → 0. But lim x→3 has a zero denominator with non-zero numerator: ' + X('does not exist'))
b('Ex 12.1 Q1–4: lim x→3 (x + 3); lim x→π (x − 22/7); lim r→1 πr²; lim x→4 (4x + 3)/(x − 2).', N('6') + ';  ' + N('π − 22/7') + ';  ' + N('π') + ';  ' + N('19/2'))
b('Ex 12.1 Q5–7: lim x→−1 (x¹⁰ + x⁵ + 1)/(x − 1); lim x→0 ((x + 1)⁵ − 1)/x; lim x→2 (3x² − x − 10)/(x² − 4).', N('−1/2') + ';  ' + N('5') + ';  (3x + 5)(x − 2)/((x − 2)(x + 2)) → ' + N('11/4'))
b('Ex 12.1 Q8–9: lim x→3 (x⁴ − 81)/(2x² − 5x − 3); lim x→0 (ax + b)/(cx + 1).', '(x − 3)(x + 3)(x² + 9)/((x − 3)(2x + 1)) → ' + N('108/7') + ';  ' + N('b'))
b('Ex 12.1 Q10–12: lim z→1 (z^(1/3) − 1)/(z^(1/6) − 1); lim x→1 (ax² + bx + c)/(cx² + bx + a) (a + b + c ≠ 0); lim x→−2 (1/x + 1/2)/(x + 2).', 'Put w = z^(1/6): (w² − 1)/(w − 1) = w + 1 → ' + N('2') + ';  ' + N('1') + ';  (2 + x)/(2x(x + 2)) → ' + N('−1/4'))

d.sec('12.3.2-standard-power-limit')
b('Theorem 2: lim x→a (xⁿ − aⁿ)/(x − a) = ?', N('n · aⁿ⁻¹') + ' (true for any rational n and a > 0). It is the derivative of xⁿ at a')
b('Proof idea of lim (xⁿ − aⁿ)/(x − a) = n aⁿ⁻¹.', 'xⁿ − aⁿ = (x − a)(xⁿ⁻¹ + xⁿ⁻²a + … + aⁿ⁻¹); cancel (x − a); substitute x = a: n terms each aⁿ⁻¹')
b('Example 3: lim x→1 (x¹⁵ − 1)/(x¹⁰ − 1) and lim x→0 (√(1 + x) − 1)/x.', '15/10 = ' + N('3/2') + ';  put y = 1 + x: (y^(1/2) − 1)/(y − 1) → ' + N('1/2'))
b('Trick: lim x→a (xᵐ − aᵐ)/(xⁿ − aⁿ)?', N('(m/n) aᵐ⁻ⁿ') + ': divide numerator and denominator by (x − a)')

# ---------------------------------------------------------------- 12.4 Trig limits
d.sec('12.4-trig-limits')
b('Theorem 3: if f(x) ≤ g(x) near a and both limits exist?', N('lim f ≤ lim g') + ' (limits preserve non-strict inequalities; strict inequalities may become equalities)')
b('Sandwich (squeeze) theorem?', 'If f(x) ≤ g(x) ≤ h(x) and ' + T('lim f = lim h = l') + ', then lim g = l')
b('Key inequality for 0 < x < π/2?', T('cos x < sin x / x < 1') + ', from sin x < x < tan x (unit-circle areas)')
sm.sandwich_circle(d)
b('Theorem 5: lim x→0 sin x / x and lim x→0 (1 − cos x)/x?', N('1') + ' (x in radians!) and ' + N('0'))
sm.sinc_graph(d)
b('Why must x be in radians in lim sin x / x = 1?', 'The arc length equals the angle only when the angle is in radians (arc = radius × angle). In degrees the limit would be π/180')
b('Proof of lim (1 − cos x)/x = 0.', '1 − cos x = 2 sin²(x/2): (2 sin²(x/2))/x = sin(x/2) · (sin(x/2)/(x/2)) → 0 · 1 = 0')
b('Example 4: lim x→0 sin 4x / sin 2x and lim x→0 tan x / x.', '(sin 4x/4x)(2x/sin 2x)·2 = ' + N('2') + ';  (sin x/x)(1/cos x) → ' + N('1'))
b('Method: limits of the type sin(ax)/(bx).', 'Rewrite so the argument of sine equals the denominator: sin(ax)/(bx) = (a/b)·(sin ax/ax) → ' + T('a/b'))
b('Ex 12.1 Q13–14: lim x→0 sin ax/bx; lim x→0 sin ax/sin bx (a, b ≠ 0).', N('a/b') + ' and ' + N('a/b'))
b('Ex 12.1 Q15–16: lim x→π sin(π − x)/(π(π − x)); lim x→0 cos x/(π − x).', 'Put y = π − x: sin y/(πy) → ' + N('1/π') + ';  1/π → ' + N('1/π'))
b('Ex 12.1 Q17–18: lim x→0 (cos 2x − 1)/(cos x − 1); lim x→0 (ax + x cos x)/(b sin x).', '(−2 sin²x)/(−2 sin²(x/2)) → ' + N('4') + ';  (a + cos x)/(b · sin x/x) → ' + N('(a + 1)/b'))
b('Ex 12.1 Q19–20: lim x→0 x sec x; lim x→0 (sin ax + bx)/(ax + sin bx) (a, b, a + b ≠ 0).', N('0') + ';  divide by x: (a + b)/(a + b) = ' + N('1'))
b('Ex 12.1 Q21–22: lim x→0 (cosec x − cot x); lim x→π/2 tan 2x/(x − π/2).', '(1 − cos x)/sin x → ' + N('0') + ';  put y = x − π/2: tan 2x = tan(2y + π) = tan 2y, so tan 2y / y → ' + N('2'))
b('Ex 12.1 Q24–27: f = x² − 1 (x ≤ 1), −x² − 1 (x > 1) at 1; |x|/x at 0; x/|x| at 0; |x| − 5 at 5.', 'At 1: LHL 0, RHL −2 → ' + N('does not exist') + '. |x|/x: LHL −1, RHL 1 → ' + N('does not exist') + '. Same for x/|x|. At 5: |5| − 5 = ' + N('0'))
b('Ex 12.1 Q28: f = a + bx (x < 1), 4 (x = 1), b − ax (x > 1), and lim f = f(1). Find a, b.', 'LHL a + b = 4 and RHL b − a = 4 → ' + N('a = 0, b = 4'))
b('Ex 12.1 Q23: f(x) = 2x + 3 (x ≤ 0), 3(x + 1) (x > 0). Find lim x→0 f and lim x→1 f.', 'At 0: LHL = 3, RHL = 3 → ' + N('3') + '. At 1: 3(1 + 1) = ' + N('6'))
b('Method: piecewise functions and limits.', 'At the break point compute the ' + T('left limit from the left formula and the right limit from the right formula') + '; compare. Away from the break point just substitute')
b('General rule (from the text) for evaluating lim f(x)/g(x) when f(a) = g(a) = 0?', 'Factor out the vanishing factor from both: f = (x − a)ᵏ f₁ and g = (x − a)ˡ g₁ (f₁(a), g₁(a) ≠ 0), cancel the common power, and substitute')

# ---------------------------------------------------------------- Standard limits beyond text
d.sec('12.z-standard-limits')
table_card(d, 'Standard limits · JEE', 'Value of each limit (x → 0 unless stated).', [
    ('sin x / x', '1', False), ('tan x / x', '1', False), ('(1 − cos x) / x²', '1/2', False), ('(eˣ − 1) / x', '1', False),
    ('(aˣ − 1) / x', 'ln a', False), ('ln(1 + x) / x', '1', False), ('(1 + x)^(1/x)', 'e', False), ('(1 + 1/x)ˣ as x → ∞', 'e', False)], term='Standard limits table')
b('Limits at infinity: lim x→∞ (3x² + 2)/(x² + 5)?', 'Divide by the highest power: ' + N('3') + '. Rule: degree top < bottom → 0; equal → ratio of leading coefficients; top > bottom → ±∞')
b('lim x→∞ (√(x² + x) − x)?', 'Rationalise: x/(√(x² + x) + x) → ' + N('1/2'))
b('Indeterminate forms (list)?', T('0/0, ∞/∞, 0·∞, ∞ − ∞, 1^∞, 0⁰, ∞⁰') + '. Each needs rewriting; 1^∞ uses (1 + u)^(1/u) → e')
b('L’Hôpital’s rule (JEE, beyond the syllabus core)?', 'If f(a) = g(a) = 0 (or both ∞) and f′, g′ exist: ' + T('lim f/g = lim f′/g′') + ' (repeat if still 0/0). Faster than factorising for hard limits, but not allowed as a “proof” in board answers')
b('lim x→0 (1 − cos x)/x² = ?', '2 sin²(x/2)/x² = (1/2)(sin(x/2)/(x/2))² → ' + N('1/2'))
b('lim x→0 (√(1 + x) − 1)/x by rationalising?', 'x/(x(√(1 + x) + 1)) → ' + N('1/2'))
b('lim x→0 (tan x − sin x)/x³?', 'tan x (1 − cos x)/x³ → 1 · 1/2 = ' + N('1/2'))
b('lim x→0 (1 + 2x)^(1/x)?', 'Write (1 + 2x)^(1/x) = [(1 + 2x)^(1/(2x))]² → ' + N('e²'))

# ---------------------------------------------------------------- 12.5 Derivatives
d.sec('12.5-derivatives')
b('Definition of the derivative of f at a?', r"\(f^{\prime}(a) = \lim_{h 	o 0}\dfrac{f(a + h) - f(a)}{h}\)" + ', provided the limit exists')
b('Definition of the derivative function (first principle)?', r'\(f^{\prime}(x) = \lim_{h \to 0}\dfrac{f(x + h) - f(x)}{h}\)' + '. Notations: f′(x), dy/dx, D f(x), (d/dx) f(x)')
b('Geometric meaning of f′(a)?', 'The ' + T('slope of the tangent') + ' to y = f(x) at (a, f(a)): the slope of the chord PQ tends to the slope of the tangent as Q → P')
sm.parabola_tangents(d)
b('Tangent line at (a, f(a))? Normal?', T('y − f(a) = f′(a)(x − a)') + '; normal (⟂): y − f(a) = −(1/f′(a))(x − a)')
b('Example 5: derivative of 3x at x = 2.', 'lim (3(2 + h) − 6)/h = ' + N('3'))
b('Example 6: f(x) = 2x² + 3x − 5. Find f′(−1) and prove f′(0) + 3f′(−1) = 0.', 'f′(x) = 4x + 3: f′(−1) = −1, f′(0) = 3, and 3 + 3(−1) = ' + N('0') + ' ✓')
b('Example 7: derivative of sin x at 0?', 'lim sin h/h = ' + N('1') + ' (= cos 0)')
b('Example 8 and 11: derivative of a constant function?', N('0') + ': f(x + h) − f(x) = 0 for every h')
b('Example 9: derivative of 10x from first principle.', 'lim (10(x + h) − 10x)/h = ' + N('10'))
b('Example 10: derivative of x² from first principle.', 'lim ((x + h)² − x²)/h = lim (2x + h) = ' + N('2x'))
b('Example 12: derivative of 1/x from first principle.', 'lim (1/(x + h) − 1/x)/h = lim (−1)/(x(x + h)) = ' + N('−1/x²'))
b('Ex 12.2 Q1–3: derivative of x² − 2 at x = 10; of x at x = 1; of 99x at x = 100.', N('20') + ';  ' + N('1') + ';  ' + N('99'))
b('Ex 12.2 Q4: first principle: x³ − 27; (x − 1)(x − 2); 1/x²; (x + 1)/(x − 1).', N('3x²') + ';  ' + N('2x − 3') + ';  ' + N('−2/x³') + ';  ' + N('−2/(x − 1)²'))
b('Ex 12.2 Q10: derivative of cos x from first principle.', '(cos(x + h) − cos x)/h = (−2 sin(x + h/2) sin(h/2))/h → ' + N('−sin x'))
b('Example 19: derivative of 1/(x − 2)... first principle (function undefined at 2).', N('−1/(x − 2)²') + ', undefined at x = 2 as well: the derivative exists only where the function is defined and smooth')
b('Trap: is f′(a) the same as (f(a))′?', X('No') + '. (f(a))′ is the derivative of a constant = 0. f′(a) means: differentiate f first, then substitute a')

d.sec('12.5.1-algebra-of-derivatives')
table_card(d, '12.5.1 · Rules of differentiation', 'State each rule (u = f(x), v = g(x)).', [
    ('Sum / difference', '(u ± v)′ = u′ ± v′', False), ('Constant multiple', '(cu)′ = c u′', False), ('Product (Leibnitz) rule', '(uv)′ = u′v + uv′', False),
    ('Quotient rule', '(u/v)′ = (u′v − uv′)/v²', False), ('Power rule', '(xⁿ)′ = n xⁿ⁻¹', False), ('Chain rule (beyond the text)', '(f(g(x)))′ = f′(g(x)) · g′(x)', False)], term='Rules of differentiation')
b('Memory aid for the quotient rule?', T('“low d-high minus high d-low, over low squared”') + ': (u/v)′ = (v u′ − u v′)/v². The order in the numerator matters')
b('Theorem 6: derivative of xⁿ?', N('n xⁿ⁻¹') + '. Proof: by the binomial theorem (x + h)ⁿ − xⁿ = h(nxⁿ⁻¹ + … + hⁿ⁻¹). True for every real n')
b('Derivative of a polynomial a₀ + a₁x + … + aₙxⁿ?', T('a₁ + 2a₂x + 3a₃x² + … + n aₙ xⁿ⁻¹'))
b('Example 13: derivative of 6x¹⁰⁰ − x⁵⁵ + x.', N('600x⁹⁹ − 55x⁵⁴ + 1'))
b('Example 14: derivative of 1 + x + x² + … + x⁵⁰ at x = 1.', '1 + 2 + 3 + … + 50 = ' + N('1275'))
b('Ex 12.2 Q5: f(x) = x¹⁰⁰/100 + x⁹⁹/99 + … + x²/2 + x + 1. Prove f′(1) = 100 f′(0).', 'f′(x) = x⁹⁹ + x⁹⁸ + … + x + 1: f′(1) = 100 and f′(0) = 1 ✓')
b('Ex 12.2 Q9(i)–(iii): differentiate x − 3/4... use: (5x³ + 3x − 1)(x − 1) and x⁻³(5 + 3x).', 'Expand first: 5x⁴ − 5x³ + 3x² − 4x + 1 → ' + N('20x³ − 15x² + 6x − 4') + '.  x⁻³(5 + 3x) = 5x⁻³ + 3x⁻² → ' + N('−15x⁻⁴ − 6x⁻³'))
b('Ex 12.2 Q9(iv)–(v): x⁵(3 − 6x⁻⁹) and x⁻⁴(3 − 4x⁻⁵).', '3x⁵ − 6x⁻⁴ → ' + N('15x⁴ + 24x⁻⁵') + ';  3x⁻⁴ − 4x⁻⁹ → ' + N('−12x⁻⁵ + 36x⁻¹⁰'))
b('Ex 12.2 Q7: derivative of (x − a)(x − b); (ax² + b)²; (x − a)/(x − b).', N('2x − a − b') + ';  ' + N('4ax(ax² + b)') + ';  quotient rule: ' + N('(a − b)/(x − b)²'))
b('Example 15: derivative of (x + 1)/x.', 'u = x + 1, v = x: (x − (x + 1))/x² = ' + N('−1/x²'))
b('Product rule example: differentiate x² sin x.', N('2x sin x + x² cos x'))
b('Quotient rule example: differentiate x/(x² + 1).', '((x² + 1) − x · 2x)/(x² + 1)² = ' + N('(1 − x²)/(x² + 1)²'))

d.sec('12.5.2-trig-derivatives')
table_card(d, 'Standard derivatives', 'Differentiate.', [
    ('sin x', 'cos x', False), ('cos x', '−sin x', False), ('tan x', 'sec² x', False), ('cot x', '−cosec² x', False),
    ('sec x', 'sec x tan x', False), ('cosec x', '−cosec x cot x', False)], term='Derivatives of trigonometric functions')
b('Example 16: derivative of sin x from first principle.', '(sin(x + h) − sin x)/h = 2cos(x + h/2) sin(h/2)/h → ' + N('cos x'))
b('Example 17: derivative of tan x from first principle.', 'Quotient or first principle: ' + N('sec²x'))
b('Example 18: derivative of sin²x.', 'Product rule: sin x cos x + cos x sin x = ' + N('2 sin x cos x = sin 2x'))
b('Example 21: derivative of sin 2x and cot x.', 'sin 2x = 2 sin x cos x → ' + N('2 cos 2x') + ';  cot x = cos x/sin x → ' + N('−cosec²x'))
b('Example 22: derivative of cos x/(1 + sin x).', '(−sin x(1 + sin x) − cos x · cos x)/(1 + sin x)² = ' + N('−1/(1 + sin x)'))
b('Ex 12.2 Q11 (i)–(iii): derivative of sin x cos x; sec x; 5 sec x + 4 cos x.', N('cos 2x') + ';  ' + N('sec x tan x') + ';  ' + N('5 sec x tan x − 4 sin x'))
b('Ex 12.2 Q11 (iv)–(vii): cosec x; 3 cot x + 5 cosec x; 5 sin x − 6 cos x + 7; 2 tan x − 7 sec x.', N('−cosec x cot x') + ';  ' + N('−3cosec²x − 5 cosec x cot x') + ';  ' + N('5 cos x + 6 sin x') + ';  ' + N('2 sec²x − 7 sec x tan x'))
b('Misc Q15–16 style: derivative of cosec x cot x and (cos x)/(1 + sin x)? ', 'cosec x cot x: −cosec x cot²x − cosec³x. Second: ' + N('−1/(1 + sin x)'))
b('Misc Q1: first principle: (i) cos(x − π/8) (ii) sin(x + 1).', N('−sin(x − π/8)') + ' and ' + N('cos(x + 1)'))
b('Beyond the text: derivatives of eˣ, aˣ, ln x, logₐ x?', N('eˣ') + ';  ' + N('aˣ ln a') + ';  ' + N('1/x') + ';  ' + N('1/(x ln a)'))
b('Chain rule with an example: differentiate sin(3x) and (2x + 1)⁵.', T('3 cos 3x') + ';  ' + T('5(2x + 1)⁴ · 2 = 10(2x + 1)⁴') + ' (derivative of the outside × derivative of the inside)')
b('Physical meaning: s(t) → velocity → acceleration?', 'v = ds/dt, a = dv/dt = d²s/dt². For s = 4.9t²: v = 9.8t, a = 9.8 = g')
b('If f′(x) > 0 on an interval, what does f do? f′(x) < 0?', T('Increasing') + ' and ' + T('decreasing') + ' (used heavily in Class 12 applications)')
b('Differentiability and continuity?', 'Differentiable at a ⟹ continuous at a. The converse is false: |x| is continuous at 0 but has no derivative there (LHD = −1, RHD = 1)')

# ---------------------------------------------------------------- How it's asked
d.sec('12.z-how-its-asked')
b('MCQ: lim x→2 (x² − 4)/(x − 2) equals<br>(a) 0 (b) 2 (c) 4 (d) does not exist', E('(c) 4'))
b('MCQ: lim x→0 sin 3x / x equals<br>(a) 1 (b) 3 (c) 1/3 (d) 0', E('(b) 3'))
b('MCQ: lim x→0 (1 − cos x)/x² equals<br>(a) 0 (b) 1 (c) 1/2 (d) 2', E('(c) 1/2'))
b('MCQ: lim x→∞ (2x² + 3)/(x² − 5) equals<br>(a) 0 (b) 2 (c) 3 (d) ∞', E('(b) 2') + ': leading coefficients')
b('MCQ: The derivative of x³ at x = 2 is<br>(a) 6 (b) 8 (c) 12 (d) 3', '3x² = ' + E('(c) 12'))
b('MCQ: d/dx (sin x cos x) =<br>(a) cos 2x (b) sin 2x (c) −cos 2x (d) 2 cos x', E('(a)') + ': cos²x − sin²x')
b('MCQ: The derivative of (x² + 1)/x is<br>(a) 1 + 1/x² (b) 1 − 1/x² (c) 2x (d) x − 1/x', 'x + 1/x → ' + E('(b) 1 − 1/x²'))
b('MCQ: If f(x) = |x|, then lim x→0 f(x) and f′(0)?<br>(a) 0 and 0 (b) 0 and 1 (c) 0 and does not exist (d) 1 and 0', 'LHD = −1, RHD = 1 → ' + E('(c)'))
b('Integer answer (JEE Main): lim x→0 (sin 5x)/(sin 2x) × 2 =?', '(5/2)·2 = ' + N('5'))
b('Integer answer: if f(x) = x⁴ − 2x² + 1, find f′(1).', '4x³ − 4x at 1 = ' + N('0'))
b('Assertion–Reason.<br><b>A:</b> lim x→0 sin x / x = 1.<br><b>R:</b> cos x < sin x / x < 1 near 0 and cos x → 1.<br>(a) Both true, R explains A (b) Both true, R does not explain A (c) A true, R false (d) A false, R true', E('(a)') + ': sandwich theorem')
b('Assertion–Reason.<br><b>A:</b> If lim x→a f(x) exists then f is defined at a.<br><b>R:</b> The limit depends only on the values of f near a, not at a.<br>(a) Both true, R explains A (b) Both true (c) A false, R true (d) Both false', E('(c)'))
b('True/False: the derivative of a product is the product of the derivatives.', X('False') + ': (uv)′ = u′v + uv′')
b('3-mark: differentiate f(x) = x² sin x from first principle? or by rule.', 'Product rule: ' + N('2x sin x + x² cos x'))
b('4-mark: find the equation of the tangent to y = x² at (2, 4).', 'f′(2) = 4: y − 4 = 4(x − 2) → ' + N('4x − y − 4 = 0'))
b('Case-based: the height of a ball is h(t) = 20t − 5t² metres. Velocity at t = 1 and when is it at rest momentarily?', 'h′(t) = 20 − 10t: v(1) = ' + N('10 m/s') + '; v = 0 at ' + N('t = 2 s') + ' (the top of the flight)')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
