import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch14-probability')
d = Deck('Chapter 14: Probability', 'Class 11', ['class-11', 'mathematics', 'ch-14'])
d.description = 'Events and their algebra, axiomatic probability, addition rule, complement, equally likely outcomes, plus conditional probability and independence for exams.'
b = d.basic

# ---------------------------------------------------------------- 14.1 Events
d.sec('14.1-events')
b('Define an event.', 'Any ' + T('subset of the sample space S') + ' of a random experiment')
b('When does an event E occur?', 'When the outcome ω of the experiment satisfies ' + T('ω ∈ E') + '; if ω ∉ E the event has not occurred')
b('Two coins are tossed: sample space and the event “exactly one head”.', 'S = {HH, HT, TH, TT}; E = ' + N('{HT, TH}'))
b('Impossible event and sure event?', T('Impossible') + ': the empty set φ (e.g. a multiple of 7 on a die)<br>' + T('Sure') + ': the whole sample space S (e.g. “odd or even”)')
b('Simple (elementary) event and compound event?', T('Simple') + ': exactly one sample point, e.g. {HH}<br>' + T('Compound') + ': more than one sample point, e.g. “exactly one head in three tosses” = {HTT, THT, TTH}<br>A sample space with n points has n simple events')
sm.coin_tree(d)
sm.dice_grid(d)
b('Complementary event A′ (“not A”)?', T('A′ = S − A') + ' = {ω ∈ S : ω ∉ A}. P(A′) = 1 − P(A)')
b('Events “A or B”, “A and B”, “A but not B” as sets?', T('A ∪ B') + ', ' + T('A ∩ B') + ', ' + T('A − B = A ∩ B′'))
b('Example 1: die; A = prime = {2, 3, 5}, B = odd = {1, 3, 5}. Find A or B, A and B, A but not B, not A.', N('{1, 2, 3, 5}') + ';  ' + N('{3, 5}') + ';  ' + N('{2}') + ';  ' + N('{1, 4, 6}'))
b('Two dice: A = first throw is 6, B = sum ≥ 11. Find A ∩ B.', 'A = {(6,1), …, (6,6)}, B = {(5,6), (6,5), (6,6)} → ' + N('{(6,5), (6,6)}'))
b('Mutually exclusive events: definition?', T('A ∩ B = φ') + ': they cannot occur together. Simple events of a sample space are always mutually exclusive')
b('Die: A = odd, B = less than 4. Mutually exclusive?', X('No') + ': A = {1, 3, 5}, B = {1, 2, 3} share 1 and 3')
b('Exhaustive events?', 'E₁ ∪ E₂ ∪ … ∪ Eₙ = S: at least one of them must occur. If also pairwise disjoint they are ' + T('mutually exclusive and exhaustive') + ' (a partition of S)')
b('Example 2: two dice, A sum even, B sum multiple of 3, C sum < 4, D sum > 11. Which pairs are mutually exclusive?', 'C = {(1,1), (2,1), (1,2)} and D = {(6,6)} share nothing: only ' + N('(C, D)') + '<br>All other pairs overlap (e.g. A ∩ B contains (3,3))')
b('Example 3: three coins: A no head, B exactly one head, C at least two heads. Exclusive and exhaustive?', 'A = {TTT}, B has 3 outcomes, C has 4: pairwise disjoint and A ∪ B ∪ C = S → ' + E('yes, both'))
b('Ex 14.1 Q1: die; E = “shows 4”, F = “shows an even number”. Mutually exclusive?', X('No') + ': E = {4} ⊂ F = {2, 4, 6}, so 4 is common')
b('Ex 14.1 Q2: die events A: < 7, B: > 7, C: multiple of 3, D: < 4, E: even > 4, F: not < 3.', 'A = S = {1,…,6}; B = ' + N('φ') + '; C = {3, 6}; D = {1, 2, 3}; E = {6}; F = {3, 4, 5, 6}')
b('Ex 14.1 Q2: A ∪ B, A ∩ B, B ∪ C, E ∩ F, D ∩ E, A − C, D − E, E ∩ F′, F′.', 'S;  φ;  {3, 6};  {6};  φ;  {1, 2, 4, 5};  {1, 2, 3};  φ;  {1, 2}')
b('Ex 14.1 Q3: two dice, A sum > 8, B a 2 on either die, C sum ≥ 7 and a multiple of 3. Exclusive pairs?', 'A has 10 outcomes, B has 11, C = {(3,6), (4,5), (5,4), (6,3), (6,6)}. A and B cannot meet (max sum with a 2 is 8); B and C cannot meet. So ' + N('(A, B) and (B, C)') + ' are mutually exclusive; A and C are not')
b('Ex 14.1 Q4: three coins; A = 3 heads, B = 2 heads and a tail, C = 3 tails, D = head on the first coin.', 'Mutually exclusive: ' + N('A,B; A,C; B,C; C,D') + '. Simple: ' + N('A and C') + '. Compound: ' + N('B and D'))
b('Ex 14.1 Q5: examples of events for three coins.', 'Two exclusive: “3 heads” and “3 tails”<br>Three exclusive and exhaustive: “no head”, “exactly 1–2 heads”, “3 heads”<br>Not exclusive: “first is H” and “last is H”<br>Exclusive but not exhaustive: “3 heads”, “3 tails”')
b('Method: showing events are mutually exclusive / exhaustive.', 'Write the events as sets. Exclusive: check each pair has empty intersection. Exhaustive: check the union is S (counts add to n(S) if also disjoint)')

# ---------------------------------------------------------------- 14.2 Axiomatic probability
d.sec('14.2-axioms')
b('Axioms of probability?', T('(i) P(E) ≥ 0') + ';  ' + T('(ii) P(S) = 1') + ';  ' + T('(iii) P(E ∪ F) = P(E) + P(F)') + ' for mutually exclusive E, F')
b('Prove P(φ) = 0 from the axioms.', 'E and φ are disjoint: P(E) = P(E ∪ φ) = P(E) + P(φ) → ' + N('P(φ) = 0'))
b('Probability on a finite sample space {ω₁, …, ωₙ}?', 'Assign P(ωᵢ) with 0 ≤ P(ωᵢ) ≤ 1 and ΣP(ωᵢ) = 1. Then P(A) = ' + T('Σ P(ωᵢ) over ωᵢ ∈ A'))
b('A coin: P(H) = ½ = P(T). Are P(H) = ¼, P(T) = ¾ also valid?', E('Yes') + '. Any p and 1 − p with 0 ≤ p ≤ 1 satisfy the axioms: infinitely many valid assignments. Equal probabilities are just one choice (the fair coin)')
b('Example 4: which assignments to six outcomes are valid: (a) six positive probabilities summing to 1, (b) 1, 0, 0, 0, 0, 0, (c) with two negative values, (d) with 3/2, (e) 0.1, 0.2, …, 0.6?', '(a) ' + E('valid') + ' (b) ' + E('valid') + ' (c) ' + X('no: negative probabilities') + ' (d) ' + X('no: 3/2 > 1') + ' (e) ' + X('no: sum = 2.1'))
b('Validity test for a proposed assignment?', 'Check (1) every value in [0, 1] and (2) the values ' + T('sum to exactly 1') + '. Fail either and it is invalid')
b('Ex 14.2 Q1: which of the seven-outcome assignments are invalid: (c) 0.1, 0.2, …, 0.7; (d) −0.1, 0.2, 0.3, 0.4, −0.2, 0.1, 0.3?', '(c) sums to ' + N('2.8') + ' → invalid. (d) has ' + N('negative values') + ' → invalid. (a) 0.1, 0.01, 0.05, 0.03, 0.01, 0.2, 0.6 sums to 1.0 → valid')
b('Equally likely outcomes: probability of an event?', r'\(P(E) = \dfrac{n(E)}{n(S)} = \dfrac{m}{n}\)' + ' (m favourable outcomes out of n equally likely outcomes)')
b('Why is P(each outcome) = 1/n for n equally likely outcomes?', 'The n probabilities are equal (p each) and sum to 1: np = 1 → ' + N('p = 1/n'))
b('Addition rule for any two events?', r'\(P(A \cup B) = P(A) + P(B) - P(A \cap B)\)' + '. If mutually exclusive, the last term is 0')
b('Why do we subtract P(A ∩ B)?', 'Outcomes in A ∩ B are counted ' + T('twice') + ' in P(A) + P(B). Example (3 coins): A = {HHT, HTH, THH}, B = {HTH, THH, HHH}: 3/8 + 3/8 = 6/8 but P(A ∪ B) = 4/8')
b('Proof of the addition rule (short)?', 'A ∪ B = A ∪ (B − A) (disjoint) and B = (A ∩ B) ∪ (B − A) (disjoint). Subtract: P(A ∪ B) − P(B) = P(A) − P(A ∩ B)')
b('Probability of “not A”?', T('P(A′) = 1 − P(A)') + ' since A and A′ are mutually exclusive and exhaustive: P(A) + P(A′) = 1')
b('Complement trick: P(at least one) = ?', T('1 − P(none)') + '. E.g. at least one tail in two tosses = 1 − P(HH) = 3/4')
b('Inclusion–exclusion for three events (Example 11)?', r'\(P(A\cup B\cup C) = \sum P(A) - \sum P(A\cap B) + P(A\cap B\cap C)\)')
sm.prob_venn(d)

d.sec('14.2-examples')
b('Example 5: one card from 52. P(diamond), P(not an ace), P(black), P(not a diamond), P(not black)?', N('1/4') + ';  ' + N('12/13') + ';  ' + N('1/2') + ';  ' + N('3/4') + ';  ' + N('1/2'))
b('Example 6: bag with 4 red, 3 blue, 2 yellow discs. P(red), P(yellow), P(blue), P(not blue), P(red or blue)?', N('4/9') + ', ' + N('2/9') + ', ' + N('1/3') + ', ' + N('2/3') + ', ' + N('7/9') + ' (red and blue are exclusive, so add)')
b('Example 7: P(E) = 0.05, P(F) = 0.10, P(E ∩ F) = 0.02. Find P(neither), P(at least one fails), P(only one qualifies).', 'P(E ∪ F) = 0.13 → ' + N('0.87') + '; ' + N('1 − 0.02 = 0.98') + '; ' + N('0.03 + 0.08 = 0.11'))
b('Example 8: committee of 2 chosen from 2 men and 2 women. P(no man), P(one man), P(two men)?', 'Total ⁴C₂ = 6: ' + N('1/6') + ', ' + N('4/6 = 2/3') + ', ' + N('1/6'))
b('Ex 14.2 Q2: a coin is tossed twice. P(at least one tail)?', N('3/4'))
b('Ex 14.2 Q3: a die. P(prime), P(≥ 3), P(≤ 1), P(> 6), P(< 6).', N('1/2') + ', ' + N('2/3') + ', ' + N('1/6') + ', ' + N('0') + ', ' + N('5/6'))
b('Ex 14.2 Q4: a card from 52: number of sample points; P(ace of spades); P(ace); P(black).', N('52') + ';  ' + N('1/52') + ';  ' + N('1/13') + ';  ' + N('1/2'))
b('Ex 14.2 Q5: a coin marked 1 and 6 and a die are tossed. P(sum = 3) and P(sum = 12).', 'Sum 3 needs (1, 2); sum 12 needs (6, 6): each ' + N('1/12') + ' (12 equally likely outcomes)')
b('Ex 14.2 Q6: 4 men and 6 women on a council; one member is picked at random. P(woman)?', N('6/10 = 3/5'))
b('Ex 14.2 Q7: four tosses; win ₹1 per head, lose ₹1.50 per tail. Possible amounts and their probabilities?', 'k heads → 2.5k − 6: ' + N('−6 (1/16), −3.5 (1/4), −1 (3/8), +1.5 (1/4), +4 (1/16)') + ': five different amounts')
b('Ex 14.2 Q8: three coins. P(3 heads), P(2 heads), P(at least 2), P(at most 2), P(no head), P(3 tails), P(exactly two tails), P(no tail), P(at most two tails).', N('1/8, 3/8, 1/2, 7/8, 1/8, 1/8, 3/8, 1/8, 7/8'))
b('Ex 14.2 Q9: P(A) = 2/11. Find P(not A).', N('9/11'))
b('Ex 14.2 Q10: a letter chosen at random from ASSASSINATION. P(vowel), P(consonant).', '13 letters, vowels A, A, I, A, I, O = 6: ' + N('6/13') + ' and ' + N('7/13'))
b('Ex 14.2 Q11: lottery: choose 6 numbers from 1–20; probability of matching the fixed six?', N('1/²⁰C₆ = 1/38760') + ' (order does not matter)')
b('Ex 14.2 Q12: are these consistent? (i) P(A) = 0.5, P(B) = 0.7, P(A ∩ B) = 0.6; (ii) P(A) = 0.5, P(B) = 0.4, P(A ∪ B) = 0.8.', '(i) ' + X('No') + ': P(A ∩ B) cannot exceed P(A). (ii) P(A ∩ B) = 0.9 − 0.8 = 0.1 ≤ min → ' + E('consistent'))
b('Ex 14.2 Q13: fill in: P(A) = 0.35, P(A ∩ B) = 0.25, P(A ∪ B) = 0.6; and P(A) = 0.5, P(B) = 0.35, P(A ∪ B) = 0.7.', 'P(B) = 0.6 − 0.35 + 0.25 = ' + N('0.5') + ';  P(A ∩ B) = 0.85 − 0.7 = ' + N('0.15'))
b('Ex 14.2 Q14: P(A) = 3/5, P(B) = 1/5, mutually exclusive. P(A or B)?', N('4/5'))
b('Ex 14.2 Q15: P(E) = 1/4, P(F) = 1/2, P(E and F) = 1/8. Find P(E or F) and P(not E and not F).', N('5/8') + ' and ' + N('3/8'))
b('Ex 14.2 Q16: P(not E or not F) = 0.25. Are E and F mutually exclusive?', 'P(E ∩ F) = 1 − 0.25 = 0.75 ≠ 0 → ' + N('not mutually exclusive'))
b('Ex 14.2 Q17: P(A) = 0.42, P(B) = 0.48, P(A and B) = 0.16. Find P(not A), P(not B), P(A or B).', N('0.58') + ', ' + N('0.52') + ', ' + N('0.74'))
b('Ex 14.2 Q18: 40% study Maths, 30% Biology, 10% both. P(Maths or Biology)?', N('0.4 + 0.3 − 0.1 = 0.6'))
b('Ex 14.2 Q19: P(pass first) = 0.8, P(pass second) = 0.7, P(at least one) = 0.95. P(both)?', '0.8 + 0.7 − 0.95 = ' + N('0.55'))
b('Ex 14.2 Q20: P(pass English and Hindi) = 0.5, P(neither) = 0.1, P(English) = 0.75. P(Hindi)?', 'P(E ∪ H) = 0.9 → P(H) = 0.9 − 0.75 + 0.5 = ' + N('0.65'))
b('Ex 14.2 Q21: 60 students; 30 NCC, 32 NSS, 24 both. P(NCC or NSS), P(neither), P(NSS but not NCC).', 'Union = 38: ' + N('38/60 = 19/30') + ';  ' + N('22/60 = 11/30') + ';  ' + N('8/60 = 2/15'))

# ---------------------------------------------------------------- Miscellaneous
d.sec('14.z-miscellaneous')
b('Example 9: four cities visited in random order (24 orders). P(A before B)? P(A before B before C)?', N('12/24 = 1/2') + '; ' + N('4/24 = 1/6') + ' (by symmetry: 1/3! for any fixed order of three named cities)')
b('Example 9 (iii)–(v): P(A first and B last); P(A first or second); P(A just before B).', N('2/24 = 1/12') + ';  ' + N('12/24 = 1/2') + ';  ' + N('6/24 = 1/4') + ' (treat AB as a block: 3! = 6)')
b('Example 10: a 7-card hand from 52. P(all four kings), P(exactly 3 kings), P(at least 3 kings)?', N('1/7735') + ';  ' + N('9/1547') + ' (⁴C₃·⁴⁸C₄/⁵²C₇);  ' + N('46/7735'))
b('Example 12: five teams in a relay; P(A, B, C finish 1st, 2nd, 3rd in that order); P(they are the first three in any order)?', 'Sample space ⁵P₃ = 60: ' + N('1/60') + ';  3! orders: ' + N('6/60 = 1/10'))
b('Misc Q1: box of 10 red, 20 blue, 30 green marbles; 5 drawn. P(all blue), P(at least one green)?', N('²⁰C₅/⁶⁰C₅ = 34/11977 ≈ 0.0028') + ';  ' + N('1 − ³⁰C₅/⁶⁰C₅ = 4367/4484 ≈ 0.974'))
b('Misc Q2: 4 cards from 52. P(3 diamonds and 1 spade)?', '¹³C₃ · ¹³C₁ / ⁵²C₄ = 286 × 13/270725 = ' + N('286/20825 ≈ 0.0137'))
b('Misc Q3: a die with two faces marked 1, three faces 2, one face 3. P(2), P(1 or 3), P(not 3).', N('3/6 = 1/2') + ';  ' + N('3/6 = 1/2') + ';  ' + N('5/6'))
b('Misc Q4: 10000 tickets, 10 prizes. P(no prize) with one ticket; two tickets.', N('1 − 10/10000 = 999/1000') + ';  ' + N('(9990/10000)(9989/9999) ≈ 0.998'))
b('Misc Q5: 100 students in sections of 40 and 60. P(you and your friend in the same section)? Different?', 'You are in the 40-section with probability 0.4 (friend joins: 39/99)<br>You are in the 60-section with probability 0.6 (friend joins: 59/99)<br>Same section: ' + N('17/33') + '; different sections: ' + N('16/33'))
b('Misc Q6: three letters put at random into three addressed envelopes. P(at least one letter in its own envelope)?', '1 − P(none) = 1 − 2/6 = ' + N('2/3') + ' (2 derangements out of 6)')
b('Misc Q7: P(A) = 0.54, P(B) = 0.69, P(A ∩ B) = 0.35. Find P(A ∪ B), P(A′ ∩ B′), P(A ∩ B′), P(B ∩ A′).', N('0.88') + ',  ' + N('0.12') + ',  ' + N('0.19') + ',  ' + N('0.34'))
b('Misc Q9: 4-digit numbers > 5000 from 0, 1, 3, 5, 7. P(divisible by 5) with repetition; without?', 'With repetition: 250 numbers, last digit 0 or 5: 100 → ' + N('2/5') + '. Without: 48 numbers, 18 end in 0 or 5 → ' + N('3/8'))
b('Misc Q10: a 4-wheel suitcase lock opens with a sequence of four distinct digits. P(guessing it)?', '¹⁰P₄ = 5040 sequences → ' + N('1/5040'))

# ---------------------------------------------------------------- Beyond the textbook
d.sec('14.z-beyond-text')
b('Conditional probability P(A | B)?', r'\(P(A \mid B) = \dfrac{P(A \cap B)}{P(B)}\)' + ', P(B) > 0: the probability of A given that B has occurred (the sample space shrinks to B)')
b('Multiplication rule?', T('P(A ∩ B) = P(A) · P(B | A) = P(B) · P(A | B)'))
b('Independent events: definition and test?', T('P(A ∩ B) = P(A) · P(B)') + ' (equivalently P(A | B) = P(A)). Independent is not the same as mutually exclusive')
b('Trap: mutually exclusive vs independent?', 'If P(A), P(B) > 0 and A, B are mutually exclusive, then P(A ∩ B) = 0 ≠ P(A)P(B): they are ' + X('dependent') + '<br>Exclusive events are the most dependent: if one occurs, the other cannot')
b('Two dice: P(sum 8 | first die is 3)?', 'Given a 3, the second must be 5: ' + N('1/6'))
b('Two independent events with P(A) = 0.3, P(B) = 0.4: P(A ∪ B)?', '0.3 + 0.4 − 0.12 = ' + N('0.58') + ' (or 1 − 0.7 × 0.6)')
b('At least one success in n independent trials, each with probability p?', T('1 − (1 − p)ⁿ') + '. E.g. at least one six in 3 rolls: 1 − (5/6)³ = 91/216')
b('Total probability and Bayes’ theorem (Class 12)?', 'For a partition E₁, …, Eₙ: ' + T('P(A) = Σ P(Eᵢ)P(A | Eᵢ)') + ';  ' + T('P(Eⱼ | A) = P(Eⱼ)P(A | Eⱼ) / Σ P(Eᵢ)P(A | Eᵢ)'))
b('Odds in favour and against?', 'If P(A) = m/(m + n): odds in favour ' + T('m : n') + ', odds against n : m. P(rain) = 0.2 → odds in favour 1 : 4')
b('Card facts to remember?', '52 cards, 4 suits × 13 ranks; 26 red and 26 black; 12 face cards (J, Q, K); 4 aces; 16 honour cards (10, J, Q, K, A) if asked. A hand of n cards: ⁵²Cₙ')
b('Number of outcomes for n coins, n dice, and a pair of dice?', N('2ⁿ') + ', ' + N('6ⁿ') + ', ' + N('36'))
b('Dice sums: which sum is most likely and how many ways for each sum 2 to 12?', T('7') + ' (6 ways). Ways: 1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1 for sums 2 through 12')
b('Coin sequences: P(exactly k heads in n tosses)?', r'\(\dfrac{\binom{n}{k}}{2^n}\)' + '. E.g. exactly 2 heads in 4 tosses: 6/16 = 3/8')
b('Birthday-type problems: P(all n people have different birthdays)?', r'\(\dfrac{365\cdot364\cdots(365-n+1)}{365^n}\)' + ': 1 − this is P(at least two share): for n = 23 it exceeds ½')

# ---------------------------------------------------------------- How it's asked
d.sec('14.z-how-its-asked')
b('MCQ: A die is thrown. P(number > 4) is<br>(a) 1/6 (b) 1/3 (c) 1/2 (d) 2/3', E('(b) 1/3') + ' (5, 6)')
b('MCQ: Two coins are tossed. P(at least one head) is<br>(a) 1/4 (b) 1/2 (c) 3/4 (d) 1', E('(c) 3/4'))
b('MCQ: Two dice are thrown. P(sum = 9) is<br>(a) 1/9 (b) 1/6 (c) 1/12 (d) 5/36', 'Ways: (3,6), (4,5), (5,4), (6,3) → 4/36 = ' + E('(a) 1/9'))
b('MCQ: A card is drawn from 52. P(king or heart) is<br>(a) 17/52 (b) 16/52 (c) 4/13 (d) 1/4', '4/52 + 13/52 − 1/52 = 16/52 = ' + E('(b)'))
b('MCQ: If P(A) = 0.4, P(B) = 0.5, P(A ∩ B) = 0.2 then P(A ∪ B) =<br>(a) 0.9 (b) 0.7 (c) 0.1 (d) 0.3', '0.4 + 0.5 − 0.2 = ' + E('(b) 0.7'))
b('MCQ: The probability of an event and its complement add to<br>(a) 0 (b) 1/2 (c) 1 (d) 2', E('(c) 1'))
b('MCQ: A bag has 3 red and 5 blue balls. P(red ball) is<br>(a) 3/5 (b) 3/8 (c) 5/8 (d) 1/3', E('(b) 3/8'))
b('MCQ: The probability that a leap year has 53 Sundays is<br>(a) 1/7 (b) 2/7 (c) 3/7 (d) 5/7', '366 = 52 weeks + 2 days; the extra two include Sunday in 2 of 7 cases → ' + E('(b) 2/7'))
b('Integer answer (JEE Main): three coins are tossed; if P(at least two heads) = p/q in lowest terms, find p + q.', 'P = 1/2 → ' + N('3'))
b('Integer answer: two dice are rolled; the number of outcomes with sum 7 or 11 is?', '6 + 2 = ' + N('8'))
b('Assertion–Reason.<br><b>A:</b> P(A ∪ B) ≤ P(A) + P(B).<br><b>R:</b> P(A ∪ B) = P(A) + P(B) − P(A ∩ B) and P(A ∩ B) ≥ 0.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> If P(A) = 0.6 then P(A′) = 0.4.<br><b>R:</b> A and A′ are mutually exclusive and exhaustive.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('True/False: the probability of an event can be 1.5 if the event is very likely.', X('False') + ': 0 ≤ P(E) ≤ 1 always')
b('2-mark: two dice thrown. P(doublet) and P(sum is a prime).', 'Doublets: 6/36 = ' + N('1/6') + '. Prime sums 2, 3, 5, 7, 11: 1 + 2 + 4 + 6 + 2 = 15 → ' + N('15/36 = 5/12'))
b('3-mark: from a well-shuffled deck, two cards are drawn together. P(both aces)?', '⁴C₂/⁵²C₂ = 6/1326 = ' + N('1/221'))
b('4-mark: P(A) = 0.5, P(B) = 0.3, P(A ∩ B) = 0.1. Find P(A′ ∩ B′) and P(exactly one of A, B).', 'P(A ∪ B) = 0.7 → ' + N('0.3') + '; exactly one: 0.4 + 0.2 = ' + N('0.6'))
b('Case-based: a raffle sells 500 tickets with 3 prizes (a ticket wins at most once). You buy 5. P(win at least one prize)?', '1 − ⁴⁹⁵C₃/⁵⁰⁰C₃ ≈ ' + N('0.0298') + ' (about 3%). Rough check: 3 × 5/500 = 0.03')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
