import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch09-straight-lines')
d = Deck('Chapter 9: Straight Lines', 'Class 11', ['class-11', 'mathematics', 'ch-9'])
d.description = 'Slope, angle between lines, forms of a line, distance formulas, concurrency, images and reflections, families of lines.'
b = d.basic

# ---------------------------------------------------------------- 9.1 Recap
d.sec('9.1-recap')
b('Distance between P(x₁, y₁) and Q(x₂, y₂)?', r'\(PQ = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}\)')
b('Section formula (internal, ratio m : n)?', r'\(\left(\dfrac{mx_2 + nx_1}{m+n},\ \dfrac{my_2 + ny_1}{m+n}\right)\)' + '. Midpoint: m = n')
b('Area of the triangle with vertices (x₁, y₁), (x₂, y₂), (x₃, y₃)?', r'\(\dfrac12\left|x_1(y_2-y_3) + x_2(y_3-y_1) + x_3(y_1-y_2)\right|\)' + '. Area = 0 ⟺ points are collinear')
b('Distance between (6, −4) and (3, 0)? Area of (4,4), (3,−2), (−3,16)?', N('5') + '; area ' + N('27') + ' (½|4(−18) + 3(12) + (−3)(6)| = ½·54)')
b('Centroid of a triangle? Which other points are asked?', 'Centroid ((x₁+x₂+x₃)/3, (y₁+y₂+y₃)/3). Also: ' + T('incentre') + ' ((ax₁ + bx₂ + cx₃)/(a+b+c), …), circumcentre (equidistant from vertices), orthocentre (meet of altitudes)')
b('Ex 9.1 Q1: area of the quadrilateral (−4,5), (0,7), (5,−5), (−4,−2)?', 'Shoelace: ½|−28 − 35 − 30 − 28| = ' + N('60.5'))
b('Ex 9.1 Q2: equilateral triangle, side 2a, base along the y-axis with midpoint at the origin. Vertices?', N('(0, a), (0, −a), (√3a, 0)') + ' (or (−√3a, 0) as the third vertex)')
b('Ex 9.1 Q3: distance PQ when PQ ∥ y-axis; when PQ ∥ x-axis?', N('|y₂ − y₁|') + ' and ' + N('|x₂ − x₁|'))
b('Ex 9.1 Q4: a point on the x-axis equidistant from (7, 6) and (3, 4)?', '(x − 7)² + 36 = (x − 3)² + 16 → −8x = −60 → ' + N('(15/2, 0)'))

# ---------------------------------------------------------------- 9.2 Slope
d.sec('9.2-slope')
b('Define the inclination and slope of a line.', 'Inclination θ = angle the line makes with the positive x-axis, measured anticlockwise, 0° ≤ θ < 180°. Slope ' + T('m = tan θ') + ' (θ ≠ 90°)')
b('Slope of the x-axis, of a horizontal line, of a vertical line?', N('0') + ', ' + N('0') + ', ' + X('undefined') + ' (θ = 90°)')
sm.slope_sweep(d)
b('Slope of the line through (x₁, y₁) and (x₂, y₂)?', r'\(m = \dfrac{y_2 - y_1}{x_2 - x_1}\)' + ', x₁ ≠ x₂ (if x₁ = x₂ the line is vertical)')
b('Example 1: slopes through (3,−2)&(−1,4); (3,−2)&(7,−2); (3,−2)&(3,4); inclination 60°.', N('−3/2') + ';  ' + N('0') + ';  ' + X('undefined') + ';  ' + N('√3'))
b('Condition for two non-vertical lines to be parallel? Perpendicular?', T('m₁ = m₂') + ' (parallel);  ' + T('m₁m₂ = −1') + ' (perpendicular: negative reciprocals)')
b('Why is m₁m₂ = −1 for perpendicular lines?', 'β = α + 90° → tan β = −cot α = −1/tan α. A 90° turn sends slope m to −1/m (e.g. 2 → −½)')
b('Condition for three points A, B, C to be collinear?', T('slope AB = slope BC') + ' (or area of ABC = 0)')
b('Angle between two lines with slopes m₁ and m₂?', r'\(\tan\theta = \left|\dfrac{m_1 - m_2}{1 + m_1m_2}\right|\)' + ' (acute angle); if 1 + m₁m₂ = 0 the lines are perpendicular')
sm.two_answers_angle(d)
b('Example 3: line through (−2, 6), (4, 8) ⟂ line through (8, 12), (x, 24). Find x.', 'm₁ = 1/3, m₂ = 12/(x − 8) → product −1 → x − 8 = −36 → ' + N('x = −28'))
b('Ex 9.1 Q5: slope of the line through the origin and the midpoint of (0, −4) and (8, 0)?', 'Midpoint (4, −2): slope ' + N('−1/2'))
b('Ex 9.1 Q6: show (4, 4), (3, 5), (−1, −1) form a right triangle without Pythagoras.', 'Slope of (4,4)→(3,5) is −1; slope of (4,4)→(−1,−1) is 1; product −1, so the right angle is at ' + N('(4, 4)'))
b('Ex 9.1 Q7: slope of a line making 30° with the positive y-axis (anticlockwise)?', 'Inclination = 90° + 30° = 120° → ' + N('m = tan 120° = −√3'))
b('Ex 9.1 Q8: show (−2,−1), (4,0), (3,3), (−3,2) form a parallelogram using slopes.', 'AB and DC both have slope 1/6; BC and AD both have slope −3. Opposite sides parallel ✓')
b('Ex 9.1 Q9: angle between the x-axis and the line through (3, −1) and (4, −2)?', 'm = −1 → inclination ' + N('135°') + ' (angle with the axis 45°)')
b('Ex 9.1 Q10: one slope is double the other; tan of the angle between them is 1/3. Slopes?', '|m|/(1 + 2m²) = 1/3 → 2m² − 3|m| + 1 = 0 → ' + N('(1, 2) or (½, 1)') + ' (or their negatives)')
b('Ex 9.3 Q8: angle between √3x + y = 1 and x + √3y = 1.', 'm₁ = −√3, m₂ = −1/√3: tan θ = |(−√3 + 1/√3)/(1 + 1)| = 1/√3 → ' + N('30°') + ' (and 150°)')
b('Ex 9.3 Q9: line through (h, 3), (4, 1) is ⟂ to 7x − 9y − 19 = 0. Find h.', 'Slope needed −9/7: (1 − 3)/(4 − h) = −9/7 → ' + N('h = 22/9'))
b('Ex 9.3 Q11: two lines through (2, 3) meet at 60°; one has slope 2. The other?', '|(m − 2)/(1 + 2m)| = √3 → ' + N('m = −(8 + 5√3)/11') + ' or ' + N('m = (5√3 − 8)/11') + ' (two lines, one each side)')
b('Misc Q18: y = 3x + 1 and 2y = x + 3 are equally inclined to y = mx + 4. Find m.', 'Equal angles: |(m − 3)/(1 + 3m)| = |(m − ½)/(1 + m/2)|; the non-trivial case gives 7m² − 2m − 7 = 0 → ' + N('m = (1 ± 5√2)/7'))
b('Misc Q12: line through the origin at angle θ to y = mx + c?', N('y = ((m ± tan θ)/(1 ∓ m tan θ)) x'))

# ---------------------------------------------------------------- 9.3 Forms of the equation
d.sec('9.3-equations-of-a-line')
b('Horizontal and vertical lines at distance a from the axes?', 'Horizontal: ' + T('y = ±a') + '; vertical: ' + T('x = ±b'))
b('Example 4: lines through (−2, 3) parallel to the axes?', N('y = 3') + ' (∥ x-axis) and ' + N('x = −2') + ' (∥ y-axis)')
table_card(d, '9.3 · Forms of a line', 'Write the equation.', [
    ('Point–slope: through (x₀, y₀), slope m', 'y − y₀ = m(x − x₀)', False), ('Two-point: through (x₁, y₁), (x₂, y₂)', 'y − y₁ = ((y₂ − y₁)/(x₂ − x₁))(x − x₁)', False),
    ('Slope–intercept: slope m, y-intercept c', 'y = mx + c', False), ('Slope with x-intercept d', 'y = m(x − d)', False),
    ('Intercept form: intercepts a, b', 'x/a + y/b = 1', False), ('General form', 'Ax + By + C = 0  (A, B not both 0)', False)], term='Forms of the equation of a line')
b('Slope and intercepts from Ax + By + C = 0?', 'Slope ' + T('−A/B') + '; y-intercept ' + T('−C/B') + '; x-intercept ' + T('−C/A'))
b('Example 5: line through (−2, 3) with slope −4.', 'y − 3 = −4(x + 2) → ' + N('4x + y + 5 = 0'))
b('Example 6: line through (1, −1) and (3, 5).', 'slope 3: y + 1 = 3(x − 1) → ' + N('3x − y − 4 = 0') + ' (NCERT writes −3x + y + 4 = 0)')
b('Example 7: tan θ = ½ with (i) y-intercept −3/2 (ii) x-intercept 4.', '(i) y = x/2 − 3/2 → ' + N('x − 2y − 3 = 0') + ' (ii) y = (x − 4)/2 → ' + N('x − 2y − 4 = 0'))
b('Example 8: intercepts −3 and 2.', 'x/(−3) + y/2 = 1 → ' + N('2x − 3y + 6 = 0'))
b('Ex 9.2 Q1–3: equations of the axes; through (−4, 3) with slope ½; through the origin with slope m.', N('y = 0') + ' and ' + N('x = 0') + ';  y − 3 = (x + 4)/2 → ' + N('x − 2y + 10 = 0') + ';  ' + N('y = mx'))
b('Ex 9.2 Q5–6: x-intercept 3 units left of the origin, slope −2; y-intercept 2 above the origin at 30°.', N('2x + y + 6 = 0') + ';  y = x/√3 + 2 → ' + N('x − √3y + 2√3 = 0'))
b('Ex 9.2 Q7: line through (−1, 1) and (2, −4).', 'slope −5/3 → ' + N('5x + 3y + 2 = 0'))
b('Ex 9.2 Q8: median through R in triangle P(2,1), Q(−2,3), R(4,5).', 'Midpoint of PQ = (0, 2); slope (5 − 2)/4 = 3/4 → ' + N('3x − 4y + 8 = 0'))
b('Ex 9.2 Q9: through (−3, 5) ⟂ the line through (2, 5) and (−3, 6).', 'That slope is −1/5, so use 5: y − 5 = 5(x + 3) → ' + N('5x − y + 20 = 0'))
b('Ex 9.2 Q10: a line ⟂ to the segment (1,0)–(2,3) divides it 1 : n. Equation?', 'Point ((n + 2)/(n + 1), 3/(n + 1)), slope −1/3: ' + N('(n + 1)x + 3(n + 1)y = n + 11'))
b('Ex 9.2 Q11: equal intercepts, through (2, 3).', 'x + y = a with 2 + 3 = a → ' + N('x + y = 5'))
b('Ex 9.2 Q12: through (2, 2), sum of intercepts 9.', '2/a + 2/(9 − a) = 1 → a² − 9a + 18 = 0 → a = 3 or 6: ' + N('2x + y = 6') + ' and ' + N('x + 2y = 6'))
b('Ex 9.2 Q13: through (0, 2) at 2π/3; and the parallel line 2 units below the origin.', 'slope −√3: ' + N('√3x + y − 2 = 0') + ' and ' + N('√3x + y + 2 = 0'))
b('Ex 9.2 Q14: the perpendicular from the origin meets the line at (−2, 9). Equation?', 'Normal direction (−2, 9): −2(x + 2) + 9(y − 9) = 0 → ' + N('2x − 9y + 85 = 0'))
b('Ex 9.2 Q15: L is linear in C: L = 124.942 at 20°C and 125.134 at 110°C. Find L(C).', 'slope 0.192/90: ' + N('L = 0.00213C + 124.899') + ' (approx)')
b('Ex 9.2 Q16: 980 L sold at ₹14, 1220 L at ₹16 (linear). Demand at ₹17?', 'Slope 120 L per rupee: 980 + 120·3 = ' + N('1340 litres'))
b('Ex 9.2 Q17–18: midpoint (a, b) of a segment between the axes; point (h, k) dividing it 1 : 2.', 'Intercepts 2a, 2b: ' + N('x/a + y/b = 2') + '. Second: ' + N('2kx + hy = 3hk'))
b('Ex 9.2 Q19: show (3, 0), (−2, −2), (8, 2) are collinear.', 'Slope of the first two: 2/5; slope of the first and third: 2/5 → same line ✓')
b('Method: which form of a line to use?', 'Slope + point → point–slope. Two points → two-point (or find slope). Intercepts → x/a + y/b = 1. Normal direction known → A(x − x₁) + B(y − y₁) = 0')
b('Ex 9.3 Q1: slope–intercept form of x + 7y = 0, 6x + 3y − 5 = 0, y = 0.', 'y = −x/7 (slope −1/7, c = 0);  y = −2x + 5/3 (slope −2, c = 5/3);  slope 0, c = 0')
b('Ex 9.3 Q2: intercept form of 3x + 2y − 12 = 0, 4x − 3y = 6, 3y + 2 = 0.', 'x/4 + y/6 = 1 (4, 6);  x/(3/2) + y/(−2) = 1 (3/2, −2);  y = −2/3: y-intercept −2/3, ' + X('no x-intercept'))
b('Ex 9.3 Q6–7: ∥ to 3x − 4y + 2 = 0 through (−2, 3); ⟂ to x − 7y + 5 = 0 with x-intercept 3.', N('3x − 4y + 18 = 0') + ';  slope −7: y = −7(x − 3) → ' + N('7x + y − 21 = 0'))
b('Ex 9.3 Q10: the line through (x₁, y₁) parallel to Ax + By + C = 0?', T('A(x − x₁) + B(y − y₁) = 0') + ': same A, B (same direction), new constant. Perpendicular: B(x − x₁) − A(y − y₁) = 0')
b('Ex 9.3 Q12: right bisector of (3, 4) and (−1, 2).', 'Midpoint (1, 3), slope of segment ½ → perpendicular slope −2: ' + N('2x + y − 5 = 0'))
b('Ex 9.3 Q14: the perpendicular from the origin to y = mx + c meets it at (−1, 2). m and c?', 'Origin-to-point slope −2 = −1/m → ' + N('m = ½') + ', c = 2 + m = ' + N('5/2'))
b('Ex 9.3 Q16: altitude from A(2, 3) in the triangle A, B(4, −1), C(1, 2): equation and length.', 'BC has slope −1 (x + y = 3), so the altitude has slope 1: ' + N('x − y + 1 = 0') + '; length = |2 + 3 − 3|/√2 = ' + N('√2'))
b('Ex 9.3 Q17: p = perpendicular from the origin to the line with intercepts a, b. Show 1/p² = 1/a² + 1/b².', 'Line bx + ay = ab: p = ab/√(a² + b²) → 1/p² = (a² + b²)/(a²b²) = 1/a² + 1/b² ✓')

# ---------------------------------------------------------------- 9.4 Distance
d.sec('9.4-distance')
b('Distance of the point (x₁, y₁) from the line Ax + By + C = 0?', r'\(d = \dfrac{|Ax_1 + By_1 + C|}{\sqrt{A^2 + B^2}}\)')
sm.distance_to_line(d)
b('Distance between parallel lines Ax + By + C₁ = 0 and Ax + By + C₂ = 0?', r'\(d = \dfrac{|C_1 - C_2|}{\sqrt{A^2 + B^2}}\)' + ' (first make the A, B identical in both)')
b('Trap: distance between 3x + 4y + 5 = 0 and 6x + 8y − 10 = 0.', 'Divide the second by 2: 3x + 4y − 5 = 0. Then d = |5 − (−5)|/5 = ' + N('2'))
b('Example 9: distance of (3, −5) from 3x − 4y − 26 = 0.', '|9 + 20 − 26|/5 = ' + N('3/5'))
b('Example 10: distance between 3x − 4y + 7 = 0 and 3x − 4y + 5 = 0.', '|7 − 5|/5 = ' + N('2/5'))
b('Ex 9.3 Q3: distance of (−1, 1) from 12(x + 6) = 5(y − 2).', '12x − 5y + 82 = 0: |−12 − 5 + 82|/13 = ' + N('5'))
b('Ex 9.3 Q4: points on the x-axis at distance 4 from x/3 + y/4 = 1.', '4x + 3y − 12 = 0: |4x − 12|/5 = 4 → ' + N('(8, 0) and (−2, 0)'))
b('Ex 9.3 Q5: distance between 15x + 8y − 34 = 0 and 15x + 8y + 31 = 0; and between l(x + y) + p = 0 and l(x + y) − r = 0.', '65/17 = ' + N('65/17') + ';  |p + r|/(|l|√2) = ' + N('|p + r|/(|l|√2)'))
b('Ex 9.3 Q13: foot of the perpendicular from (−1, 3) to 3x − 4y − 16 = 0.', 'Move by t = (−3 − 12 − 16)/25 = −31/25 along (3, −4): ' + N('(68/25, −49/25)'))
b('Ex 9.3 Q15: p, q are perpendiculars from the origin to x cos θ − y sin θ = k cos 2θ and x sec θ + y cosec θ = k. Show p² + 4q² = k².', 'p = |k cos 2θ|; q = k/√(sec²θ + cosec²θ) = k sinθ cosθ = (k/2) sin 2θ. Then p² + 4q² = k²(cos²2θ + sin²2θ) = k² ✓')
b('Misc Q3: points on the y-axis at distance 4 from x/3 + y/4 = 1.', '|3y − 12|/5 = 4 → ' + N('(0, 32/3) and (0, −8/3)'))
b('Misc Q4: perpendicular distance from the origin to the line joining (cos θ, sin θ) and (cos φ, sin φ).', N('|cos((θ − φ)/2)|') + ' (a chord of the unit circle)')
b('Misc Q20: the line equidistant from the parallels 9x + 6y − 7 = 0 and 3x + 2y + 6 = 0.', 'Rewrite the second as 9x + 6y + 18 = 0. Middle constant: (−7 + 18)/2 = 11/2 → ' + N('18x + 12y + 11 = 0'))
b('Misc Q22: product of the perpendiculars from (±√(a² − b²), 0) to x cos θ/a + y sin θ/b = 1.', 'Multiply the two distances: the denominators combine to (cos²θ/a² + sin²θ/b²) and the numerators to 1 − (a² − b²)cos²θ/a² = b²(cos²θ/a² + sin²θ/b²). The product is ' + N('b²'))

# ---------------------------------------------------------------- Concurrency, families, loci
d.sec('9.z-concurrency-and-families')
b('Three lines are concurrent. What does that mean and how do you test it?', 'They pass through one point. Solve two, then check the third; or ' + T('the 3×3 determinant of coefficients = 0'))
b('Example 11: 2x + y − 3 = 0, 5x + ky − 3 = 0, 3x − y − 2 = 0 are concurrent. Find k.', 'Lines 1 and 3 meet at (1, 1); it must satisfy the second: 5 + k − 3 = 0 → ' + N('k = −2'))
b('Misc Q8: 3x + y − 2 = 0, px + 2y − 3 = 0, 2x − y − 3 = 0 meet at one point. p?', 'Lines 1 and 3 meet at (1, −1): p − 2 − 3 = 0 → ' + N('p = 5'))
b('Misc Q9: y = m₁x + c₁ etc. concurrent ⟹ m₁(c₂ − c₃) + m₂(c₃ − c₁) + m₃(c₁ − c₂) = 0. Idea?', 'Concurrency ⟺ determinant |m₁ −1 c₁; m₂ −1 c₂; m₃ −1 c₃| = 0; expanding gives the identity')
b('Family of lines through the intersection of L₁ = 0 and L₂ = 0?', T('L₁ + λL₂ = 0') + ' (λ a parameter). Choose λ using an extra condition, e.g. passing through a given point')
b('Misc Q11: through the intersection of 4x + 7y − 3 = 0 and 2x − 3y + 1 = 0 with equal intercepts.', 'Intersection (1/13, 5/13). Equal intercepts: x + y = k with k = 6/13 → ' + N('13x + 13y = 6'))
b('Misc Q5: line ∥ the y-axis through the intersection of x − 7y + 5 = 0 and 3x + y = 0.', 'y = −3x → x + 21x + 5 = 0 → x = −5/22: ' + N('22x + 5 = 0'))
b('Misc Q1: (k − 3)x − (4 − k²)y + k² − 7k + 6 = 0 is (a) ∥ x-axis (b) ∥ y-axis (c) through the origin.', '(a) coefficient of x = 0 → ' + N('k = 3') + ' (b) coefficient of y = 0 → ' + N('k = ±2') + ' (c) constant = 0 → k² − 7k + 6 = 0 → ' + N('k = 1, 6'))
b('Misc Q2: intercepts with sum 1 and product −6.', '(a, b) = (3, −2) or (−2, 3): ' + N('2x − 3y = 6') + ' and ' + N('3x − 2y + 6 = 0'))
b('Misc Q7: area of the triangle formed by y = x, y = −x, x = k.', 'Vertices (0,0), (k,k), (k,−k): ' + N('k²'))
b('Example 14: area of the triangle from y = m₁x + c₁, y = m₂x + c₂, x = 0.', N('(c₁ − c₂)² / (2|m₁ − m₂|)'))
b('Example 15: a line whose segment between 5x − y + 4 = 0 and 3x + 4y − 4 = 0 is bisected at (1, 5).', 'Endpoints (α₁, 5α₁ + 4), (α₂, (4 − 3α₂)/4) with α₁ + α₂ = 2 gives α₁ = 26/23: ' + N('107x − 3y − 92 = 0'))
b('Example 16: path of a point equidistant from 3x − 2y = 5 and 3x + 2y = 5.', 'Equal distances give k = 0 or h = 5/3: the ' + T('angle bisectors') + ' y = 0 and x = 5/3, both straight lines')
b('Angle bisectors of a₁x + b₁y + c₁ = 0 and a₂x + b₂y + c₂ = 0?', T('(a₁x + b₁y + c₁)/√(a₁² + b₁²) = ±(a₂x + b₂y + c₂)/√(a₂² + b₂²)') + ': two perpendicular bisectors (make c₁, c₂ same sign to pick the one containing the origin)')
b('Misc Q19: the sum of the distances of P(x, y) from x + y − 5 = 0 and 3x − 2y + 7 = 0 is always 10. Locus?', 'Removing the modulus in each region gives a linear equation, so P moves on a ' + T('line (segment)'))
b('Misc Q23: a person at the meeting point of 2x − 3y + 4 = 0 and 3x + 4y − 5 = 0 wants to reach 6x − 7y + 8 = 0 fastest.', 'The shortest path is the perpendicular from (−1/17, 22/17): ' + N('119x + 102y − 125 = 0'))

d.sec('9.z-reflection')
sm.foot_and_image(d)
sm.light_ray(d)
b('Reflection of (x₁, y₁) in Ax + By + C = 0?', r'\(\dfrac{x^{\prime}-x_1}{A} = \dfrac{y^{\prime}-y_1}{B} = \dfrac{-2(Ax_1 + By_1 + C)}{A^2 + B^2}\)')
b('Misc Q17: image of (3, 8) in x + 3y = 7.', 'Ax₁ + By₁ + C = 3 + 24 − 7 = 20 → −2·20/10 = −4: ' + N('(−1, −4)'))
b('Reflection of (a, b) in the axes and in y = x, y = −x?', 'x-axis: (a, −b); y-axis: (−a, b); y = x: (b, a); y = −x: (−b, −a)')
b('Example 12: distance of 4x − y = 0 from (4, 1) measured along a line at 135°.', 'Line x + y = 5 meets 4x − y = 0 at Q(1, 4): PQ = ' + N('3√2'))
b('Misc Q14: distance of 4x + 7y + 5 = 0 from (1, 2) along 2x − y = 0.', 'Point (1 + t/√5, 2 + 2t/√5): 23 + 18t/√5 = 0 → |t| = ' + N('23√5/18'))
b('Misc Q15: through (−1, 2) so that the intersection with x + y = 4 is 3 units away.', '(−1 + 3cos θ) + (2 + 3sin θ) = 4 → cos θ + sin θ = 1 → ' + N('θ = 0° or 90°') + ' (horizontal or vertical line)')
b('Misc Q16: hypotenuse ends (1, 3) and (−4, 1); legs parallel to the axes.', 'The right-angle vertex is (1, 1) or (−4, 3): legs ' + N('x = 1, y = 1') + ' or ' + N('x = −4, y = 3'))
b('Misc Q13: in what ratio does x + y = 4 divide the segment (−1, 1) to (5, 7)?', 'λ: (−1 + 5λ + 1 + 7λ)/(1 + λ) = 4 → 8λ = 4 → ' + N('1 : 2'))

# ---------------------------------------------------------------- How it's asked
d.sec('9.z-how-its-asked')
b('MCQ: The slope of the line through (2, 3) and (4, 7) is<br>(a) 1 (b) 2 (c) 1/2 (d) −2', '4/2 = ' + E('(b) 2'))
b('MCQ: The equation of the line with slope 3 and y-intercept −2 is<br>(a) y = 3x − 2 (b) y = −2x + 3 (c) 3y = x − 2 (d) y = 3x + 2', E('(a)'))
b('MCQ: The distance of (1, 2) from 3x + 4y − 5 = 0 is<br>(a) 1 (b) 2 (c) 3 (d) 6/5', '|3 + 8 − 5|/5 = ' + E('(d) 6/5'))
b('MCQ: The lines 2x + 3y = 5 and 3x − 2y = 7 are<br>(a) parallel (b) perpendicular (c) coincident (d) none', 'Slopes −2/3 and 3/2: product −1 → ' + E('(b)'))
b('MCQ: If the points (1, 2), (3, 4), (k, 6) are collinear, k =<br>(a) 4 (b) 5 (c) 6 (d) 3', 'Slope 1: (6 − 2)/(k − 1) = 1 → ' + E('(a) 4'))
b('MCQ: The angle between y = x and y = √3 x is<br>(a) 15° (b) 30° (c) 45° (d) 60°', '60° − 45° = ' + E('(a) 15°'))
b('Integer answer (JEE Main): the area of the triangle formed by x + y = 4 and the axes is?', 'Legs 4 and 4: ' + N('8'))
b('Integer answer: the distance between the lines 3x + 4y = 9 and 6x + 8y = 15 (as a multiple of 1/10).', '6x + 8y = 18 vs 15: |18 − 15|/10 = 3/10 → ' + N('3'))
b('Assertion–Reason.<br><b>A:</b> The slope of the y-axis is not defined.<br><b>R:</b> The y-axis makes an angle of 90° with the x-axis and tan 90° is not defined.<br>(a) Both true, R explains A (b) Both true, R does not explain A (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> If m₁m₂ = −1 the lines are perpendicular.<br><b>R:</b> tan θ = |(m₁ − m₂)/(1 + m₁m₂)| is undefined when m₁m₂ = −1.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)') + ': the angle is 90°')
b('True/False: the lines x − 2y = 3 and 2x − 4y = 7 are perpendicular.', X('False') + ': both have slope ½, so they are parallel')
b('3-mark: find the equation of the line through (2, 3) making equal intercepts on the axes.', 'x + y = 5 (and y = (3/2)x through the origin has intercepts 0, 0 if allowed). Standard answer ' + N('x + y = 5'))
b('4-mark: find the foot of the perpendicular from (1, 2) to x + y − 5 = 0 and the image.', 'Ax₁ + By₁ + C = −2, so t = −2/2 = −1: foot = (1 + 1, 2 + 1) = ' + N('(2, 3)') + '; image = (3, 4)')
b('Case-based: a road passes through A(0, 0) and B(4, 3). A well is at W(5, 0). Shortest distance from W to the road?', 'Road: 3x − 4y = 0; d = |15|/5 = ' + N('3 units'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
