import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch08-application-of-integrals')
d = Deck('Chapter 8: Application of Integrals', 'Class 12', ['class-12', 'mathematics', 'ch-8'])
d.description = 'Area under a curve with vertical and horizontal strips, areas of the circle and ellipse, curves that cross the axis, and areas between curves with exam-style problems.'
b = d.basic

# ---------------------------------------------------------------- 8.2 Area under simple curves
d.sec('8.2-area-under-curves')
b('Area under y = f(x) from x = a to x = b (f ≥ 0)?', T('A = ∫ₐᵇ y dx = ∫ₐᵇ f(x) dx') + ': the sum of thin vertical strips of height y and width dx (the elementary strip)')
b('Area bounded by x = g(y), the y-axis and the lines y = c, y = d?', T('A = ∫꜀ᵈ x dy = ∫꜀ᵈ g(y) dy') + ': horizontal strips of length x and width dy')
b('Which strips should you choose: vertical or horizontal?', 'Use ' + T('vertical strips') + ' when boundaries are naturally y = f(x); ' + T('horizontal strips') + ' when they are x = g(y) (e.g. y² = 4x). Pick the direction that lets you describe the region with one integral and no splitting')
sm.horizontal_strips_parabola(d)
b('What if the curve lies below the x-axis?', 'Then f(x) < 0 and ∫ₐᵇ f dx < 0. The area is its ' + T('absolute value') + ': A = |∫ₐᵇ f(x) dx|')
b('What if the curve crosses the x-axis between a and b?', 'Split at the zeros:<br>' + T('A = |A₁| + A₂ + ...') + '<br>Each Aᵢ is the integral over a sub-interval where f does not change sign')
b('Trap: is the area always equal to ∫ₐᵇ f(x) dx?', X('No') + ': only if f ≥ 0 on [a, b]. For y = sin x on [0, 2π] the integral is 0 but the area is 4')
b('Steps for an area problem.', '1) Sketch the region and find intersection points. 2) Decide vertical or horizontal strips. 3) Write area = ∫ (upper − lower) or ∫ (right − left). 4) Split where the upper or lower curve changes. 5) Integrate and give the answer in square units')

d.sec('8.2-circle-and-ellipse')
b('Example 1: area enclosed by the circle x² + y² = a².', '4 ∫₀ᵃ √(a² − x²) dx = 4[(x/2)√(a² − x²) + (a²/2) sin⁻¹(x/a)]₀ᵃ = ' + N('πa²'))
sm.ellipse_quarter(d)
b('Example 2: area of the ellipse x²/a² + y²/b² = 1?', N('πab') + '. Four times the first quadrant: 4 ∫₀ᵃ (b/a)√(a² − x²) dx')
b('Ex 8.1 Q1: area bounded by x²/16 + y²/9 = 1.', 'a = 4, b = 3: πab = ' + N('12π'))
b('Ex 8.1 Q2: area bounded by x²/4 + y²/9 = 1.', 'a = 2, b = 3: ' + N('6π'))
b('Ex 8.1 Q3: area in the first quadrant bounded by x² + y² = 4 and the lines x = 0, x = 2 is (A) π (B) π/2 (C) π/3 (D) π/4', 'Quarter of the circle of radius 2: π · 4/4 = ' + E('(A) π'))
b('Ex 8.1 Q4: area bounded by y² = 4x, the y-axis and y = 3 is (A) 2 (B) 9/4 (C) 9/3 (D) 9/2', '∫₀³ (y²/4) dy = [y³/12]₀³ = 27/12 = ' + E('(B) 9/4'))
b('Area of a semicircle of radius r and of a quarter ellipse?', N('πr²/2') + ' and ' + N('πab/4'))
b('Area of the region bounded by y = √(a² − x²) and the x-axis?', 'The upper half of the circle: ' + N('πa²/2'))

# ---------------------------------------------------------------- Miscellaneous
d.sec('8.3-miscellaneous')
b('Example 3: area of the region bounded by y = 3x + 2, the x-axis and the ordinates x = −1 and x = 1.', 'The line crosses the axis at x = −2/3. |∫₋₁^(−2/3) (3x + 2) dx| + ∫_(−2/3)^1 (3x + 2) dx = 1/6 + 25/6 = ' + N('13/3'))
sm.cos_area_sign(d)
b('Example 4: area bounded by y = cos x between x = 0 and x = 2π.', N('4') + ' (1 + 2 + 1, splitting at π/2 and 3π/2)')
b('Misc Q1(i): area under y = x², x = 1, x = 2 and the x-axis.', '∫₁² x² dx = [x³/3]₁² = ' + N('7/3'))
b('Misc Q1(ii): area under y = x⁴, x = 1, x = 5 and the x-axis.', '∫₁⁵ x⁴ dx = [x⁵/5]₁⁵ = (3125 − 1)/5 = ' + N('3124/5'))
b('Misc Q2: sketch y = |x + 3| and evaluate ∫₋₆⁰ |x + 3| dx.', 'A V with vertex (−3, 0). Two triangles of area ½ · 3 · 3 = 9/2 each: ' + N('9'))
b('Misc Q3: area bounded by y = sin x between x = 0 and x = 2π.', 'Two arches, each of area 2: ' + N('4'))
b('Misc Q4: area bounded by y = x³, the x-axis and the ordinates x = −2, x = 1 is (A) −9 (B) −15/4 (C) 15/4 (D) 17/4', 'Area = |∫₋₂⁰ x³| + ∫₀¹ x³ = 4 + 1/4 = ' + E('(D) 17/4'))
sm.cubic_negative_area(d)
b('Misc Q5: area bounded by y = x|x|, the x-axis and x = −1, x = 1 is (A) 0 (B) 1/3 (C) 2/3 (D) 4/3', 'y = x² for x > 0 and −x² for x < 0, so the areas above and below are equal: 2 ∫₀¹ x² dx = ' + E('(C) 2/3') + '. (The signed integral would be 0: option A is the trap.)')

# ---------------------------------------------------------------- Beyond: areas between curves
d.sec('8.z-area-between-curves')
b('Area between two curves y = f(x) (upper) and y = g(x) (lower) from x = a to b?', T('A = ∫ₐᵇ [f(x) − g(x)] dx') + '. Find a and b as the x-coordinates where the curves meet. If they cross, split there')
sm.area_between_parabolas(d)
b('Area between y = x and y = x²?', 'Meet at 0 and 1: ∫₀¹ (x − x²) dx = 1/2 − 1/3 = ' + N('1/6'))
b('Area between y = x² and y = 2x?', 'Meet at 0 and 2: ∫₀² (2x − x²) dx = 4 − 8/3 = ' + N('4/3'))
b('Area between y = x² and the line y = 4?', 'x from −2 to 2: ∫₋₂² (4 − x²) dx = 16 − 16/3 = ' + N('32/3'))
b('Area between y = x³ and y = x?', 'Meet at −1, 0, 1 and the curves swap sides at 0: 2 ∫₀¹ (x − x³) dx = 2(1/2 − 1/4) = ' + N('1/2'))
b('Area between y² = 4x and y = x?', 'Meet at 0 and 4: ∫₀⁴ (2√x − x) dx = 32/3 − 8 = ' + N('8/3'))
b('Area of the segment of the parabola y² = 4ax cut off by its latus rectum x = a?', '2 ∫₀ᵃ 2√(ax) dx = 4√a · (2/3) a^(3/2) = ' + N('8a²/3'))
b('Area between y² = 4ax and x² = 4ay?', N('16a²/3') + ' (4 × 4 case: 16/3)')
b('Area between y = sin x and y = cos x from x = 0 to π/4?', '∫₀^(π/4) (cos x − sin x) dx = [sin x + cos x]₀^(π/4) = √2 − 1: ' + N('√2 − 1'))
b('Area between y = sin x and y = cos x between two successive intersections (π/4 to 5π/4)?', '∫ (sin x − cos x) dx = [−cos x − sin x] = 2√2: ' + N('2√2'))
b('Area under y = |x| from x = −1 to 2?', 'Triangle 1/2 plus triangle 2: ' + N('5/2'))
b('Area under y = eˣ from 0 to 1, and under y = 1/x from 1 to e?', N('e − 1') + ' and ' + N('1'))
b('Area of a triangle with vertices (0, 0), (2, 0), (2, 3) by integration?', 'The hypotenuse is y = 3x/2: ∫₀² (3x/2) dx = ' + N('3'))
b('Area of the region enclosed by the circle x² + y² = 4 and the line x + y = 2 (smaller part)?', 'Quarter circle minus triangle: π − 2. ' + N('π − 2'))
b('Area between y = x² and y = |x|?', 'By symmetry 2 ∫₀¹ (x − x²) dx = ' + N('1/3'))

# ---------------------------------------------------------------- How it is asked
d.sec('8.z-how-its-asked')
b('MCQ: the area bounded by y = x², the x-axis and x = 3 is<br>(a) 9 (b) 27 (c) 9/2 (d) 3', '∫₀³ x² dx = 27/3 = ' + E('(a) 9'))
b('MCQ: the area of the ellipse x²/25 + y²/9 = 1 is<br>(a) 15π (b) 30π (c) 8π (d) 45π', 'πab = π · 5 · 3 = ' + E('(a) 15π'))
b('MCQ: the area of the circle x² + y² = 16 is<br>(a) 16π (b) 8π (c) 4π (d) 64π', 'r = 4: ' + E('(a) 16π'))
b('MCQ: the area of the region bounded by y = sin x, the x-axis, x = 0 and x = π is<br>(a) 2 (b) 1 (c) 0 (d) 4', E('(a) 2'))
b('MCQ: the area of the region between y = x and y = x² is<br>(a) 1/6 (b) 1/3 (c) 1/2 (d) 1', E('(a) 1/6'))
b('MCQ: the area between the parabola y² = 4x and the line x = 1 is<br>(a) 8/3 (b) 4/3 (c) 16/3 (d) 2', '2 ∫₀¹ 2√x dx = 4 · 2/3 = ' + E('(a) 8/3'))
b('MCQ: the area bounded by y = cos x, x = 0 and x = π/2 is<br>(a) 1 (b) 2 (c) 0 (d) 1/2', '[sin x]₀^(π/2) = ' + E('(a) 1'))
b('Integer answer (JEE Main): the area enclosed by y = 4 − x² and the x-axis is 32/k. Find k.', '∫₋₂² (4 − x²) dx = 32/3: k = ' + N('3'))
b('Integer answer: the area (in square units) of the region bounded by y = |x| and y = 2 is?', 'A triangle with base 4 and height 2: ' + N('4'))
b('Integer answer: the area of the region bounded by y = x³ and y = 8 and the y-axis is?', '∫₀⁸ y^(1/3) dy with horizontal strips = (3/4)(16) = ' + N('12'))
b('Assertion–Reason.<br><b>A:</b> the area under y = sin x from 0 to 2π is 0.<br><b>R:</b> ∫₀^(2π) sin x dx = 0.<br>(a) Both true, R explains A (b) A false, R true (c) A true, R false (d) Both false', E('(b)') + ': the area is 4; the integral is the signed value 0')
b('Assertion–Reason.<br><b>A:</b> the area of the ellipse x²/a² + y²/b² = 1 is πab.<br><b>R:</b> the area of a circle of radius r is πr².<br>(a) Both true, R explains A (b) Both true, R does not (c) A false, R true (d) A true, R false', E('(b)') + ': both true; the circle is the special case a = b = r but R alone does not give A')
b('True/False: the area of a region below the x-axis computed as ∫ f dx is negative, so we take its absolute value.', E('True'))
b('True/False: horizontal strips can never be used for y = f(x).', X('False') + ': they can, if you can solve for x in terms of y (for example, y = x³ becomes x = y^(1/3))')
b('2-mark: find the area under y = 2x from x = 0 to x = 3.', '∫₀³ 2x dx = ' + N('9'))
b('3-mark: find the area bounded by y = x², x = 1, x = 3 and the x-axis.', '[x³/3]₁³ = 9 − 1/3 = ' + N('26/3'))
b('3-mark: find the area of the circle x² + y² = 9 using integration.', '4 ∫₀³ √(9 − x²) dx = 4 · (9/2)(π/2) = ' + N('9π'))
b('4-mark: find the area between the curves y = x² and y = 2x.', 'Intersections x = 0, 2. ∫₀² (2x − x²) dx = ' + N('4/3'))
b('4-mark: find the area between y = sin x and the x-axis from 0 to 2π.', 'Split at π: 2 + |−2| = ' + N('4'))
b('Case-based: a garden is bounded by the x-axis and the curve y = 4x − x² (metres). Find its area.', 'The curve meets the axis at x = 0 and 4: ∫₀⁴ (4x − x²) dx = 32 − 64/3 = ' + N('32/3 m²'))
b('Case-based: a pond is shaped like the ellipse x²/100 + y²/64 = 1 (units in metres). What is its area?', 'a = 10, b = 8: πab = ' + N('80π m² ≈ 251 m²'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
