import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch11-introduction-to-three-dimensional-geometry')
d = Deck('Chapter 11: Introduction to Three Dimensional Geometry', 'Class 11', ['class-11', 'mathematics', 'ch-11'])
d.description = 'Coordinate axes and planes, octants, coordinates of a point, distance formula, section formula and centroid in space.'
b = d.basic

d.sec('11.2-axes-planes-octants')
b('Why do we need three coordinates to locate a point in space?', 'A point in space needs its distances from ' + T('three mutually perpendicular planes') + '<br>(like the floor and two walls of a room): x, y, z')
b('Coordinate axes and coordinate planes in 3-D?', 'Axes: three mutually perpendicular lines ' + T('X′OX, Y′OY, Z′OZ') + ' meeting at the origin O<br>Coordinate planes: the planes ' + T('XY, YZ, ZX') + ' they determine')
b('How many octants? What are they?', N('8') + ': the three coordinate planes divide space into eight parts. Numbered I to VIII')
table_card(d, '11.3 · Octants', 'Signs of (x, y, z).', [
    ('I', '(+, +, +)', False), ('II', '(−, +, +)', False), ('III', '(−, −, +)', False), ('IV', '(+, −, +)', False),
    ('V', '(+, +, −)', False), ('VI', '(−, +, −)', False), ('VII', '(−, −, −)', False), ('VIII', '(+, −, −)', False)], term='Signs of coordinates in the eight octants')
b('Mnemonic for the octants?', 'Octants I–IV are above the XY-plane (z > 0), in the plane quadrant order I, II, III, IV<br>Octants V–VIII are the same four quadrants below the plane (z < 0)')
b('Example 2: octants of (−3, 1, 2) and (−3, 1, −2).', N('II') + ' and ' + N('VI'))
b('Ex 11.1 Q3: octants of (1,2,3), (4,−2,3), (4,−2,−5), (4,2,−5).', N('I, IV, VIII, V'))
b('Ex 11.1 Q3: octants of (−4,2,−5), (−4,2,5), (−3,−1,6), (−2,−4,−7).', N('VI, II, III, VII'))
b('Ex 11.1: a point is on the x-axis. Its y and z coordinates? A point is in the XZ-plane. Its y-coordinate?', N('y = 0, z = 0') + ';  ' + N('y = 0'))
b('Points on the axes and planes: general forms?', 'x-axis (x, 0, 0); y-axis (0, y, 0); z-axis (0, 0, z); XY-plane (x, y, 0); YZ-plane (0, y, z); ZX-plane (x, 0, z)')
b('Ex 11.1 Q4: fill in: the x- and y-axes determine the ____; points in the XY-plane are of the form ____; the coordinate planes divide space into ____ octants.', N('XY-plane') + ';  ' + N('(x, y, 0)') + ';  ' + N('eight'))
b('What do x, y, z of a point P represent?', 'The perpendicular ' + T('distances from the YZ, ZX and XY planes') + ' (with sign)')
sm.point_in_space(d)
b('Example 1: P is (2, 4, 5); F is the foot on the ZX-plane? Find F.', 'F has zero distance along OY: ' + N('(2, 0, 5)'))
b('Distance of P(x, y, z) from the three axes and the three planes?', 'From the x-axis √(y² + z²), y-axis √(x² + z²), z-axis √(x² + y²); from the YZ, ZX, XY planes |x|, |y|, |z|')
b('Reflection of (x, y, z) in the XY-plane, in the x-axis, in the origin?', 'XY-plane: ' + T('(x, y, −z)') + '; x-axis: ' + T('(x, −y, −z)') + '; origin: ' + T('(−x, −y, −z)'))
b('Foot of the perpendicular from (x, y, z) to the XY-plane, to the x-axis?', T('(x, y, 0)') + ' and ' + T('(x, 0, 0)'))

d.sec('11.4-distance')
b('Distance between P(x₁, y₁, z₁) and Q(x₂, y₂, z₂)?', r'\(PQ = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}\)')
b('Distance of Q(x, y, z) from the origin?', r'\(OQ = \sqrt{x^2 + y^2 + z^2}\)')
sm.space_diagonal(d)
b('Example 3: distance between P(1, −3, 4) and Q(−4, 1, 2).', '√(25 + 16 + 4) = √45 = ' + N('3√5'))
b('Example 4: show P(−2, 3, 5), Q(1, 2, 3), R(7, 0, −1) are collinear.', 'PQ = √14, QR = √56 = 2√14, PR = √126 = 3√14: ' + T('PQ + QR = PR') + ' → collinear')
b('Method: three points collinear in space?', 'Check that the ' + T('largest distance equals the sum of the other two') + '<br>(or that the direction ratios are proportional)')
b('Example 5: are A(3,6,9), B(10,20,30), C(25,−41,5) vertices of a right triangle?', 'AB² = 686, BC² = 4571, CA² = 2709. No pair adds to the third (686 + 2709 = 3395 ≠ 4571): ' + N('not a right triangle'))
b('Example 6: locus of P with PA² + PB² = 2k², A(3,4,5), B(−1,3,−7).', N('2x² + 2y² + 2z² − 4x − 14y + 4z = 2k² − 109'))
b('Ex 11.2 Q1: distances between (2,3,5)&(4,3,1); (−3,7,2)&(2,4,−1); (−1,3,−4)&(1,−3,4); (2,−1,3)&(−2,1,3).', N('2√5') + ';  ' + N('√43') + ';  ' + N('2√26') + ';  ' + N('2√5'))
b('Ex 11.2 Q3(i): (0,7,−10), (1,6,−6), (4,9,−6): isosceles?', 'Sides 3√2, 3√2, 6 (using √18, √18, √36): two equal sides → ' + N('isosceles'))
b('Ex 11.2 Q3(ii): (0,7,10), (−1,6,6), (−4,9,6): right-angled?', 'Sides² = 18, 18, 36 and 18 + 18 = 36 → ' + N('right angle at (−1, 6, 6)'))
b('Ex 11.2 Q3(iii): (−1,2,1), (1,−2,5), (4,−7,8), (2,−3,4): parallelogram?', 'AB = CD = 6 and BC = DA = √43: opposite sides equal → ' + N('parallelogram'))
b('Ex 11.2 Q4: the set of points equidistant from (1, 2, 3) and (3, 2, −1).', 'Equate squared distances: −2x − 6z + 10 = −6x + 2z + 10 → ' + N('x − 2z = 0') + '<br>It is a plane: the perpendicular bisector plane')
b('Ex 11.2 Q5: points P with PA + PB = 10, A(4,0,0), B(−4,0,0).', 'A surface of revolution of the ellipse x²/25 + y²/9 = 1 about the x-axis: ' + N('9x² + 25y² + 25z² = 225'))
b('Example 7: A(1,2,3), B(−1,−2,−1), C(2,3,2), D(4,7,6): parallelogram but not a rectangle?', 'AB = CD = 6 and BC = DA = √43 → parallelogram. Diagonals AC = √3 and BD = √155 are unequal → ' + N('not a rectangle'))
b('Example 8: equidistant from A(3,4,−5) and B(−2,1,4).', N('10x + 6y − 18z − 29 = 0'))
b('Method: the set of points equidistant from two points.', 'Square PA = PB and expand.<br>The squares cancel and you get a ' + T('linear equation: a plane') + '<br>(the perpendicular bisector plane of AB)')
b('Locus with PA² + PB² = constant: shape?', 'A ' + T('sphere') + ' centred at the midpoint of AB (x², y², z² all appear with the same coefficient)')

d.sec('11.z-section-formula-centroid')
b('Beyond the textbook text (Class 12 and JEE): section formula for P dividing AB internally in the ratio m : n?', r'\(\left(\dfrac{mx_2 + nx_1}{m+n},\ \dfrac{my_2 + ny_1}{m+n},\ \dfrac{mz_2 + nz_1}{m+n}\right)\)' + ' (external: replace n by −n)')
b('Midpoint and centroid formulas in space?', 'Midpoint ' + T('((x₁ + x₂)/2, (y₁ + y₂)/2, (z₁ + z₂)/2)') + '; centroid of a triangle ' + T('((x₁ + x₂ + x₃)/3, …)') + '; of a tetrahedron divide by 4')
b('Example 9: centroid (1, 1, 1), A(3, −5, 7), B(−1, 7, −6). Find C.', '(3 − 1 + x)/3 = 1, (−5 + 7 + y)/3 = 1, (7 − 6 + z)/3 = 1 → ' + N('C = (1, 1, 2)'))
b('Misc Q1: parallelogram ABCD with A(3, −1, 2), B(1, 2, −4), C(−1, 1, 2). Find D.', 'Diagonals bisect: D = A + C − B = ' + N('(1, −2, 8)'))
b('Misc Q2: lengths of the medians of the triangle A(0,0,6), B(0,4,0), C(6,0,0).', 'Midpoints (3,2,0), (3,0,3), (0,2,3): lengths ' + N('7, √34, 7'))
b('Misc Q3: origin is the centroid of P(2a, 2, 6), Q(−4, 3b, −10), R(8, 14, 2c). Find a, b, c.', '2a − 4 + 8 = 0; 2 + 3b + 14 = 0; 6 − 10 + 2c = 0 → ' + N('a = −2, b = −16/3, c = 2'))
b('Misc Q4: PA² + PB² = k², A(3,4,5), B(−1,3,−7).', N('2x² + 2y² + 2z² − 4x − 14y + 4z = k² − 109'))
b('Equation of a sphere with centre (a, b, c) and radius r?', T('(x − a)² + (y − b)² + (z − c)² = r²') + '; x² + y² + z² = r² for a sphere at the origin')
b('Length of the diagonal of a cuboid with edges l, b, h?', r'\(\sqrt{l^2 + b^2 + h^2}\)' + '. Cube of side a: a√3')
b('Show A, B, C are collinear using the section formula: how?', 'Find the ratio λ from one coordinate and check the other two coordinates give the same ratio')

d.sec('11.z-how-its-asked')
b('MCQ: The distance of (3, 4, 12) from the origin is<br>(a) 5 (b) 12 (c) 13 (d) 19', '√(9 + 16 + 144) = ' + E('(c) 13'))
b('MCQ: The point (−2, 3, −1) lies in the octant<br>(a) II (b) VI (c) III (d) VII', '(−, +, −) → ' + E('(b) VI'))
b('MCQ: The distance of P(2, 3, 4) from the x-axis is<br>(a) 5 (b) 2 (c) √13 (d) √20', '√(3² + 4²) = ' + E('(a) 5'))
b('MCQ: The distance of (1, 2, 3) from the XY-plane is<br>(a) 1 (b) 2 (c) 3 (d) 6', E('(c) 3') + ' = |z|')
b('MCQ: The image of (1, 2, 3) in the YZ-plane is<br>(a) (−1, 2, 3) (b) (1, −2, 3) (c) (1, 2, −3) (d) (−1, −2, −3)', 'Only x changes sign: ' + E('(a)'))
b('Integer answer (JEE Main): the distance between (1, 2, 3) and (4, 6, 15) is?', '√(9 + 16 + 144) = ' + N('13'))
b('Assertion–Reason.<br><b>A:</b> The points (0, 0, 0), (1, 1, 1), (2, 2, 2) are collinear.<br><b>R:</b> Distances 0→1: √3, 1→2: √3, 0→2: 2√3 add up.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('True/False: the distance formula in 3-D reduces to the 2-D formula when z₁ = z₂.', E('True') + ': the (z₂ − z₁)² term vanishes')
b('3-mark: show that the points (0, 7, 10), (−1, 6, 6), (−4, 9, 6) form a right triangle.', 'Squared sides 18, 18, 36 with 18 + 18 = 36 (Pythagoras converse) → right angle at ' + N('(−1, 6, 6)'))
b('Case-based: a drone moves from (0, 0, 0) to (30, 40, 120) metres (z is height). Straight-line distance?', '√(900 + 1600 + 14400) = ' + N('130 m'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
