import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch01-relations-and-functions')
d = Deck('Chapter 1: Relations and Functions', 'Class 12', ['class-12', 'mathematics', 'ch-1'])
d.description = 'Types of relations, equivalence relations and classes, one-one and onto functions, composition, inverse, counting functions and relations, with exam-style problems.'
b = d.basic

# ---------------------------------------------------------------- 1.1 Relations
d.sec('1.1-relations')
b('Define a relation R from A to B.', 'Any ' + T('subset of A × B') + '. If (a, b) ∈ R we write a R b. There need be no “meaning” connecting a and b')
b('Empty and universal relation on a set A?', T('Empty') + ': R = φ (nothing is related). ' + T('Universal') + ': R = A × A (everything is related to everything). Both are “trivial” relations')
b('Example 1: on the students of a boys’ school, is “a is sister of b” empty or universal? And “heights differ by less than 3 m”?', 'No student has a sister in the school: ' + N('empty') + '. Every height difference is under 3 m: ' + N('universal (A × A)'))
b('Define reflexive, symmetric, transitive.', T('Reflexive') + ': (a, a) ∈ R ∀ a.<br>' + T('Symmetric') + ': (a, b) ∈ R ⇒ (b, a) ∈ R.<br>' + T('Transitive') + ': (a, b), (b, c) ∈ R ⇒ (a, c) ∈ R')
b('What is an equivalence relation?', 'A relation that is ' + T('reflexive, symmetric and transitive') + ' (all three)')
sm.rst_digraph(d)
b('Trap: “symmetric and transitive, so it must be reflexive” (use (a,b),(b,a),(a,a)).', X('False') + '. R = {(1, 2), (2, 1), (1, 1), (2, 2)} on {1, 2, 3} is symmetric and transitive but 3 is unrelated to itself: not reflexive. Every element of A must have (a, a)')
b('Which pairs decide transitivity?', 'Only chains: (a, b) and (b, c) both in R force (a, c). If there is no such chain the relation is ' + T('vacuously transitive') + ' (e.g. R = {(1, 2)} is transitive, R = φ is symmetric and transitive)')
b('Example 3: L = lines in a plane, L₁ R L₂ iff L₁ ⟂ L₂. Which properties?', T('Symmetric only') + '.<br>' + X('Not reflexive') + ': a line is not ⟂ to itself.<br>' + X('Not transitive') + ': L₁ ⟂ L₂ ⟂ L₃ gives L₁ ∥ L₃, so (L₁, L₃) ∉ R')
b('Example 2: T₁ R T₂ iff T₁ is congruent to T₂ (triangles). Which properties?', E('Equivalence relation') + ': congruent to itself; if T₁ ≅ T₂ then T₂ ≅ T₁; T₁ ≅ T₂ ≅ T₃ gives T₁ ≅ T₃')
b('Example 5: R = {(a, b) : 2 divides a − b} on Z. Show it is an equivalence relation.', 'Reflexive: a − a = 0 is even. Symmetric: b − a = −(a − b) is even. Transitive: a − c = (a − b) + (b − c) is even. ' + E('Equivalence ✓'))
sm.equiv_classes_mod3(d)
b('What is an equivalence class [a]? What do the classes do to the set?', T('[a] = {b : (a, b) ∈ R}') + ', all elements related to a. The classes are ' + T('non-empty, mutually disjoint, and their union is the whole set') + ': a partition. Conversely every partition gives an equivalence relation')
b('Example 5: the classes of “2 divides a − b” on Z?', T('[0] = even integers') + '<br>' + T('[1] = odd integers') + '<br>[0] = [2r], [1] = [2r + 1], [0] ≠ [1]<br>Z = E ∪ O with E ∩ O = φ')
b('Example 6: R = {(a, b) : a and b both odd or both even} on {1, ..., 7}. Its classes?', E('{1, 3, 5, 7}') + ' and ' + E('{2, 4, 6}') + '. Elements of one are related to each other, none related across')
b('Example 18: R₁, R₂ equivalence relations on A. Is R₁ ∩ R₂ an equivalence relation? R₁ ∪ R₂?', E('R₁ ∩ R₂ is') + ' an equivalence relation (each property survives intersection).<br>' + X('R₁ ∪ R₂ need not be') + ': it can fail transitivity.<br>Example on {1, 2, 3}: R₁ = {1, 2 together}, R₂ = {2, 3 together} give (1, 2) and (2, 3) but not (1, 3)')
b('Example 19: (x, y) R (u, v) iff xv = yu on pairs of positive integers. Equivalence? What is it saying?', E('Yes') + '. It says ' + T('x/y = u/v') + ': two pairs are related when they are the same fraction. Transitivity: xv = yu and ub = va give x/y = u/v = a/b')
b('Example 21: f : X → Y, R = {(a, b) : f(a) = f(b)}. Type of relation?', E('Equivalence relation') + '. Reflexive, symmetric, transitive all come from equality of values. Its classes are the ' + T('fibres (preimages) f⁻¹(y)'))
b('Example 20: R₁ = “x − y divisible by 3” on {1,...,9} equals R₂ = “x, y in the same one of {1,4,7}, {2,5,8}, {3,6,9}”. Why?', 'Each block is one residue class mod 3, so two numbers differ by a multiple of 3 exactly when they are in the same block: ' + N('R₁ = R₂'))

d.sec('1.1-exercise-1-1')
b('Ex 1.1 Q1(i): R = {(x, y) : 3x − y = 0} on A = {1, ..., 14}. Reflexive, symmetric, transitive?', 'R = {(1,3), (2,6), (3,9), (4,12)}. (1, 1) ∉ R: not reflexive. (1, 3) ∈ R but (3, 1) ∉ R: not symmetric. (1,3), (3,9) ∈ R but (1, 9) ∉ R: not transitive. ' + N('None of the three'))
b('Ex 1.1 Q1(ii): R = {(x, y) : y = x + 5 and x < 4} on N. Properties?', 'R = {(1,6), (2,7), (3,8)}. Not reflexive, not symmetric. No chain (b, c) starts from a second coordinate (6, 7, 8 are not first coordinates), so transitive holds vacuously: ' + N('transitive only'))
b('Ex 1.1 Q1(iii): R = {(x, y) : y is divisible by x} on {1, ..., 6}. Properties?', T('Reflexive') + ': x | x.<br>' + X('Not symmetric') + ': 2 | 4 but 4 ∤ 2.<br>' + T('Transitive') + ': x | y and y | z ⇒ x | z.<br>' + N('Reflexive and transitive, not symmetric'))
b('Ex 1.1 Q1(iv): R = {(x, y) : x − y is an integer} on Z. Properties?', 'x − y is always an integer, so R = Z × Z is the universal relation: ' + E('equivalence relation'))
b('Ex 1.1 Q1(v)(a),(b): “work at the same place”, “live in the same locality”?', E('Both are equivalence relations') + '.<br>“Same place” and “same locality” are reflexive, symmetric and transitive.<br>The classes are the workplaces / localities')
b('Ex 1.1 Q1(v)(c): “x is exactly 7 cm taller than y”. Properties?', X('None') + ': x is not 7 cm taller than x; if x is 7 cm taller than y then y is not taller than x; and x is 14 cm taller than z, not 7 cm')
b('Ex 1.1 Q1(v)(d),(e): “x is wife of y” and “x is father of y”?', '(d) not reflexive, not symmetric (y is not the wife of x), but ' + T('transitive (vacuously)') + '. (e) neither reflexive, symmetric nor transitive (father of father is grandfather)')
b('Ex 1.1 Q2: show R = {(a, b) : a ≤ b²} on R is neither reflexive, symmetric nor transitive.', 'Reflexive fails: ½ ≤ ¼ is false, so (½, ½) ∉ R. Symmetric fails: (1, 4) ∈ R (1 ≤ 16) but (4, 1) ∉ R (4 ≤ 1 is false). Transitive fails: (3, 2) ∈ R (3 ≤ 4) and (2, 1.5) ∈ R (2 ≤ 2.25) but (3, 1.5) ∉ R (3 ≤ 2.25 false)')
b('Ex 1.1 Q3: R = {(a, b) : b = a + 1} on {1, ..., 6}. Properties?', 'R = {(1,2), (2,3), (3,4), (4,5), (5,6)}. (1,1) ∉ R; (1,2) ∈ R but (2,1) ∉ R; (1,2), (2,3) ∈ R but (1,3) ∉ R. ' + N('None of the three'))
b('Ex 1.1 Q4: R = {(a, b) : a ≤ b} on R. Properties?', E('Reflexive') + ' (a ≤ a), ' + E('transitive') + ' (a ≤ b ≤ c ⇒ a ≤ c), ' + X('not symmetric') + ' (1 ≤ 2 but 2 ≰ 1). This is a partial order, not an equivalence relation')
b('Ex 1.1 Q5: R = {(a, b) : a ≤ b³} on R. Properties?', 'Not reflexive: ½ ≰ (½)³ = ⅛. Not symmetric: (1, 2) ∈ R but 2 ≰ 1. Not transitive: (10, 3): 10 ≤ 27, (3, 1.5): 3 ≤ 3.375, but 10 ≤ (1.5)³ = 3.375 is false. ' + N('None of the three'))
b('Ex 1.1 Q6: R = {(1, 2), (2, 1)} on {1, 2, 3}. Show symmetric but neither reflexive nor transitive.', 'Symmetric: (1,2) and (2,1) both there. Not reflexive: (1,1) ∉ R. Not transitive: (1,2), (2,1) ∈ R but (1,1) ∉ R')
b('Ex 1.1 Q7: R = {(x, y) : x and y books with the same number of pages}. Show equivalence.', 'Same page count:<br>' + T('Reflexive') + ' (a book has its own page count)<br>' + T('Symmetric') + ' (equality is symmetric)<br>' + T('Transitive') + ' (equality is transitive)<br>' + E('Equivalence ✓') + ': the classes are the books with a given page count')
b('Ex 1.1 Q8: R = {(a, b) : |a − b| is even} on {1, 2, 3, 4, 5}. Equivalence? Classes?', 'Even difference ⇔ same parity, so equivalence. Classes ' + N('{1, 3, 5}') + ' and ' + N('{2, 4}') + ': none related across (an odd and an even number differ by an odd number)')
b('Ex 1.1 Q9: A = {0, ..., 12}. R = {(a, b) : |a − b| is a multiple of 4}. Elements related to 1?', 'Equivalence (same remainder mod 4). Need |1 − b| ∈ {0, 4, 8, 12}: ' + N('{1, 5, 9}') + '. For R = {(a, b) : a = b} only ' + N('{1}'))
b('Ex 1.1 Q10: give an example of a relation on {1, 2, 3} that is (i) symmetric not reflexive nor transitive, (ii) transitive not reflexive nor symmetric.', '(i) {(1,2), (2,1)}. (ii) {(1,2)}: no chain, so vacuously transitive; not symmetric, not reflexive')
b('Ex 1.1 Q10 (iii)–(v): reflexive+symmetric not transitive; reflexive+transitive not symmetric; symmetric+transitive not reflexive.', '(iii) {(1,1),(2,2),(3,3),(1,2),(2,1),(2,3),(3,2)}: (1,2),(2,3) but no (1,3). (iv) {(1,1),(2,2),(3,3),(1,2)}. (v) {(1,2),(2,1),(1,1),(2,2)}: 3 is not related to itself')
b('Ex 1.1 Q11: R = {(P, Q) : OP = OQ} for points of the plane. Class of P ≠ (0, 0)?', 'Same distance from the origin is an equivalence relation. The class of P is all points at distance OP: ' + N('the circle through P with centre O'))
b('Ex 1.1 Q12: T₁ (3,4,5), T₂ (5,12,13), T₃ (6,8,10). Under “similar to”, which are related?', 'Similar triangles have proportional sides: 6:8:10 = 3:4:5, so ' + N('T₁ and T₃') + ' are related; T₂ is not')
b('Ex 1.1 Q13: R = {(P₁, P₂) : same number of sides} on polygons. Class of the 3-4-5 triangle?', N('The set of all triangles') + ' (all polygons with 3 sides)')
b('Ex 1.1 Q14: R = {(L₁, L₂) : L₁ ∥ L₂} on lines in the XY plane. Lines related to y = 2x + 4?', 'Parallel ⇔ same slope 2: ' + N('all lines y = 2x + c, c ∈ R'))
b('Ex 1.1 Q15: R = {(1,2), (2,2), (1,1), (4,4), (1,3), (3,3), (3,2)} on {1,2,3,4}. Choose: (A) reflexive, symmetric not transitive (B) reflexive, transitive not symmetric (C) symmetric, transitive not reflexive (D) equivalence', 'All four (a, a) present: reflexive. (1,2) ∈ R, (2,1) ∉ R: not symmetric. (1,3),(3,2) give (1,2) ✓: transitive. ' + E('(B)'))
b('Ex 1.1 Q16: R = {(a, b) : a = b − 2, b > 6} on N. Which pair is in R? (A) (2,4) (B) (3,8) (C) (6,8) (D) (8,7)', 'Need b > 6 and a = b − 2.<br>(6, 8): 8 > 6 and 6 = 8 − 2 ✓<br>(2, 4) and (3, 8) fail a = b − 2 (and 4 is not above 6)<br>(8, 7) fails a = b − 2.<br>' + E('(C)'))

# ---------------------------------------------------------------- 1.2 Types of functions
d.sec('1.2-types-of-functions')
b('Define one-one (injective).', T('f(x₁) = f(x₂) ⇒ x₁ = x₂') + ' for all x₁, x₂. Distinct elements have distinct images; otherwise f is many-one')
b('Define onto (surjective).', T('Every y ∈ Y is f(x) for some x ∈ X') + ', equivalently ' + T('range = codomain'))
b('Define bijective.', 'One-one ' + T('and') + ' onto')
b('Why is “range = codomain” the same as onto?', 'Range = the set of values actually hit; codomain = the set we declared. If every codomain element is hit they are equal; if some element is missed, range ⊊ codomain')
sm.inj_surj_panels(d)
b('How do you prove f is one-one? How do you prove it is onto?', T('One-one') + ':<br>1) Assume f(x₁) = f(x₂).<br>2) Derive x₁ = x₂.<br>' + T('Onto') + ':<br>1) Take any y in the codomain.<br>2) Solve y = f(x) for x.<br>3) Check that x lies in the domain')
b('How do you disprove one-one? Disprove onto?', T('Not one-one') + ': exhibit two different inputs with the same output, e.g. f(−1) = f(1).<br>' + T('Not onto') + ': exhibit one codomain element with no input, e.g. −2 = x² has no real x')
sm.horizontal_line_test(d)
b('Example 8: f : N → N, f(x) = 2x. One-one? Onto?', E('One-one') + ' (2x₁ = 2x₂ ⇒ x₁ = x₂), ' + X('not onto') + ': 1 = 2x has no natural solution (odd numbers are missed)')
b('Example 9: f : R → R, f(x) = 2x. One-one and onto?', E('Both') + '.<br>Given y ∈ R, x = y/2 ∈ R and f(y/2) = y.<br>' + T('Same rule, bigger domain and codomain, now onto') + ' (compare Example 8)')
b('Trap: does a function’s rule alone decide one-one/onto?', X('No') + ': the ' + T('domain and codomain') + ' matter.<br>f(x) = 2x is not onto N → N but is onto R → R<br>x² is not one-one on R but is one-one on [0, ∞)')
b('Example 10: f : N → N, f(1) = f(2) = 1, f(x) = x − 1 for x > 2. One-one? Onto?', X('Not one-one') + ' (f(1) = f(2) = 1). ' + E('Onto') + ': for y ≠ 1 take x = y + 1 (> 2), f(y + 1) = y; and f(1) = 1')
b('Example 11: f : R → R, f(x) = x². One-one? Onto?', X('Neither') + ': f(−1) = f(1) = 1 and −2 is not a square')
b('Example 12: f(x) = x + 1 (x odd), x − 1 (x even), on N. Bijective?', E('Yes') + '. It swaps 1 ↔ 2, 3 ↔ 4, 5 ↔ 6, …: an involution, so f(f(x)) = x and f is its own inverse. If f(x₁) = f(x₂) with x₁ odd, x₂ even then x₂ − x₁ = 2, impossible (odd and even differ by an odd number)')
b('Example 7: A = 50 students, f : A → N, f(x) = roll number. One-one? Onto?', E('One-one') + ' (roll numbers are distinct) but ' + X('not onto N') + ' (51 is no student’s roll number)')
b('Examples 13 and 14: f : {1, 2, 3} → {1, 2, 3}. Onto ⇒ one-one? One-one ⇒ onto?', E('Both true') + ' for any ' + T('finite set X') + ' and f : X → X. Not true for infinite sets: f(x) = 2x on N is one-one not onto; Example 10 is onto not one-one. This is the difference between finite and infinite')
b('Pigeonhole view: A and B finite, f : A → B one-one. What do you know about n(A), n(B)?', T('n(A) ≤ n(B)') + '. If f is onto then n(A) ≥ n(B); if bijective then n(A) = n(B)')

d.sec('1.2-exercise-1-2')
b('Ex 1.2 Q1: f : R* → R*, f(x) = 1/x. One-one and onto? What if the domain is N (codomain R* as before)?', '1/x₁ = 1/x₂ ⇒ x₁ = x₂; and y ∈ R* has source 1/y ∈ R*: bijective. With domain N: ' + X('still one-one but not onto') + ' (e.g. 2/3 has 3/2 ∉ N as a source)')
b('Ex 1.2 Q2(i),(ii): f(x) = x² on N → N and Z → Z.', 'N → N: ' + N('one-one, not onto') + ' (2 is not a perfect square). Z → Z: ' + N('neither') + ' (f(−1) = f(1), and −1, 2 are not squares)')
b('Ex 1.2 Q2(iii)–(v): f(x) = x² on R → R; x³ on N → N; x³ on Z → Z.', 'x² on R: ' + N('neither') + '<br>x³ on N: ' + N('one-one, not onto') + ' (2 is not a cube)<br>x³ on Z: ' + N('one-one, not onto') + ' (2 is not a cube of an integer)')
b('Ex 1.2 Q3: greatest integer function f(x) = [x] on R → R is neither one-one nor onto. Why?', 'f(1.2) = f(1.5) = 1: not one-one. Range = Z ⊊ R (e.g. 0.5 has no source): not onto')
b('Ex 1.2 Q4: modulus f(x) = |x| on R → R. Why neither?', 'f(−2) = f(2) = 2: not one-one. Range = [0, ∞), so −1 is not attained: not onto')
b('Ex 1.2 Q5: signum function on R → R. Why neither?', 'Values are only −1, 0, 1. f(2) = f(3) = 1: not one-one; range {−1, 0, 1} ≠ R: not onto')
b('Ex 1.2 Q6: A = {1,2,3}, B = {4,5,6,7}, f = {(1,4), (2,5), (3,6)}. Show one-one.', 'Distinct inputs 1, 2, 3 go to distinct outputs 4, 5, 6: ' + E('one-one') + ' (not onto: 7 is missed)')
b('Ex 1.2 Q7(i): f : R → R, f(x) = 3 − 4x. One-one? Onto?', 'f(x₁) = f(x₂) ⇒ −4x₁ = −4x₂ ⇒ x₁ = x₂. For y take x = (3 − y)/4. ' + E('Bijective') + ' (any non-constant linear function R → R is)')
b('Ex 1.2 Q7(ii): f : R → R, f(x) = 1 + x². One-one? Onto?', X('Neither') + ': f(−1) = f(1) = 2; range [1, ∞) so 0 has no source')
b('Ex 1.2 Q8: f : A × B → B × A, f(a, b) = (b, a). Bijective?', 'If (b₁, a₁) = (b₂, a₂) then a₁ = a₂, b₁ = b₂: one-one. Any (b, a) ∈ B × A is f(a, b): onto. ' + E('Bijective') + ' (it is its own “swap” inverse)')
b('Ex 1.2 Q9: f : N → N, f(n) = (n + 1)/2 for n odd, n/2 for n even. Bijective?', 'f(1) = 1 and f(2) = 1: ' + X('not one-one') + ', so not bijective (it is onto: every m has source 2m). Answer ' + N('No'))
b('Ex 1.2 Q10: f : R − {3} → R − {1}, f(x) = (x − 2)/(x − 3). One-one and onto?', 'f(x₁) = f(x₂) ⇒ (x₁ − 2)(x₂ − 3) = (x₂ − 2)(x₁ − 3) ⇒ x₁ = x₂. Solving y = (x − 2)/(x − 3): x = (3y − 2)/(y − 1), defined for y ≠ 1. ' + E('Yes, bijective'))
b('Ex 1.2 Q11: f : R → R, f(x) = x⁴. (A) one-one onto (B) many-one onto (C) one-one not onto (D) neither', 'f(−1) = f(1): not one-one. Range [0, ∞), −1 missed: not onto. ' + E('(D)'))
b('Ex 1.2 Q12: f : R → R, f(x) = 3x. (A) one-one onto (B) many-one onto (C) one-one not onto (D) neither', 'Linear with non-zero slope: ' + E('(A) one-one and onto'))

# ---------------------------------------------------------------- 1.3 Composition and inverse
d.sec('1.3-composition-and-inverse')
b('Define the composition gof.', 'f : A → B, g : B → C. Then ' + T('gof : A → C, gof(x) = g(f(x))') + ': f acts first, g second. Needs range of f ⊂ domain of g')
sm.composition_chain(d)
b('Example 16: f(x) = cos x, g(x) = 3x². Find gof and fog. Are they equal?', 'gof(x) = g(cos x) = ' + T('3 cos²x') + '; fog(x) = f(3x²) = ' + T('cos 3x²') + '. At x = 0: gof = 3 but fog = 1. ' + X('gof ≠ fog'))
b('Is composition commutative? associative?', X('Not commutative') + ' (gof ≠ fog in general). ' + E('Associative') + ': (hog)of = ho(gof). ' + T('f o I = I o f = f') + ' for the identity')
b('Compose: f(x) = 2x + 1, g(x) = x². Find gof(3), fog(3).', 'f(3) = 7, gof(3) = g(7) = ' + N('49') + '. g(3) = 9, fog(3) = f(9) = ' + N('19'))
b('If f is one-one and g is one-one, is gof one-one? If both onto?', E('Yes') + ' in both cases. And if gof is one-one then ' + T('f is one-one') + '; if gof is onto then ' + T('g is onto') + ' (the outer/inner function that must “carry” the property)')
b('Definition of invertible function.', 'f : X → Y is invertible if ∃ g : Y → X with ' + T('gof = I_X') + ' and ' + T('fog = I_Y') + '. Then g = f⁻¹')
b('Which functions are invertible?', T('Exactly the bijections') + ' (one-one and onto). One-one makes the inverse single-valued, onto makes it defined on all of Y')
sm.inverse_mirror(d)
b('Example 17: f : N → Y, f(x) = 4x + 3, Y = {4x + 3 : x ∈ N}. Show invertible and find the inverse.', 'f is one-one and onto Y. From y = 4x + 3: x = (y − 3)/4. So ' + N('g(y) = (y − 3)/4') + '. Check: g(f(x)) = (4x + 3 − 3)/4 = x and f(g(y)) = 4(y − 3)/4 + 3 = y')
b('Method: find f⁻¹ of a bijection.', '1) Write y = f(x). 2) Solve for x in terms of y. 3) Swap names: f⁻¹(x) = that expression. 4) Check f⁻¹(f(x)) = x. The domain of f⁻¹ is the range of f')
b('Find the inverse of f(x) = (2x + 1)/(x − 3) (x ≠ 3).', 'y(x − 3) = 2x + 1 → x(y − 2) = 3y + 1 → ' + N('f⁻¹(x) = (3x + 1)/(x − 2)') + ' (x ≠ 2). Note f⁻¹ has the same form, with the roles of the numbers rearranged')
b('If f and g are invertible, what is (gof)⁻¹?', T('f⁻¹ o g⁻¹') + ' (socks and shoes: undo the last step first)')
b('Trap: is f⁻¹(x) the same as 1/f(x)?', X('No') + '. f⁻¹ is the inverse function (undoes f). 1/f(x) is the reciprocal. For f(x) = 2x: f⁻¹(x) = x/2 but 1/f(x) = 1/(2x)')
b('When is f = f⁻¹ (an involution)?', 'When f(f(x)) = x. Examples: f(x) = 1/x, f(x) = −x + c, and Example 12 (swapping 1 ↔ 2, 3 ↔ 4, …). The graph is symmetric about y = x')
b('Domain restriction: f(x) = x² is not invertible on R. How to make it invertible?', 'Restrict to ' + T('[0, ∞) → [0, ∞)') + ': now one-one and onto, with inverse √x. Restricting to (−∞, 0] gives the inverse −√x')

# ---------------------------------------------------------------- Miscellaneous
d.sec('1.4-miscellaneous-examples')
b('Example 22: number of one-one functions from {1, 2, 3} to itself?', 'Each is a permutation of 3 symbols: ' + N('3! = 6') + '. In general n! for a set of n elements (Misc Q4)')
b('Example 23: A = {1,2,3}. How many relations contain (1,2) and (2,3) and are reflexive and transitive but not symmetric?', 'Forced: the diagonal, (1,2), (2,3) and, by transitivity, (1,3). That is R₁. Add (2,1) alone: still transitive, not symmetric. Add (3,2) alone: same. Adding (3,1), or two of the missing pairs, forces every pair and the relation becomes symmetric. So ' + N('3') + ': R₁, R₁ ∪ {(2,1)}, R₁ ∪ {(3,2)}')
b('Example 24: number of equivalence relations on {1, 2, 3} containing (1, 2) and (2, 1)?', 'Smallest: {(1,1),(2,2),(3,3),(1,2),(2,1)} (classes {1,2}, {3}). Relating 3 to either forces everything (universal). ' + N('2'))
b('Example 25: I_N is onto. Is I_N + I_N (x ↦ 2x) onto N → N?', X('No') + ': 3 ∈ N has no natural x with 2x = 3. Sum of onto functions need not be onto')
b('Example 26: f = sin, g = cos on [0, π/2]. One-one? Is f + g one-one?', 'sin and cos are each strictly monotone there: one-one. But (f + g)(0) = 1 = (f + g)(π/2), so ' + X('f + g is not one-one'))
b('Misc Q1: f : R → (−1, 1), f(x) = x/(1 + |x|). One-one and onto?', 'For x ≥ 0, f = x/(1 + x) ∈ [0, 1); for x < 0, f = x/(1 − x) ∈ (−1, 0). Solving y = x/(1 + |x|): x = y/(1 − |y|). ' + E('Bijective') + ' (a stretched “S-curve” squeezing R into (−1, 1))')
b('Misc Q2: f : R → R, f(x) = x³ is injective. Proof?', 'x₁³ = x₂³ ⇒ (x₁ − x₂)(x₁² + x₁x₂ + x₂²) = 0. The second factor is > 0 unless both are 0, so ' + N('x₁ = x₂'))
b('Misc Q3: on P(X), ARB iff A ⊂ B. Equivalence relation?', T('Reflexive') + ' ✓ (A ⊂ A)<br>' + T('Transitive') + ' ✓<br>' + X('Not symmetric') + ': {1} ⊂ {1, 2} but {1, 2} ⊄ {1}<br>' + N('No') + ', it is a partial order')
b('Misc Q4: number of onto functions from {1, 2, ..., n} to itself?', 'For a finite set onto ⇔ one-one ⇔ permutation: ' + N('n!'))
b('Misc Q5: A = {−1,0,1,2}, B = {−4,−2,0,2}, f(x) = x² − x, g(x) = 2|x − ½| − 1. Are f = g?', 'f at −1, 0, 1, 2: 2, 0, 0, 2<br>g at −1, 0, 1, 2: 2·1.5 − 1 = 2, then 0, 0, 2<br>' + E('Equal') + ': same domain, same codomain, same value at every point')
b('Misc Q6: A = {1,2,3}. Relations containing (1,2) and (1,3), reflexive and symmetric, not transitive: (A) 1 (B) 2 (C) 3 (D) 4', 'Forced: diagonal plus (1,2), (2,1), (1,3), (3,1). Missing (2,3), (3,2): adding one alone breaks symmetry, adding both makes it universal (transitive). So exactly ' + E('(A) 1'))
b('Misc Q7: A = {1,2,3}. Equivalence relations containing (1, 2): (A) 1 (B) 2 (C) 3 (D) 4', 'Partitions with 1 and 2 together: {1,2}{3} and {1,2,3}. ' + E('(B) 2'))
b('Two equal functions: what must match?', 'Same ' + T('domain') + '<br>Same ' + T('codomain') + '<br>f(x) = g(x) for every x in the domain (Misc Q5)<br>' + X('Trap') + ': f(x) = x on R and f(x) = √(x²) are different functions')

# ---------------------------------------------------------------- Counting
d.sec('1.z-counting-functions-and-relations')
b('n(A) = m, n(B) = n. Number of functions A → B?', N('nᵐ') + ': each of the m inputs chooses one of n outputs')
b('n(A) = m, n(B) = n. Number of one-one functions A → B?', N('ⁿPₘ = n(n − 1)···(n − m + 1)') + ' (0 if m > n). Example: from {1,2,3} to a 5-set: 5·4·3 = 60')
b('Number of onto functions from an m-set onto an n-set?', 'Inclusion–exclusion: ' + T('Σₖ (−1)ᵏ ⁿCₖ (n − k)ᵐ') + '<br>Two useful cases:<br>onto from an m-set to a 2-set is ' + N('2ᵐ − 2') + '<br>onto from a 4-set to a 3-set is ' + N('36'))
b('Number of bijections from an n-set to itself?', N('n!'))
b('Number of relations from A to B and on A (n(A) = n)?', 'A → B: ' + N('2^(mn)') + ' (subsets of A × B). On A: ' + N('2^(n²)'))
b('Number of reflexive relations on an n-set? Of symmetric ones?', T('Reflexive') + ': diagonal forced, the other n² − n pairs are free: ' + N('2^(n² − n)') + '<br>' + T('Symmetric') + ': choose each unordered pair and each loop: ' + N('2^(n(n+1)/2)') + '<br>For n = 3 both are 64')
b('Number of reflexive AND symmetric relations on an n-set?', N('2^(n(n − 1)/2)') + ' (only the off-diagonal unordered pairs are free). n = 3: 8')
b('Number of equivalence relations on sets of size 1, 2, 3, 4, 5?', 'Number of partitions (Bell numbers): ' + N('1, 2, 5, 15, 52'))
b('Number of equivalence relations on {1, 2, 3, 4} containing (1, 2)?', 'Partitions of {1,2,3,4} where 1 and 2 are together = partitions of {12, 3, 4} = ' + N('5'))
b('Number of symmetric relations on {1, 2, 3} containing (1, 2)?', 'Free unordered pairs/loops: 6 in total, one fixed: ' + N('2⁵ = 32'))
b('f : A → B is one-one with n(A) = 4 and n(B) = 3. Possible?', X('No') + ': one-one needs n(A) ≤ n(B) (pigeonhole). Six or more distinct outputs would be needed')
b('f : {1, 2, 3} → {a, b, c}. How many are neither one-one nor onto?', 'Total 27; bijections 6; for finite equal sets onto ⇔ one-one, so neither = 27 − 6 = ' + N('21'))

# ---------------------------------------------------------------- How it is asked
d.sec('1.z-how-its-asked')
b('MCQ: R = {(1,1), (2,2), (3,3), (1,2), (2,1)} on {1,2,3} is<br>(a) reflexive only (b) symmetric only (c) transitive only (d) equivalence', 'Reflexive ✓; symmetric ✓; transitive: (1,2),(2,1) ⇒ (1,1) ✓; (2,1),(1,2) ⇒ (2,2) ✓. ' + E('(d) equivalence'))
b('MCQ: R = {(a, b) : a ≤ b} on R is<br>(a) equivalence (b) reflexive and transitive only (c) symmetric only (d) none', E('(b)') + ': partial order')
b('MCQ: on Z, R = {(a, b) : a − b is divisible by 5}. Number of equivalence classes?<br>(a) 1 (b) 2 (c) 4 (d) 5', 'One class per remainder 0–4: ' + E('(d) 5'))
b('MCQ: f : R → R, f(x) = x|x| is<br>(a) one-one, not onto (b) onto, not one-one (c) bijective (d) neither', 'Increasing (−x² for x < 0, x² for x ≥ 0), and every real is attained: ' + E('(c) bijective'))
b('MCQ: f : R → R, f(x) = sin x is<br>(a) one-one (b) onto (c) both (d) neither', 'sin(0) = sin(π), range [−1, 1] ≠ R: ' + E('(d) neither'))
b('MCQ: f : R → R, f(x) = x³ + x. Then f is<br>(a) one-one, not onto (b) many-one (c) bijective (d) neither', 'Strictly increasing (f′ = 3x² + 1 > 0) and cubic (goes to ±∞): ' + E('(c) bijective'))
b('MCQ: f : [0, ∞) → [0, ∞), f(x) = x². f is<br>(a) one-one not onto (b) onto not one-one (c) bijective (d) neither', E('(c)') + '. Compare f : R → R, where it is neither')
b('MCQ: f(x) = 2x + 3, g(x) = x². (fog)(2) =<br>(a) 11 (b) 49 (c) 7 (d) 25', 'g(2) = 4, f(4) = 11: ' + E('(a) 11'))
b('MCQ: f(x) = (x − 1)/(x + 1). f(f(x)) =<br>(a) x (b) −1/x (c) 1/x (d) −x', 'f(f(x)) = ((x − 1)/(x + 1) − 1) / ((x − 1)/(x + 1) + 1) = −2/(2x) = ' + E('(b) −1/x'))
b('MCQ: f : R → R, f(x) = 5x − 3. f⁻¹(x) =<br>(a) (x + 3)/5 (b) (x − 3)/5 (c) 5x + 3 (d) 1/(5x − 3)', 'y = 5x − 3 → x = (y + 3)/5: ' + E('(a)'))
b('MCQ: number of one-one functions from {1, 2, 3} to {a, b, c, d, e} is<br>(a) 15 (b) 60 (c) 125 (d) 243', '5 × 4 × 3 = ' + E('(b) 60'))
b('MCQ: number of onto functions from {1, 2, 3, 4} to {a, b, c} is<br>(a) 36 (b) 81 (c) 24 (d) 12', '3⁴ − 3·2⁴ + 3 = 81 − 48 + 3 = ' + E('(a) 36'))
b('MCQ: number of reflexive relations on a set with 3 elements is<br>(a) 8 (b) 64 (c) 512 (d) 9', '2^(9 − 3) = ' + E('(b) 64'))
b('Integer answer (JEE Main): number of equivalence relations on {a, b, c, d} containing (a, b)?', 'Partitions of {ab, c, d} = ' + N('5'))
b('Integer answer: n(A) = 3, n(B) = 4. Number of one-one functions A → B?', '4 · 3 · 2 = ' + N('24'))
b('Assertion–Reason.<br><b>A:</b> f : R → R, f(x) = x² is not invertible.<br><b>R:</b> f is not one-one.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)') + ': invertible ⇔ bijective; f(−1) = f(1) shows f is not one-one (and also not onto)')
b('Assertion–Reason.<br><b>A:</b> A relation on {1, 2, 3} that is symmetric and transitive is reflexive.<br><b>R:</b> (a, b) and (b, a) give (a, a).<br>(a) Both true, R explains A (b) A false, R true (c) A true, R false (d) Both false', E('(b)') + ': R is true only for elements that appear in some pair; an isolated element (like 3 in {(1,2),(2,1),(1,1),(2,2)}) breaks A')
b('True/False: every reflexive relation on a set with two or more elements is symmetric.', X('False') + ': {(1,1), (2,2), (1,2)} is reflexive but not symmetric')
b('True/False: if f : A → B is onto and A, B are finite with n(A) = n(B), then f is one-one.', E('True') + ': finite sets, same size: onto ⇔ one-one')
b('2-mark: check whether R = {(x, y) : x + y = 6} on {1, ..., 5} is reflexive, symmetric or transitive.', 'R = {(1,5), (2,4), (3,3), (4,2), (5,1)}. Not reflexive ((1,1) ∉ R). ' + T('Symmetric') + ' (x + y = y + x). Not transitive: (1,5), (5,1) ∈ R but (1,1) ∉ R')
b('3-mark: show that f : R → R, f(x) = (2x − 1)/3 is bijective and find f⁻¹.', 'f(x₁) = f(x₂) ⇒ x₁ = x₂ (one-one). For y take x = (3y + 1)/2 (onto). ' + N('f⁻¹(x) = (3x + 1)/2'))
b('3-mark: f(x) = x + 5 on Z. Show that f is invertible; find f⁻¹.', 'One-one (x₁ + 5 = x₂ + 5), onto (y − 5 ∈ Z is a source). ' + N('f⁻¹(y) = y − 5'))
b('4-mark: show that R = {(a, b) : a − b is divisible by 3} on Z is an equivalence relation. Find [1].', 'Reflexive (0), symmetric (negation), transitive (sum). ' + N('[1] = {…, −5, −2, 1, 4, 7, …} = {3r + 1}'))
b('4-mark: show that f : R → R, f(x) = x² + 1 is neither one-one nor onto. Restrict the domain and codomain to make it a bijection.', 'f(−1) = f(1) = 2 and 0 ∉ range. Take ' + N('f : [0, ∞) → [1, ∞)') + ': one-one (x ≥ 0) and onto ([1, ∞) is exactly the range), with f⁻¹(y) = √(y − 1)')
b('Case-based: the relation “sits in the same bench” on the students of a class (each student sits on exactly one bench). What type of relation is it? What are its equivalence classes?', E('Equivalence relation') + ' (each student is on the same bench as themselves; symmetric; transitive). The classes are ' + N('the benches (groups of students on the same bench)'))
b('Case-based: a school assigns each student in a class a roll number, f(x) = roll number, A = 40 students, codomain N. One-one? Onto? Make it a bijection.', E('One-one') + ' (no two share a roll number), ' + X('not onto N') + '.<br>Restrict the codomain to {1, …, 40}: then f is a bijection and invertible')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
