import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch05-continuity-and-differentiability')
d = Deck('Chapter 5: Continuity and Differentiability', 'Class 12', ['class-12', 'mathematics', 'ch-5'])
d.description = 'Continuity, algebra of continuous functions, differentiability, chain rule, implicit, inverse trig, exponential and logarithmic differentiation, parametric forms, second derivatives, and exam-style problems.'
b = d.basic

# ---------------------------------------------------------------- 5.2 Continuity
d.sec('5.2-continuity')
b('Definition of continuity of f at x = c.', 'f is continuous at c if ' + T('lim x→c f(x) = f(c)') + '. That means the left limit, the right limit and f(c) all exist and are equal')
b('What three things must hold for continuity at c?', '(1) f(c) is defined; (2) lim x→c f(x) exists (left limit = right limit); (3) the limit equals f(c). Breaking any one gives a point of discontinuity')
sm.discontinuity_types(d)
b('What does “f is continuous” mean for a function on an interval [a, b]?', 'Continuous at every interior point, ' + T('right-continuous at a') + ' (lim x→a⁺ f(x) = f(a)) and ' + T('left-continuous at b') + ' (lim x→b⁻ f(x) = f(b))')
b('Pen test for continuity?', 'Can you draw the graph around the point ' + T('without lifting the pen') + '? A jump, hole, or blow-up forces you to lift it. (A function like 1/x is continuous on its domain, though its graph has a gap at 0 where it is not defined)')
b('Example 1: continuity of f(x) = 2x + 3 at x = 1?', 'lim x→1 (2x + 3) = 5 = f(1): ' + E('continuous'))
b('Example 3: is f(x) = |x| continuous at 0? Everywhere?', 'Left limit lim(−x) = 0, right limit 0, f(0) = 0: ' + E('continuous at 0') + '. It is continuous at every real number (Example 7)')
b('Example 4: f(x) = x³ + 3 (x ≠ 0), f(0) = 1. Continuous at 0?', 'lim x→0 f(x) = 3 but f(0) = 1: ' + X('not continuous') + '. A removable discontinuity (fix f(0) = 3)')
b('Example 5 and 6: which constant functions and the identity function are continuous?', E('All of them, at every real number') + ': lim x→c k = k and lim x→c x = c')
b('Example 10: f(x) = x + 2 (x ≤ 1), x − 2 (x > 1). Points of discontinuity?', 'At x = 1: left limit 3, right limit −1, differ. So ' + N('x = 1 is the only point of discontinuity') + ' (a jump)')
b('Example 12: f(x) = x + 2 (x < 0), −x + 2 (x > 0). Continuous?', 'f is not defined at 0, so 0 is not in the domain; f is continuous at every point of its domain. ' + E('Yes, continuous'))
b('Example 13: f(x) = x² (x < 0), x (x ≥ 0). Continuous?', 'At 0: left limit 0, right limit 0, f(0) = 0. Elsewhere f is a polynomial: ' + E('continuous everywhere'))
b('Example 15: greatest integer function [x]. Where is it discontinuous?', 'At ' + N('every integer c') + ': left limit c − 1, right limit c (a jump of 1). Continuous at all non-integers')
b('Which functions are continuous everywhere on their domains?', T('Polynomials') + ', ' + T('rational functions') + ' (except where the denominator is 0), ' + T('|x|, sin x, cos x, tan x') + ' (tan on its domain), exponentials, logarithms (x > 0), inverse trig on their domains')
b('Theorem 1: algebra of continuous functions.', 'If f, g are continuous at c: ' + T('f + g, f − g, f·g, λf') + ' are continuous at c, and ' + T('f/g') + ' too provided g(c) ≠ 0')
b('Theorem 2: continuity of a composite function.', 'If g is continuous at c and f is continuous at g(c), then ' + T('f∘g is continuous at c') + '. Example 19: sin(x²) is continuous; Example 20: |1 − x + |x|| is continuous')
b('Example 17: how is the continuity of sin x proved?', 'x = c + h, so lim x→c sin x = lim h→0 [sin c cos h + cos c sin h] = sin c · 1 + cos c · 0 = ' + N('sin c') + ', using cos h → 1 and sin h → 0')

d.sec('5.2-exercise-5-1')
b('Ex 5.1 Q1: prove f(x) = 5x − 3 is continuous at x = 0, −3 and 5.', 'A polynomial: lim x→c (5x − 3) = 5c − 3 = f(c) for c = 0, −3, 5. ' + E('✓') + ' (values −3, −18, 22)')
b('Ex 5.1 Q2: continuity of f(x) = 2x² − 1 at x = 3.', 'lim x→3 (2x² − 1) = 17 = f(3): ' + E('continuous'))
b('Ex 5.1 Q3: which of these are continuous? (a) x − 5 (b) 1/(x − 5), x ≠ 5 (c) (x² − 25)/(x + 5), x ≠ −5 (d) |x − 5|', T('All four are continuous') + ' on their domains: (a) polynomial, (b) rational, (c) equals x − 5 wherever defined, (d) composition of |x| and x − 5. (b) and (c) simply have no point at 5 and −5 in the domain')
b('Ex 5.1 Q4: prove f(x) = xⁿ (n a positive integer) is continuous at x = n.', 'lim x→n xⁿ = nⁿ = f(n) (a polynomial, or product of n continuous functions x). ' + E('✓'))
b('Ex 5.1 Q5: f(x) = x (x ≤ 1), 5 (x > 1). Continuous at 0? at 1? at 2?', 'At 0: f = x near 0, ' + E('continuous') + '. At 1: left limit 1, right limit 5: ' + X('not continuous') + '. At 2: f = 5 near 2: ' + E('continuous'))
b('Ex 5.1 Q6: f(x) = 2x + 3 (x ≤ 2), 2x − 3 (x > 2). Points of discontinuity?', 'At 2: left limit 7, right limit 1. ' + N('Discontinuous at x = 2'))
b('Ex 5.1 Q7: f(x) = |x| + 3 (x ≤ −3), −2x (−3 < x < 3), 6x + 2 (x ≥ 3). Points of discontinuity?', 'At −3: left 6, right 6, f = 6: continuous. At 3: left −6, right 20: ' + N('discontinuous at x = 3'))
b('Ex 5.1 Q8: f(x) = |x|/x (x ≠ 0), 0 (x = 0).', 'For x > 0, f = 1; for x < 0, f = −1: left limit −1, right limit 1. ' + N('Discontinuous at x = 0'))
b('Ex 5.1 Q9: f(x) = x/|x| (x < 0), −1 (x ≥ 0).', 'For x < 0, x/|x| = −1. So f = −1 everywhere: ' + E('no point of discontinuity'))
b('Ex 5.1 Q10: f(x) = x + 1 (x ≥ 1), x² + 1 (x < 1).', 'At 1: left limit 2, right limit 2, f(1) = 2: ' + E('no point of discontinuity'))
b('Ex 5.1 Q11: f(x) = x³ − 3 (x ≤ 2), x² + 1 (x > 2).', 'At 2: left limit 5, right limit 5, f(2) = 5: ' + E('no point of discontinuity'))
b('Ex 5.1 Q12: f(x) = x¹⁰ − 1 (x ≤ 1), x² (x > 1).', 'At 1: left limit 0, right limit 1: ' + N('discontinuous at x = 1'))
b('Ex 5.1 Q13: f(x) = x + 5 (x ≤ 1), x − 5 (x > 1). Continuous?', 'At 1: left limit 6, right limit −4: ' + X('not continuous at x = 1'))
b('Ex 5.1 Q14: f = 3 (0 ≤ x ≤ 1), 4 (1 < x < 3), 5 (3 ≤ x ≤ 10).', 'Jumps at x = 1 (3 → 4) and x = 3 (4 → 5): ' + N('discontinuous at x = 1 and x = 3'))
b('Ex 5.1 Q15: f = 2x (x < 0), 0 (0 ≤ x ≤ 1), 4x (x > 1).', 'At 0: left limit 0, f = 0: continuous. At 1: left value 0, right limit 4: ' + N('x = 1 is the only point of discontinuity'))
b('Ex 5.1 Q16: f = −2 (x ≤ −1), 2x (−1 < x ≤ 1), 2 (x > 1).', 'At −1: left −2, right −2 ✓. At 1: left 2, right 2 ✓. ' + E('Continuous everywhere'))
b('Ex 5.1 Q17: f(x) = ax + 1 (x ≤ 3), bx + 3 (x > 3). Find the relation between a and b for continuity at 3.', '3a + 1 = 3b + 3 → 3a − 3b = 2 → ' + N('a = b + 2/3'))
b('Ex 5.1 Q18: f(x) = λ(x² − 2x) (x ≤ 0), 4x + 1 (x > 0). Continuity at 0 and at 1?', 'At 0: left limit 0, right limit 1. ' + N('No value of λ makes it continuous at 0') + '. At 1: f = 4x + 1 nearby, continuous for any λ')
sm.sawtooth_fractional(d)
b('Ex 5.1 Q20: is f(x) = x² − sin x + 5 continuous at x = π?', 'A sum of continuous functions: ' + E('yes') + '. lim x→π f = π² − 0 + 5 = f(π)')
b('Ex 5.1 Q21: continuity of (a) sin x + cos x (b) sin x − cos x (c) sin x · cos x.', 'Sums, differences and products of the continuous functions sin and cos: ' + E('all continuous everywhere'))
b('Ex 5.1 Q22: discuss the continuity of cos x, cosec x, sec x, cot x.', T('cos x') + ' continuous for all x. ' + T('cosec x') + ' and ' + T('cot x') + ' continuous except x = nπ. ' + T('sec x') + ' continuous except x = (2n + 1)π/2 (n ∈ Z)')
b('Ex 5.1 Q23: f(x) = sin x/x (x < 0), x + 1 (x ≥ 0). Points of discontinuity?', 'At 0: left limit lim sin x/x = 1, f(0) = 1, right limit 1. ' + E('No point of discontinuity'))
b('Ex 5.1 Q24: f(x) = x² sin(1/x) (x ≠ 0), 0 (x = 0). Continuous?', 'Squeeze: |x² sin(1/x)| ≤ x² → 0 = f(0). ' + E('Continuous for all x'))
b('Ex 5.1 Q25: f(x) = sin x − cos x (x ≠ 0), −1 (x = 0). Continuous?', 'lim x→0 (sin x − cos x) = −1 = f(0): ' + E('continuous for all x'))
b('Ex 5.1 Q26: find k so that f(x) = k cos x/(π − 2x) (x ≠ π/2), 3 (x = π/2) is continuous at π/2.', 'Put x = π/2 + h: cos x = −sin h and π − 2x = −2h, so the limit is k/2. Set k/2 = 3: ' + N('k = 6'))
b('Ex 5.1 Q27: find k so that f = kx² (x ≤ 2), 3 (x > 2) is continuous at 2.', '4k = 3 → ' + N('k = 3/4'))
b('Ex 5.1 Q28: find k so that f = kx + 1 (x ≤ π), cos x (x > π) is continuous at π.', 'kπ + 1 = cos π = −1 → ' + N('k = −2/π'))
b('Ex 5.1 Q29: find k so that f = kx + 1 (x ≤ 5), 3x − 5 (x > 5) is continuous at 5.', '5k + 1 = 10 → ' + N('k = 9/5'))
b('Ex 5.1 Q30: find a, b so that f = 5 (x ≤ 2), ax + b (2 < x < 10), 21 (x ≥ 10) is continuous.', 'At 2: 2a + b = 5. At 10: 10a + b = 21. Subtract: 8a = 16: ' + N('a = 2, b = 1'))
b('Ex 5.1 Q31–33: show cos(x²), |cos x|, |sin x| are continuous.', 'Each is a composite of continuous functions (cos and x²; |·| and cos; |·| and sin). By Theorem 2: ' + E('continuous'))
b('Ex 5.1 Q34: find all points of discontinuity of f(x) = |x| − |x + 1|.', 'A difference of continuous functions: ' + N('no point of discontinuity') + ' (f = 1 for x < −1, −2x − 1 for −1 ≤ x < 0, −1 for x ≥ 0)')
b('Trap: is a function continuous if lim x→c f(x) exists?', X('Not necessarily') + ': the limit must also equal f(c). Example: f(x) = 1 (x ≠ 0), f(0) = 2 has a limit at 0 but is discontinuous there')
b('Trap: does a formula like f(x) = (x² − 1)/(x − 1) have a discontinuity at 1?', 'It is undefined at 1: a ' + T('removable discontinuity') + '. Defining f(1) = 2 makes it continuous (it equals x + 1 elsewhere)')

# ---------------------------------------------------------------- 5.3 Differentiability
d.sec('5.3-differentiability')
b('Definition of the derivative of f at c.', T("f′(c) = lim h→0 [f(c + h) − f(c)]/h") + ', when the limit exists (the slope of the tangent at c)')
b('When is f differentiable at c? What are LHD and RHD?', 'When the ' + T('left derivative (LHD)') + ' lim h→0⁻ [f(c + h) − f(c)]/h equals the ' + T('right derivative (RHD)') + ' lim h→0⁺ [...]/h and both are finite')
sm.smooth_vs_corner(d)
sm.diff_implies_cont(d)
b('Trap: “f is continuous at c, so f′(c) exists”?', X('False') + '. |x| at 0 and ∛x at 0 are continuous but not differentiable. Only the reverse holds (differentiable ⇒ continuous)')
b('Ex 5.2 Q9: show f(x) = |x − 1| is not differentiable at x = 1.', 'LHD = lim h→0⁻ (|h| − 0)/h = −1; RHD = lim h→0⁺ |h|/h = +1. ' + X('LHD ≠ RHD'))
b('Ex 5.2 Q10: show [x] is not differentiable at x = 1 and x = 2.', '[x] is not even continuous at integers (left limit c − 1, right limit c), so it cannot be differentiable there. ' + X('Not differentiable'))
b('Chain rule: if y = f(u) and u = g(x), dy/dx = ?', T('dy/dx = (dy/du)·(du/dx)') + ' (differentiate the outside, then multiply by the derivative of the inside). For several layers multiply all links')
b('Example 21: differentiate sin(x²).', 'Let t = x²: d/dx sin t = cos t · 2x = ' + N('2x cos x²'))

d.sec('5.3-exercise-5-2')
b('Standard derivatives to know (list).', 'd/dx: xⁿ → nxⁿ⁻¹; sin x → cos x; cos x → −sin x; tan x → sec²x; cot x → −cosec²x; sec x → sec x tan x; cosec x → −cosec x cot x; eˣ → eˣ; log x → 1/x; aˣ → aˣ log a')
b('Standard derivatives of inverse trig functions.', 'sin⁻¹x → ' + T('1/√(1 − x²)') + ', cos⁻¹x → ' + T('−1/√(1 − x²)') + ', tan⁻¹x → ' + T('1/(1 + x²)') + ', cot⁻¹x → −1/(1 + x²), sec⁻¹x → 1/(|x|√(x² − 1)), cosec⁻¹x → −1/(|x|√(x² − 1))')
b('Ex 5.2 Q1: differentiate sin(x² + 5).', 'Chain rule: ' + N('2x cos(x² + 5)'))
b('Ex 5.2 Q2: differentiate cos(sin x).', 'Outer: −sin(sin x); inner: cos x. ' + N('−cos x · sin(sin x)'))
b('Ex 5.2 Q3: differentiate sin(ax + b).', N('a cos(ax + b)'))
b('Ex 5.2 Q4: differentiate sec(tan(√x)).', 'sec(u) tan(u) · du/dx with u = tan √x and du/dx = sec²√x/(2√x): ' + N('sec(tan√x) · tan(tan√x) · sec²√x / (2√x)'))
b('Ex 5.2 Q5: differentiate sin(ax + b)/cos(cx + d).', 'Quotient rule: ' + N('a cos(ax + b) sec(cx + d) + c sin(ax + b) tan(cx + d) sec(cx + d)'))
b('Ex 5.2 Q6: differentiate cos x³ · sin²(x⁵).', 'Product rule: ' + N('−3x² sin x³ · sin²x⁵ + 10x⁴ sin x⁵ cos x⁵ · cos x³'))
b('Ex 5.2 Q7: differentiate 2√(cot x²).', 'y = 2(cot x²)^½, y′ = (cot x²)^(−½)(−cosec²x²)(2x): ' + N('−2√2 x / (sin x² √(sin 2x²))'))
b('Ex 5.2 Q8: differentiate cos(√x).', N('−sin√x/(2√x)'))

d.sec('5.3-implicit-differentiation')
b('Implicit differentiation: method.', 'Differentiate both sides with respect to x, treating y as a function of x (so d/dx yⁿ = n yⁿ⁻¹ · dy/dx and d/dx sin y = cos y · dy/dx). Collect the dy/dx terms and solve')
b('Example 23: find dy/dx if y + sin y = cos x.', 'dy/dx + cos y · dy/dx = −sin x → ' + N('dy/dx = −sin x/(1 + cos y)') + ', y ≠ (2n + 1)π')
b('Ex 5.3 Q1: 2x + 3y = sin x.', '2 + 3y′ = cos x → ' + N('y′ = (cos x − 2)/3'))
b('Ex 5.3 Q2: 2x + 3y = sin y.', '2 + 3y′ = y′ cos y → ' + N('y′ = 2/(cos y − 3)'))
b('Ex 5.3 Q3: ax + by² = cos y.', 'a + 2by · y′ = −sin y · y′ → ' + N('y′ = −a/(2by + sin y)'))
b('Ex 5.3 Q4: xy + y² = tan x + y.', 'y + xy′ + 2yy′ = sec²x + y′ → ' + N('y′ = (sec²x − y)/(x + 2y − 1)'))
b('Ex 5.3 Q5: x² + xy + y² = 100.', '2x + y + xy′ + 2yy′ = 0 → ' + N('y′ = −(2x + y)/(x + 2y)'))
b('Ex 5.3 Q6: x³ + x²y + xy² + y³ = 81.', '3x² + 2xy + x²y′ + y² + 2xyy′ + 3y²y′ = 0 → ' + N('y′ = −(3x² + 2xy + y²)/(x² + 2xy + 3y²)'))
b('Ex 5.3 Q7: sin²y + cos xy = κ.', '2 sin y cos y · y′ − sin(xy)(y + xy′) = 0 → ' + N('y′ = y sin xy / (sin 2y − x sin xy)'))
b('Ex 5.3 Q8: sin²x + cos²y = 1.', '2 sin x cos x − 2 cos y sin y · y′ = 0 → ' + N('y′ = sin 2x/sin 2y'))
b('Method: differentiating inverse trig expressions like sin⁻¹(2x/(1 + x²)).', 'Simplify first by a substitution (x = tan θ, sin θ, cos θ, …) to a multiple of one inverse function, then differentiate. This turns a heavy chain rule into a one-line answer (Ex 5.3 Q9–Q15)')
b('Ex 5.3 Q9: y = sin⁻¹(2x/(1 + x²)).', 'x = tan θ: y = sin⁻¹(sin 2θ) = 2 tan⁻¹x (valid for |x| ≤ 1). ' + N('dy/dx = 2/(1 + x²)'))
b('Ex 5.3 Q10: y = tan⁻¹((3x − x³)/(1 − 3x²)), −1/√3 < x < 1/√3.', 'x = tan θ: y = tan⁻¹(tan 3θ) = 3 tan⁻¹x. ' + N('dy/dx = 3/(1 + x²)'))
b('Ex 5.3 Q11: y = cos⁻¹((1 − x²)/(1 + x²)), 0 < x < 1.', 'x = tan θ: y = cos⁻¹(cos 2θ) = 2θ. ' + N('dy/dx = 2/(1 + x²)'))
b('Ex 5.3 Q12: y = sin⁻¹((1 − x²)/(1 + x²)), 0 < x < 1.', 'x = tan θ: (1 − x²)/(1 + x²) = cos 2θ, y = sin⁻¹(cos 2θ) = π/2 − 2θ. ' + N('dy/dx = −2/(1 + x²)'))
b('Ex 5.3 Q13: y = cos⁻¹(2x/(1 + x²)), −1 < x < 1.', 'x = tan θ: y = cos⁻¹(sin 2θ) = π/2 − 2θ. ' + N('dy/dx = −2/(1 + x²)'))
b('Ex 5.3 Q14: y = sin⁻¹(2x√(1 − x²)), −1/√2 < x < 1/√2.', 'x = sin θ: y = sin⁻¹(sin 2θ) = 2θ. ' + N('dy/dx = 2/√(1 − x²)'))
b('Ex 5.3 Q15: y = sec⁻¹(1/(2x² − 1)), 0 < x < 1/√2.', 'sec⁻¹(1/u) = cos⁻¹u, so y = cos⁻¹(2x² − 1) = 2 cos⁻¹x (x = cos θ). ' + N('dy/dx = −2/√(1 − x²)'))
b('Example 24: derivative of sin⁻¹x?', 'y = sin⁻¹x → x = sin y → 1 = cos y · y′ → y′ = 1/cos y = ' + N('1/√(1 − x²)') + ' (cos y ≥ 0 on the principal branch)')

# ---------------------------------------------------------------- 5.4 Exponential and logarithmic
d.sec('5.4-exponential-and-logarithmic')
sm.exp_slope_equals_height(d)
b('Derivative of aˣ (a > 0)?', T('aˣ log a') + '. Since aˣ = e^(x log a), the chain rule gives e^(x log a) · log a. For a = e this is eˣ')
b('Derivative of log x, and of logₐ x?', T('d/dx log x = 1/x') + ' (x > 0). ' + T('d/dx logₐ x = 1/(x log a)') + '. Also d/dx log|x| = 1/x for x ≠ 0')
b('Relation between eˣ and log x?', 'Inverses: ' + T('e^(log x) = x') + ' for x > 0 and ' + T('log(eˣ) = x') + ' for all real x. Example 25: x = e^(log x) is true only for x > 0')
b('Properties of log?', 'log(ab) = log a + log b; log(a/b) = log a − log b; ' + T('log(aᵇ) = b log a') + '; log 1 = 0; logₐ b = log b/log a')
b('Example 26: differentiate cos⁻¹(eˣ) and e^(cos x).', 'd/dx cos⁻¹(eˣ) = −eˣ/√(1 − e²ˣ). d/dx e^(cos x) = e^(cos x) · (−sin x) = ' + N('−(sin x) e^(cos x)'))
b('Ex 5.4 Q1: differentiate eˣ/sin x.', 'Quotient rule: ' + N('eˣ (sin x − cos x)/sin²x'))
b('Ex 5.4 Q2: differentiate e^(sin⁻¹x).', N('e^(sin⁻¹x)/√(1 − x²)'))
b('Ex 5.4 Q3: differentiate e^(x³).', N('3x² e^(x³)'))
b('Ex 5.4 Q4: differentiate sin(tan⁻¹ e^(−x)).', 'cos(tan⁻¹e^(−x)) · 1/(1 + e^(−2x)) · (−e^(−x)): ' + N('−e^(−x) cos(tan⁻¹ e^(−x))/(1 + e^(−2x))'))
b('Ex 5.4 Q5: differentiate log(cos eˣ).', '(1/cos eˣ)(−sin eˣ)(eˣ) = ' + N('−eˣ tan eˣ'))
b('Ex 5.4 Q6: differentiate eˣ + e^(x²) + ... + e^(x⁵).', 'Term by term: ' + N('eˣ + 2x e^(x²) + 3x² e^(x³) + 4x³ e^(x⁴) + 5x⁴ e^(x⁵)'))
b('Ex 5.4 Q7: differentiate √(e^√x), x > 0.', 'y = e^(√x/2): y′ = e^(√x/2) · 1/(4√x) = ' + N('e^√x /(4√(x e^√x))'))
b('Ex 5.4 Q8: differentiate log(log x), x > 1.', '(1/log x) · (1/x) = ' + N('1/(x log x)'))
b('Ex 5.4 Q9: differentiate cos x/log x, x > 0.', 'Quotient rule: ' + N('−(x sin x log x + cos x)/(x (log x)²)'))
b('Ex 5.4 Q10: differentiate cos(log x + eˣ), x > 0.', N('−sin(log x + eˣ) · (1/x + eˣ)'))

d.sec('5.5-logarithmic-differentiation')
b('When do you use logarithmic differentiation?', 'For ' + T('y = u(x)^v(x)') + ' (variable base and exponent) and for long products/quotients/roots. Take log, differentiate: (1/y) y′ = v′ log u + v u′/u, so ' + T('y′ = y [v′ log u + v u′/u]'))
b('Why must u(x) > 0 in log differentiation?', 'Because log u is defined only for positive u. For a product of many factors the sign does not matter for the final algebra, but the method needs ' + T('u > 0'))
b('Example 29: differentiate x^(sin x), x > 0.', 'log y = sin x log x → y′/y = cos x log x + sin x/x → ' + N('y′ = x^(sin x) [ (sin x)/x + cos x log x ]'))
steps_card(d, 'Logarithmic differentiation', 'Find dy/dx for y = xˣ (x > 0).', 'y = xˣ', [
    'Take log: log y = x log x',
    'Differentiate: (1/y) y′ = log x + x · (1/x) = log x + 1',
    'Multiply by y: y′ = xˣ (1 + log x)',
    'Check at x = 1: y′ = 1 · 1 = 1 (slope of xˣ at x = 1)'], 2, 'Logarithmic differentiation of xˣ', 'y = x^x: log y = x log x, y\'/y = 1 + log x, y\' = x^x (1 + log x)')
b('Ex 5.5 Q1: differentiate cos x · cos 2x · cos 3x.', 'Log differentiation: y′ = y(−tan x − 2 tan 2x − 3 tan 3x). ' + N('−cos x cos 2x cos 3x [tan x + 2 tan 2x + 3 tan 3x]'))
b('Ex 5.5 Q2: differentiate √((x − 1)(x − 2)/((x − 3)(x − 4)(x − 5))).', 'log y = ½[log(x−1) + log(x−2) − log(x−3) − log(x−4) − log(x−5)]. ' + N('y′ = ½ y [1/(x−1) + 1/(x−2) − 1/(x−3) − 1/(x−4) − 1/(x−5)]'))
b('Ex 5.5 Q3: differentiate (log x)^(cos x).', 'log y = cos x · log(log x). ' + N('y′ = (log x)^(cos x) [cos x/(x log x) − sin x log(log x)]'))
b('Ex 5.5 Q4: differentiate x^x − 2^(sin x).', 'd/dx x^x = x^x(1 + log x); d/dx 2^(sin x) = 2^(sin x) log 2 cos x. ' + N('x^x (1 + log x) − 2^(sin x) cos x log 2'))
b('Ex 5.5 Q5: differentiate (x + 3)²(x + 4)³(x + 5)⁴.', 'y′/y = 2/(x+3) + 3/(x+4) + 4/(x+5). ' + N('(x + 3)(x + 4)²(x + 5)³ (9x² + 70x + 133)'))
b('Ex 5.5 Q6: differentiate (x + 1/x)^x + x^(1 + 1/x).', N('(x + 1/x)^x [ (x² − 1)/(x² + 1) + log(x + 1/x) ] + x^(1 + 1/x) [ (x + 1 − log x)/x² ]'))
b('Ex 5.5 Q7: differentiate (log x)^x + x^(log x).', N('(log x)^(x−1) [1 + log x · log(log x)] + 2 x^(log x − 1) log x'))
b('Ex 5.5 Q8: differentiate (sin x)^x + sin⁻¹√x.', N('(sin x)^x [x cot x + log sin x] + 1/(2√(x − x²))'))
b('Ex 5.5 Q9: differentiate x^(sin x) + (sin x)^(cos x).', N('x^(sin x)[sin x/x + cos x log x] + (sin x)^(cos x)[cos x cot x − sin x log sin x]'))
b('Ex 5.5 Q10: differentiate x^(x cos x) + (x² + 1)/(x² − 1).', N('x^(x cos x)[cos x (1 + log x) − x sin x log x] − 4x/(x² − 1)²'))
b('Ex 5.5 Q11: differentiate (x cos x)^x + (x sin x)^(1/x).', N('(x cos x)^x [1 − x tan x + log(x cos x)] + (x sin x)^(1/x) [ (x cot x + 1 − log(x sin x))/x² ]'))
b('Ex 5.5 Q12: dy/dx if x^y + y^x = 1.', 'Differentiate x^y and y^x by logs: ' + N('dy/dx = −(y x^(y−1) + y^x log y)/(x^y log x + x y^(x−1))'))
b('Ex 5.5 Q13: dy/dx if y^x = x^y.', 'x log y = y log x → ' + N('dy/dx = (y/x)(y − x log y)/(x − y log x)'))
b('Ex 5.5 Q14: dy/dx if (cos x)^y = (cos y)^x.', 'y log cos x = x log cos y → ' + N('dy/dx = (y tan x + log cos y)/(x tan y + log cos x)'))
b('Ex 5.5 Q15: dy/dx if xy = e^(x − y).', 'log x + log y = x − y → 1/x + y′/y = 1 − y′ → ' + N('dy/dx = y(x − 1)/(x(y + 1))'))
b('Ex 5.5 Q16: f(x) = (1 + x)(1 + x²)(1 + x⁴)(1 + x⁸). Find f′(x) and f′(1).', 'f′/f = 1/(1 + x) + 2x/(1 + x²) + 4x³/(1 + x⁴) + 8x⁷/(1 + x⁸). At x = 1: f(1) = 16 and the sum is ½ + 1 + 2 + 4 = 7.5. ' + N('f′(1) = 16 × 7.5 = 120'))
b('Ex 5.5 Q17: differentiate (x² − 5x + 8)(x³ + 7x + 9) three ways.', '(i) Product rule; (ii) expand to x⁵ − 5x⁴ + 15x³ − 26x² + 11x + 72 and differentiate; (iii) logarithmic differentiation. All agree: ' + N('5x⁴ − 20x³ + 45x² − 52x + 11'))
b('Ex 5.5 Q18: prove d(uvw)/dx = u′vw + uv′w + uvw′.', 'Product rule twice: (uv)w gives (uv)′w + uvw′ = (u′v + uv′)w + uvw′. Or log: (uvw)′/(uvw) = u′/u + v′/v + w′/w. ' + E('✓'))
b('Trap: is d/dx (xˣ) = x · x^(x−1) = xˣ?', X('No') + '. The power rule needs a constant exponent, the exponential rule a constant base. For xˣ use logs: xˣ(1 + log x)')

# ---------------------------------------------------------------- 5.6 Parametric
d.sec('5.6-parametric-forms')
b('Derivative of a parametric curve x = f(t), y = g(t)?', T('dy/dx = (dy/dt)/(dx/dt)') + ', provided dx/dt ≠ 0. No need to eliminate t')
sm.cycloid_parametric(d)
b('Ex 5.6 Q1: x = 2at², y = at⁴.', 'dx/dt = 4at, dy/dt = 4at³: ' + N('dy/dx = t²'))
b('Ex 5.6 Q2: x = a cos θ, y = b cos θ.', 'dx/dθ = −a sin θ, dy/dθ = −b sin θ: ' + N('dy/dx = b/a'))
b('Ex 5.6 Q3: x = sin t, y = cos 2t.', 'dx/dt = cos t, dy/dt = −2 sin 2t = −4 sin t cos t: ' + N('dy/dx = −4 sin t'))
b('Ex 5.6 Q4: x = 4t, y = 4/t.', 'dx/dt = 4, dy/dt = −4/t²: ' + N('dy/dx = −1/t²'))
b('Ex 5.6 Q5: x = cos θ − cos 2θ, y = sin θ − sin 2θ.', 'dx/dθ = −sin θ + 2 sin 2θ, dy/dθ = cos θ − 2 cos 2θ: ' + N('dy/dx = (cos θ − 2 cos 2θ)/(2 sin 2θ − sin θ)'))
b('Ex 5.6 Q6: x = a(θ − sin θ), y = a(1 + cos θ).', 'dx/dθ = a(1 − cos θ), dy/dθ = −a sin θ: dy/dx = −sin θ/(1 − cos θ) = ' + N('−cot(θ/2)'))
b('Ex 5.6 Q7: x = sin³t/√(cos 2t), y = cos³t/√(cos 2t).', 'After differentiating and simplifying: ' + N('dy/dx = −cot 3t'))
b('Ex 5.6 Q8: x = a(cos t + log tan(t/2)), y = a sin t.', 'dx/dt = a(−sin t + 1/sin t) = a cos²t/sin t, dy/dt = a cos t: ' + N('dy/dx = tan t'))
b('Ex 5.6 Q9: x = a sec θ, y = b tan θ.', 'dx/dθ = a sec θ tan θ, dy/dθ = b sec²θ: ' + N('dy/dx = (b/a) cosec θ'))
b('Ex 5.6 Q10: x = a(cos θ + θ sin θ), y = a(sin θ − θ cos θ).', 'dx/dθ = aθ cos θ, dy/dθ = aθ sin θ: ' + N('dy/dx = tan θ'))
b('Ex 5.6 Q11: x = √(a^(sin⁻¹t)), y = √(a^(cos⁻¹t)). Show dy/dx = −y/x.', 'x = a^(½ sin⁻¹t), y = a^(½ cos⁻¹t): dx/dt = x log a/(2√(1 − t²)), dy/dt = −y log a/(2√(1 − t²)). Divide: ' + N('dy/dx = −y/x') + ' ✓ (also xy = a^(π/4), constant)')

# ---------------------------------------------------------------- 5.7 Second derivative
d.sec('5.7-second-order-derivative')
b('Notation for the second derivative?', T('d²y/dx² = f″(x) = y″ = y₂') + ': differentiate f′(x) once more. The derivative of the derivative')
b('For a parametric curve, is d²y/dx² = (d²y/dt²)/(d²x/dt²)?', X('No') + '. Differentiate dy/dx (a function of t) with respect to t and divide by dx/dt again: ' + T('d²y/dx² = [d(dy/dx)/dt]/(dx/dt)'))
b('Example 36: y = A sin x + B cos x. Show y″ + y = 0.', 'y′ = A cos x − B sin x; y″ = −A sin x − B cos x = −y. ' + E('✓'))
b('Example 37: y = 3e^(2x) + 2e^(3x). Show y″ − 5y′ + 6y = 0.', 'y′ = 6e^(2x) + 6e^(3x), y″ = 12e^(2x) + 18e^(3x). y″ − 5y′ + 6y = (12 − 30 + 18)e^(2x) + (18 − 30 + 12)e^(3x) = 0. ' + E('✓'))
b('Example 38: y = sin⁻¹x. Show (1 − x²) y″ − x y′ = 0.', 'y′ = 1/√(1 − x²), so √(1 − x²) y′ = 1. Differentiate: √(1 − x²) y″ − x y′/√(1 − x²) = 0. Multiply by √(1 − x²): ' + E('(1 − x²)y″ − xy′ = 0 ✓'))
b('Ex 5.7 Q1: y = x² + 3x + 2. Find y″.', 'y′ = 2x + 3, y″ = ' + N('2'))
b('Ex 5.7 Q2: y = x²⁰. Find y″.', N('380 x¹⁸') + ' (20 · 19 = 380)')
b('Ex 5.7 Q3: y = x cos x.', 'y′ = cos x − x sin x; ' + N('y″ = −x cos x − 2 sin x'))
b('Ex 5.7 Q4: y = log x.', 'y′ = 1/x; ' + N('y″ = −1/x²'))
b('Ex 5.7 Q5: y = x³ log x.', 'y′ = 3x² log x + x²; ' + N('y″ = x(5 + 6 log x)'))
b('Ex 5.7 Q6: y = eˣ sin 5x.', 'y′ = eˣ(sin 5x + 5 cos 5x); ' + N('y″ = 2eˣ(5 cos 5x − 12 sin 5x)'))
b('Ex 5.7 Q7: y = e^(6x) cos 3x.', 'y′ = e^(6x)(6 cos 3x − 3 sin 3x); ' + N('y″ = 9e^(6x)(3 cos 3x − 4 sin 3x)'))
b('Ex 5.7 Q8: y = tan⁻¹x.', 'y′ = 1/(1 + x²); ' + N('y″ = −2x/(1 + x²)²'))
b('Ex 5.7 Q9: y = log(log x).', 'y′ = 1/(x log x); ' + N('y″ = −(1 + log x)/(x log x)²'))
b('Ex 5.7 Q10: y = sin(log x).', 'y′ = cos(log x)/x; ' + N('y″ = −[sin(log x) + cos(log x)]/x²'))
b('Ex 5.7 Q11: y = 5 cos x − 3 sin x. Prove y″ + y = 0.', 'y′ = −5 sin x − 3 cos x, y″ = −5 cos x + 3 sin x = −y. ' + E('✓'))
b('Ex 5.7 Q12: y = cos⁻¹x. Find d²y/dx² in terms of y alone.', 'y′ = −1/√(1 − x²) and y″ = −x/(1 − x²)^(3/2). With x = cos y, √(1 − x²) = sin y: ' + N('y″ = −cot y cosec²y'))
b('Ex 5.7 Q13: y = 3 cos(log x) + 4 sin(log x). Show x²y₂ + xy₁ + y = 0.', 'xy₁ = −3 sin(log x) + 4 cos(log x); differentiate: x y₂ + y₁ = −3 cos(log x)/x − 4 sin(log x)/x = −y/x. Multiply by x: ' + E('x²y₂ + xy₁ + y = 0 ✓'))
b('Ex 5.7 Q14: y = Ae^(mx) + Be^(nx). Show y″ − (m + n)y′ + mny = 0.', 'The coefficient of Ae^(mx) is m² − (m + n)m + mn = 0 and of Be^(nx) is n² − (m + n)n + mn = 0. ' + E('✓'))
b('Ex 5.7 Q15: y = 500e^(7x) + 600e^(−7x). Show y″ = 49y.', 'y″ = 49·500e^(7x) + 49·600e^(−7x) = 49y. ' + E('✓'))
b('Ex 5.7 Q16: eʸ(x + 1) = 1. Show y″ = (y′)².', 'y = −log(x + 1), y′ = −1/(x + 1), y″ = 1/(x + 1)² = (y′)². ' + E('✓'))
b('Ex 5.7 Q17: y = (tan⁻¹x)². Show (x² + 1)²y₂ + 2x(x² + 1)y₁ = 2.', 'y₁ = 2 tan⁻¹x/(1 + x²), so (1 + x²)y₁ = 2 tan⁻¹x. Differentiate: (1 + x²)y₂ + 2xy₁ = 2/(1 + x²). Multiply by (1 + x²): ' + E('✓'))

# ---------------------------------------------------------------- Miscellaneous
d.sec('5.8-miscellaneous')
b('Example 39(i): differentiate √(3x + 2) + 1/√(2x² + 4).', N('3/(2√(3x + 2)) − 2x/(2x² + 4)^(3/2)') + ' for x > −2/3')
b('Example 43: differentiate sin²x with respect to e^(cos x).', 'du/dv = (du/dx)/(dv/dx) = 2 sin x cos x/(−sin x e^(cos x)) = ' + N('−2 cos x/e^(cos x)') + '. Differentiating one function with respect to another: divide their derivatives')
b('Misc Q1: differentiate (3x² − 9x + 5)⁹.', 'Chain rule: ' + N('27(3x² − 9x + 5)⁸ (2x − 3)'))
b('Misc Q2: differentiate sin³x + cos⁶x.', '3 sin²x cos x − 6 cos⁵x sin x = ' + N('3 sin x cos x (sin x − 2 cos⁴x)'))
b('Misc Q3: differentiate (5x)^(3cos 2x).', 'log y = 3 cos 2x log 5x: ' + N('(5x)^(3cos 2x) [3 cos 2x/x − 6 sin 2x log 5x]'))
b('Misc Q4: differentiate sin⁻¹(x√x), 0 ≤ x ≤ 1.', 'u = x^(3/2), u′ = (3/2)√x: ' + N('(3/2)√(x/(1 − x³))'))
b('Misc Q5: differentiate cos⁻¹(x/2)/√(2x + 7), −2 < x < 2.', N('−[1/(√(4 − x²)√(2x + 7)) + cos⁻¹(x/2)/(2x + 7)^(3/2)]'))
b('Misc Q6: differentiate cot⁻¹[(√(1 + sin x) + √(1 − sin x))/(√(1 + sin x) − √(1 − sin x))], 0 < x < π/2.', 'The fraction equals cot(x/2) (as in the inverse trig chapter), so y = x/2. ' + N('dy/dx = 1/2'))
b('Misc Q7: differentiate (log x)^(log x), x > 1.', N('(log x)^(log x) [1/x + log(log x)/x]'))
b('Misc Q8: differentiate cos(a cos x + b sin x).', N('(a sin x − b cos x) sin(a cos x + b sin x)'))
b('Misc Q9: differentiate (sin x − cos x)^(sin x − cos x), π/4 < x < 3π/4.', 'Base u = sin x − cos x > 0: y = u^u, y′ = u^u (1 + log u) u′ with u′ = cos x + sin x. ' + N('(sin x − cos x)^(sin x − cos x) (cos x + sin x)(1 + log(sin x − cos x))'))
b('Misc Q10: differentiate x^x + x^a + a^x + a^a (a > 0 fixed).', N('x^x (1 + log x) + a x^(a−1) + a^x log a') + ' (a^a is a constant, derivative 0)')
b('Misc Q11: differentiate x^(x² − 3) + (x − 3)^(x²), x > 3.', N('x^(x²−3)[(x² − 3)/x + 2x log x] + (x − 3)^(x²)[x²/(x − 3) + 2x log(x − 3)]'))
b('Misc Q12: dy/dx if y = 12(1 − cos t), x = 10(t − sin t), −π/2 < t < π/2.', 'dy/dt = 12 sin t, dx/dt = 10(1 − cos t): dy/dx = (6/5) sin t/(1 − cos t) = ' + N('(6/5) cot(t/2)'))
b('Misc Q13: dy/dx if y = sin⁻¹x + sin⁻¹√(1 − x²), 0 < x < 1.', 'With x = sin θ (0 < θ < π/2): sin⁻¹√(1 − x²) = cos⁻¹x... y = θ + (π/2 − θ) = π/2, a constant. ' + N('dy/dx = 0'))
b('Misc Q14: if x√(1 + y) + y√(1 + x) = 0, −1 < x < 1, prove dy/dx = −1/(1 + x)².', 'Then y = −x/(1 + x) (solve: x²(1 + y) = y²(1 + x) → (x − y)(x + y + xy) = 0). So y′ = −1/(1 + x)². ' + E('✓'))
b('Misc Q15: (x − a)² + (y − b)² = c². Show [1 + (y′)²]^(3/2)/y″ is a constant independent of a and b.', 'With u = x − a, v = y − b: y′ = −u/v, y″ = −(u² + v²)/v³ = −c²/v³, and 1 + y′² = c²/v². The ratio is ' + N('±c (constant)') + ', its sign depending only on whether y > b or y < b')
b('Misc Q16: cos y = x cos(a + y), cos a ≠ ±1. Prove dy/dx = cos²(a + y)/sin a.', 'x = cos y/cos(a + y). Differentiate: dx/dy = sin a/cos²(a + y). Invert: ' + E('dy/dx = cos²(a + y)/sin a ✓'))
b('Misc Q17: x = a(cos t + t sin t), y = a(sin t − t cos t). Find d²y/dx².', 'dy/dx = tan t (Ex 5.6 Q10). Then d²y/dx² = sec²t/(dx/dt) = sec²t/(at cos t) = ' + N('sec³t/(at)') + ', 0 < t < π/2')
b('Misc Q18: f(x) = |x|³. Show f″(x) exists for all real x and find it.', 'f = x³ (x ≥ 0), −x³ (x < 0): f′ = 3x², −3x²; f″ = 6x, −6x, and both are 0 at x = 0: ' + N('f″(x) = 6|x|'))
b('Misc Q19: use sin(A + B) = sin A cos B + cos A sin B and differentiation to obtain cos(A + B).', 'Differentiate with respect to A (B fixed): cos(A + B) = cos A cos B − sin A sin B. ' + E('✓') + ' (or with respect to B)')
b('Misc Q20: is there a function continuous everywhere but not differentiable at exactly two points?', E('Yes') + ': f(x) = |x| + |x − 1| has corners at x = 0 and x = 1 and is smooth elsewhere')
b('Misc Q21: y = |f g h; l m n; a b c| (a determinant). Prove dy/dx = |f′ g′ h′; l m n; a b c|.', 'Only the first row contains functions of x; the other entries are constants. Differentiating the determinant expansion row 1 gives the same determinant with row 1 replaced by the derivatives. ' + E('✓'))
b('Misc Q22: y = e^(a cos⁻¹x), −1 ≤ x ≤ 1. Show (1 − x²)y″ − xy′ − a²y = 0.', 'y′ = −a y/√(1 − x²), so (1 − x²)y′² = a²y². Differentiate to get (1 − x²)y″ − xy′ − a²y = 0. ' + E('✓'))

# ---------------------------------------------------------------- Beyond: exam patterns
d.sec('5.z-exam-patterns')
b('Number of points where f(x) = |x − 1| + |x − 2| + |x − 3| is not differentiable?', 'Corners at ' + N('x = 1, 2, 3: three points') + ' (each modulus has a corner)')
b('f(x) = |sin x| is not differentiable at which points?', N('x = nπ') + ' (n ∈ Z): the graph has a corner where sin x crosses zero')
b('Is f(x) = x|x| differentiable at 0? Twice differentiable?', 'f = x² (x ≥ 0), −x² (x < 0). f′ = 2|x|, so ' + E('yes at 0') + ' with f′(0) = 0. But f′ = 2|x| has a corner at 0, so ' + X('f″(0) does not exist'))
b('Find f′(0) for f(x) = x² sin(1/x) (x ≠ 0), f(0) = 0.', 'From the definition: (h² sin(1/h))/h = h sin(1/h) → ' + N('0') + '. But f′(x) = 2x sin(1/x) − cos(1/x) is not continuous at 0')
b('Continuity vs differentiability of f(x) = x sin(1/x) (x ≠ 0), f(0) = 0?', E('Continuous at 0') + ' (|x sin(1/x)| ≤ |x|) but ' + X('not differentiable at 0') + ' (the difference quotient sin(1/h) oscillates)')
b('For what value of k is f(x) = (sin 3x)/x (x ≠ 0), k (x = 0) continuous at 0?', 'lim x→0 sin 3x/x = 3. ' + N('k = 3'))
b('Find a, b if f(x) = ax + b (x ≥ 1), x² (x < 1)... is continuous and differentiable at 1.', 'Continuity: a + b = 1. Differentiability: a = 2 (derivative of x² at 1). So ' + N('a = 2, b = −1'))
b('Chain rule for three layers: differentiate sin(cos(tan x)).', 'Outside to inside: cos(cos(tan x)) · (−sin(tan x)) · sec²x = ' + N('−cos(cos tan x) sin(tan x) sec²x'))
b('d/dx of |x| for x ≠ 0?', T('|x|/x') + ' (= 1 for x > 0, −1 for x < 0). Undefined at 0. Also d/dx |f(x)| = f f′/|f|')
b('If f(x) = x² + 3x + 1... find d/dx f(f(x)) at x = 0.', 'f′(x) = 2x + 3; f(0) = 1; chain rule: f′(f(0)) f′(0) = f′(1) f′(0) = 5 × 3 = ' + N('15'))
b('If y = x^(x^x), find dy/dx at x = 1.', 'log y = x^x log x. At x = 1: y = 1, x^x = 1. d/dx(x^x log x) = x^x(1 + log x) log x + x^x/x = (1)(1)(0) + 1 = 1. So y′/y = 1 and ' + N('dy/dx = 1'))
b('Differentiate y = x^(1/x) (x > 0).', 'log y = (log x)/x: y′/y = (1 − log x)/x². ' + N('y′ = x^(1/x)(1 − log x)/x²') + ' (zero at x = e: the maximum)')
b('Logarithmic derivative of a product f = f₁f₂···fₙ?', T('f′ = f · Σ fᵢ′/fᵢ') + '. Handy for Ex 5.5 Q1, Q2 and Q16')

# ---------------------------------------------------------------- How it is asked
d.sec('5.z-how-its-asked')
b('MCQ: the function f(x) = |x − 2| is<br>(a) not continuous at 2 (b) continuous but not differentiable at 2 (c) differentiable at 2 (d) not defined at 2', 'Continuous with a corner: ' + E('(b)'))
b('MCQ: f(x) = [x] is discontinuous at<br>(a) integers only (b) rationals only (c) no point (d) all real numbers', E('(a) integers only'))
b('MCQ: if f(x) = (x² − 4)/(x − 2) (x ≠ 2) is continuous at x = 2, then f(2) =<br>(a) 0 (b) 2 (c) 4 (d) not possible', 'The limit is 4: ' + E('(c) 4'))
b('MCQ: d/dx (sin⁻¹x + cos⁻¹x) =<br>(a) 0 (b) 1 (c) π/2 (d) 2/√(1 − x²)', 'The sum is the constant π/2: ' + E('(a) 0'))
b('MCQ: d/dx (xˣ) at x = 1 is<br>(a) 0 (b) 1 (c) e (d) 2', 'xˣ(1 + log x) at 1 = 1: ' + E('(b) 1'))
b('MCQ: d/dx (log₁₀ x) =<br>(a) 1/x (b) 1/(x log 10) (c) log 10/x (d) x/log 10', E('(b)'))
b('MCQ: if y = e^(2x), then d²y/dx² at x = 0 is<br>(a) 1 (b) 2 (c) 4 (d) 8', 'y″ = 4e^(2x) = 4: ' + E('(c) 4'))
b('MCQ: if x = t², y = t³ then dy/dx =<br>(a) 3t/2 (b) 2t/3 (c) t (d) 3t²', '(3t²)/(2t): ' + E('(a) 3t/2'))
b('MCQ: the derivative of sin x with respect to cos x is<br>(a) −cot x (b) tan x (c) cot x (d) −tan x', 'cos x/(−sin x): ' + E('(a) −cot x'))
b('MCQ: if f(x) = x + 5 (x ≤ 1), kx + 3 (x > 1) is continuous, k =<br>(a) 1 (b) 3 (c) 6 (d) 0', '6 = k + 3: ' + E('(b) 3'))
b('Integer answer (JEE Main): the number of points where f(x) = |x² − 4| is not differentiable is?', 'Corners where x² − 4 changes sign: ' + N('2') + ' (x = ±2)')
b('Integer answer: if f(x) = x³ − 3x, the value of f′(2) is?', '3x² − 3 = 12 − 3 = ' + N('9'))
b('Integer answer: if y = x^(2x), the value of dy/dx at x = 1 is?', 'log y = 2x log x, y′/y = 2 log x + 2. At x = 1: y = 1, so ' + N('dy/dx = 2'))
b('Assertion–Reason.<br><b>A:</b> f(x) = |x| is continuous at 0 but not differentiable at 0.<br><b>R:</b> the left and right derivatives of |x| at 0 are −1 and +1.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> if f is differentiable at c, it is continuous at c.<br><b>R:</b> if f is continuous at c then it is differentiable at c.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(c)') + ': R is the false converse')
b('True/False: the derivative of a constant is 1.', X('False') + ': it is 0')
b('True/False: every polynomial is differentiable everywhere.', E('True'))
b('2-mark: find dy/dx if y = sin(x²).', N('2x cos x²'))
b('2-mark: examine the continuity of f(x) = 2x + 3 at x = 1.', 'lim x→1 (2x + 3) = 5 = f(1): ' + E('continuous'))
b('3-mark: if y = x^(sin x), find dy/dx.', 'log y = sin x log x → ' + N('dy/dx = x^(sin x)[sin x/x + cos x log x]'))
b('3-mark: find dy/dx if x = a cos θ, y = a sin θ.', '(a cos θ)/(−a sin θ) = ' + N('−cot θ'))
b('3-mark: if y = e^(sin⁻¹x), show (1 − x²) y″ − x y′ − y = 0.', 'y′ = y/√(1 − x²), so (1 − x²)y′² = y². Differentiate: (1 − x²)y″ − xy′ − y = 0 after dividing by 2y′. ' + E('✓'))
b('4-mark: for what value of k is f(x) = kx + 1 (x ≤ π), cos x (x > π) continuous at x = π?', 'kπ + 1 = −1 → ' + N('k = −2/π'))
b('4-mark: if x = a(t + sin t), y = a(1 − cos t), find dy/dx at t = π/2.', 'dy/dx = sin t/(1 + cos t) = tan(t/2). At t = π/2: ' + N('1'))
b('4-mark: differentiate y = (x)^(x) + (sin x)^(x) with respect to x.', N('xˣ(1 + log x) + (sin x)ˣ(log sin x + x cot x)'))
b('Case-based: a particle moves so that s = t³ − 6t² + 9t (metres, seconds). Find the velocity and acceleration at t = 2.', 'v = ds/dt = 3t² − 12t + 9 = ' + N('−3 m/s') + ' at t = 2; a = dv/dt = 6t − 12 = ' + N('0 m/s²'))
b('Case-based: the radius of a circle grows as r = 2t cm. How fast is the area changing at t = 3?', 'A = πr² = 4πt²; dA/dt = 8πt = ' + N('24π cm²/s') + ' at t = 3 (chain rule: dA/dt = 2πr dr/dt)')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
