import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch13-statistics')
d = Deck('Chapter 13: Statistics', 'Class 11', ['class-11', 'mathematics', 'ch-13'])
d.description = 'Measures of dispersion: range, mean deviation, variance and standard deviation for ungrouped and grouped data, shortcut methods.'
b = d.basic

# ---------------------------------------------------------------- 13.1 Introduction
d.sec('13.1-introduction')
b('Name the three measures of central tendency and what they tell you.', T('Mean, median, mode') + ': a single value around which the data are centred (a “typical” value)')
b('Mean and median rule (ungrouped data)?', r'\(\bar{x} = \dfrac{\sum x_i}{n}\)' + '. Median: sort the data; odd n → the ((n + 1)/2)th value; even n → the mean of the (n/2)th and (n/2 + 1)th values')
sm.batsmen_dotplots(d)
b('Why are measures of central tendency not enough?', 'Two data sets can have the same mean and median but very different ' + T('scatter') + '.<br>We need a number for the spread: a ' + T('measure of dispersion'))
b('Measures of dispersion in the syllabus?', 'Range, mean deviation, variance and standard deviation. (Quartile deviation is mentioned but not studied here.)')

# ---------------------------------------------------------------- 13.3 Range
d.sec('13.3-range')
b('Range of a data set?', T('Maximum value − minimum value') + '. Batsman A: 117 − 0 = 117; batsman B: 60 − 46 = 14')
b('Limitation of the range?', 'It uses only the two extreme values, so one outlier changes it hugely.<br>It says nothing about how the data spread ' + T('around a central value'))

# ---------------------------------------------------------------- 13.4 Mean deviation
d.sec('13.4-mean-deviation')
b('Deviation of x from a?', T('x − a') + ' (signed distance). Deviations from the mean add to zero: Σ(xᵢ − x̄) = 0, so their plain average is useless as a spread')
b('Why do we take absolute values of the deviations?', 'Positive and negative deviations cancel: Σ(xᵢ − x̄) = 0<br>|x − a| is the actual ' + T('distance') + ' on the number line, so it does not cancel')
b('Define mean deviation about a.', r'\(\mathrm{M.D.}(a) = \dfrac{\sum |x_i - a|}{n}\)' + ': the mean of the absolute deviations from a')
b('Steps to find the mean deviation about the mean/median (ungrouped)?', '1) Find the mean (or median) a. 2) Find |xᵢ − a| for each value. 3) Add them and ' + T('divide by n'))
b('Example 1: mean deviation about the mean of 6, 7, 10, 12, 13, 4, 8, 12.', 'x̄ = 72/8 = 9; |deviations| 3, 2, 1, 3, 4, 5, 1, 3 = 22 → ' + N('M.D.(x̄) = 2.75'))
b('Example 2: mean deviation about the mean of the 20 data 12, 3, 18, 17, 4, 9, 17, 19, 20, 15, 8, 17, 2, 3, 16, 11, 3, 1, 0, 5.', 'x̄ = 200/20 = 10; Σ|xᵢ − x̄| = 124 → ' + N('6.2'))
b('Example 3: mean deviation about the median of 3, 9, 5, 3, 12, 10, 18, 4, 7, 19, 21.', 'Sorted: 3, 3, 4, 5, 7, 9, 10, 12, 18, 19, 21; median = 6th = 9; Σ|xᵢ − 9| = 58 → ' + N('58/11 ≈ 5.27'))
b('Ex 13.1 Q1–2: mean deviation about the mean: 4, 7, 8, 9, 10, 12, 13, 17; and 38, 70, 48, 40, 42, 55, 63, 46, 54, 44.', 'Mean 10: |dev| sum 24 → ' + N('3') + '. Mean 50: |dev| sum 84 → ' + N('8.4'))
b('Ex 13.1 Q3–4: mean deviation about the median: 13, 17, 16, 14, 11, 13, 10, 16, 11, 18, 12, 17; and 36, 72, 46, 42, 60, 45, 53, 46, 51, 49.', 'Median 13.5; |dev| sum 28 → ' + N('28/12 ≈ 2.33') + '. Median 47.5; |dev| sum 70 → ' + N('7'))
b('Mean deviation about which point is the smallest?', 'About the ' + T('median') + ': Σ|xᵢ − a| is minimum at a = median. So M.D. about the median ≤ M.D. about the mean')
b('Mean deviation for a discrete frequency distribution?', r'\(\mathrm{M.D.}(\bar{x}) = \dfrac{\sum f_i|x_i - \bar{x}|}{N},\quad \bar{x} = \dfrac{\sum f_ix_i}{N},\quad N = \sum f_i\)' + '. About the median: replace x̄ by M')
b('Median of a discrete frequency distribution?', 'Make the cumulative frequencies. The median is the observation whose c.f. is first ' + T('≥ N/2') + ' (if N is even, average the N/2 th and (N/2 + 1)th observations, which are often the same value)')
b('Method: mean deviation for a discrete distribution.', '1) Build a table: xᵢ, fᵢ, fᵢxᵢ (to get x̄ = Σfx/N), |xᵢ − x̄|, fᵢ|xᵢ − x̄|.<br>2) M.D. = Σf|x − x̄|/N.<br>3) Check Σf = N and that the mean lies inside the data range')
b('Example 5: N = 30, median = 13, Σf|xᵢ − M| = 149. Find M.D.(M).', '149/30 = ' + N('4.97'))
b('Mean deviation for a continuous frequency distribution?', 'Replace each class by its ' + T('mid-point') + ', then proceed as for a discrete distribution (mean or median)')
b('Median of a continuous distribution: formula?', r'\(M = l + \dfrac{\frac{N}{2} - C}{f}\times h\)' + ': median class = first class with c.f. ≥ N/2; l = its lower limit, f = its frequency, h = width, C = c.f. of the preceding class')
b('Example 7: median of a distribution with N = 50, median class 20–30, l = 20, C = 13, f = 15, h = 10.', '20 + (25 − 13)/15 × 10 = ' + N('28') + '; then Σf|xᵢ − M| = 508 → M.D.(M) = 508/50 = ' + N('10.16'))
b('Example 6: how does the mean deviation about the mean for grouped data proceed (data 10–20 … 70–80, N = 40)?', 'x̄ = Σfx/N = 1800/40 = ' + N('45') + '; M.D. = Σf|xᵢ − x̄|/N = 400/40 = ' + N('10'))
b('Step-deviation (shortcut) for the mean?', 'Take an assumed mean a and class width h: d = (x − a)/h, then<br>' + T('x̄ = a + h·(Σfd/N)') + '<br>Only the mean uses it; the M.D. still uses |x − x̄|')
b('Ex 13.1 Q12: age data is given as 16–20, 21–25, …. What must you do first?', 'Make the classes continuous before using the median formula:<br>subtract 0.5 from each lower limit and add 0.5 to each upper limit<br>(15.5–20.5, 20.5–25.5, …)')
b('Limitations of the mean deviation?', 'About the median it is unreliable when variability is very high; about the mean it is less “scientific”; and since it uses |·| it ' + T('cannot be treated algebraically') + ' → we need the standard deviation')

# ---------------------------------------------------------------- 13.5 Variance and SD
d.sec('13.5-variance-sd')
b('Why not use Σ(xᵢ − x̄)² directly as the dispersion?', 'It grows with the number of observations: set A (6 values, spread 5–55) has sum of squares 1750 while set B (31 values, 15–45) has 2480, even though A is more scattered. So we take the ' + T('mean'))
b('Define the variance σ² of n observations.', r'\(\sigma^2 = \dfrac{1}{n}\sum_{i=1}^{n}(x_i - \bar{x})^2\)' + ': the mean of the squared deviations from the mean')
b('Define the standard deviation.', r'\(\sigma = \sqrt{\dfrac{1}{n}\sum (x_i - \bar{x})^2}\)' + ': the positive square root of the variance; it has the ' + T('same unit as the data'))
b('Set A: 5, 15, 25, 35, 45, 55 versus set B: 15, 16, …, 45. Compare σ².', 'A: 1750/6 ≈ ' + N('291.67') + '. B: 2480/31 = ' + N('80') + '. A is far more dispersed (both have mean 30)')
b('Computational formula for variance?', r'\(\sigma^2 = \dfrac{\sum x_i^2}{n} - \bar{x}^2\)' + ': mean of squares minus square of the mean. Faster and less error-prone')
b('Example 8: variance and SD of 6, 8, 10, …, 24.', 'x̄ = 15; Σ(xᵢ − x̄)² = 330; σ² = ' + N('33') + ', σ = ' + N('5.74'))
b('Discrete frequency distribution: variance formula?', r'\(\sigma^2 = \dfrac{1}{N}\sum f_i(x_i - \bar{x})^2 = \dfrac{\sum f_ix_i^2}{N} - \left(\dfrac{\sum f_ix_i}{N}\right)^2\)')
b('Example 9: N = 30, Σfx = 420, Σf(x − x̄)² = 1374. Find the mean, variance, SD.', 'x̄ = ' + N('14') + ', σ² = 1374/30 = ' + N('45.8') + ', σ ≈ ' + N('6.77'))
b('Standard deviation of a continuous distribution?', 'Use the class mid-points xᵢ as in a discrete distribution: ' + T('σ = (1/N)√(NΣfx² − (Σfx)²)'))
b('Example 10: the table with mid-points 35 … 95: Σfx = 3100, Σf(x − x̄)² = 10050, N = 50.', 'x̄ = ' + N('62') + ', σ² = ' + N('201') + ', σ = ' + N('14.18'))
sm.histogram_sd(d)
b('Example 11: N = 48, Σfx = 614 and Σfx² = 9652. Find the standard deviation.', 'σ = (1/N)√(NΣfx² − (Σfx)²) = √(463296 − 376996)/48 = √86300/48 = ' + N('6.12'))
b('Shortcut method for variance and SD?', 'Let y = (x − A)/h. Then ' + T('σ² = h²[Σfy²/N − (Σfy/N)²]') + ', σ = h·√(Σfy²/N − (Σfy/N)²), and x̄ = A + h·Σfy/N')
b('Example 12 (shortcut): A = 65, h = 10, N = 50, Σfy = −15, Σfy² = 105 for the data of Example 10. Find mean, variance, SD.', 'x̄ = 65 + 10(−15/50) = ' + N('62') + '; σ² = 100[105/50 − (−0.3)²] = ' + N('201') + '; σ = ' + N('14.18') + '. Same as Example 10')
b('Ex 13.2 Q1: mean and variance of 6, 7, 10, 12, 13, 4, 8, 12.', 'x̄ = 9; Σ(x − 9)² = 74 → ' + N('σ² = 9.25'))
b('Ex 13.2 Q2–3: mean and variance of the first n natural numbers; of the first 10 multiples of 3.', 'Mean ' + N('(n + 1)/2') + ', variance ' + N('(n² − 1)/12') + '. Multiples of 3: mean 16.5, variance 9 × 99/12 = ' + N('74.25'))
b('Variance of the first n terms of any A.P. with common difference d?', N('d²(n² − 1)/12') + ' (the general form of the previous card)')
b('Interpretation: small vs large σ?', 'Small σ: data close to the mean (consistent, uniform). Large σ: data scattered. σ = 0 iff every observation equals the mean')
b('Ex 13.2 Q9–10: what to do for the diameters 33–36, 37–40, …?', 'The classes have gaps.<br>1) Make them continuous using half the gap (32.5–36.5, 36.5–40.5, …).<br>2) Use mid-points and the shortcut method')

# ---------------------------------------------------------------- Miscellaneous
d.sec('13.z-miscellaneous')
sm.shift_and_scale(d)
b('Example 13: the variance of 20 observations is 5. Each is multiplied by 2. New variance?', N('20') + ' (variance × 2² = 5 × 4). SD becomes 2σ')
b('Example 15: each observation is increased by a. Effect on variance?', N('None') + ': variance unchanged (mean also shifts by a, so deviations stay the same)')
b('Effect of y = ax + b on mean, variance, SD?', T('ȳ = a x̄ + b') + ',  ' + T('σ_y² = a²σ_x²') + ',  ' + T('σ_y = |a|σ_x'))
b('Example 14: mean of 5 observations is 4.4, variance 8.24; three are 1, 2, 6. Find the others.', 'x + y = 13 and x² + y² = 97 → (x − y)² = 25 → ' + N('4 and 9'))
b('Example 16: 100 observations, mean 40 and σ = 5.1, but one value 40 was recorded as 50. Correct mean and σ.', 'Correct sum 4000 − 50 + 40 = 3990 → mean ' + N('39.9') + '; Σx² = 162601 − 2500 + 1600 = 161701 → σ = ' + N('5'))
b('Method: correcting a wrong observation.', 'Recompute Σx and Σx² by removing the wrong value and adding the right one.<br>Σx² = n(σ² + x̄²) gives the old sum of squares')
b('Misc Q1: 8 observations, mean 9, variance 9.25; six are 6, 7, 10, 12, 12, 13. Find the other two.', 'x + y = 12 and x² + y² = 80 → ' + N('4 and 8'))
b('Misc Q2: 7 observations, mean 8, variance 16; five are 2, 4, 10, 12, 14. Find the other two.', 'x + y = 14 and x² + y² = 100 → ' + N('6 and 8'))
b('Misc Q3: mean 8 and SD 4 for six observations, each multiplied by 3. New mean and SD?', N('24') + ' and ' + N('12'))
b('Misc Q4: prove that ax₁, …, axₙ have mean a x̄ and variance a²σ².', 'Mean = Σax/n = a x̄; deviations become a(x − x̄), so squares × a²: variance a²σ² ✓')
b('Misc Q5: 20 observations, mean 10, σ = 2; one value 8 was wrong. Correct mean and σ if (i) omitted (ii) replaced by 12.', '(i) 19 values: sum 192, Σx² = 2016 → mean ' + N('10.11') + ', σ ≈ ' + N('2.0') + '. (ii) sum 204, Σx² = 2160 → mean ' + N('10.2') + ', σ ≈ ' + N('1.99'))
b('Misc Q6: 100 observations, mean 20, σ = 3; three incorrect values 21, 21, 18 are omitted. New mean and σ?', 'Sum 2000 − 60 = 1940 over 97 values → mean ' + N('20') + '; Σx² = 40900 − 1206 = 39694 → σ ≈ ' + N('3.04'))

# ---------------------------------------------------------------- Beyond the textbook: CV, combined, etc.
d.sec('13.z-beyond-text')
b('Coefficient of variation (compare consistency of two data sets)?', r'\(\mathrm{C.V.} = \dfrac{\sigma}{\bar{x}}\times 100\%\)' + '. The set with the ' + T('smaller C.V.') + ' is more consistent')
b('Series A: mean 50, σ = 5. Series B: mean 80, σ = 6. Which is more consistent?', 'C.V.(A) = 10%, C.V.(B) = 7.5% → ' + N('B') + ' is more consistent (its σ is smaller relative to its mean)')
b('Combined mean and variance of two groups (n₁, x̄₁, σ₁²), (n₂, x̄₂, σ₂²)?', 'Combined mean ' + T('(n₁x̄₁ + n₂x̄₂)/(n₁ + n₂)') + '<br>Combined variance ' + T('[n₁(σ₁² + d₁²) + n₂(σ₂² + d₂²)]/(n₁ + n₂)') + '<br>with dᵢ = x̄ᵢ − x̄_combined')
b('Empirical relation between mean, median, mode?', T('Mode ≈ 3 Median − 2 Mean') + ' (for moderately skewed data)')
b('Weighted mean?', r'\(\dfrac{\sum w_ix_i}{\sum w_i}\)' + ': e.g. exam components with weights 20%, 30%, 50%')
b('Mean of an A.P. and of the first n natural numbers?', 'The mean of an A.P. is the average of its first and last terms (= the middle term)<br>First n natural numbers: (n + 1)/2')
b('Sum of squared deviations from a: which a minimises Σ(x − a)²? Which minimises Σ|x − a|?', 'Σ(x − a)² is minimum at ' + T('a = mean') + ' (and the minimum value is nσ²). Σ|x − a| is minimum at ' + T('a = median'))
b('Variance of n identical observations? Of two values a and b?', N('0') + ' and ' + N('((b − a)/2)²') + ' (SD = half the difference)')
b('Relation: Σ(xᵢ − a)² = Σ(xᵢ − x̄)² + n(x̄ − a)². Why useful?', 'It shows the sum of squares about any a exceeds the one about the mean by n(x̄ − a)². Handy for the assumed-mean method and for proving that the mean minimises it')

# ---------------------------------------------------------------- How it's asked
d.sec('13.z-how-its-asked')
b('MCQ: The range of 3, 8, 12, 5, 20, 15 is<br>(a) 12 (b) 17 (c) 20 (d) 3', '20 − 3 = ' + E('(b) 17'))
b('MCQ: The mean deviation about the mean of 2, 4, 6, 8, 10 is<br>(a) 2.4 (b) 2 (c) 3 (d) 6', 'Mean 6; |dev| 4, 2, 0, 2, 4 = 12 → 12/5 = ' + E('(a) 2.4'))
b('MCQ: The variance of 2, 4, 6, 8, 10 is<br>(a) 6 (b) 8 (c) 10 (d) 40', 'Σ(x − 6)² = 40 → ' + E('(b) 8'))
b('MCQ: If the SD of a set is 4, the variance is<br>(a) 2 (b) 4 (c) 8 (d) 16', E('(d) 16'))
b('MCQ: If each observation is multiplied by 3, the SD becomes<br>(a) σ (b) 3σ (c) 9σ (d) σ + 3', E('(b) 3σ'))
b('MCQ: Each observation is increased by 5. Then the variance<br>(a) increases by 5 (b) increases by 25 (c) is unchanged (d) is multiplied by 5', E('(c)'))
b('MCQ: The standard deviation of the first 10 natural numbers is<br>(a) √8.25 (b) 2.87 (c) 3.03 (d) both (a) and (b)', '√((100 − 1)/12) = √8.25 ≈ 2.87 → ' + E('(d)'))
b('MCQ: The sum of deviations of the observations from their mean is<br>(a) always positive (b) always negative (c) zero (d) depends on n', E('(c) zero'))
b('Integer answer (JEE Main): the variance of the first 10 natural numbers is σ². Find 12σ².', 'σ² = (n² − 1)/12 = 99/12 → 12σ² = ' + N('99'))
b('Integer answer: mean of 5 observations is 6 and Σx² = 200. Find 5 × variance.', 'σ² = 200/5 − 36 = 4 → 5σ² = ' + N('20'))
b('Assertion–Reason.<br><b>A:</b> The standard deviation is never negative.<br><b>R:</b> It is the positive square root of the variance.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> Adding 10 to every observation leaves the standard deviation unchanged.<br><b>R:</b> Dispersion depends only on the deviations from the mean, not on the location of the mean.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('True/False: the mean deviation about the mean is always less than or equal to the standard deviation.', E('True') + ': M.D. ≤ σ (by the Cauchy–Schwarz inequality). Equality only if all |deviations| are equal')
b('3-mark: find the variance of 5, 12, 3, 18, 45, 9.', 'Sum 92, mean 15.33; Σx² = 2608; σ² = 2608/6 − (15.33)² = 434.67 − 235.11 = ' + N('≈ 199.6'))
b('4-mark: two firms: A pays mean ₹520 with σ = ₹100; B pays mean ₹495 with σ = ₹80. Which has more uniform wages?', 'C.V.(A) = 100/520 × 100 ≈ 19.2%; C.V.(B) = 80/495 × 100 ≈ 16.2% → ' + N('B is more uniform'))
b('Case-based: test scores of a class: mean 62, standard deviation 14.18 (Example 10). About which range do most students lie?', 'About x̄ ± σ = ' + N('47.8 to 76.2') + ' (roughly two-thirds of students for bell-shaped data)')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
