import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch06-permutations-and-combinations')
d = Deck('Chapter 6: Permutations and Combinations', 'Class 11', ['class-11', 'mathematics', 'ch-6'])
d.description = 'Counting principles, factorials, permutations with and without repetition, combinations, words, digits, committees, cards and exam techniques.'
b = d.basic

# ---------------------------------------------------------------- 6.2 Fundamental principle of counting
d.sec('6.2-counting-principle')
b('State the fundamental (multiplication) principle of counting.', 'If one event can occur in ' + T('m') + ' ways, and after it another event in ' + T('n') + ' ways, the two together can occur in ' + N('m × n') + ' ways. It extends to any number of events: m × n × p …')
b('Addition principle of counting?', 'If two tasks are ' + T('mutually exclusive') + ' (you do one OR the other) and can be done in m and n ways, the total is ' + N('m + n') + '. Rule of thumb: ' + T('AND → multiply, OR → add'))
sm.tree_pants_shirts(d)
b('Sabnam has 2 school bags, 3 tiffin boxes and 2 water bottles (one of each). Number of ways?', '2 × 3 × 2 = ' + N('12'))
b('Example 1: 4-letter words (with or without meaning) from the letters of ROSE, no repetition?', '4 × 3 × 2 × 1 = ' + N('24') + '. With repetition allowed: 4 × 4 × 4 × 4 = ' + N('256'))
b('Example 2: 4 flags of different colours; signals use 2 flags, one below the other. How many?', '4 × 3 = ' + N('12'))
b('Example 3: 2-digit even numbers from 1, 2, 3, 4, 5 with repetition allowed?', 'Units: 2 or 4 (2 ways). Tens: any of 5. ' + N('2 × 5 = 10'))
sm.slot_method(d)
b('Method: the slot (box) method for counting numbers or words.', '1) Draw one box per place. 2) Fill the boxes with a ' + T('condition first') + ' (units digit even, first letter a vowel, leading digit ≠ 0). 3) Multiply the choices')
b('Example 4: signals with at least 2 of 5 different flags on a staff. How many?', '2 flags: 5·4 = 20; 3 flags: 5·4·3 = 60; 4 flags: 120; 5 flags: 120. Add (“or”): ' + N('320'))
b('Ex 6.1 Q1: 3-digit numbers from 1, 2, 3, 4, 5 (i) with repetition (ii) without?', N('125') + ' (5 × 5 × 5) and ' + N('60') + ' (5 × 4 × 3)')
b('Ex 6.1 Q2: 3-digit even numbers from 1–6 with repetition allowed?', 'Units 2, 4 or 6 (3 ways); tens 6; hundreds 6: ' + N('6 × 6 × 3 = 108'))
b('Ex 6.1 Q3: 4-letter codes from the first 10 letters, no repetition?', '10 × 9 × 8 × 7 = ' + N('5040'))
b('Ex 6.1 Q4: 5-digit phone numbers starting with 67, digits 0–9, no digit repeated?', 'Remaining 3 places from the 8 unused digits: 8 × 7 × 6 = ' + N('336'))
b('Ex 6.1 Q5: a coin is tossed 3 times. Number of outcomes?', '2 × 2 × 2 = ' + N('8'))
b('Ex 6.1 Q6: 5 flags of different colours; 2-flag signals?', '5 × 4 = ' + N('20'))
b('Number of ways to answer 10 true/false questions?', N('2¹⁰ = 1024'))
b('Number of 3-digit numbers (any digits allowed)?', 'Hundreds 1–9 (9 ways), tens 10, units 10: ' + N('900') + '. A leading 0 is not allowed')

# ---------------------------------------------------------------- 6.3 Permutations
d.sec('6.3-permutations')
b('Define a permutation.', 'An ' + T('arrangement in a definite order') + ' of objects taken some or all at a time: ' + T('order matters'))
b('Theorem 1: number of permutations of n different objects taken r at a time (no repetition)?', r'\({}^nP_r = n(n-1)(n-2)\cdots(n-r+1) = \dfrac{n!}{(n-r)!}\)' + ', 0 ≤ r ≤ n')
b('Define n! and 0!.', T('n! = 1 × 2 × 3 × … × n') + ', and ' + N('0! = 1') + ' by definition. Also n! = n·(n − 1)!')
b('Why is 0! = 1?', 'ⁿPₙ = n!/0! must equal n! (arrange all n objects). Equivalently there is exactly one way to arrange nothing')
b('Example 5: evaluate 5!, 7!, 7! − 5!.', N('120') + ', ' + N('5040') + ', ' + N('4920'))
b('Example 6: 7!/5! and 12!/(10!·2!).', '7 × 6 = ' + N('42') + ';  (12 × 11)/2 = ' + N('66'))
b('Ex 6.2: is 3! + 4! = 7!?', X('No') + ': 6 + 24 = 30 but 7! = 5040. Factorials do not add or multiply term by term')
b('Trap: is (m + n)! = m! + n!, or (2n)! = 2·n!?', X('Neither') + '. e.g. (2·3)! = 720 but 2·3! = 12')
b('Ex 6.2 Q3: compute 8!/(6! × 2!).', '(8 × 7)/2 = ' + N('28'))
b('Example 7: evaluate n!/(r!(n − r)!) for n = 5, r = 2.', '5!/(2!·3!) = (5 × 4)/2 = ' + N('10'))
b('Example 8: 1/8! + 1/9! = x/10!. Find x.', '10!/8! = 90 and 10!/9! = 10, so x = 90 + 10 = ' + N('100'))
b('Ex 6.2 Q4: 1/6! + 1/7! = x/8!. Find x.', '8!/6! = 56, 8!/7! = 8 → x = ' + N('64'))
b('Ex 6.2 Q5: evaluate n!/(n − r)! for n = 6, r = 2 and n = 9, r = 5.', N('30') + ' (6 × 5) and ' + N('15120') + ' (9 × 8 × 7 × 6 × 5)')
b('ⁿP₀, ⁿP₁, ⁿPₙ₋₁ and ⁿPₙ?', N('1') + ',  ' + N('n') + ',  ' + N('n!') + ',  ' + N('n!') + '<br><small>ⁿPₙ₋₁ = n!/1! = n!</small>')
b('Theorem 2: permutations of n different objects taken r at a time with repetition allowed?', N('nʳ') + ' (each of the r places can be filled in n ways)')
b('Chairman and vice-chairman from 12 persons (one person, one post)?', '¹²P₂ = 12 × 11 = ' + N('132'))
b('Ex 6.3 Q5: chairman and vice-chairman from a committee of 8?', '⁸P₂ = 8 × 7 = ' + N('56'))
b('Ex 6.3 Q1–2: 3-digit numbers from 1–9 with no repetition; 4-digit numbers with no repeated digit?', '⁹P₃ = ' + N('504') + '. 4-digit: first digit 9 ways (not 0), then 9, 8, 7: ' + N('9 × 9 × 8 × 7 = 4536'))
b('Trap: “4-digit numbers with no digit repeated”. Is the answer ¹⁰P₄?', X('No') + '. ¹⁰P₄ = 5040 includes numbers starting with 0. Subtract them: 5040 − ⁹P₃ = 5040 − 504 = 4536')
b('Ex 6.3 Q3: 3-digit even numbers from 1, 2, 3, 4, 6, 7, no repetition?', 'Units 2, 4 or 6 (3 ways); tens 5; hundreds 4: ' + N('3 × 5 × 4 = 60'))
b('Ex 6.3 Q4: 4-digit numbers from 1, 2, 3, 4, 5, no repetition. How many are even?', '⁵P₄ = ' + N('120') + '. Even: units 2 or 4 (2 ways) then 4 × 3 × 2: ' + N('48'))
b('Example 10 and 11: 4-digit numbers from 1–9 without repetition; numbers between 100 and 1000 from 0, 1, 2, 3, 4, 5 without repetition?', '⁹P₄ = ' + N('3024') + '. Second: ⁶P₃ − ⁵P₂ = 120 − 20 = ' + N('100') + ' (subtract those with 0 in the hundreds place)')
b('Ex 6.3 Q8: words using all letters of EQUATION once each?', '8! = ' + N('40320'))
b('Ex 6.3 Q9: words from MONDAY, no repetition: (i) 4 letters (ii) all letters (iii) all letters, first letter a vowel?', '(i) ⁶P₄ = ' + N('360') + ' (ii) 6! = ' + N('720') + ' (iii) vowels O or A: 2 × 5! = ' + N('240'))
b('Example 12(i): find n if ⁿP₅ = 42 · ⁿP₃ (n > 4).', 'Divide by n(n − 1)(n − 2): (n − 3)(n − 4) = 42 → n² − 7n − 30 = 0 → (n − 10)(n + 3) = 0 → ' + N('n = 10') + ' (n = −3 rejected)')
b('Example 12(ii): find n if ⁿP₄ / ⁿ⁻¹P₄ = 5/3 (n > 4).', 'ⁿP₄/ⁿ⁻¹P₄ = n/(n − 4) after cancelling (n − 1)(n − 2)(n − 3). So 3n = 5(n − 4) → ' + N('n = 10'))
b('Method: solving equations with nPr.', 'Write each ⁿPᵣ as a product (n)(n − 1)…, cancel the common factors ' + T('after checking they are non-zero (n > r)') + ', solve the resulting polynomial, then ' + X('reject values that violate n ≥ r, n, r ∈ N'))
b('Ex 6.3 Q6: find n if ⁿ⁻¹P₃ : ⁿP₄ = 1 : 9.', (
    r'\(\dfrac{(n-1)(n-2)(n-3)}{n(n-1)(n-2)(n-3)} = \dfrac1n = \dfrac19\)') + ' → ' + N('n = 9'))
b('Example 13: 5·⁴Pᵣ = 6·⁵Pᵣ₋₁. Find r.', 'Algebra gives (6 − r)(5 − r) = 6 → r² − 11r + 24 = 0 → r = 3 or 8. But ⁴Pᵣ needs r ≤ 4, so ' + N('r = 3') + ' only. Check: 5·24 = 120 = 6·20')
b('Correction: NCERT Example 13 ends with “r = 8, 3”. Is r = 8 valid?', X('No') + '. ⁴P₈ does not exist (r cannot exceed n = 4). Always test roots against the conditions r ≤ n. The correct answer is r = 3')
b('Ex 6.3 Q7: find r if (i) ⁵Pᵣ = 2·⁶Pᵣ₋₁, (ii) ⁵Pᵣ = ⁶Pᵣ₋₁.', '(i) (7 − r)(6 − r) = 12 → r² − 13r + 30 = 0 → r = 3 or 10; r ≤ 5 → ' + N('r = 3') + '. (ii) (7 − r)(6 − r) = 6 → r² − 13r + 36 = 0 → r = 4 or 9 → ' + N('r = 4'))

d.sec('6.3.4-alike-objects')
b('Permutations of n objects when p of them are alike and the rest different?', r'\(\dfrac{n!}{p!}\)')
b('Permutations of n objects with p₁ alike of one kind, p₂ of another, …, pₖ of the k-th kind?', r'\(\dfrac{n!}{p_1!\,p_2!\cdots p_k!}\)')
b('Why divide by p! for identical objects?', 'Treating the p alike objects as different overcounts: every real arrangement is counted ' + T('p! times') + ' (the alike ones can be shuffled among themselves without any visible change)')
b('Arrangements of the letters of ROOT?', '4!/2! = ' + N('12'))
b('Arrangements of the letters of INSTITUTE?', '9 letters: I twice, T three times → 9!/(2!·3!) = ' + N('30240'))
b('Example 9: permutations of the letters of ALLAHABAD?', '9 letters: A four times, L twice → 9!/(4!·2!) = ' + N('7560'))
b('Example 15: 4 red, 3 yellow and 2 green discs in a row (same colour identical)?', '9!/(4!·3!·2!) = ' + N('1260'))
b('Number of arrangements of the letters of MISSISSIPPI?', '11!/(4!·4!·2!) = ' + N('34650') + ' (I ×4, S ×4, P ×2)')
b('Ex 6.3 Q10: in how many of them do the four I’s not come together?', 'Together: treat IIII as one letter: 8!/(4!·2!) = 840. So ' + N('34650 − 840 = 33810'))
b('Method: “vowels always together”.', 'Tie the vowels into ' + T('one block') + '. Arrange the block with the other letters, then multiply by the arrangements ' + T('inside') + ' the block')
b('Method: “vowels never together”.', T('Total − (vowels together)') + '. Complement counting is faster than direct counting')
b('Example 14: 8-letter arrangements of DAUGHTER with (i) all vowels together (ii) not together?', '(i) block AUE + 5 letters = 6 objects: 6!·3! = ' + N('4320') + '. (ii) 8! − 4320 = ' + N('36000'))
b('Example 16: INDEPENDENCE has 12 letters (N ×3, E ×4, D ×2). Total, and words starting with P?', '12!/(3!·4!·2!) = ' + N('1663200') + '. Start with P: 11!/(3!·4!·2!) = ' + N('138600'))
b('Example 16(ii)–(iv): INDEPENDENCE: vowels together; vowels never together; begin with I and end with P?', 'Vowels EEEEI form a block: 8!/(3!·2!) × 5!/4! = ' + N('16800') + '. Never together: 1663200 − 16800 = ' + N('1646400') + '. I first, P last: 10!/(3!·2!·4!) = ' + N('12600'))
b('Ex 6.3 Q11: PERMUTATIONS (12 letters, T twice) with (i) P first and S last (ii) vowels together (iii) exactly 4 letters between P and S?', '(i) 10!/2! = ' + N('1814400') + '. (ii) 5 vowels as a block: 8!/2! × 5! = ' + N('2419200') + '. (iii) P and S can sit in 7 position-pairs (1–6, 2–7, …, 7–12), in 2 orders: 14 × 10!/2! = ' + N('25401600'))
b('Example 22: rank of a word. AGAIN in dictionary order: how many words, and what is the 50th?', '5!/2! = 60 words. Starting with A: 4! = 24; G: 4!/2! = 12; I: 12 → 48. Next letter N: 49th NAAGI, ' + N('50th NAAIG'))
b('Method: rank of a word in dictionary order.', 'Sort the letters. For each position count the words that start with every smaller letter (with the correct repeated-letter division), add them up, and add 1')
b('Misc Q4: EXAMINATION arranged as in a dictionary: how many words come before the first word starting with E?', 'Only words starting with A come before E. Fix A: remaining 10 letters with I ×2, N ×2: 10!/(2!·2!) = ' + N('907200'))
b('Example 23: numbers greater than 1000000 using the digits 1, 2, 0, 2, 4, 2, 4?', 'All 7-digit arrangements: 7!/(3!·2!) = 420, minus those starting with 0: 6!/(3!·2!) = 60 → ' + N('360'))
b('Misc Q11: arrangements of ASSASSINATION with all S’s together?', '13 letters: A ×3, S ×4, I ×2, N ×2. Block SSSS + 9 others = 10 objects: 10!/(3!·2!·2!) = ' + N('151200'))

# ---------------------------------------------------------------- 6.4 Combinations
d.sec('6.4-combinations')
b('Define a combination. Permutation vs combination?', 'A ' + T('selection') + ' where order does not matter. Permutation: ' + T('arrangement') + ' (order matters). Memory: ' + T('P = Position, C = Committee'))
table_card(d, '6.4 · Order matters?', 'Choose P (permutation) or C (combination).', [
    ('Forming a 3-letter word', 'P', False), ('Choosing a team of 3 players', 'C', False), ('Seating 5 people in a row', 'P', False),
    ('Handshakes among 12 people', 'C', False), ('A 4-digit PIN', 'P', False), ('Selecting 5 cards from a pack', 'C', False),
    ('President and secretary from 10', 'P', False), ('Chords joining 7 points on a circle', 'C', False)], term='Permutation or combination?')
b('Formula for ⁿCᵣ?', r'\({}^nC_r = \dfrac{n!}{r!\,(n-r)!}\)' + ', 0 ≤ r ≤ n')
b('Relation between ⁿPᵣ and ⁿCᵣ?', r'\({}^nP_r = {}^nC_r \times r!\)' + ': choose the r objects, then arrange them in r! ways')
b('ⁿC₀, ⁿC₁, ⁿCₙ?', N('1') + ', ' + N('n') + ', ' + N('1'))
b('Why is ⁿC₀ = 1?', 'Choosing nothing can be done in exactly one way (leave everything behind)')
b('Theorem: ⁿCᵣ = ⁿCₙ₋ᵣ. Meaning?', 'Selecting r objects to take is the same as selecting n − r objects to ' + T('leave behind'))
b('ⁿCₐ = ⁿC_b implies?', T('a = b') + ' or ' + T('a + b = n'))
b('Theorem 6 (Pascal’s rule): ⁿCᵣ + ⁿCᵣ₋₁ = ?', N('ⁿ⁺¹Cᵣ') + '. Proof by writing both over r!(n − r + 1)! or by “is a particular object chosen or not”')
sm.pascal_triangle(d)
b('Example 17: if ⁹Cᵣ = ⁹Cᵣ₋₁ … i.e. ⁿC₉ = ⁿC₈, find ⁿC₁₇.', 'Equal values → 9 + 8 = n → n = 17, so ⁿC₁₇ = ¹⁷C₁₇ = ' + N('1'))
b('Ex 6.4 Q1: if ⁿC₈ = ⁿC₂, find ⁿC₂.', 'n = 8 + 2 = 10 → ¹⁰C₂ = ' + N('45'))
b('Ex 6.4 Q2: find n if ²ⁿC₃ : ⁿC₃ = 12 : 1 and = 11 : 1.', '²ⁿC₃/ⁿC₃ = 4(2n − 1)/(n − 2). For 12: 8n − 4 = 12n − 24 → ' + N('n = 5') + '. For 11: 8n − 4 = 11n − 22 → ' + N('n = 6'))
b('Chords through 21 points on a circle?', '²¹C₂ = ' + N('210') + '. In general n points give ⁿC₂ chords (handshake count)')
b('Ex 6.4 Q4: team of 3 boys and 3 girls from 5 boys and 4 girls?', '⁵C₃ × ⁴C₃ = 10 × 4 = ' + N('40'))
b('Ex 6.4 Q5: choose 9 balls from 6 red, 5 white, 5 blue with 3 of each colour?', '⁶C₃ × ⁵C₃ × ⁵C₃ = 20 × 10 × 10 = ' + N('2000'))
b('Ex 6.4 Q6 and Misc Q8: 5-card hands with exactly one ace (or exactly one king)?', '⁴C₁ × ⁴⁸C₄ = 4 × 194580 = ' + N('778320'))
b('Ex 6.4 Q7: cricket team of 11 from 17 players (5 can bowl) with exactly 4 bowlers?', '⁵C₄ × ¹²C₇ = 5 × 792 = ' + N('3960'))
b('Ex 6.4 Q8: 2 black and 3 red balls from 5 black and 6 red?', '⁵C₂ × ⁶C₃ = 10 × 20 = ' + N('200'))
b('Ex 6.4 Q9: 5 courses from 9, two specific courses compulsory?', 'Choose the other 3 from 7: ⁷C₃ = ' + N('35'))
b('Example 18: committee of 3 from 2 men and 3 women. Total, and with 1 man and 2 women?', '⁵C₃ = ' + N('10') + ';  ²C₁ × ³C₂ = ' + N('6'))
b('Example 19: 4 cards from 52. Total number of hands?', '⁵²C₄ = ' + N('270725'))
b('Example 19: 4 cards (i) same suit (ii) one from each suit (iii) all face cards?', '(i) 4 × ¹³C₄ = ' + N('2860') + ' (ii) 13⁴ = ' + N('28561') + ' (iii) ¹²C₄ = ' + N('495'))
b('Example 19: 4 cards (iv) two red and two black (v) all the same colour?', '(iv) ²⁶C₂ × ²⁶C₂ = 325² = ' + N('105625') + ' (v) 2 × ²⁶C₄ = ' + N('29900'))
b('Example 20: words of 3 vowels and 2 consonants from INVOLUTE (4 vowels, 4 consonants)?', 'Select: ⁴C₃ × ⁴C₂ = 24; arrange each in 5! ways: 24 × 120 = ' + N('2880') + '. Select first, then arrange')
b('Example 21: 5-member team from 4 girls and 7 boys: (i) no girl (ii) at least one boy and one girl (iii) at least 3 girls?', '(i) ⁷C₅ = ' + N('21') + '. (ii) 7 + 84 + 210 + 140 = ' + N('441') + ' (or ¹¹C₅ − 21 = 462 − 21 = 441). (iii) ⁴C₃·⁷C₂ + ⁴C₄·⁷C₁ = 84 + 7 = ' + N('91'))
b('Trap: “at least one boy and one girl”. Fastest method?', T('Total − (all boys) − (all girls)') + ' = ¹¹C₅ − ⁷C₅ − 0 = 462 − 21 = 441 (no all-girl team: only 4 girls)')
b('Method: “at least” and “at most” selection problems.', 'Either add the separate cases, or use ' + T('total − the opposite cases') + ' (whichever has fewer cases). For “at least k”, the complement is “fewer than k”')
b('Misc Q1: words of 2 vowels and 3 consonants from DAUGHTER?', 'Vowels A, U, E; consonants 5: ³C₂ × ⁵C₃ × 5! = 3 × 10 × 120 = ' + N('3600'))
b('Misc Q2: words using all letters of EQUATION with vowels together and consonants together?', 'Two blocks can be ordered in 2! ways; vowels 5! ; consonants 3!: ' + N('2 × 120 × 6 = 1440'))
b('Misc Q3: committee of 7 from 9 boys and 4 girls: (i) exactly 3 girls (ii) at least 3 girls (iii) at most 3 girls?', '(i) ⁴C₃·⁹C₄ = ' + N('504') + ' (ii) 504 + ⁴C₄·⁹C₃ = 504 + 84 = ' + N('588') + ' (iii) ¹³C₇ − 84 = 1716 − 84 = ' + N('1632'))
b('Misc Q5: 6-digit numbers from 0, 1, 3, 5, 7, 9, divisible by 10, no repetition?', 'Last digit must be 0; arrange the other five: 5! = ' + N('120'))
b('Misc Q6: words with 2 different vowels and 2 different consonants from the English alphabet (5 vowels, 21 consonants)?', '⁵C₂ × ²¹C₂ × 4! = 10 × 210 × 24 = ' + N('50400'))
b('Misc Q7: attempt 8 of 12 questions (Part I: 5, Part II: 7) with at least 3 from each part?', '(3,5): ⁵C₃·⁷C₅ = 210; (4,4): ⁵C₄·⁷C₄ = 175; (5,3): ⁵C₅·⁷C₃ = 35. Total ' + N('420'))
b('Misc Q9: 5 men and 4 women in a row with women in the even places?', '4 even places (2, 4, 6, 8) for the women: 4!; the 5 other places for the men: 5!. ' + N('24 × 120 = 2880'))
b('Misc Q10: choose 10 of 25 students; 3 of them will all join or all stay out.', 'All three join: ²²C₇; none joins: ²²C₁₀. ' + N('170544 + 646646 = 817190'))
b('Example 24: 5 girls and 3 boys in a row, no two boys together?', 'Girls first: 5!; boys into 3 of the 6 gaps: ⁶P₃. ' + N('120 × 120 = 14400'))
sm.gaps_method(d)

# ---------------------------------------------------------------- Beyond the text: exam favourites
d.sec('6.z-exam-favourites')
sm.circular_seating(d)
b('Necklace or garland of n different beads?', r'\(\dfrac{(n-1)!}{2}\)' + ': a necklace can be flipped over, so clockwise and anticlockwise orders coincide')
b('Selecting any number (≥ 1) of n different objects?', N('2ⁿ − 1') + ': each object is in or out, minus the empty selection')
b('Number of selections of r objects when repetition allowed / non-negative integral solutions of x₁ + … + xᵣ = n?', r'\({}^{n+r-1}C_{r-1}\)' + ' (stars and bars). Example: x + y + z = 10 has ¹²C₂ = 66 solutions')
b('Number of positive integral solutions of x₁ + x₂ + … + xᵣ = n?', r'\({}^{n-1}C_{r-1}\)' + ' (each xᵢ ≥ 1)')
b('Number of diagonals of a convex n-gon?', r'\({}^nC_2 - n = \dfrac{n(n-3)}{2}\)' + '. Hexagon: 9')
b('Number of triangles from n points, no three collinear? With p points collinear?', T('ⁿC₃') + '; with p collinear: ' + T('ⁿC₃ − ᵖC₃'))
b('Number of lines from n points, no three collinear? With p collinear?', T('ⁿC₂') + '; with p collinear: ' + T('ⁿC₂ − ᵖC₂ + 1'))
b('Rectangles in an 8 × 8 chessboard?', 'Choose 2 of 9 horizontal lines and 2 of 9 vertical: ⁹C₂ × ⁹C₂ = 36² = ' + N('1296') + '. Squares: 1² + 2² + … + 8² = ' + N('204'))
b('Number of divisors of N = p^a · q^b · r^c?', N('(a + 1)(b + 1)(c + 1)') + '. Example: 360 = 2³·3²·5 has 4 × 3 × 2 = 24 divisors')
b('Dividing 8 people into two equal groups of 4 (unlabelled) versus two named teams?', 'Named teams: ⁸C₄ = 70. Unlabelled groups: ⁸C₄/2! = ' + N('35') + '. Divide by (number of equal groups)! when the groups are indistinguishable')
b('Derangements (nobody gets their own item): D₃ and D₄?', N('D₃ = 2') + ', ' + N('D₄ = 9') + ' (formula Dₙ = n!(1 − 1/1! + 1/2! − … ± 1/n!))')
b('Identities: r·ⁿCᵣ and ⁿPᵣ in terms of smaller cases?', T('r · ⁿCᵣ = n · ⁿ⁻¹Cᵣ₋₁') + ';  ' + T('ⁿPᵣ = n · ⁿ⁻¹Pᵣ₋₁') + ';  ' + T('ⁿCᵣ = (n/r) · ⁿ⁻¹Cᵣ₋₁'))
b('Sum of ⁿC₀ + ⁿC₁ + … + ⁿCₙ?', N('2ⁿ') + ' (all subsets); alternating sum ⁿC₀ − ⁿC₁ + … = 0 for n ≥ 1; sum of even-indexed = sum of odd-indexed = 2ⁿ⁻¹')
b('Hockey-stick identity: ʳCᵣ + ʳ⁺¹Cᵣ + … + ⁿCᵣ?', N('ⁿ⁺¹Cᵣ₊₁') + '. e.g. ²C₂ + ³C₂ + ⁴C₂ + ⁵C₂ = 1 + 3 + 6 + 10 = 20 = ⁶C₃')
b('In how many ways can 10 identical sweets be distributed among 4 children (any child may get none)?', r'\({}^{13}C_3 = 286\)' + ' (stars and bars with n = 10, r = 4)')
b('Number of ways to arrange the letters of BANANA so that no two A’s are adjacent?', 'Arrange B, N, N: 3!/2! = 3 ways; they make 4 gaps; choose 3 gaps for the A’s: ⁴C₃ = 4. Total ' + N('3 × 4 = 12'))
b('Number of 5-digit numbers divisible by 5 using digits 0–9 (any repetition)?', 'Units 0 or 5 (2 ways), first digit 1–9 (9 ways), middle three 10³: 9 × 10 × 10 × 10 × 2 = ' + N('18000'))

# ---------------------------------------------------------------- How it's asked
d.sec('6.z-how-its-asked')
b('MCQ: The value of ⁵P₃ is<br>(a) 10 (b) 60 (c) 120 (d) 15', E('(b) 60') + ' = 5 × 4 × 3')
b('MCQ: If ⁿC₁₀ = ⁿC₁₂, then n =<br>(a) 22 (b) 2 (c) 12 (d) 10', E('(a) 22') + ' since 10 + 12 = n')
b('MCQ: The number of ways to arrange the letters of the word LEVEL is<br>(a) 120 (b) 60 (c) 30 (d) 24', '5!/(2!·2!) = ' + E('(c) 30'))
b('MCQ: A committee of 3 is chosen from 5 people. Number of ways?<br>(a) 60 (b) 10 (c) 20 (d) 15', '⁵C₃ = ' + E('(b) 10'))
b('MCQ: If ⁿP₂ = 20, then n =<br>(a) 4 (b) 5 (c) 6 (d) 10', 'n(n − 1) = 20 → ' + E('(b) 5'))
b('MCQ: The number of 3-digit numbers with distinct digits is<br>(a) 720 (b) 648 (c) 900 (d) 504', '9 × 9 × 8 = ' + E('(b) 648'))
b('MCQ: ⁿCᵣ + ⁿCᵣ₋₁ equals<br>(a) ⁿ⁺¹Cᵣ (b) ⁿCᵣ₊₁ (c) ⁿ⁻¹Cᵣ (d) 2ⁿCᵣ', E('(a)') + ': Pascal’s rule')
b('Integer answer (JEE Main): number of 4-letter words (any letters) from the letters of MATH with no letter repeated?', N('24') + ' (4!)')
b('Integer answer: the number of straight lines joining 8 points, of which 3 are collinear?', '⁸C₂ − ³C₂ + 1 = 28 − 3 + 1 = ' + N('26'))
b('Integer answer: number of diagonals of a decagon?', '10 × 7/2 = ' + N('35'))
b('Assertion–Reason.<br><b>A:</b> ⁿPᵣ ≥ ⁿCᵣ.<br><b>R:</b> ⁿPᵣ = r! · ⁿCᵣ.<br>(a) Both true, R explains A (b) Both true, R does not explain A (c) A true, R false (d) A false, R true', E('(a)') + ': r! ≥ 1')
b('Assertion–Reason.<br><b>A:</b> The number of subsets of a set of 5 elements is 32.<br><b>R:</b> ⁵C₀ + ⁵C₁ + … + ⁵C₅ = 2⁵.<br>(a) Both true, R explains A (b) Both true, R does not explain A (c) A false, R true (d) Both false', E('(a)'))
b('True/False: ⁿCᵣ = ⁿCₛ implies r = s.', X('False') + ': it also holds when r + s = n (e.g. ⁸C₃ = ⁸C₅)')
b('Case-based: a school has 6 teachers and 8 students for a 5-member panel with exactly 2 teachers. In how many ways?', '⁶C₂ × ⁸C₃ = 15 × 56 = ' + N('840'))
b('Case-based: a PIN has 4 digits (0–9), repetition allowed, and the first digit is not 0. How many PINs?', '9 × 10 × 10 × 10 = ' + N('9000'))
b('3-mark: how many 4-digit numbers greater than 5000 can be formed from 3, 5, 6, 7, 9 with no repetition?', 'Thousands digit 5, 6, 7 or 9 (4 ways), then 4 × 3 × 2: ' + N('4 × 24 = 96'))
b('4-mark: 5 boys and 4 girls form a team of 5 with at least 2 girls. How many teams?', 'Total ⁹C₅ = 126 minus (0 girls: ⁵C₅ = 1) minus (1 girl: ⁴C₁·⁵C₄ = 20) = ' + N('105'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
