import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch03-matrices')
d = Deck('Chapter 3: Matrices', 'Class 12', ['class-12', 'mathematics', 'ch-3'])
d.description = 'Order and types of matrices, equality, addition and scalar multiplication, matrix multiplication, transpose, symmetric and skew-symmetric matrices, invertible matrices, and exam-style problems.'
b = d.basic

# ---------------------------------------------------------------- 3.2 Matrix, order
d.sec('3.2-matrix-and-order')
b('Define a matrix.', 'An ' + T('ordered rectangular array of numbers or functions') + '.<br>The numbers are its elements (entries).<br>Horizontal lines are rows, vertical lines are columns')
b('What is the order of a matrix? How many elements?', 'm rows and n columns: order ' + T('m × n') + ' (“m by n”), with ' + T('mn') + ' elements. Rows come first, then columns')
b('What does aᵢⱼ mean?', 'The element in the ' + T('i-th row and j-th column') + '.<br>i-th row: (aᵢ₁, ..., aᵢₙ)<br>j-th column: (a₁ⱼ, ..., aₘⱼ)')
b('Example 2: if a matrix has 8 elements, what orders are possible?', 'All pairs of natural numbers with product 8: ' + N('1 × 8, 8 × 1, 2 × 4, 4 × 2'))
b('How do you find all possible orders for a matrix with N elements?', 'List the ' + T('ordered factor pairs') + ' (m, n) with mn = N. A prime N (like 13 or 5) gives only ' + N('1 × N and N × 1'))
b('Ex 3.1 Q1: for A = [[2, 5, 19, −7], [35, −2, 5/2, 12], [√3, 1, −5, 17]] find the order, number of elements, a₁₃, a₂₁, a₃₃, a₂₄, a₂₃.', 'Order ' + N('3 × 4') + ', ' + N('12') + ' elements. a₁₃ = 19, a₂₁ = 35, a₃₃ = −5, a₂₄ = 12, a₂₃ = 5/2')
b('Ex 3.1 Q2: possible orders for 24 elements? for 13 elements?', '24: ' + N('1×24, 2×12, 3×8, 4×6, 6×4, 8×3, 12×2, 24×1') + '. 13 (prime): ' + N('1×13, 13×1'))
b('Ex 3.1 Q3: possible orders for 18 elements? for 5 elements?', '18: ' + N('1×18, 2×9, 3×6, 6×3, 9×2, 18×1') + '. 5: ' + N('1×5, 5×1'))
b('Ex 3.1 Q4(i): build the 2 × 2 matrix with aᵢⱼ = (i + j)²/2.', 'a₁₁ = 2, a₁₂ = 9/2, a₂₁ = 9/2, a₂₂ = 8: ' + N('[[2, 9/2], [9/2, 8]]'))
b('Ex 3.1 Q4(ii),(iii): 2 × 2 with aᵢⱼ = i/j, and with aᵢⱼ = (i + 2j)²/2.', '(ii) ' + N('[[1, 1/2], [2, 1]]') + '. (iii) a₁₁ = 9/2, a₁₂ = 25/2, a₂₁ = 8, a₂₂ = 18: ' + N('[[9/2, 25/2], [8, 18]]'))
b('Ex 3.1 Q5: build the 3 × 4 matrices with (i) aᵢⱼ = ½|−3i + j| and (ii) aᵢⱼ = 2i − j.', '(i) rows: [1, 1/2, 0, 1/2], [5/2, 2, 3/2, 1], [4, 7/2, 3, 5/2]. (ii) rows: ' + N('[1, 0, −1, −2], [3, 2, 1, 0], [5, 4, 3, 2]'))
b('How are the vertices of a polygon written as a matrix?', 'Each vertex (x, y) is a row [x y] (or a column). ABCD with A(1,0), B(3,2), C(1,3), D(−1,2) is a ' + T('4 × 2 matrix') + ' with rows [1 0], [3 2], [1 3], [−1 2]. Transformations (rotation, reflection) are then matrix multiplications')

d.sec('3.3-types-of-matrices')
table_card(d, 'Types of matrices', 'Define each type of matrix.', [
    ('Column matrix', 'only one column (m × 1)', False), ('Row matrix', 'only one row (1 × n)', False),
    ('Square matrix', 'rows = columns (n × n); diagonal a₁₁, a₂₂, …, aₙₙ', False),
    ('Diagonal matrix', 'square, aᵢⱼ = 0 for i ≠ j', False), ('Scalar matrix', 'diagonal with all diagonal entries equal (k)', False),
    ('Identity matrix Iₙ', 'diagonal with all diagonal entries 1', False), ('Zero matrix O', 'all elements 0 (any order)', False)], term='Types of matrices',
    note='Identity ⊂ scalar ⊂ diagonal ⊂ square')
b('How are identity, scalar and diagonal matrices related?', T('Identity ⊂ scalar ⊂ diagonal ⊂ square') + '<br>Every identity matrix is scalar (k = 1).<br>Every scalar matrix is diagonal.<br>' + X('But') + ' a diagonal matrix like diag(1, 2) is not scalar')
b('Is a zero matrix a square matrix? Is it a diagonal matrix?', 'A zero matrix can have any order. If it is square it is also ' + T('diagonal and scalar') + ' (k = 0), but not an identity matrix')
b('Define equal matrices.', 'Same ' + T('order') + ' and ' + T('aᵢⱼ = bᵢⱼ') + ' for every position. [[2, 3], [0, 1]] ≠ [[2, 3, 0]] because the orders differ')
b('Example 4: two equal 3 × 3 matrices give x + 3 = 0, z + 4 = 6, 2y − 7 = 3y − 2, a − 1 = −3, 0 = 2c + 2, b − 3 = 2b + 4. Solve.', 'Each equation has one unknown: ' + N('x = −3, z = 2, y = −5, a = −2, c = −1, b = −7'))
b('Example 5: [[2a + b, a − 2b], [5c − d, 4c + 3d]] = [[4, −3], [11, 24]]. Find a, b, c, d.', 'Two systems: 2a + b = 4, a − 2b = −3 give ' + N('a = 1, b = 2') + '; 5c − d = 11, 4c + 3d = 24 give ' + N('c = 3, d = 4'))
b('Ex 3.1 Q6(i): [[4, 3], [x, 5]] = [[y, z], [1, 5]].', 'Equal entries: ' + N('y = 4, z = 3, x = 1'))
b('Ex 3.1 Q6(ii): [[x + y, 2], [5 + z, xy]] = [[6, 2], [5, 8]].', 'z = 0, x + y = 6, xy = 8: x, y are 2 and 4 in either order: ' + N('(x, y, z) = (2, 4, 0) or (4, 2, 0)'))
b('Ex 3.1 Q6(iii): column (x + y + z, x + z, y + z) = (9, 5, 7).', 'Subtract: y = 9 − 5 = 4, x = 9 − 7 = 2, z = 3: ' + N('x = 2, y = 4, z = 3'))
b('Ex 3.1 Q7: [[a − b, 2a + c], [2a − b, 3c + d]] = [[−1, 5], [0, 13]].', 'a − b = −1 and 2a − b = 0 give a = 1, b = 2. Then 2 + c = 5 gives c = 3; 9 + d = 13 gives d = 4: ' + N('a = 1, b = 2, c = 3, d = 4'))
b('Ex 3.1 Q8: A = [aᵢⱼ]ₘₓₙ is a square matrix if (A) m < n (B) m > n (C) m = n (D) none', E('(C) m = n'))
b('Ex 3.1 Q9: for which x, y are [[3x + 7, 5], [y + 1, 2 − 3x]] and [[0, y − 2], [8, 4]] equal?', 'x = −7/3 and y = 7 from the first row and first column, but then 2 − 3x = 9 ≠ 4. ' + N('Not possible') + ' (B)')
b('Ex 3.1 Q10: number of 3 × 3 matrices with each entry 0 or 1?', 'Nine entries, two choices each: ' + N('2⁹ = 512') + ' (D)')

# ---------------------------------------------------------------- 3.4 Operations
d.sec('3.4-operations')
b('When can two matrices be added? How?', 'Only when they have the ' + T('same order') + '. Add ' + T('corresponding entries') + ': (A + B)ᵢⱼ = aᵢⱼ + bᵢⱼ')
b('Multiplication of a matrix by a scalar k?', T('kA = [k aᵢⱼ]') + ': multiply every element by k. −A = (−1)A, and A − B = A + (−1)B (same order needed)')
b('Properties of matrix addition?', T('Commutative') + ' A + B = B + A; ' + T('associative') + ' (A + B) + C = A + (B + C); additive identity ' + T('O') + ' (A + O = A); additive inverse ' + T('−A') + ' (A + (−A) = O)')
b('Properties of scalar multiplication?', T('k(A + B) = kA + kB') + ' and ' + T('(k + l)A = kA + lA') + ' (also k(lA) = (kl)A and 1·A = A)')
b('Example 9: X + Y = [[5, 2], [0, 9]] and X − Y = [[3, 6], [0, −1]]. Find X and Y.', 'Add: 2X = [[8, 8], [0, 8]], so X = ' + N('[[4, 4], [0, 4]]') + '. Subtract: 2Y = [[2, −4], [0, 10]], so Y = ' + N('[[1, −2], [0, 5]]'))
b('Method: solve 2A + 3X = 5B for X.', '3X = 5B − 2A, so ' + T('X = (1/3)(5B − 2A)') + '<br>Treat matrix equations like algebra, but never divide by a matrix: multiply by scalars only')
b('Ex 3.2 Q1: A = [[2, 4], [3, 2]], B = [[1, 3], [−2, 5]], C = [[−2, 5], [3, 4]]. Find A + B, A − B, 3A − C.', 'A + B = ' + N('[[3, 7], [1, 7]]') + ', A − B = ' + N('[[1, 1], [5, −3]]') + ', 3A − C = [[6 + 2, 12 − 5], [9 − 3, 6 − 4]] = ' + N('[[8, 7], [6, 2]]'))
b('Ex 3.2 Q2(i),(ii): [[a, b], [−b, a]] + [[a, b], [b, a]] and [[a² + b², b² + c²], [a² + c², a² + b²]] + [[2ab, 2bc], [−2ac, −2ab]].', '(i) ' + N('[[2a, 2b], [0, 2a]]') + '. (ii) ' + N('[[(a + b)², (b + c)²], [(a − c)², (a − b)²]]'))
b('Ex 3.2 Q2(iii),(iv): (iii) [[−1, 4, −6], [8, 5, 16], [2, 8, 5]] + [[12, 7, 6], [8, 0, 5], [3, 2, 4]]. (iv) [[cos²x, sin²x], [sin²x, cos²x]] + [[sin²x, cos²x], [cos²x, sin²x]].', '(iii) ' + N('[[11, 11, 0], [16, 5, 21], [5, 10, 9]]') + '. (iv) every entry is cos²x + sin²x = 1: ' + N('[[1, 1], [1, 1]]'))
b('Ex 3.2 Q4: A = [[1, 2, −3], [5, 0, 2], [1, −1, 1]], B = [[3, −1, 2], [4, 2, 5], [2, 0, 3]], C = [[4, 1, 2], [0, 3, 2], [1, −2, 3]]. Find A + B and B − C.', 'A + B = ' + N('[[4, 1, −1], [9, 2, 7], [3, −1, 4]]') + ', B − C = ' + N('[[−1, −2, 0], [4, −1, 3], [1, 2, 0]]') + '. Then A + (B − C) = (A + B) − C by associativity')
b('Ex 3.2 Q5: A = [[2/3, 1, 5/3], [1/3, 2/3, 4/3], [7/3, 2, 2/3]], B = [[2/5, 3/5, 1], [1/5, 2/5, 4/5], [7/5, 6/5, 2/5]]. Compute 3A − 5B.', 'Each entry: 3aᵢⱼ − 5bᵢⱼ = 0 (for example 3·2/3 − 5·2/5 = 0): ' + N('the 3 × 3 zero matrix'))
b('Ex 3.2 Q6: simplify cos θ [[cos θ, sin θ], [−sin θ, cos θ]] + sin θ [[sin θ, −cos θ], [cos θ, sin θ]].', 'Top-left cos²θ + sin²θ = 1, top-right cosθ sinθ − sinθ cosθ = 0, and so on: ' + N('I = [[1, 0], [0, 1]]'))
b('Ex 3.2 Q7(i): X + Y = [[7, 0], [2, 5]] and X − Y = [[3, 0], [0, 3]]. Find X, Y.', 'X = ½(sum + difference) = ' + N('[[5, 0], [1, 4]]') + ', Y = ½(sum − difference) = ' + N('[[2, 0], [1, 1]]'))
b('Ex 3.2 Q7(ii): 2X + 3Y = [[2, 3], [4, 0]] and 3X + 2Y = [[2, −2], [−1, 5]]. Find X, Y.', 'Eliminate: X = (3Q − 2P)/5 and Y = (3P − 2Q)/5 where P, Q are the two right-hand sides. That gives ' + N('X = [[2/5, −12/5], [−11/5, 3]]') + ' and ' + N('Y = [[2/5, 13/5], [14/5, −2]]') + '. Check: 2X + 3Y top-left = 4/5 + 6/5 = 2 ✓')
b('Ex 3.2 Q8: Y = [[3, 2], [1, 4]] and 2X + Y = [[1, 0], [−3, 2]]. Find X.', '2X = [[1 − 3, 0 − 2], [−3 − 1, 2 − 4]] = [[−2, −2], [−4, −2]]: ' + N('X = [[−1, −1], [−2, −1]]'))
b('Ex 3.2 Q9: 2[[1, 3], [0, x]] + [[y, 0], [1, 2]] = [[5, 6], [1, 8]]. Find x, y.', 'LHS = [[2 + y, 6], [1, 2x + 2]]. So y = 3 and 2x + 2 = 8: ' + N('x = 3, y = 3'))
b('Ex 3.2 Q10: 2[[x, z], [y, t]] + 3[[1, −1], [0, 2]] = 3[[3, 5], [4, 6]]. Solve.', '2x + 3 = 9, 2z − 3 = 15, 2y = 12, 2t + 6 = 18: ' + N('x = 3, y = 6, z = 9, t = 6'))
b('Ex 3.2 Q11: x[2, 3]ᵀ + y[−1, 1]ᵀ = [10, 5]ᵀ.', '2x − y = 10 and 3x + y = 5. Add: 5x = 15: ' + N('x = 3, y = −4'))
b('Ex 3.2 Q12: 3[[x, y], [z, w]] = [[x, 6], [−1, 2w]] + [[4, x + y], [z + w, 3]].', '3x = x + 4, 3y = 6 + x + y, 3z = −1 + z + w, 3w = 2w + 3: ' + N('x = 2, y = 4, w = 3, z = 1'))

# ---------------------------------------------------------------- Multiplication
d.sec('3.4-multiplication')
b('When is the product AB defined, and what is its order?', 'When ' + T('columns of A = rows of B') + '. For A (m × n) and B (n × p): AB is ' + T('m × p'))
sm.matmul_dims(d)
sm.matmul_steps(d)
b('Formula for the (i, k) entry of AB?', T('cᵢₖ = aᵢ₁b₁ₖ + aᵢ₂b₂ₖ + ... + aᵢₙbₙₖ = Σⱼ aᵢⱼ bⱼₖ') + ': row i of A dotted with column k of B')
b('Example 12: A = [[6, 9], [2, 3]], B = [[2, 6, 0], [7, 9, 8]]. Find AB. Is BA defined?', 'AB is 2 × 3: ' + N('[[75, 117, 72], [25, 39, 24]]') + '. BA: B has 3 columns but A has 2 rows: ' + X('not defined'))
b('If AB is defined, is BA defined? When are both defined?', X('Not necessarily') + '. For A (m × n), B (k × l): both AB and BA exist iff n = k and l = m. For square matrices of the same order both always exist')
b('Is matrix multiplication commutative?', X('No') + ': AB ≠ BA in general (they may even have different orders). Example 14: A = [[1, 0], [0, −1]], B = [[0, 1], [1, 0]] give AB = [[0, 1], [−1, 0]] but BA = [[0, −1], [1, 0]]')
b('When is AB = BA guaranteed?', 'Diagonal matrices of the same order commute. Also A commutes with ' + T('I, O, and any scalar matrix kI') + ', with itself and its powers, and with polynomials in A')
b('Example 15: A = [[0, −1], [0, 2]], B = [[3, 5], [0, 0]]. Find AB. What does it show?', 'AB = ' + N('O') + '. So ' + X('AB = O does not imply A = O or B = O') + ' (real numbers behave differently)')
b('Trap: does AB = AC imply B = C?', X('No') + ' (no cancellation law). A(B − C) = O does not force B = C when A ≠ O. Example: A = [[1, 1], [1, 1]], B = [[1, 0], [0, 1]], C = [[0, 1], [1, 0]] give AB = AC')
b('Properties of matrix multiplication?', T('Associative') + ' (AB)C = A(BC); ' + T('distributive') + ' A(B + C) = AB + AC and (A + B)C = AC + BC; ' + T('identity') + ' IA = AI = A; but ' + X('not commutative'))
b('Trap: (A + B)² = A² + 2AB + B²?', X('Not in general') + '.<br>(A + B)² = A² + AB + BA + B², and AB ≠ BA.<br>It holds only when AB = BA.<br>Likewise (AB)² ≠ A²B² and A² − B² ≠ (A − B)(A + B) in general')
b('Example 19: cost per contact A = [40, 100, 50]ᵀ paise; contacts X: [1000, 500, 5000], Y: [3000, 1000, 10000]. Total cost for each city?', 'City X: 40 000 + 50 000 + 250 000 = ' + N('340 000') + ' paise<br>City Y: 120 000 + 100 000 + 500 000 = ' + N('720 000') + ' paise<br>That is ' + N('₹3400 and ₹7200'))
b('Example 18: A = [[1, 2, 3], [3, −2, 1], [4, 2, 1]]. Show A³ − 23A − 40I = O.', 'A² = [[19, 4, 8], [1, 12, 8], [14, 6, 15]], A³ = [[63, 46, 69], [69, −6, 23], [92, 46, 63]]. Then A³ − 23A − 40I = O entry by entry. (Cayley–Hamilton: a matrix satisfies its own characteristic equation)')

d.sec('3.4-exercise-3-2-products')
b('Ex 3.2 Q1(iv),(v): AB and BA for A = [[2, 4], [3, 2]], B = [[1, 3], [−2, 5]].', 'AB = ' + N('[[−6, 26], [−1, 19]]') + ' and BA = ' + N('[[11, 10], [11, 2]]') + '. Different, so AB ≠ BA')
b('Ex 3.2 Q3(i): [[a, b], [−b, a]] [[a, −b], [b, a]].', 'Top-left a² + b², top-right −ab + ab = 0, bottom-left −ab + ab = 0, bottom-right b² + a²: ' + N('(a² + b²) I'))
b('Ex 3.2 Q3(ii): the column [1, 2, 3]ᵀ times the row [2, 3, 4].', 'A 3 × 1 times a 1 × 3 gives a 3 × 3 (outer product): ' + N('[[2, 3, 4], [4, 6, 8], [6, 9, 12]]'))
b('Ex 3.2 Q3(iii): [[1, −2], [2, 3]] [[1, 2, 3], [2, 3, 1]].', '2 × 2 by 2 × 3 is 2 × 3: ' + N('[[−3, −4, 1], [8, 13, 9]]'))
b('Ex 3.2 Q3(iv): [[2, 3, 4], [3, 4, 5], [4, 5, 6]] [[1, −3, 5], [0, 2, 4], [3, 0, 5]].', N('[[14, 0, 42], [18, −1, 56], [22, −2, 70]]'))
b('Ex 3.2 Q3(v): [[2, 1], [3, 2], [−1, 1]] [[1, 0, 1], [−1, 2, 1]].', '3 × 2 by 2 × 3 is 3 × 3: ' + N('[[1, 2, 3], [1, 4, 5], [−2, 2, 0]]'))
b('Ex 3.2 Q3(vi): [[3, −1, 3], [−1, 0, 2]] [[2, −3], [1, 0], [3, 1]].', '2 × 3 by 3 × 2 is 2 × 2: ' + N('[[14, −6], [4, 5]]'))
b('Ex 3.2 Q13: F(x) = [[cos x, −sin x, 0], [sin x, cos x, 0], [0, 0, 1]]. Show F(x)F(y) = F(x + y).', 'Top-left: cos x cos y − sin x sin y = cos(x + y); top-right: −cos x sin y − sin x cos y = −sin(x + y); and so on. ' + E('Rotations about the z-axis compose by adding angles'))
b('Ex 3.2 Q14(i): show [[5, −1], [6, 7]][[2, 1], [3, 4]] ≠ [[2, 1], [3, 4]][[5, −1], [6, 7]].', 'Left: [[7, 1], [33, 34]]. Right: [[16, 5], [39, 25]]. ' + X('Different'))
b('Ex 3.2 Q14(ii): the 3 × 3 non-commutativity example.', 'One order gives [[5, 8, 14], [0, −1, 1], [−1, 0, 1]], the other [[−1, −1, −3], [1, 0, 0], [6, 11, 6]]: ' + X('not equal'))
b('Ex 3.2 Q15: A = [[2, 0, 1], [2, 1, 3], [1, −1, 0]]. Find A² − 5A + 6I.', 'A² = [[5, −1, 2], [9, −2, 5], [0, −1, −2]]. Then A² − 5A + 6I = ' + N('[[1, −1, −3], [−1, −1, −10], [−5, 4, 4]]'))
b('Ex 3.2 Q16: A = [[1, 0, 2], [0, 2, 1], [2, 0, 3]]. Prove A³ − 6A² + 7A + 2I = O.', 'Compute A² and A³, then combine entry by entry: every entry cancels to 0. ' + E('✓') + ' (Cayley–Hamilton again)')
b('Ex 3.2 Q17: A = [[3, −2], [4, −2]]. Find k with A² = kA − 2I.', 'A² = [[1, −2], [4, −4]] and kA − 2I = [[3k − 2, −2k], [4k, −2k − 2]]. Then k = 1 fits every entry: ' + N('k = 1'))
b('Ex 3.2 Q18: A = [[0, −tan(α/2)], [tan(α/2), 0]]. Show I + A = (I − A)[[cos α, −sin α], [sin α, cos α]].', 'With t = tan(α/2): cos α = (1 − t²)/(1 + t²), sin α = 2t/(1 + t²). Multiply out (I − A)(rotation) = [[1, t], [−t, 1]] · [[cos α, −sin α], [sin α, cos α]] and simplify to [[1, −t], [t, 1]] = I + A. ' + E('✓'))
b('Ex 3.2 Q19: ₹30 000 is split between bonds paying 5% and 7%. How much in each to earn (a) ₹1800 (b) ₹2000?', 'Let x and 30 000 − x: 0.05x + 0.07(30 000 − x) = interest. (a) 2100 − 0.02x = 1800 gives ' + N('₹15 000 and ₹15 000') + '. (b) 2100 − 0.02x = 2000 gives ' + N('₹5 000 and ₹25 000'))
b('Ex 3.2 Q20: 10 dozen chemistry books at ₹80, 8 dozen physics at ₹60, 10 dozen economics at ₹40. Total receipts?', 'Quantities (120, 96, 120) times prices (80, 60, 40): 9600 + 5760 + 4800 = ' + N('₹20 160'))
b('Ex 3.2 Q21: X is 2 × n, Y is 3 × k, Z is 2 × p, W is n × 3, P is p × k. When is PY + WY defined?', 'PY = (p × k)(3 × k) needs k = 3 and then has order p × 3. WY = (n × 3)(3 × k) has order n × 3. To add them the orders must agree: p = n. ' + E('(A) k = 3, p = n'))
b('Ex 3.2 Q22: if n = p, the order of 7X − 5Z is (A) p × 2 (B) 2 × n (C) n × 3 (D) p × n', 'X is 2 × n and Z is 2 × p = 2 × n, so the combination is ' + E('(B) 2 × n'))

# ---------------------------------------------------------------- 3.5-3.6 Transpose, symmetric
d.sec('3.5-transpose')
b('Define the transpose of a matrix.', T('A′ (or Aᵀ)') + ': swap rows and columns. If A is m × n then A′ is n × m and (A′)ᵢⱼ = aⱼᵢ')
b('Properties of the transpose?', T('(A′)′ = A') + ', ' + T('(kA)′ = kA′') + ', ' + T('(A + B)′ = A′ + B′') + ', ' + T('(AB)′ = B′A′') + ' (order reverses, like socks and shoes)')
b('Trap: (AB)′ = A′B′?', X('No') + '. It is ' + T('B′A′') + '.<br>A′B′ may not even be defined.<br>A (2 × 3), B (3 × 4): (AB)′ is 4 × 2 = (4 × 3)(3 × 2) = B′A′')
b('Ex 3.3 Q1: transposes of the column [5, 1/2, −1]ᵀ, of [[1, −1], [2, 3]] and of [[−1, 5, 6], [√3, 5, 6], [2, 3, −1]].', '(i) the row ' + N('[5, 1/2, −1]') + '. (ii) ' + N('[[1, 2], [−1, 3]]') + '. (iii) ' + N('[[−1, √3, 2], [5, 5, 3], [6, 6, −1]]'))
b('Ex 3.3 Q4: A′ = [[−2, 3], [1, 2]] and B = [[−1, 0], [1, 2]]. Find (A + 2B)′.', 'A = [[−2, 1], [3, 2]]; A + 2B = [[−4, 1], [5, 6]]; transpose ' + N('[[−4, 5], [1, 6]]') + '. Or use (A + 2B)′ = A′ + 2B′')
b('Ex 3.3 Q5(i): A = [1, −4, 3]ᵀ, B = [−1, 2, 1]. Verify (AB)′ = B′A′.', 'AB = [[−1, 2, 1], [4, −8, −4], [−3, 6, 3]] (3 × 3); its transpose equals B′A′ = the column [−1, 2, 1]ᵀ times the row [1, −4, 3]. ' + E('✓'))
b('Ex 3.3 Q6: A = [[cos α, sin α], [−sin α, cos α]]. Verify A′A = I.', 'A′A = [[cos²α + sin²α, 0], [0, sin²α + cos²α]] = ' + N('I') + ' (A is an orthogonal / rotation matrix: A′ = A⁻¹)')

d.sec('3.6-symmetric-skew')
b('Define symmetric and skew-symmetric matrices.', T('Symmetric') + ': A′ = A (aᵢⱼ = aⱼᵢ). ' + T('Skew-symmetric') + ': A′ = −A (aⱼᵢ = −aᵢⱼ). Both must be square')
sm.sym_skew_grid(d)
b('Why is every diagonal entry of a skew-symmetric matrix 0?', 'aᵢᵢ = −aᵢᵢ ⇒ 2aᵢᵢ = 0 ⇒ ' + N('aᵢᵢ = 0'))
b('Theorem 1: what do you know about A + A′ and A − A′ for a square matrix A?', T('A + A′ is symmetric') + ' and ' + T('A − A′ is skew-symmetric') + ' ((A + A′)′ = A′ + A; (A − A′)′ = A′ − A = −(A − A′))')
b('Theorem 2: express any square matrix as symmetric + skew-symmetric.', T('A = ½(A + A′) + ½(A − A′)') + '. The decomposition is unique')
b('Can a matrix be both symmetric and skew-symmetric?', 'Only the ' + T('zero matrix') + ' (A′ = A = −A ⇒ A = O). That is Misc Q10: answer (B) zero matrix')
b('Ex 3.3 Q7: show [[1, −1, 5], [−1, 2, 1], [5, 1, 3]] is symmetric and [[0, 1, −1], [−1, 0, 1], [1, −1, 0]] is skew-symmetric.', 'First: equals its transpose (mirror entries match: −1, 5, 1). Second: zero diagonal and mirror entries are opposites: 1 vs −1, −1 vs 1, 1 vs −1. ' + E('✓'))
b('Ex 3.3 Q8: A = [[1, 5], [6, 7]]. Verify A + A′ is symmetric and A − A′ is skew-symmetric.', 'A + A′ = [[2, 11], [11, 14]] (symmetric); A − A′ = [[0, −1], [1, 0]] (skew-symmetric). ' + E('✓'))
b('Ex 3.3 Q9: find ½(A + A′) and ½(A − A′) for A = [[0, a, b], [−a, 0, c], [−b, −c, 0]].', 'A is already skew-symmetric: ½(A + A′) = ' + N('O (zero matrix)') + ' and ½(A − A′) = ' + N('A itself'))
b('Ex 3.3 Q10(i): write [[3, 5], [1, −1]] as symmetric + skew-symmetric.', 'Symmetric part [[3, 3], [3, −1]], skew part [[0, 2], [−2, 0]]: ' + N('[[3, 3], [3, −1]] + [[0, 2], [−2, 0]]'))
b('Ex 3.3 Q10(ii): [[6, −2, 2], [−2, 3, −1], [2, −1, 3]].', 'It is already symmetric: ' + N('symmetric part = A, skew part = O'))
b('Ex 3.3 Q10(iii): [[3, 3, −1], [−2, −2, 1], [−4, −5, 2]].', 'Symmetric ½(A + A′) = [[3, 1/2, −5/2], [1/2, −2, −2], [−5/2, −2, 2]]; skew ½(A − A′) = ' + N('[[0, 5/2, 3/2], [−5/2, 0, 3], [−3/2, −3, 0]]'))
b('Ex 3.3 Q10(iv): [[1, 5], [−1, 2]].', 'Symmetric [[1, 2], [2, 2]], skew [[0, 3], [−3, 0]]: ' + N('[[1, 2], [2, 2]] + [[0, 3], [−3, 0]]'))
b('Ex 3.3 Q11: if A, B are symmetric of the same order, AB − BA is (A) skew-symmetric (B) symmetric (C) zero (D) identity', '(AB − BA)′ = B′A′ − A′B′ = BA − AB = −(AB − BA): ' + E('(A) skew-symmetric'))
b('Ex 3.3 Q12: A = [[cos α, −sin α], [sin α, cos α]] and A + A′ = I. Then α = ?', 'A + A′ = 2 cos α · I = I so cos α = ½: ' + E('(B) π/3'))
b('Example 24: A, B symmetric. When is AB symmetric?', 'Exactly when ' + T('AB = BA') + '. (AB)′ = B′A′ = BA, which equals AB iff they commute')
b('Which of A + A′, A·A′, A′A are always symmetric for a square matrix A?', T('All three') + '. (A + A′)′ = A + A′; (AA′)′ = (A′)′A′ = AA′; (A′A)′ = A′A. But AB for two symmetric matrices is not symmetric in general')
b('Misc Q1: A, B symmetric, prove AB − BA is skew-symmetric.', '(AB − BA)′ = B′A′ − A′B′ = BA − AB = −(AB − BA). ' + E('✓'))
b('Misc Q2: show B′AB is symmetric if A is symmetric and skew-symmetric if A is skew-symmetric.', '(B′AB)′ = B′A′(B′)′ = B′A′B. If A′ = A it equals B′AB (symmetric); if A′ = −A it equals −B′AB (skew). ' + E('✓'))

# ---------------------------------------------------------------- 3.7 Invertible matrices
d.sec('3.7-invertible-matrices')
b('Define an invertible matrix and its inverse.', 'A square matrix A of order n is invertible if ∃ a square matrix B of the same order with<br>' + T('AB = BA = I') + '<br>Then B = A⁻¹')
b('Can a non-square matrix have an inverse?', X('No') + '.<br>AB and BA would need to be equal identities of the same order,<br>which forces A and B to be square of the same order')
b('The book’s example: A = [[2, 3], [1, 2]] and B = [[2, −3], [−1, 2]]. Are they inverses?', 'AB = [[4 − 3, −6 + 6], [2 − 2, −3 + 4]] = ' + N('I') + ' and BA = I. So B = A⁻¹')
sm.inverse_2x2(d)
b('Theorem 3: is the inverse of a matrix unique?', E('Yes') + '. If B and C are inverses, B = BI = B(AC) = (BA)C = IC = C')
b('Theorem 4: (AB)⁻¹ = ?', T('B⁻¹A⁻¹') + ': undo the last operation first. Proof: (AB)(B⁻¹A⁻¹) = A(BB⁻¹)A⁻¹ = AA⁻¹ = I. Similarly (ABC)⁻¹ = C⁻¹B⁻¹A⁻¹')
b('Relation between transpose and inverse: (A′)⁻¹ = ?', T('(A⁻¹)′') + ', and (A⁻¹)⁻¹ = A, (kA)⁻¹ = (1/k)A⁻¹ (k ≠ 0)')
b('Ex 3.4 Q1: matrices A and B are inverses of each other only if (A) AB = BA (B) AB = BA = O (C) AB = O, BA = I (D) AB = BA = I', E('(D) AB = BA = I'))
b('Which is true: AB = I ⇒ BA = I?', 'For ' + T('square') + ' matrices of the same order, yes (a one-sided inverse is two-sided). This can fail for non-square matrices')
b('If A is invertible and AB = AC, what follows?', 'Multiply by A⁻¹: ' + T('B = C') + '. Invertibility restores the cancellation law that fails for singular matrices')
b('If AB = O and A is invertible, what is B?', 'B = A⁻¹(AB) = A⁻¹O = ' + N('O'))

# ---------------------------------------------------------------- Rotation
d.sec('3.8-miscellaneous')
sm.rotation_powers(d)
b('Example 23: A = [[cos θ, sin θ], [−sin θ, cos θ]]. Prove Aⁿ = [[cos nθ, sin nθ], [−sin nθ, cos nθ]] for n ∈ N.', 'Induction: true for n = 1. If it holds for k, A^(k+1) = A·Aᵏ has top-left cos θ cos kθ − sin θ sin kθ = cos(k + 1)θ and top-right cos θ sin kθ + sin θ cos kθ = sin(k + 1)θ, etc. ' + E('✓'))
b('Misc Q3: A = [[0, 2y, z], [x, y, −z], [x, −y, z]] satisfies A′A = I. Find x, y, z.', 'Columns must be orthonormal:<br>2x² = 1, 6y² = 1, 3z² = 1 (and the cross terms vanish)<br>' + N('x = ±1/√2, y = ±1/√6, z = ±1/√3'))
b('Misc Q4: for what x is [1 2 1] [[1, 2, 0], [2, 0, 1], [1, 0, 2]] [0, 2, x]ᵀ = O?', 'Middle product = [4, x, 2x]ᵀ; then 4 + 2x + 2x = 0: ' + N('x = −1'))
b('Misc Q5: A = [[3, 1], [−1, 2]]. Show A² − 5A + 7I = O.', 'A² = [[8, 5], [−5, 3]], 5A = [[15, 5], [−5, 10]]. Entry by entry: 8 − 15 + 7 = 0, 5 − 5 = 0, −5 + 5 = 0, 3 − 10 + 7 = 0. ' + E('✓') + '<br>Here tr A = 5 and det A = 7: A² − (tr A)A + (det A)I = O')
b('Misc Q6: find x if [x, −5, −1] [[1, 0, 2], [0, 2, 1], [2, 0, 3]] [x, 4, 1]ᵀ = O.', 'Middle product = [x + 2, 9, 2x + 3]ᵀ, then x(x + 2) − 45 − (2x + 3) = x² − 48 = 0: ' + N('x = ±4√3'))
b('Misc Q7: sales matrix: market I sells x, y, z as 10 000, 2 000, 18 000; market II as 6 000, 20 000, 8 000. Unit sale prices ₹2.50, ₹1.50, ₹1.00. Revenue in each market?', 'Multiply by the price column: I: 25 000 + 3 000 + 18 000 = ' + N('₹46 000') + '; II: 15 000 + 30 000 + 8 000 = ' + N('₹53 000'))
b('Misc Q7(b): unit costs ₹2.00, ₹1.00, ₹0.50. Gross profit?', 'Costs: I: 20 000 + 2 000 + 9 000 = 31 000; II: 12 000 + 20 000 + 4 000 = 36 000. Profit: I ' + N('₹15 000') + ', II ' + N('₹17 000') + ', total ₹32 000')
b('Misc Q8: find X with X [[1, 2, 3], [4, 5, 6]] = [[−7, −8, −9], [2, 4, 6]].', 'X is 2 × 2. Row 1: a + 4b = −7, 2a + 5b = −8, so a = 1, b = −2. Row 2: c + 4d = 2, 2c + 5d = 4, so c = 2, d = 0: ' + N('X = [[1, −2], [2, 0]]'))
b('Misc Q9: A = [[α, β], [γ, −α]] with A² = I. Then (A) 1 + α² + βγ = 0 (B) 1 − α² + βγ = 0 (C) 1 − α² − βγ = 0 (D) 1 + α² − βγ = 0', 'A² = (α² + βγ) I, so α² + βγ = 1: ' + E('(C)'))
b('Misc Q10: if A is both symmetric and skew-symmetric, then A is (A) diagonal (B) zero matrix (C) square (D) none', E('(B) zero matrix') + ' (it is square and diagonal too, but zero is the precise answer)')
b('Misc Q11: A² = A, then (I + A)³ − 7A = (A) A (B) I − A (C) I (D) 3A', 'Aⁿ = A for all n ≥ 1: (I + A)³ = I + 3A + 3A² + A³ = I + 7A, so the expression is ' + E('(C) I'))

# ---------------------------------------------------------------- Beyond: exam patterns
d.sec('3.z-exam-patterns')
b('Idempotent, involutory and nilpotent matrices?', T('Idempotent') + ': A² = A<br>' + T('Involutory') + ': A² = I<br>' + T('Nilpotent') + ': Aᵏ = O for some k<br>Example: [[0, 1], [0, 0]] is nilpotent (A² = O)')
b('Find [[1, 1], [0, 1]]ⁿ.', 'Compute A², A³: [[1, 2], [0, 1]], [[1, 3], [0, 1]]. Pattern (by induction): ' + N('[[1, n], [0, 1]]'))
b('Powers of a diagonal matrix diag(a, b)?', N('diag(aⁿ, bⁿ)') + ': multiply the diagonal entries separately (diagonal matrices multiply entrywise on the diagonal)')
b('Find A⁻¹ for A = [[1, 2], [3, 4]] with the shortcut.', 'ad − bc = 4 − 6 = −2. A⁻¹ = (1/−2)[[4, −2], [−3, 1]] = ' + N('[[−2, 1], [3/2, −1/2]]'))
b('Number of 3 × 3 symmetric matrices with entries in {0, 1}?', 'Six free entries (diagonal 3 and above-diagonal 3): ' + N('2⁶ = 64'))
b('Number of 3 × 3 skew-symmetric matrices with entries in {−1, 0, 1}?', 'Diagonal is 0; three free entries above it, each with 3 choices: ' + N('3³ = 27'))
b('Trace of a square matrix: tr(A + B), tr(kA), tr(AB) vs tr(BA)?', T('tr A = sum of diagonal entries') + '<br>tr(A + B) = tr A + tr B<br>tr(kA) = k tr A<br>' + T('tr(AB) = tr(BA)') + ' (even if AB ≠ BA)')
b('If A and B are 3 × 3 with AB = BA, expand (A + B)³.', 'Only because they commute: A³ + 3A²B + 3AB² + B³. Same for (A + B)² = A² + 2AB + B² and A² − B² = (A − B)(A + B)')
b('If A² − A + I = O, what is A⁻¹?', 'Multiply A² − A + I = O by A⁻¹ (A is invertible, since A(A − I) = −I): ' + N('A⁻¹ = I − A'))
b('If A is a 3 × 3 matrix with A² = O, what is (I + A)⁻¹?', '(I + A)(I − A) = I − A² = I, so ' + N('(I + A)⁻¹ = I − A'))

# ---------------------------------------------------------------- How it is asked
d.sec('3.z-how-its-asked')
b('MCQ: if a matrix has 12 elements, the number of possible orders is<br>(a) 4 (b) 6 (c) 8 (d) 12', 'Divisor pairs of 12: 1, 2, 3, 4, 6, 12 → ' + E('(b) 6'))
b('MCQ: if A is 3 × 4 and B is 4 × 2, the order of AB is<br>(a) 3 × 2 (b) 4 × 4 (c) 2 × 3 (d) not defined', E('(a) 3 × 2'))
b('MCQ: if A = [[1, 2], [3, 4]] and B = [[0, 1], [1, 0]], AB =<br>(a) [[2, 1], [4, 3]] (b) [[3, 4], [1, 2]] (c) [[0, 2], [3, 0]] (d) [[1, 3], [2, 4]]', 'Multiplying by B on the right swaps the columns: ' + E('(a) [[2, 1], [4, 3]]'))
b('MCQ: if A is a square matrix with A² = A, then (I + A)² =<br>(a) I + A (b) I + 2A (c) I + 3A (d) I − A', 'I + 2A + A² = I + 3A: ' + E('(c)'))
b('MCQ: if A = [[cos θ, −sin θ], [sin θ, cos θ]], then A² =<br>(a) [[cos 2θ, −sin 2θ], [sin 2θ, cos 2θ]] (b) [[cos²θ, −sin²θ], [sin²θ, cos²θ]] (c) I (d) 2A', 'Rotation by θ twice is rotation by 2θ: ' + E('(a)'))
b('MCQ: the matrix [[0, 5, −7], [−5, 0, 11], [7, −11, 0]] is<br>(a) symmetric (b) skew-symmetric (c) diagonal (d) scalar', 'Zero diagonal and aⱼᵢ = −aᵢⱼ: ' + E('(b) skew-symmetric'))
b('MCQ: for a square matrix A, A + A′ is always<br>(a) skew-symmetric (b) symmetric (c) diagonal (d) identity', E('(b) symmetric'))
b('MCQ: if A is invertible, (A′)⁻¹ =<br>(a) A′ (b) (A⁻¹)′ (c) A (d) −A′', E('(b) (A⁻¹)′'))
b('MCQ: if A = [[1, 0], [0, −1]], then A² =<br>(a) A (b) −A (c) I (d) O', E('(c) I') + '. A is involutory')
b('MCQ: the number of 2 × 2 matrices with entries from {0, 1} is<br>(a) 4 (b) 8 (c) 16 (d) 2', '2⁴ = ' + E('(c) 16'))
b('Integer answer (JEE Main): if A = [[1, 1], [0, 1]], the (1, 2) entry of A¹⁰⁰ is?', 'Aⁿ = [[1, n], [0, 1]], so ' + N('100'))
b('Integer answer: if A = [[2, 3], [1, 2]], the sum of the entries of A⁻¹ is?', 'ad − bc = 1, so A⁻¹ = [[2, −3], [−1, 2]]. Sum = 2 − 3 − 1 + 2 = ' + N('0'))
b('Integer answer: how many 3 × 3 matrices with entries 0 or 1 are there with exactly two 1s?', 'Choose which 2 of 9 positions: ' + N('⁹C₂ = 36'))
b('Assertion–Reason.<br><b>A:</b> if AB = O then A = O or B = O.<br><b>R:</b> the product of two non-zero real numbers is non-zero.<br>(a) Both true, R explains A (b) Both true, R does not (c) A false, R true (d) Both false', E('(c)') + ': R is true for numbers, but matrices can be zero divisors: A = [[0, −1], [0, 2]], B = [[3, 5], [0, 0]] have AB = O')
b('Assertion–Reason.<br><b>A:</b> (AB)′ = A′B′ for all conformable A, B.<br><b>R:</b> (AB)′ = B′A′.<br>(a) Both true, R explains A (b) A false, R true (c) A true, R false (d) Both false', E('(b)') + ': the correct rule reverses the order, so A is false')
b('True/False: every diagonal matrix commutes with every square matrix of the same order.', X('False') + '. Only ' + T('scalar matrices') + ' commute with all matrices.<br>Counterexample: diag(1, 2) does not commute with [[0, 1], [1, 0]]')
b('True/False: the product of two symmetric matrices is symmetric.', X('False') + ' in general; it is symmetric iff they commute')
b('2-mark: if A = [[1, 2], [−1, 3]] find A′ and check (A′)′ = A.', 'A′ = [[1, −1], [2, 3]] and (A′)′ = [[1, 2], [−1, 3]] = A. ' + E('✓'))
b('3-mark: express [[2, 4], [1, 3]] as the sum of a symmetric and a skew-symmetric matrix.', 'P = ½(A + A′) = [[2, 5/2], [5/2, 3]]; Q = ½(A − A′) = [[0, 3/2], [−3/2, 0]]. ' + N('A = P + Q'))
b('3-mark: A = [[1, 2], [2, 1]]. Show A² − 2A − 3I = O and hence find A⁻¹.', 'A² = [[5, 4], [4, 5]], so A² − 2A − 3I = O.<br>Then A(A − 2I) = 3I, so<br>' + N('A⁻¹ = (1/3)(A − 2I) = (1/3)[[−1, 2], [2, −1]]'))
b('4-mark: if A = [[1, 2], [3, 4]] and f(x) = x² − 5x − 2, find f(A).', 'A² = [[7, 10], [15, 22]]<br>A² − 5A − 2I = [[7 − 5 − 2, 10 − 10], [15 − 15, 22 − 20 − 2]] = ' + N('O') + '<br>This is Cayley–Hamilton: tr A = 5, det A = −2')
b('4-mark: A = [[1, −1], [2, −1]], B = [[a, 1], [b, −1]] and (A + B)² = A² + B². Find a and b.', '(A + B)² = A² + AB + BA + B², so we need AB + BA = O.<br>AB = [[a − b, 2], [2a − b, 3]] and BA = [[a + 2, −a − 1], [b − 2, 1 − b]]<br>Entry (1, 2): 2 − a − 1 = 0 gives a = 1<br>Entry (1, 1): 2a − b + 2 = 0 gives b = 4<br>' + N('a = 1, b = 4'))
b('Case-based: a shop sells pens, notebooks and files. Monday sales [30, 20, 10], price per item [₹5, ₹25, ₹40]. Write the revenue as a matrix product and compute it.', 'Row [30 20 10] times the column [5, 25, 40]ᵀ: 150 + 500 + 400 = ' + N('₹1050') + '. A 1 × 3 times a 3 × 1 is 1 × 1')
b('Case-based: coordinates of triangle vertices are the columns of [[0, 4, 2], [0, 0, 3]]. Multiplying on the left by [[1, 0], [0, −1]] does what?', 'It changes the sign of every y-coordinate: ' + N('reflection in the x-axis') + '. New vertices (0, 0), (4, 0), (2, −3)')

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
