import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch06-applications-of-derivatives')
d = Deck('Chapter 6: Applications of Derivatives', 'Class 12', ['class-12', 'mathematics', 'ch-6'])
d.description = 'Rate of change and related rates, marginal cost and revenue, increasing and decreasing functions, local and absolute maxima and minima, derivative tests, and optimisation problems with exam-style questions.'
b = d.basic

# ---------------------------------------------------------------- 6.2 Rate of change
d.sec('6.2-rate-of-change')
b('What does dy/dx represent?', T('The rate of change of y with respect to x') + '. At x = x₀ it is dy/dx at x₀, the instantaneous rate (slope of the tangent). Positive: y increases as x increases; negative: it decreases')
b('If x = f(t) and y = g(t), how are dy/dt, dx/dt and dy/dx related?', T('dy/dx = (dy/dt)/(dx/dt)') + ' (dx/dt ≠ 0), or dy/dt = (dy/dx)(dx/dt), the chain rule')
sm.rate_area_ring(d)
b('Related rates: general method.', '1) Draw a figure and name the variables. 2) Write an equation linking them that is true at ' + T('all times') + ' (do not substitute numbers yet). 3) ' + T('Differentiate with respect to t') + '. 4) Substitute the instant’s values. 5) State the answer with units and sign')
b('Trap: substituting the instant’s values before differentiating.', X('Wrong') + ': a constant has zero derivative. For a ladder with x = 4 fixed in the equation you would lose the term. Differentiate first, then plug in numbers (except for quantities that really stay constant)')
sm.ladder_frames(d)
b('Useful formulas for related-rates problems.', 'Circle: A = πr², C = 2πr. Sphere: V = (4/3)πr³, S = 4πr². Cube: V = x³, S = 6x². Cone: V = (1/3)πr²h. Cylinder: V = πr²h. Pythagoras for ladders and shadows; similar triangles for cones and shadows')
b('Example 1: rate of change of the area of a circle with respect to its radius when r = 5 cm.', 'dA/dr = 2πr = ' + N('10π cm²/cm'))
b('Marginal cost and marginal revenue: definitions.', T('Marginal cost') + ' = dC/dx, the rate of change of total cost with output. ' + T('Marginal revenue') + ' = dR/dx. Each approximates the cost (revenue) of the next unit')
b('Example 5: C(x) = 0.005x³ − 0.02x² + 30x + 5000. Marginal cost at x = 3?', 'C′(x) = 0.015x² − 0.04x + 30. At x = 3: 0.135 − 0.12 + 30 = ' + N('₹30.015 ≈ ₹30.02'))
b('Example 6: R(x) = 3x² + 36x + 5. Marginal revenue at x = 5?', 'R′(x) = 6x + 36 = 6(5) + 36 = ' + N('₹66'))

d.sec('6.2-exercise-6-1')
b('Ex 6.1 Q1: rate of change of the area of a circle with respect to r when (a) r = 3 cm (b) r = 4 cm.', '2πr: (a) ' + N('6π cm²/cm') + ', (b) ' + N('8π cm²/cm'))
b('Ex 6.1 Q2: the volume of a cube increases at 8 cm³/s. How fast is the surface area increasing when the edge is 12 cm?', 'V = x³: 3x² dx/dt = 8, so dx/dt = 8/432 = 1/54. S = 6x²: dS/dt = 12x dx/dt = 144/54 = ' + N('8/3 cm²/s'))
b('Ex 6.1 Q3: the radius of a circle increases uniformly at 3 cm/s. Rate of change of area when r = 10 cm?', 'dA/dt = 2πr dr/dt = 2π · 10 · 3 = ' + N('60π cm²/s'))
b('Ex 6.1 Q4: an edge of a cube increases at 3 cm/s. How fast does the volume increase when the edge is 10 cm?', 'dV/dt = 3x² dx/dt = 3 · 100 · 3 = ' + N('900 cm³/s'))
b('Ex 6.1 Q5: waves in a lake spread as circles at 5 cm/s. How fast is the enclosed area increasing when r = 8 cm?', 'dA/dt = 2πr dr/dt = 2π · 8 · 5 = ' + N('80π cm²/s'))
b('Ex 6.1 Q6: the radius of a circle grows at 0.7 cm/s. Rate of change of its circumference?', 'C = 2πr: dC/dt = 2π · 0.7 = ' + N('1.4π cm/s'))
b('Ex 6.1 Q7: rectangle length x decreases at 5 cm/min, width y increases at 4 cm/min. When x = 8 and y = 6, rates of change of (a) perimeter (b) area?', '(a) P = 2(x + y): 2(−5 + 4) = ' + N('−2 cm/min') + '. (b) A = xy: y dx/dt + x dy/dt = 6(−5) + 8(4) = ' + N('2 cm²/min'))
b('Ex 6.1 Q8: a spherical balloon is inflated at 900 cm³/s. How fast does the radius grow when r = 15 cm?', 'V = (4/3)πr³: dV/dt = 4πr² dr/dt → dr/dt = 900/(4π · 225) = ' + N('1/π cm/s'))
b('Ex 6.1 Q9: rate of change of the volume of a sphere with respect to its radius when r = 10 cm?', 'dV/dr = 4πr² = ' + N('400π cm³/cm'))
b('Ex 6.1 Q10: a 5 m ladder slides away from a wall at 2 cm/s. How fast does the top slide down when the foot is 4 m away?', 'x² + y² = 25, y = 3: 2x x′ + 2y y′ = 0 → y′ = −(4/3)(2) = ' + N('−8/3: down at 8/3 cm/s'))
b('Ex 6.1 Q11: a particle moves on 6y = x³ + 2. Find the points where the y-coordinate changes 8 times as fast as the x-coordinate.', '6 dy/dt = 3x² dx/dt and dy/dt = 8 dx/dt → 48 = 3x² → x = ±4. Points ' + N('(4, 11)') + ' and ' + N('(−4, −31/3)'))
b('Ex 6.1 Q12: the radius of an air bubble increases at ½ cm/s. Rate of increase of the volume when r = 1 cm?', 'dV/dt = 4πr² dr/dt = 4π · 1 · ½ = ' + N('2π cm³/s'))
b('Ex 6.1 Q13: a balloon has diameter (3/2)(2x + 1). Find dV/dx.', 'r = (3/4)(2x + 1), dr/dx = 3/2. V = (4/3)πr³: dV/dx = 4πr² dr/dx = 4π · (9/16)(2x + 1)² · (3/2) = ' + N('(27/8)π (2x + 1)²'))
b('Ex 6.1 Q14: sand pours at 12 cm³/s into a cone whose height is always one-sixth of the base radius. How fast is the height increasing when h = 4 cm?', 'r = 6h, V = (1/3)π(6h)²h = 12πh³. dV/dt = 36πh² dh/dt = 12 → dh/dt = 12/(36π · 16) = ' + N('1/(48π) cm/s'))
b('Ex 6.1 Q15: C(x) = 0.007x³ − 0.003x² + 15x + 4000. Marginal cost when 17 units are produced?', 'C′(x) = 0.021x² − 0.006x + 15; at x = 17: 6.069 − 0.102 + 15 = ' + N('₹20.967'))
b('Ex 6.1 Q16: R(x) = 13x² + 26x + 15. Marginal revenue at x = 7?', 'R′ = 26x + 26 = ' + N('₹208'))
b('Ex 6.1 Q17: the rate of change of the area of a circle with respect to r at r = 6 cm is (A) 10π (B) 12π (C) 8π (D) 11π', '2π · 6 = ' + E('(B) 12π'))
b('Ex 6.1 Q18: R(x) = 3x² + 36x + 5. Marginal revenue at x = 15? (A) 116 (B) 96 (C) 90 (D) 126', '6 · 15 + 36 = ' + E('(D) 126'))
b('Example 30: distance x = t²(2 − t/3) metres. When does the car stop, and how far has it gone?', 'v = dx/dt = 4t − t² = t(4 − t) = 0 at t = 0 and t = 4. So it stops after ' + N('4 s') + ' having covered 16(2 − 4/3) = ' + N('32/3 m'))

# ---------------------------------------------------------------- 6.3 Increasing/decreasing
d.sec('6.3-increasing-decreasing')
b('Define increasing, decreasing, constant on an interval I.', T('Increasing') + ': x₁ < x₂ ⇒ f(x₁) ≤ f(x₂). ' + T('Decreasing') + ': x₁ < x₂ ⇒ f(x₁) ≥ f(x₂). ' + T('Strictly') + ' increasing/decreasing: replace ≤, ≥ by <, >. Constant: f(x) = c on I')
b('Theorem 1: the derivative test for monotonicity.', 'Let f be continuous on [a, b] and differentiable on (a, b). ' + T('f′(x) > 0 on (a, b) ⇒ strictly increasing') + '; ' + T('f′(x) < 0 ⇒ strictly decreasing') + '; f′(x) = 0 ⇒ constant. (f′ ≥ 0 gives increasing, f′ ≤ 0 decreasing)')
b('Method: find where f is increasing or decreasing.', '1) Find f′. 2) Solve f′ = 0 and mark the points where f′ is undefined. 3) These split the domain into intervals. 4) Check the sign of f′ on each interval (test point or factorisation). 5) Write the intervals (open at the split points)')
b('Why does the derivative test need the Mean Value Theorem?', 'f(x₂) − f(x₁) = f′(c)(x₂ − x₁) for some c between x₁ and x₂. So the sign of f′ decides the sign of the difference. (The MVT is the bridge between slope and function values.)')
b('Example 7: show f(x) = 7x − 3 is increasing on R.', 'f′(x) = 7 > 0 for all x: ' + E('increasing on R'))
b('Example 10: intervals of f(x) = x² − 4x + 6.', 'f′ = 2x − 4 = 0 at x = 2. Increasing on ' + N('(2, ∞)') + ', decreasing on ' + N('(−∞, 2)'))
b('Example 11: intervals of f(x) = 4x³ − 6x² − 72x + 30.', 'f′ = 12x² − 12x − 72 = 12(x − 3)(x + 2). Increasing on ' + N('(−∞, −2) ∪ (3, ∞)') + ', decreasing on ' + N('(−2, 3)'))
b('Example 9: is cos x increasing or decreasing on (0, π)? On (π, 2π)?', 'f′ = −sin x < 0 on (0, π): ' + N('decreasing') + '. On (π, 2π), −sin x > 0: ' + N('increasing') + '. Neither on (0, 2π)')
b('Example 12: intervals of sin 3x on (0, π/2).', 'f′ = 3 cos 3x = 0 at x = π/6. Increasing on ' + N('(0, π/6)') + ' and decreasing on ' + N('(π/6, π/2)'))
sm.sign_strip_cubic(d)
b('Trap: “f′(c) = 0 means f has a local extremum at c”?', X('False') + '. For f(x) = x³, f′(0) = 0 but f is increasing on both sides: a point of inflexion, not an extremum. You must check the sign change of f′')
b('Is f(x) = x³ strictly increasing on R even though f′(0) = 0?', E('Yes') + '. f′ ≥ 0 with equality only at isolated points, so f is still strictly increasing. Strictness fails only if f′ = 0 on a whole interval')

d.sec('6.3-exercise-6-2')
b('Ex 6.2 Q1–Q2: show 3x + 17 and e^(2x) are increasing on R.', 'f′ = 3 > 0. For e^(2x): f′ = 2e^(2x) > 0. ' + E('✓') + ' (exponentials are always increasing)')
b('Ex 6.2 Q3: show sin x is (a) increasing on (0, π/2) (b) decreasing on (π/2, π) (c) neither on (0, π).', 'f′ = cos x: positive on (0, π/2), negative on (π/2, π), so on (0, π) it changes sign: ' + E('✓'))
b('Ex 6.2 Q4: intervals for f(x) = 2x² − 3x.', 'f′ = 4x − 3. (a) increasing on ' + N('(3/4, ∞)') + '; (b) decreasing on ' + N('(−∞, 3/4)'))
b('Ex 6.2 Q5: intervals for f(x) = 2x³ − 3x² − 36x + 7.', 'f′ = 6(x − 3)(x + 2). (a) increasing on ' + N('(−∞, −2) and (3, ∞)') + '; (b) decreasing on ' + N('(−2, 3)'))
b('Ex 6.2 Q6(a): strictly monotone intervals of x² + 2x − 5.', 'f′ = 2x + 2: ' + N('decreasing for x < −1, increasing for x > −1'))
b('Ex 6.2 Q6(b): 10 − 6x − 2x².', 'f′ = −6 − 4x: ' + N('increasing for x < −3/2, decreasing for x > −3/2'))
b('Ex 6.2 Q6(c): −2x³ − 9x² − 12x + 1.', 'f′ = −6(x + 1)(x + 2): ' + N('increasing for −2 < x < −1; decreasing for x < −2 and for x > −1'))
b('Ex 6.2 Q6(d): 6 − 9x − x².', 'f′ = −9 − 2x: ' + N('increasing for x < −9/2, decreasing for x > −9/2'))
b('Ex 6.2 Q6(e): (x + 1)³(x − 3)³.', 'f′ = 3[(x + 1)(x − 3)]²(2x − 2), sign of (x − 1): ' + N('increasing on (1, 3) and (3, ∞); decreasing on (−∞, −1) and (−1, 1)'))
b('Ex 6.2 Q7: show y = log(1 + x) − 2x/(2 + x) is increasing for x > −1.', 'y′ = 1/(1 + x) − 4/(2 + x)² = x²/((1 + x)(2 + x)²) ≥ 0 for x > −1 (zero only at 0). ' + E('✓'))
b('Ex 6.2 Q8: for which x is y = [x(x − 2)]² increasing?', 'y′ = 2x(x − 2)(2x − 2) = 4x(x − 1)(x − 2). Positive for ' + N('0 < x < 1 and x > 2'))
b('Ex 6.2 Q9: show y = 4 sin θ/(2 + cos θ) − θ is increasing on [0, π/2].', 'y′ = (8 cos θ + 4)/(2 + cos θ)² − 1 = cos θ (4 − cos θ)/(2 + cos θ)² ≥ 0 when cos θ ≥ 0. ' + E('✓'))
b('Ex 6.2 Q10: show the logarithmic function is increasing on (0, ∞).', 'f = log x, f′ = 1/x > 0 for x > 0. ' + E('✓'))
b('Ex 6.2 Q11: show f(x) = x² − x + 1 is neither strictly increasing nor decreasing on (−1, 1).', 'f′ = 2x − 1 is negative for x < ½ and positive for x > ½: ' + E('✓') + ' (f is decreasing then increasing)')
b('Ex 6.2 Q12: which functions are decreasing on (0, π/2)? (A) cos x (B) cos 2x (C) cos 3x (D) tan x', 'cos x and cos 2x decrease on (0, π/2); cos 3x rises after x = π/3; tan x increases. ' + E('(A) and (B)'))
b('Ex 6.2 Q13: f(x) = x¹⁰⁰ + sin x − 1 is decreasing on (A) (0, 1) (B) (π/2, π) (C) (0, π/2) (D) none', 'f′ = 100x⁹⁹ + cos x. On (0, 1) and (0, π/2) it starts positive (cos x near 1) and stays so; on (π/2, π), 100x⁹⁹ is huge. It is never negative: ' + E('(D) none of these'))
b('Ex 6.2 Q14: for what values of a is f(x) = x² + ax + 1 increasing on [1, 2]?', 'f′ = 2x + a ≥ 0 on [1, 2] needs 2 + a > 0 (strict): ' + N('a > −2'))
b('Ex 6.2 Q15: show f(x) = x + 1/x is increasing on any interval I disjoint from [−1, 1].', 'f′ = 1 − 1/x² > 0 when |x| > 1, and I lies inside |x| > 1. ' + E('✓'))
b('Ex 6.2 Q16: show f(x) = log sin x is increasing on (0, π/2) and decreasing on (π/2, π).', 'f′ = cot x: positive on (0, π/2), negative on (π/2, π). ' + E('✓'))
b('Ex 6.2 Q17: show f(x) = log|cos x| is decreasing on (0, π/2) and increasing on (3π/2, 2π).', 'f′ = −tan x: negative on (0, π/2); tan x < 0 on (3π/2, 2π) so f′ > 0. ' + E('✓'))
b('Ex 6.2 Q18: show f(x) = x³ − 3x² + 3x − 100 is increasing on R.', 'f′ = 3(x − 1)² ≥ 0, zero only at x = 1. ' + E('✓'))
b('Ex 6.2 Q19: y = x²e^(−x) is increasing on (A) (−∞, ∞) (B) (−2, 0) (C) (2, ∞) (D) (0, 2)', 'y′ = x(2 − x)e^(−x) > 0 for 0 < x < 2: ' + E('(D) (0, 2)'))

# ---------------------------------------------------------------- 6.4 Maxima and minima
d.sec('6.4-maxima-and-minima')
b('Definitions: local maximum, local minimum, absolute maximum.', T('Local max at c') + ': f(c) ≥ f(x) for x near c. ' + T('Local min') + ': f(c) ≤ f(x) near c. ' + T('Absolute (global) max') + ': f(c) ≥ f(x) for every x in the domain. A local max need not be the highest value overall')
b('What is a critical point?', 'A point c in the domain where ' + T('f′(c) = 0') + ' or ' + T('f′ does not exist') + '. Extremes occur only at critical points (interior) or end-points')
b('Theorem 2 (necessary condition): if f has a local extremum at an interior c and f is differentiable there, then?', T('f′(c) = 0') + '. The converse is false (x³ at 0)')
b('First derivative test: statement.', 'At a critical point c: if f′ changes ' + T('+ to −') + ' (left to right), c is a ' + T('local maximum') + '; if ' + T('− to +') + ', a ' + T('local minimum') + '; if it does not change sign, c is a point of inflexion (neither)')
b('Second derivative test: statement.', 'If f′(c) = 0: ' + T('f″(c) < 0') + ' ⇒ local maximum; ' + T('f″(c) > 0') + ' ⇒ local minimum; ' + T('f″(c) = 0') + ' ⇒ test fails (use the first derivative test)')
sm.concavity_second_test(d)
b('Which test should you use?', 'Second derivative test is faster if f″ is easy and non-zero at c. Use the ' + T('first derivative test') + ' when f″(c) = 0, when f′ does not exist at c, or when f″ is messy')
b('What is a point of inflexion?', 'A point where the ' + T('concavity changes') + ' (f″ changes sign). Typically f″ = 0 there. It may or may not have f′ = 0 (x³ at 0 does; at a general inflexion the slope need not be 0)')
b('Absolute extrema on [a, b]: procedure.', 'f continuous on [a, b]: 1) find critical points inside; 2) evaluate f at those points and at ' + T('both end-points') + '; 3) the largest is the absolute max, the smallest the absolute min. (A continuous function on a closed interval attains both.)')
sm.closed_interval_extrema(d)
b('Do continuous functions on open or infinite intervals always have extrema?', X('No') + ': eˣ, log x, x³ + x² + x + 1 have neither maximum nor minimum on R (or (0, ∞)); f(x) = x on (−1, 1) has none either')

d.sec('6.4-exercise-6-3')
b('Ex 6.3 Q1(i)–(ii): extrema of f(x) = (2x − 1)² + 3 and 9x² + 12x + 2.', '(i) (2x − 1)² ≥ 0: ' + N('minimum 3') + ', no maximum. (ii) (3x + 2)² − 2: ' + N('minimum −2') + ', no maximum')
b('Ex 6.3 Q1(iii)–(iv): f(x) = −(x − 1)² + 10 and g(x) = x³ + 1.', '(iii) ' + N('maximum 10') + ', no minimum. (iv) g is strictly increasing and unbounded: ' + N('neither maximum nor minimum'))
b('Ex 6.3 Q2(i),(ii): f(x) = |x + 2| − 1 and g(x) = −|x + 1| + 3.', '(i) |x + 2| ≥ 0: ' + N('minimum −1') + ', no maximum. (ii) −|x + 1| ≤ 0: ' + N('maximum 3') + ', no minimum')
b('Ex 6.3 Q2(iii),(iv): h(x) = sin 2x + 5 and f(x) = |sin 4x + 3|.', '(iii) sin 2x ∈ [−1, 1]: ' + N('min 4, max 6') + '. (iv) sin 4x + 3 ∈ [2, 4]: ' + N('min 2, max 4'))
b('Ex 6.3 Q2(v): h(x) = x + 1 on (−1, 1).', 'h is strictly increasing on an open interval; its values fill (0, 2) but 0 and 2 are never attained: ' + N('neither minimum nor maximum'))
b('Ex 6.3 Q3(i),(ii): local extrema of x² and x³ − 3x.', '(i) local minimum at x = 0, value 0. (ii) g′ = 3x² − 3: local max at x = −1 (value 2), local min at x = 1 (value −2)')
b('Ex 6.3 Q3(iii): local extrema of h(x) = sin x + cos x on (0, π/2).', 'h′ = cos x − sin x = 0 at π/4; h″ = −(sin x + cos x) < 0: ' + N('local maximum √2 at x = π/4'))
b('Ex 6.3 Q3(iv): local extrema of f(x) = sin x − cos x on (0, 2π).', 'f′ = cos x + sin x = 0 at 3π/4 and 7π/4. ' + N('Local max √2 at 3π/4') + ', ' + N('local min −√2 at 7π/4'))
b('Ex 6.3 Q3(v): local extrema of f(x) = x³ − 6x² + 9x + 15.', 'f′ = 3(x − 1)(x − 3). ' + N('Local max 19 at x = 1') + ', ' + N('local min 15 at x = 3'))
b('Ex 6.3 Q3(vi): local extrema of g(x) = x/2 + 2/x, x > 0.', 'g′ = ½ − 2/x² = 0 at x = 2; g″ = 4/x³ > 0: ' + N('local minimum 2 at x = 2'))
b('Ex 6.3 Q3(vii): local extrema of g(x) = 1/(x² + 2).', 'g′ = −2x/(x² + 2)² = 0 at x = 0, sign + to −: ' + N('local maximum 1/2 at x = 0'))
b('Ex 6.3 Q3(viii): local extrema of f(x) = x√(1 − x), 0 < x < 1.', 'f′ = (2 − 3x)/(2√(1 − x)) = 0 at x = 2/3: ' + N('local maximum 2√3/9 at x = 2/3'))
b('Ex 6.3 Q4: prove eˣ, log x and x³ + x² + x + 1 have no maxima or minima.', 'eˣ and log x have f′ ≠ 0 for all x in their domains. For h = x³ + x² + x + 1: h′ = 3x² + 2x + 1 has discriminant 4 − 12 < 0, so h′ > 0 always. ' + E('No critical points ⇒ no extrema'))
b('Ex 6.3 Q5(i): absolute extrema of x³ on [−2, 2].', 'f′ = 3x² = 0 at 0 (f = 0); ends f(−2) = −8, f(2) = 8: ' + N('min −8, max 8'))
b('Ex 6.3 Q5(ii): absolute extrema of sin x + cos x on [0, π].', 'Critical π/4: √2. Ends f(0) = 1, f(π) = −1: ' + N('min −1, max √2'))
b('Ex 6.3 Q5(iii): absolute extrema of 4x − x²/2 on [−2, 9/2].', 'Critical x = 4: 8. Ends: f(−2) = −10, f(9/2) = 7.875: ' + N('min −10, max 8'))
b('Ex 6.3 Q5(iv): absolute extrema of (x − 1)² + 3 on [−3, 1].', 'f(1) = 3 (the vertex, at the right end) and f(−3) = 19. So ' + N('min 3, max 19') + ' (the printed key lists these two values in the opposite order; recomputing gives min 3 at x = 1 and max 19 at x = −3)')
b('Ex 6.3 Q6: the profit function is p(x) = 41 − 72x − 18x². Find the maximum profit.', 'p′ = −72 − 36x = 0 → x = −2; p″ = −36 < 0. p(−2) = 41 + 144 − 72 = ' + N('113'))
b('Ex 6.3 Q7: absolute max and min of 3x⁴ − 8x³ + 12x² − 48x + 25 on [0, 3].', 'f′ = 12(x − 2)(x² + 2) = 0 at x = 2. f(0) = 25, f(2) = −39, f(3) = 16: ' + N('min −39 at x = 2; max 25 at x = 0'))
b('Ex 6.3 Q8: at which points of [0, 2π] does sin 2x attain its maximum?', 'sin 2x = 1 when 2x = π/2 or 5π/2: ' + N('x = π/4 and 5π/4'))
b('Ex 6.3 Q9: maximum value of sin x + cos x?', 'sin x + cos x = √2 sin(x + π/4): ' + N('√2'))
b('Ex 6.3 Q10: maximum of 2x³ − 24x + 107 on [1, 3], and on [−3, −1].', 'f′ = 6(x² − 4), critical ±2. On [1, 3]: f(1) = 85, f(2) = 75, f(3) = 89 → ' + N('89 at x = 3') + '. On [−3, −1]: f(−3) = 125, f(−2) = 139, f(−1) = 129 → ' + N('139 at x = −2'))
b('Ex 6.3 Q11: x⁴ − 62x² + ax + 9 attains its maximum at x = 1 on [0, 2]. Find a.', 'f′(1) = 4 − 124 + a = 0 → ' + N('a = 120'))
b('Ex 6.3 Q12: max and min of x + sin 2x on [0, 2π].', 'f′ = 1 + 2 cos 2x = 0 at x = π/3, 2π/3, 4π/3, 5π/3. Compare with f(0) = 0 and f(2π) = 2π: ' + N('max 2π at x = 2π; min 0 at x = 0'))

d.sec('6.4-optimisation')
b('Optimisation: general method.', '1) Identify the quantity to maximise or minimise. 2) Express it in ' + T('one variable') + ' using the constraint. 3) Find the domain. 4) Set the derivative to 0. 5) Verify max/min (second derivative or end-points). 6) Answer the question asked, with units')
sm.box_volume_opt(d)
b('Ex 6.3 Q13: two numbers with sum 24 and product as large as possible.', 'x(24 − x): derivative 24 − 2x = 0 → ' + N('12 and 12'))
b('Ex 6.3 Q14: positive x, y with x + y = 60 and xy³ maximum.', 'f = x(60 − x)³ (y = 60 − x). f′ = (60 − x)²(60 − 4x) = 0 → ' + N('x = 15, y = 45'))
b('Ex 6.3 Q15: positive x, y with x + y = 35 and x²y⁵ maximum.', 'f = x²(35 − x)⁵: f′ = x(35 − x)⁴(70 − 7x) = 0 → ' + N('x = 10, y = 25'))
b('Ex 6.3 Q16: two positive numbers with sum 16 and the sum of cubes minimum.', 'x³ + (16 − x)³: derivative 3x² − 3(16 − x)² = 0 → x = 8: ' + N('8 and 8'))
b('Ex 6.3 Q17: an 18 cm square tin sheet; squares cut from the corners; open box of maximum volume. Side of the square?', 'V = x(18 − 2x)²: ' + N('x = 3 cm') + ' (V = 432 cm³)')
b('Ex 6.3 Q18: a 45 cm × 24 cm sheet; squares cut at the corners; maximum volume.', 'V = x(45 − 2x)(24 − 2x); V′ = 12x² − 276x + 1080 = 12(x − 5)(x − 18). x = 18 is outside the domain (x < 12): ' + N('x = 5 cm') + ' (V = 5 · 35 · 14 = 2450 cm³)')
b('Ex 6.3 Q19: show that of all rectangles inscribed in a fixed circle, the square has maximum area.', 'Rectangle with sides 2R cos θ, 2R sin θ: area = 2R² sin 2θ, maximal when sin 2θ = 1 → θ = π/4 → ' + E('a square'))
b('Ex 6.3 Q20: show the right circular cylinder of given surface area and maximum volume has height equal to the diameter of its base.', 'S = 2πr² + 2πrh fixed; V = πr²h = r(S − 2πr²)/2. V′ = 0 → S = 6πr² → h = 2r. ' + E('✓'))
b('Ex 6.3 Q21: closed cylindrical can of volume 100 cm³ with least surface area. Dimensions?', 'S = 2πr² + 200/r; S′ = 4πr − 200/r² = 0 → r³ = 50/π. ' + N('r = (50/π)^(1/3) cm, h = 2r = 2(50/π)^(1/3) cm'))
b('Ex 6.3 Q22: a 28 m wire is cut into a square and a circle. How to cut for minimum total area?', 'Square side a, circle radius r, 4a + 2πr = 28. Area A = a² + πr²: minimum when a = 2r. Square wire ' + N('112/(π + 4) m') + ', circle wire ' + N('28π/(π + 4) m'))
b('Ex 6.3 Q23: show the largest cone inscribed in a sphere of radius R has volume 8/27 of the sphere.', 'Height h = 4R/3 at the maximum. V = (1/3)πr²h with r² = h(2R − h): maximise → h = 4R/3, V = 32πR³/81 = (8/27)(4πR³/3). ' + E('✓'))
b('Ex 6.3 Q24: the right circular cone of least curved surface area and given volume has altitude √2 times the base radius.', 'Minimise S² ∝ r²(r² + h²) with r²h constant: derivative gives h² = 2r². ' + E('h = √2 r ✓'))
b('Ex 6.3 Q25: show the semi-vertical angle of the cone of maximum volume with given slant height is tan⁻¹√2.', 'r = l sin α, h = l cos α, V = (1/3)π l³ sin²α cos α. V′ = 0 → tan²α = 2. ' + E('α = tan⁻¹√2 ✓'))
b('Ex 6.3 Q26: show the semi-vertical angle of the cone of given surface area and maximum volume is sin⁻¹(1/3).', 'Maximise V with S = πr(r + l) fixed: leads to l = 3r, so sin α = r/l = 1/3. ' + E('✓'))
b('Ex 6.3 Q27: the point on x² = 2y nearest to (0, 5) is (A) (2√2, 4) (B) (2√2, 0) (C) (0, 0) (D) (2, 2)', 'D = x² + (y − 5)² = y² − 8y + 25, minimum at y = 4: ' + E('(A) (2√2, 4)'))
sm.nearest_point_circle(d)
b('Ex 6.3 Q28: for all real x, the minimum value of (1 − x + x²)/(1 + x + x²) is (A) 0 (B) 1 (C) 3 (D) 1/3', 'f′ = 2(x² − 1)/(1 + x + x²)²: minimum at x = 1: f(1) = 1/3. ' + E('(D) 1/3'))
b('Ex 6.3 Q29: the maximum value of [x(x − 1) + 1]^(1/3), 0 ≤ x ≤ 1, is (A) (1/3)^(1/3) (B) 1/2 (C) 1 (D) 0', 'x² − x + 1 has vertex at ½ (value ¾, the minimum); on [0, 1] its maximum is 1 at the ends. ' + E('(C) 1'))
b('Example 29: an enemy helicopter flies along y = x² + 7. A soldier at (3, 7). Nearest distance?', 'D² = (x − 3)² + x⁴; derivative 2(x − 3) + 4x³ = 2(x − 1)(2x² + 2x + 3) = 0 gives x = 1. D = √5 = ' + N('√5'))
b('Example 37: a manufacturer sells x items at (5 − x/100) each; cost of x items is x/5 + 500. Maximise profit.', 'P = 5x − x²/100 − x/5 − 500 = (24/5)x − x²/100 − 500. P′ = 24/5 − x/50 = 0 → ' + N('x = 240 items') + ' (P″ = −1/50 < 0)')

# ---------------------------------------------------------------- Miscellaneous
d.sec('6.5-miscellaneous')
b('Misc Q1: show f(x) = (log x)/x has its maximum at x = e.', 'f′ = (1 − log x)/x² = 0 at x = e, positive before, negative after. ' + E('✓') + ' Maximum value 1/e')
b('Misc Q2: an isosceles triangle has fixed base b; the two equal sides shrink at 3 cm/s. How fast is the area decreasing when they equal the base?', 'A = (b/4)√(4x² − b²). dA/dt = (b/4)(4x/√(4x² − b²)) dx/dt. At x = b: (b/4)(4b/(b√3))(−3) = ' + N('−b√3 cm²/s') + ' (decreasing at b√3 cm²/s)')
b('Misc Q3: intervals for f(x) = (4 sin x − 2x − x cos x)/(2 + cos x).', 'f′ = cos x (4 − cos x)/(2 + cos x)², the sign of cos x. (i) increasing on ' + N('[0, π/2] and (3π/2, 2π)') + '; (ii) decreasing on ' + N('(π/2, 3π/2)'))
b('Misc Q4: intervals for f(x) = x³ + 1/x³, x ≠ 0.', 'f′ = 3(x⁶ − 1)/x⁴. (i) increasing for ' + N('x < −1 and x > 1') + '; (ii) decreasing for ' + N('−1 < x < 1 (x ≠ 0)'))
b('Misc Q5: maximum area of an isosceles triangle inscribed in x²/a² + y²/b² = 1 with a vertex at one end of the major axis.', 'Base points (x, ±y) on the ellipse, vertex (a, 0): area = y(a − x) is maximised at x = −a/2. ' + N('Maximum area = 3√3 ab/4'))
b('Misc Q6: open tank with base a rectangle, depth 2 m, volume 8 m³; base costs ₹70/m², sides ₹45/m². Cost of the least expensive tank?', 'Base area 4: l·w = 4. Cost = 70 · 4 + 45 · 2(l + w) · 2 = 280 + 180(l + w). Minimum when l = w = 2: ' + N('₹1000'))
b('Misc Q7: perimeter of a circle plus perimeter of a square is k. Show the total area is least when the square’s side is twice the circle’s radius.', '2πr + 4a = k; A = πr² + a². Substituting r = (k − 4a)/(2π) and A′(a) = 0 gives a = 2r. ' + E('✓'))
b('Misc Q8: a window is a rectangle topped by a semicircle, perimeter 10 m. Dimensions for maximum light?', 'A = 10r − 2r² − πr²/2, A′ = 0 → r = 10/(4 + π); the height of the rectangle equals r. ' + N('Width 20/(π + 4) m, height 10/(π + 4) m'))
b('Misc Q9: a point on the hypotenuse of a right triangle is at distances a and b from the two legs. Show the minimum hypotenuse is (a^(2/3) + b^(2/3))^(3/2).', 'A line through the point meeting the legs at angle θ has length L = a/sin θ + b/cos θ. L′ = 0 gives tan³θ = a/b, and then L = (a^(2/3) + b^(2/3))^(3/2). ' + E('✓'))
b('Misc Q10: f(x) = (x − 2)⁴(x + 1)³. Find the points of (i) local maxima (ii) local minima (iii) inflexion.', 'f′ = (x − 2)³(x + 1)²(7x − 2). Sign change + to − at x = 2/7: ' + N('local max at 2/7') + '; − to + at x = 2: ' + N('local min at 2') + '; no sign change at −1 (from (x + 1)²): ' + N('point of inflexion at −1'))
b('Misc Q11: absolute max and min of cos²x + sin x on [0, π].', 'With s = sin x ∈ [0, 1]: f = 1 + s − s². Vertex at s = ½: f = 5/4. At s = 0 or 1: f = 1. ' + N('Max 5/4, min 1'))
b('Misc Q12: show the altitude of the right circular cone of maximum volume inscribed in a sphere of radius r is 4r/3.', 'V = (π/3)h²(2r − h) (base radius² = h(2r − h)). V′ = (π/3)(4rh − 3h²) = 0 → ' + E('h = 4r/3 ✓'))
b('Misc Q13: f′(x) > 0 for all x ∈ (a, b). Prove f is increasing on (a, b).', 'By the Mean Value Theorem, for x₁ < x₂ there is c with f(x₂) − f(x₁) = f′(c)(x₂ − x₁) > 0. ' + E('✓'))
b('Misc Q14: the cylinder of maximum volume inscribed in a sphere of radius R has height 2R/√3. Find its volume.', 'V = πr²h with r² = R² − h²/4: V = πh(R² − h²/4); V′ = 0 → h = 2R/√3, r² = 2R²/3. ' + N('V = 4πR³/(3√3)'))
b('Misc Q15: the cylinder of greatest volume in a cone of height h and semi-vertical angle α has height h/3; the volume is (4/27)πh³ tan²α.', 'With cylinder radius r, height H: r = (h − H) tan α. V = π(h − H)²tan²α · H; V′ = 0 → H = h/3. V = π(2h/3)²(tan²α)(h/3) = (4/27)πh³tan²α. ' + E('✓'))
b('Misc Q16: a cylindrical tank of radius 10 m is filled with wheat at 314 m³/h. Rate of increase of depth? (A) 1 m/h (B) 0.1 m/h (C) 1.1 m/h (D) 0.5 m/h', 'V = π r² h: dh/dt = 314/(π · 100) = 314/314 = ' + E('(A) 1 m/h') + ' (π = 3.14)')

# ---------------------------------------------------------------- Beyond
d.sec('6.z-exam-patterns')
b('Rolle’s theorem: statement (a JEE favourite).', 'If f is continuous on [a, b], differentiable on (a, b) and f(a) = f(b), then ∃ c ∈ (a, b) with ' + T('f′(c) = 0') + '. Example: x² − 4x + 3 on [1, 3] gives c = 2')
b('Mean value theorem: statement.', 'If f is continuous on [a, b] and differentiable on (a, b): ∃ c with ' + T('f′(c) = (f(b) − f(a))/(b − a)') + ' (some point has the average slope). Example: f = x² on [1, 3]: 2c = 4, c = 2')
b('Number of real roots of x³ − 3x + 1 = 0?', 'f = x³ − 3x + 1, local max f(−1) = 3 and local min f(1) = −1 have opposite signs: ' + N('3 real roots'))
b('Minimum value of x + 1/x for x > 0?', 'f′ = 1 − 1/x² = 0 at x = 1, f″ = 2/x³ > 0: ' + N('2') + ' (also AM–GM)')
b('Maximum value of sin x + cos x, and of a sin x + b cos x?', N('√2') + ' and ' + N('√(a² + b²)'))
b('Minimum of 4x + 9/x for x > 0?', 'f′ = 4 − 9/x² = 0 at x = 3/2: f = 6 + 6 = ' + N('12') + ' (also AM–GM: 4x + 9/x ≥ 2√36)')
b('The sum of two numbers is 20. Minimise the sum of their squares.', 'x² + (20 − x)²: derivative 4x − 40 = 0 → x = 10: ' + N('10, 10; minimum sum of squares = 200'))
b('Fence problem: 100 m of fencing encloses a rectangle. Maximum area?', 'Perimeter 2(l + w) = 100. Area l(50 − l) maximal at l = 25: ' + N('625 m² (a square)'))
b('Shortest distance from the point (1, 0) to the parabola y² = 4x?', 'D² = (x − 1)² + 4x = (x + 1)² for x ≥ 0: minimum at x = 0. ' + N('Distance 1, at the vertex (0, 0)'))
b('A closed box with a square base has volume 1000 cm³. Minimum surface area?', 'S = 2x² + 4·1000/x; S′ = 0 → x = 10: ' + N('600 cm² (a cube)'))
b('Tangent slope at the maximum of a smooth function?', 'Zero: at a local extremum of a differentiable function the tangent is ' + T('horizontal') + ' (f′ = 0). At a corner (like |x| at 0) the minimum has no tangent')
b('If the sum of a positive number and its reciprocal is at least 2, why?', 'x + 1/x ≥ 2 for x > 0, with equality at x = 1 (minimum from calculus; or AM–GM). It appears in many optimisation problems')

# ---------------------------------------------------------------- How it is asked
d.sec('6.z-how-its-asked')
b('MCQ: the function f(x) = x³ − 3x is decreasing in<br>(a) (−∞, −1) (b) (−1, 1) (c) (1, ∞) (d) R', 'f′ = 3(x − 1)(x + 1) < 0 on (−1, 1): ' + E('(b)'))
b('MCQ: the maximum value of f(x) = sin x + cos x on [0, π/2] is<br>(a) 1 (b) √2 (c) 2 (d) 1/√2', E('(b) √2'))
b('MCQ: the minimum value of x² + 16/x for x > 0 is<br>(a) 12 (b) 8 (c) 16 (d) 24', 'f′ = 2x − 16/x² = 0 at x = 2: f(2) = 4 + 8 = ' + E('(a) 12'))
b('MCQ: f(x) = x² e^(−x) has a local maximum at x =<br>(a) 0 (b) 1 (c) 2 (d) −2', 'f′ = x(2 − x)e^(−x), sign + to − at 2: ' + E('(c) 2'))
b('MCQ: the radius of a circle grows at 2 cm/s. When r = 5 cm the area grows at<br>(a) 10π (b) 20π (c) 25π (d) 5π cm²/s', '2πr dr/dt = 20π: ' + E('(b)'))
b('MCQ: the total revenue is R(x) = 5x² + 3x. The marginal revenue at x = 2 is<br>(a) 23 (b) 20 (c) 13 (d) 26', 'R′ = 10x + 3 = ' + E('(a) 23'))
b('MCQ: f(x) = |x| has at x = 0<br>(a) local maximum (b) local minimum (c) point of inflexion (d) no extremum', 'Minimum value 0, f′ changes − to +: ' + E('(b) local minimum'))
b('MCQ: the function f(x) = x³ has at x = 0<br>(a) a local maximum (b) a local minimum (c) a point of inflexion (d) none', 'f′ = 3x² does not change sign: ' + E('(c) point of inflexion'))
b('MCQ: for the function y = x + 4/x, the local minimum value is<br>(a) 2 (b) 4 (c) 8 (d) −4', 'y′ = 1 − 4/x² = 0 at x = 2: y = ' + E('(b) 4'))
b('MCQ: two positive numbers with sum 8 and maximum product are<br>(a) 4, 4 (b) 5, 3 (c) 6, 2 (d) 7, 1', E('(a) 4, 4'))
b('Integer answer (JEE Main): the number of critical points of f(x) = x³ − 3x is?', 'f′ = 3x² − 3 = 0: x = ±1: ' + N('2'))
b('Integer answer: the maximum value of f(x) = 12x − x³ on [−3, 3] is?', 'f′ = 12 − 3x² = 0 at x = ±2: f(2) = 16, f(−2) = −16, f(±3) = ±9: ' + N('16'))
b('Integer answer: if the area of a square increases at 4 cm²/s, how fast does its side increase (in cm/s) when the side is 2 cm?', 'A = s²: 2s ds/dt = 4 → ds/dt = 4/(2 · 2) = ' + N('1'))
b('Assertion–Reason.<br><b>A:</b> f′(c) = 0 implies f has an extremum at c.<br><b>R:</b> f(x) = x³ has f′(0) = 0 and no extremum at 0.<br>(a) Both true, R explains A (b) A false, R true (c) A true, R false (d) Both false', E('(b)') + ': R is a counterexample to A')
b('Assertion–Reason.<br><b>A:</b> a continuous function on a closed interval attains its maximum.<br><b>R:</b> the maximum occurs at a critical point or an end-point.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(b)') + ': both are true statements; R tells where to look, it does not explain existence')
b('True/False: if f″(c) = 0 then c is a point of inflexion.', X('False') + ': x⁴ has f″(0) = 0 and a minimum at 0. It needs f″ to change sign')
b('True/False: an absolute maximum on a closed interval can occur at an end-point.', E('True') + ': for example x on [0, 1] has its maximum at x = 1')
b('2-mark: find the rate of change of the volume of a sphere with respect to its radius when r = 2 cm.', '4πr² = ' + N('16π cm³/cm'))
b('2-mark: show f(x) = 2x + 5 is strictly increasing on R.', 'f′ = 2 > 0 for all x: ' + E('✓'))
b('3-mark: find the intervals in which f(x) = x² − 6x + 5 is increasing or decreasing.', 'f′ = 2x − 6 = 0 at 3: ' + N('decreasing on (−∞, 3), increasing on (3, ∞)'))
b('3-mark: find two positive numbers whose sum is 30 and whose product is maximum.', 'x(30 − x): derivative 30 − 2x = 0 → ' + N('15 and 15') + ' (product 225)')
b('4-mark: find the local maxima and minima of f(x) = x³ − 12x + 5.', 'f′ = 3(x − 2)(x + 2). f″ = 6x: f″(−2) < 0, f″(2) > 0. ' + N('Local max 21 at x = −2') + ', ' + N('local min −11 at x = 2'))
b('4-mark: a rectangular field with a river on one side needs fencing on three sides, 200 m in total. Maximum area?', 'x sides perpendicular, 200 − 2x along: A = x(200 − 2x); A′ = 200 − 4x = 0 → x = 50: ' + N('5000 m²') + ' (50 m by 100 m)')
b('Case-based: a ball is thrown upward: h(t) = 20t − 5t² metres. Find the maximum height and when it is reached.', 'h′ = 20 − 10t = 0 → t = 2 s; h(2) = 40 − 20 = ' + N('20 m'))
b('Case-based: the profit of a firm is P(x) = −x² + 60x − 500 (x units). How many units maximise profit and what is the maximum?', 'P′ = −2x + 60 = 0 → x = 30; P(30) = −900 + 1800 − 500 = ' + N('₹400 at 30 units'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
