import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '11th', 'Mathematics', 'class11-mathematics-ch10-conic-sections')
d = Deck('Chapter 10: Conic Sections', 'Class 11', ['class-11', 'mathematics', 'ch-10'])
d.description = 'Cone sections, circle, parabola, ellipse, hyperbola: definitions, standard equations, eccentricity, latus rectum, applications and exam patterns.'
b = d.basic

# ---------------------------------------------------------------- 10.2 Sections of a cone
d.sec('10.2-cone-sections')
b('Why are circles, ellipses, parabolas and hyperbolas called conic sections?', 'They are the curves obtained by ' + T('cutting a double-napped right circular cone with a plane') + '. Named by Apollonius')
sm.cone_sections(d)
b('Cone terms: vertex, axis, generator, nappes, α, β.', 'Vertex V; axis l (fixed line); generator m (rotating line inclined at α to the axis); the vertex splits the cone into two ' + T('nappes') + '; β = angle of the cutting plane with the axis')
b('Degenerate conics (plane through the vertex)?', 'α < β ≤ 90°: a ' + T('point') + '. β = α: a ' + T('straight line') + ' (degenerate parabola). 0 ≤ β < α: a ' + T('pair of intersecting lines') + ' (degenerate hyperbola)')

# ---------------------------------------------------------------- 10.3 Circle
d.sec('10.3-circle')
b('Define a circle.', 'The set of all points of a plane ' + T('equidistant from a fixed point') + ' (centre); the common distance is the radius')
b('Equation of a circle with centre (h, k) and radius r?', r'\((x - h)^2 + (y - k)^2 = r^2\)' + '. Centre at the origin: x² + y² = r²')
b('Example 2: circle with centre (−3, 2) and radius 4.', N('(x + 3)² + (y − 2)² = 16'))
b('General equation of a circle? Its centre and radius?', r'\(x^2 + y^2 + 2gx + 2fy + c = 0\)' + ': centre ' + T('(−g, −f)') + ', radius ' + T('√(g² + f² − c)') + ' (real only if g² + f² − c > 0)')
b('Conditions for Ax² + Bxy + Cy² + Dx + Ey + F = 0 to be a circle?', T('A = C ≠ 0 and B = 0') + ' (then divide by A). Also need positive radius²')
b('Example 3: centre and radius of x² + y² + 8x + 10y − 8 = 0.', 'Complete squares: (x + 4)² + (y + 5)² = 49 → centre ' + N('(−4, −5)') + ', radius ' + N('7'))
b('Method: centre and radius from a general equation.', 'Group x and y terms, ' + T('complete the square') + ' on each, move constants right. (Or use (−g, −f) and √(g² + f² − c).) Check the coefficients of x² and y² are 1 first')
b('Ex 10.1 Q1–5: circles with centre (0, 2) r = 2; (−2, 3) r = 4; (1/2, 1/4) r = 1/12; (1, 1) r = √2; (−a, −b) r = √(a² − b²).', 'x² + (y − 2)² = 4;  (x + 2)² + (y − 3)² = 16;  (x − ½)² + (y − ¼)² = 1/144;  (x − 1)² + (y − 1)² = 2;  (x + a)² + (y + b)² = a² − b²')
b('Ex 10.1 Q6–7: centre and radius of (x + 5)² + (y − 3)² = 36 and x² + y² − 4x − 8y − 45 = 0.', N('(−5, 3), r = 6') + ';  (x − 2)² + (y − 4)² = 65 → ' + N('(2, 4), r = √65'))
b('Ex 10.1 Q8–9: centre and radius of x² + y² − 8x + 10y − 12 = 0 and 2x² + 2y² − x = 0.', N('(4, −5), r = √53') + ';  x² + y² − x/2 = 0 → ' + N('(¼, 0), r = ¼'))
b('Example 4: circle through (2, −2) and (3, 4) with centre on x + y = 2.', 'Equate the two squared radii and use h + k = 2: h = 0.7, k = 1.3, r² = 12.58 → ' + N('(x − 0.7)² + (y − 1.3)² = 12.58'))
b('Method: circle through two points with centre on a line.', 'Let the centre be (h, k). Use ' + T('equal distance to both points') + ' (or the perpendicular bisector of the chord) together with the line equation; solve for h, k; then r² = distance²')
b('Ex 10.1 Q10: circle through (4, 1), (6, 5) with centre on 4x + y = 16.', 'Centre (h, 16 − 4h): equal distances give h = 3, k = 4, r² = 10 → ' + N('(x − 3)² + (y − 4)² = 10'))
b('Ex 10.1 Q11: circle through (2, 3), (−1, 1) with centre on x − 3y = 11.', 'Centre (3k + 11, k): k = −5/2, h = 7/2, r² = 65/2 → ' + N('(x − 7/2)² + (y + 5/2)² = 65/2'))
b('Ex 10.1 Q12: radius 5, centre on the x-axis, through (2, 3).', '(2 − h)² + 9 = 25 → h = 6 or −2: ' + N('(x − 6)² + y² = 25') + ' or ' + N('(x + 2)² + y² = 25'))
b('Ex 10.1 Q13: circle through the origin with intercepts a and b on the axes.', N('x² + y² − ax − by = 0') + ' (centre (a/2, b/2))')
b('Ex 10.1 Q14: centre (2, 2), through (4, 5).', 'r² = 4 + 9 = 13 → ' + N('(x − 2)² + (y − 2)² = 13'))
b('Ex 10.1 Q15: is (−2.5, 3.5) inside, outside or on x² + y² = 25?', '6.25 + 12.25 = 18.5 < 25 → ' + N('inside'))
b('Point versus circle: how do you decide inside/on/outside?', 'Compute S = x₁² + y₁² + 2gx₁ + 2fy₁ + c.<br>' + T('S < 0 inside') + '<br>' + T('S = 0 on the circle') + '<br>' + T('S > 0 outside') + '<br>(equivalent to comparing the distance from the centre with r)')
b('Circle with diameter endpoints (x₁, y₁) and (x₂, y₂)?', T('(x − x₁)(x − x₂) + (y − y₁)(y − y₂) = 0'))
b('Circle through three non-collinear points: method?', 'Put the three points into x² + y² + 2gx + 2fy + c = 0 to get three linear equations in g, f, c and solve')
b('Tangent condition: the line y = mx + c touches x² + y² = r² when?', r'\(c^2 = r^2(1 + m^2)\)' + ' (distance from the centre to the line equals r)')

# ---------------------------------------------------------------- 10.4 Parabola
d.sec('10.4-parabola')
b('Define a parabola.', 'The set of points equidistant from a fixed ' + T('line (directrix)') + ' and a fixed ' + T('point (focus)') + ' not on the line')
b('Degenerate parabola?', 'If the focus lies on the directrix, the locus is the ' + X('straight line through the focus perpendicular to the directrix'))
b('Axis and vertex of a parabola?', 'Axis: the line through the focus perpendicular to the directrix. Vertex: where the parabola meets its axis (midpoint of focus and directrix)')
sm.parabola_focus_directrix(d)
table_card(d, '10.4 · Standard parabolas', 'Opens which way? Focus, directrix?', [
    ('y² = 4ax', 'right; focus (a, 0); directrix x = −a', False), ('y² = −4ax', 'left; focus (−a, 0); directrix x = a', False),
    ('x² = 4ay', 'up; focus (0, a); directrix y = −a', False), ('x² = −4ay', 'down; focus (0, −a); directrix y = a', False)],
    note='Latus rectum = 4a in every case. The squared variable tells the axis.', term='Four standard parabolas')
b('Length of the latus rectum of y² = 4ax and its end points?', N('4a') + '; endpoints ' + T('(a, ±2a)') + ' (AF = 2a, by PF = PD)')
b('Reading a parabola from its equation.', 'The squared variable names the axis: y² → axis along the x-axis. The sign of the linear-term coefficient gives the direction: positive → right/up, negative → left/down. Then 4a = |coefficient|')
b('Example 5: focus, axis, directrix and latus rectum of y² = 8x.', 'a = 2: ' + N('focus (2, 0)') + ', axis the x-axis, ' + N('directrix x = −2') + ', latus rectum ' + N('8'))
b('Example 6–7: parabola with focus (2, 0), directrix x = −2; vertex (0,0), focus (0, 2).', N('y² = 8x') + ' and ' + N('x² = 8y'))
b('Example 8: parabola symmetric about the y-axis through (2, −3).', 'Point in quadrant IV → opens downward: x² = −4ay: 4 = 12a → a = 1/3 → ' + N('3x² = −4y'))
b('Ex 10.2 Q1–2: y² = 12x and x² = 6y: focus, directrix, latus rectum.', 'a = 3: ' + N('(3, 0), x = −3, 12') + '. a = 3/2: ' + N('(0, 3/2), y = −3/2, 6'))
b('Ex 10.2 Q3–4: y² = −8x and x² = −16y.', 'a = 2: ' + N('(−2, 0), x = 2, 8') + '. a = 4: ' + N('(0, −4), y = 4, 16'))
b('Ex 10.2 Q5–6: y² = 10x and x² = −9y.', 'a = 5/2: ' + N('(5/2, 0), x = −5/2, 10') + '. a = 9/4: ' + N('(0, −9/4), y = 9/4, 9'))
b('Ex 10.2 Q7–10: focus (6,0), directrix x = −6; focus (0,−3), directrix y = 3; vertex (0,0) focus (3,0); focus (−2,0).', N('y² = 24x') + ';  ' + N('x² = −12y') + ';  ' + N('y² = 12x') + ';  ' + N('y² = −8x'))
b('Ex 10.2 Q11–12: vertex (0,0) through (2, 3) with axis along the x-axis; through (5, 2) symmetric about the y-axis.', 'y² = 4ax: 9 = 8a → ' + N('y² = (9/2)x') + '. x² = 4ay: 25 = 8a → ' + N('2x² = 25y'))
b('Parabola not at the origin: (y − k)² = 4a(x − h). Vertex, focus, directrix?', 'Vertex (h, k); focus (h + a, k); directrix x = h − a. (Complete the square to bring y² + Dx + Ey + F = 0 to this form)')
b('Focal distance of a point (x₁, y₁) on y² = 4ax?', N('x₁ + a') + ' (distance to the directrix)')
b('Parametric form of y² = 4ax?', T('(at², 2at)') + '. For x² = 4ay: (2at, at²)')
b('Tangent condition: y = mx + c touches y² = 4ax when?', T('c = a/m'))
b('A chord through the focus of y² = 4ax with ends (at₁², 2at₁), (at₂², 2at₂): relation?', T('t₁t₂ = −1') + ' (focal chord). Its length is a(t + 1/t)² (with t₁ = t, t₂ = −1/t)')
sm.parabola_reflector(d)
b('Example 17: a parabolic mirror with focus 5 cm from the vertex is 45 cm deep. Width AB?', 'y² = 20x; at x = 45: y = ±30 → ' + N('60 cm'))
b('Example 18: a 12 m beam sags 3 cm at the centre in a parabola. How far from the centre is the sag 1 cm (measured from the ends)?', 'x² = 4ay with (6)² = 4a(3/100) → a = 300. At height 2 cm above the lowest point: x² = 4·300·(2/100) = 24 → ' + N('x = 2√6 m'))
b('Misc Q1: parabolic reflector 20 cm across and 5 cm deep. Focus?', 'y² = 4ax through (5, 10): 100 = 20a → a = 5. ' + N('Focus 5 cm from the vertex'))
b('Misc Q2: parabolic arch 10 m high and 5 m wide at the base. Width 2 m from the vertex?', 'x² = −4ay through (2.5, −10): a = 5/32, 4a = 5/8. At depth 2: x² = 5/4 → width 2x = ' + N('√5 ≈ 2.23 m'))
b('Misc Q3: suspension-bridge cable, roadway 100 m long, longest wire 30 m, shortest 6 m. Wire 18 m from the middle?', 'Vertex at height 6: x² = 4a(y − 6) through (50, 30): 4a = 2500/24. At x = 18: y − 6 = 324·24/2500 ≈ 3.11 → ' + N('≈ 9.11 m'))
b('Misc Q6: area of the triangle formed by the vertex of x² = 12y and the ends of its latus rectum.', 'LR at y = 3: ends (±6, 3). Area = ½ · 12 · 3 = ' + N('18'))
b('Misc Q8: an equilateral triangle in y² = 4ax with one vertex at the vertex of the parabola. Side?', 'Vertices (0,0), (at², ±2at) with tan 30° = 2at/at² → t = 2√3: side = ' + N('8√3 a'))

# ---------------------------------------------------------------- 10.5 Ellipse
d.sec('10.5-ellipse')
b('Define an ellipse.', 'The set of points whose distances from two fixed points (' + T('foci') + ') have a ' + T('constant sum') + ', greater than the distance between the foci')
sm.ellipse_string(d)
b('Ellipse terms: centre, major axis, minor axis, vertices, a, b, c?', 'Centre = midpoint of the foci. Major axis (through the foci) length ' + T('2a') + ', minor axis length ' + T('2b') + ', focal distance ' + T('2c') + '. Vertices = ends of the major axis')
b('Relation between a, b, c for an ellipse?', N('a² = b² + c²') + ' (c² = a² − b²): a is the hypotenuse, and a > b')
b('Eccentricity of an ellipse?', N('e = c/a') + ', with ' + T('0 < e < 1') + '. Foci at distance ae from the centre; b² = a²(1 − e²)')
b('Standard equation of an ellipse with foci on the x-axis? On the y-axis?', r'\(\dfrac{x^2}{a^2} + \dfrac{y^2}{b^2} = 1\)' + ' (a > b) and ' + r'\(\dfrac{x^2}{b^2} + \dfrac{y^2}{a^2} = 1\)')
b('How do you tell the major axis from the equation?', 'The variable under the ' + T('larger denominator') + ' gives the major axis (x² over the larger number → along the x-axis)')
b('Ellipse symmetry and extent?', 'Symmetric about both axes; lies in the rectangle −a ≤ x ≤ a, −b ≤ y ≤ b, touching its sides')
b('Length of the latus rectum of the ellipse?', r'\(\dfrac{2b^2}{a}\)' + ' (end points (±c, ± b²/a))')
b('Derivation: latus rectum of an ellipse.', 'At x = ae: y² = b²(1 − e²) = b⁴/a², so y = b²/a. Two ends → length 2b²/a')
b('Example 9: foci, vertices, axes, e and latus rectum of x²/25 + y²/9 = 1.', 'a = 5, b = 3, c = 4: foci ' + N('(±4, 0)') + ', vertices ' + N('(±5, 0)') + ', major 10, minor 6, ' + N('e = 4/5') + ', LR ' + N('18/5'))
b('Example 10: 9x² + 4y² = 36.', 'x²/4 + y²/9 = 1: major axis along y, a = 3, b = 2, c = √5<br>Foci ' + N('(0, ±√5)') + '<br>Vertices (0, ±3)<br>Major axis 6, minor axis 4<br>' + N('e = √5/3'))
b('Example 11: vertices (±13, 0), foci (±5, 0).', 'a = 13, c = 5 → b² = 144: ' + N('x²/169 + y²/144 = 1'))
b('Example 12: major axis 20 and foci (0, ±5).', 'a = 10, c = 5 → b² = 75: ' + N('x²/75 + y²/100 = 1'))
b('Example 13: major axis along x through (4, 3) and (−1, 4).', '16/a² + 9/b² = 1 and 1/a² + 16/b² = 1 → a² = 247/7, b² = 247/15 → ' + N('7x² + 15y² = 247'))
b('Ex 10.3 Q1–2: x²/36 + y²/16 = 1 and x²/4 + y²/25 = 1.', 'First: foci (±2√5, 0), vertices (±6, 0), 12, 8, e = √5/3, LR 16/3. Second: foci (0, ±√21), vertices (0, ±5), 10, 4, e = √21/5, LR 8/5')
b('Ex 10.3 Q3–4: x²/16 + y²/9 = 1 and x²/25 + y²/100 = 1.', 'First: foci (±√7, 0), vertices (±4, 0), 8, 6, e = √7/4, LR 9/2. Second: foci (0, ±5√3), vertices (0, ±10), 20, 10, e = √3/2, LR 5')
b('Ex 10.3 Q5–6: x²/49 + y²/36 = 1 and x²/100 + y²/400 = 1.', 'First: foci (±√13, 0), vertices (±7, 0), 14, 12, e = √13/7, LR 72/7. Second: foci (0, ±10√3), vertices (0, ±20), 40, 20, e = √3/2, LR 10')
b('Ex 10.3 Q7–9: 36x² + 4y² = 144; 16x² + y² = 16; 4x² + 9y² = 36.', '(7) x²/4 + y²/36 = 1: foci (0, ±4√2), e = 2√2/3, LR 4/3.  (8) x² + y²/16 = 1: foci (0, ±√15), e = √15/4, LR 1/2.  (9) x²/9 + y²/4 = 1: foci (±√5, 0), e = √5/3, LR 8/3')
b('Ex 10.3 Q10–12: vertices (±5,0) foci (±4,0); vertices (0,±13) foci (0,±5); vertices (±6,0) foci (±4,0).', N('x²/25 + y²/9 = 1') + ';  ' + N('x²/144 + y²/169 = 1') + ';  b² = 20: ' + N('x²/36 + y²/20 = 1'))
b('Ex 10.3 Q13–14: ends of the major axis (±3, 0), minor (0, ±2); major axis ends (0, ±√5), minor ends (±1, 0).', N('x²/9 + y²/4 = 1') + ';  ' + N('x² + y²/5 = 1'))
b('Ex 10.3 Q15–18: 2a = 26, foci (±5,0); 2b = 16, foci (0,±6); foci (±3,0), a = 4; b = 3, c = 4.', N('x²/169 + y²/144 = 1') + ';  a² = 100: ' + N('x²/64 + y²/100 = 1') + ';  b² = 7: ' + N('x²/16 + y²/7 = 1') + ';  a = 5: ' + N('x²/25 + y²/9 = 1'))
b('Ex 10.3 Q19: centre at the origin, major axis on the y-axis, through (3, 2) and (1, 6).', '9/b² + 4/a² = 1 and 1/b² + 36/a² = 1 → a² = 40, b² = 10: ' + N('x²/10 + y²/40 = 1'))
b('Ex 10.3 Q20: major axis on the x-axis, through (4, 3) and (6, 2).', '16/a² + 9/b² = 1 and 36/a² + 4/b² = 1 → a² = 52, b² = 13: ' + N('x²/52 + y²/13 = 1'))
b('Method: finding an ellipse or hyperbola through given points.', '1) Write the standard form with unknowns a², b² (choose the axis from the data).<br>2) Substitute each point to get two ' + T('linear equations in 1/a² and 1/b²') + '.<br>3) Solve, then invert')
b('Ellipse not at the origin: ((x − h)²/a²) + ((y − k)²/b²) = 1. Centre and foci?', 'Centre (h, k); foci (h ± c, k) if a is under x (major axis horizontal)')
b('Parametric form and focal distances of x²/a² + y²/b² = 1?', T('(a cos θ, b sin θ)') + '; focal distances a ± e x₁ (sum 2a)')
b('Tangent condition: y = mx + c touches x²/a² + y²/b² = 1 when?', T('c² = a²m² + b²'))
b('Area of the ellipse x²/a² + y²/b² = 1 and the auxiliary circle?', N('πab') + '; auxiliary circle x² + y² = a² (radius = semi-major axis)')
sm.ladder_ellipse(d)
b('Misc Q4: a semi-elliptical arch is 8 m wide and 2 m high at the centre. Height 1.5 m from one end?', 'x²/16 + y²/4 = 1; at x = 4 − 1.5 = 2.5: y² = 4(1 − 6.25/16) = 2.4375 → ' + N('y ≈ 1.56 m'))
b('Misc Q5: a rod of 12 cm slides on the axes; P is 3 cm from the end on the x-axis. Locus of P?', 'x = 9 cos θ, y = 3 sin θ → ' + N('x²/81 + y²/9 = 1'))
b('Misc Q7: two flag posts 8 m apart; a runner keeps the sum of distances 10 m. Path?', '2a = 10, 2c = 8 → b = 3: ' + N('x²/25 + y²/9 = 1') + ' (an ellipse)')
b('Planet orbits: which conic and where is the Sun?', 'Ellipses with the Sun at ' + T('one focus') + ' (Kepler’s first law; Physics 11 Ch 7). Eccentricity of Earth’s orbit ≈ 0.017 (nearly a circle)')

# ---------------------------------------------------------------- 10.6 Hyperbola
d.sec('10.6-hyperbola')
b('Define a hyperbola.', 'The set of points whose distances from two fixed points (foci) have a ' + T('constant difference') + ' (farther minus nearer)')
sm.hyperbola_difference(d)
b('Hyperbola terms: transverse axis, conjugate axis, vertices, a, b, c?', 'Transverse axis (through the foci, meets the curve at the vertices) length ' + T('2a') + '; conjugate axis length ' + T('2b') + '; distance between foci ' + T('2c'))
b('Relation between a, b, c for a hyperbola?', N('c² = a² + b²') + ' (b² = c² − a²): c is the hypotenuse, so c > a')
sm.abc_triangles(d)
b('Eccentricity of a hyperbola?', N('e = c/a > 1') + ' (never less than 1). Foci at distance ae from the centre; b² = a²(e² − 1)')
b('Standard equations of hyperbolas?', r'\(\dfrac{x^2}{a^2} - \dfrac{y^2}{b^2} = 1\)' + ' (transverse axis along x) and ' + r'\(\dfrac{y^2}{a^2} - \dfrac{x^2}{b^2} = 1\)' + ' (along y)')
b('How do you find the transverse axis from the equation?', 'It lies along the variable with the ' + T('positive term') + '<br>x²/9 − y²/16 = 1 has it along x (length 6)<br>y²/25 − x²/9 = 1 has it along y (length 10)<br>Note: a² is under the positive term, not necessarily the larger denominator')
b('Trap: in ellipses a > b always. In hyperbolas?', X('No') + '. For a hyperbola a can be smaller than, equal to, or larger than b. Only the sign decides the transverse axis. If a = b it is an ' + T('equilateral (rectangular) hyperbola') + ' with e = √2')
b('Extent of the hyperbola x²/a² − y²/b² = 1?', 'x²/a² ≥ 1, so ' + T('x ≤ −a or x ≥ a') + ': no part between x = −a and x = a (no y-intercepts)')
b('Length of the latus rectum of a hyperbola? Asymptotes?', N('2b²/a') + '; asymptotes ' + T('y = ±(b/a)x') + ' (for x²/a² − y²/b² = 1)')
b('Example 14: foci, vertices, e, LR of x²/9 − y²/16 = 1 and y² − 16x² = 16.', '(i) a = 3, b = 4, c = 5: ' + N('foci (±5, 0), vertices (±3, 0), e = 5/3, LR 32/3') + '. (ii) y²/16 − x² = 1: a = 4, b = 1, c = √17: ' + N('foci (0, ±√17), vertices (0, ±4), e = √17/4, LR 1/2'))
b('Example 15: foci (0, ±3), vertices (0, ±√11/2).', 'a² = 11/4, c = 3 → b² = 25/4: ' + N('100y² − 44x² = 275'))
b('Example 16: foci (0, ±12) and latus rectum 36.', '2b²/a = 36 → b² = 18a; 144 = a² + 18a → a = 6, b² = 108: ' + N('3y² − x² = 108'))
b('Ex 10.4 Q1–2: x²/16 − y²/9 = 1 and y²/9 − x²/27 = 1.', 'First: foci (±5, 0), vertices (±4, 0), e = 5/4, LR 9/2. Second: a = 3, b² = 27, c = 6: foci (0, ±6), vertices (0, ±3), e = 2, LR 18')
b('Ex 10.4 Q3–4: 9y² − 4x² = 36 and 16x² − 9y² = 576.', 'First: y²/4 − x²/9 = 1: foci (0, ±√13), vertices (0, ±2), e = √13/2, LR 9. Second: x²/36 − y²/64 = 1: foci (±10, 0), vertices (±6, 0), e = 5/3, LR 64/3')
b('Ex 10.4 Q5–6: 5y² − 9x² = 36 and 49y² − 16x² = 784.', 'First: y²/(36/5) − x²/4 = 1: foci (0, ±2√70/5), vertices (0, ±6/√5), e = √14/3, LR 4√5/3. Second: y²/16 − x²/49 = 1: foci (0, ±√65), vertices (0, ±4), e = √65/4, LR 49/2')
b('Ex 10.4 Q7–9: vertices (±2,0), foci (±3,0); vertices (0,±5), foci (0,±8); vertices (0,±3), foci (0,±5).', N('x²/4 − y²/5 = 1') + ';  ' + N('y²/25 − x²/39 = 1') + ';  ' + N('y²/9 − x²/16 = 1'))
b('Ex 10.4 Q10–11: foci (±5,0) with transverse axis 8; foci (0,±13) with conjugate axis 24.', N('x²/16 − y²/9 = 1') + ';  b = 12, a² = 25: ' + N('y²/25 − x²/144 = 1'))
b('Ex 10.4 Q12–13: foci (±3√5, 0), LR 8; foci (±4, 0), LR 12.', 'b² = 4a, a² + 4a = 45 → a = 5: ' + N('x²/25 − y²/20 = 1') + '. b² = 6a, a² + 6a = 16 → a = 2: ' + N('x²/4 − y²/12 = 1'))
b('Ex 10.4 Q14–15: vertices (±7, 0), e = 4/3; foci (0, ±√10) through (2, 3).', 'c = 28/3, b² = 784/9 − 49 = 343/9: ' + N('x²/49 − 9y²/343 = 1') + '. Second: a² + b² = 10, 9/a² − 4/b² = 1 → a² = b² = 5: ' + N('y² − x² = 5'))
b('Hyperbola not at the origin: (x − h)²/a² − (y − k)²/b² = 1. Centre, foci?', 'Centre (h, k); foci (h ± c, k). Asymptotes (y − k) = ±(b/a)(x − h)')
b('Conjugate hyperbola of x²/a² − y²/b² = 1?', T('x²/a² − y²/b² = −1') + ' (same asymptotes; transverse and conjugate axes swap)')
b('Parametric form of x²/a² − y²/b² = 1?', T('(a sec θ, b tan θ)') + '. Tangent condition y = mx + c: ' + T('c² = a²m² − b²'))
b('Rectangular hyperbola xy = c²: asymptotes, e, parametric form?', 'Axes are the asymptotes; ' + N('e = √2') + '; parametric (ct, c/t)')

# ---------------------------------------------------------------- Comparison
d.sec('10.z-comparison')
sm.eccentricity_line(d)
table_card(d, 'Conics at a glance', 'Compare (centre at the origin, foci on the x-axis).', [
    ('Ellipse', 'x²/a² + y²/b² = 1;  c² = a² − b²;  e < 1;  LR 2b²/a', False), ('Hyperbola', 'x²/a² − y²/b² = 1;  c² = a² + b²;  e > 1;  LR 2b²/a', False),
    ('Parabola', 'y² = 4ax;  e = 1;  LR 4a', False), ('Circle', 'x² + y² = r²;  e = 0', False)], term='Conics comparison table')
b('Identify the conic from the general equation Ax² + Bxy + Cy² + … = 0 (B = 0)?', 'A = C: ' + T('circle') + '. A, C same sign, A ≠ C: ' + T('ellipse') + '. A, C opposite signs: ' + T('hyperbola') + '. One of A, C zero: ' + T('parabola'))
b('Focus–directrix definition for all conics?', T('PF = e · PD') + ': e < 1 ellipse, e = 1 parabola, e > 1 hyperbola')
b('Latus rectum of ellipse and hyperbola: same formula?', E('Yes') + ': ' + N('2b²/a') + ' for both (with a = semi-major / semi-transverse). Parabola: 4a')
b('Compare focus-to-centre distance: ellipse, hyperbola?', 'Ellipse: c = ae < a. Hyperbola: c = ae > a')

# ---------------------------------------------------------------- How it's asked
d.sec('10.z-how-its-asked')
b('MCQ: The centre and radius of x² + y² − 6x + 4y − 12 = 0 are<br>(a) (3, −2), 5 (b) (−3, 2), 5 (c) (3, −2), 25 (d) (3, 2), 5', '(x − 3)² + (y + 2)² = 25 → ' + E('(a)'))
b('MCQ: The focus of the parabola y² = 16x is<br>(a) (4, 0) (b) (0, 4) (c) (16, 0) (d) (2, 0)', 'a = 4 → ' + E('(a)'))
b('MCQ: The length of the latus rectum of x² = −12y is<br>(a) 3 (b) 6 (c) 12 (d) 24', E('(c) 12') + ' = 4a with a = 3')
b('MCQ: The eccentricity of x²/25 + y²/16 = 1 is<br>(a) 3/5 (b) 4/5 (c) 5/3 (d) 9/25', 'c = 3, e = 3/5 → ' + E('(a)'))
b('MCQ: The eccentricity of x²/9 − y²/16 = 1 is<br>(a) 5/3 (b) 5/4 (c) 3/5 (d) 4/3', 'c = 5, e = 5/3 → ' + E('(a)'))
b('MCQ: The equation 4x² + 9y² = 36 represents<br>(a) a circle (b) an ellipse (c) a parabola (d) a hyperbola', 'x²/9 + y²/4 = 1 → ' + E('(b) ellipse'))
b('MCQ: The distance between the foci of x²/16 + y²/7 = 1 is<br>(a) 3 (b) 6 (c) 8 (d) 2√7', 'c² = 16 − 7 = 9, 2c = ' + E('(b) 6'))
b('MCQ: Foci of 16x² − 9y² = 144 are<br>(a) (±5, 0) (b) (±4, 0) (c) (0, ±5) (d) (±3, 0)', 'x²/9 − y²/16 = 1: c = 5 → ' + E('(a)'))
b('Integer answer (JEE Main): if the vertex of y² = 4ax is (0, 0) and it passes through (1, 2), find 4a.', '4 = 4a·1 → ' + N('4'))
b('Integer answer: the length of the major axis of x²/49 + y²/25 = 1 is?', N('14'))
b('Assertion–Reason.<br><b>A:</b> The eccentricity of every ellipse is less than 1.<br><b>R:</b> In an ellipse c < a.<br>(a) Both true, R explains A (b) Both true, R does not explain A (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> x² + y² + 2x + 2y + 5 = 0 is a circle.<br><b>R:</b> Every equation with A = C and B = 0 is a circle.<br>(a) Both true (b) A true, R false (c) A false, R true (d) Both false', 'g² + f² − c = 1 + 1 − 5 < 0: no real circle; R also fails for the same reason: ' + E('(d)'))
b('True/False: the parabola y² = 4ax has eccentricity 1.', E('True') + ': PF = PD, e = 1')
b('3-mark: find the equation of the ellipse with foci (±2, 0) and eccentricity 1/2.', 'c = 2, e = c/a = 1/2 → a = 4, b² = 12: ' + N('x²/16 + y²/12 = 1'))
b('4-mark: find the equation of the hyperbola with foci (0, ±5) and eccentricity 5/3.', 'c = 5, a = 3, b² = 16: ' + N('y²/9 − x²/16 = 1'))
b('Case-based: a satellite dish is a paraboloid 2 m across and 0.5 m deep. Where is the receiver?', 'Section y² = 4ax through (0.5, 1): 1 = 2a → a = 0.5: the receiver is ' + N('0.5 m from the vertex') + ' (at the focus)')
b('Case-based: an elliptical park has major axis 100 m and minor axis 60 m. Distance between the two focus lamps?', 'a = 50, b = 30, c = 40: ' + N('80 m'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
