import sys, os, math
from fractions import Fraction as Fr
from math import comb
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from deckkit import *
import showcase_math as sm

OUT = os.path.join(ROOT, 'premade-cards', '12th', 'Mathematics', 'class12-mathematics-ch13-probability')
d = Deck('Chapter 13: Probability', 'Class 12', ['class-12', 'mathematics', 'ch-13'])
d.description = 'Conditional probability, multiplication theorem, independent events, total probability and Bayes\' theorem, with every exercise computed exactly and exam-style problems.'
b = d.basic


def f(x):
    x = Fr(x)
    return str(x.numerator) if x.denominator == 1 else f'{x.numerator}/{x.denominator}'


def dec(x): return f'{float(x):g}'


# ---------------------------------------------------------------- 13.2 Conditional probability
d.sec('13.2-conditional-probability')
b('Definition of conditional probability.', T('P(E|F) = P(E ∩ F)/P(F)') + ', P(F) ≠ 0: the probability of E given that F has occurred. F becomes the new (reduced) sample space')
sm.cond_prob_venn(d)
b('Properties of conditional probability.', T('0 ≤ P(E|F) ≤ 1') + '; P(S|F) = P(F|F) = 1; ' + T('P(E′|F) = 1 − P(E|F)') + '; P((E ∪ F)|G) = P(E|G) + P(F|G) − P((E ∩ F)|G); P(E|F) = 0 if E and F are mutually exclusive')
b('Trap: is P(E|F) the same as P(F|E)?', X('No') + ': they share the numerator P(E ∩ F) but have different denominators. P(rain | clouds) ≠ P(clouds | rain). (Example 1 type: P(E|F) = 2/3, P(F|E) = 1/3)')
b('Two ways to compute a conditional probability.', '1) Formula P(E ∩ F)/P(F). 2) ' + T('Reduce the sample space') + ': count only outcomes in F and see how many are also in E (works when outcomes are equally likely)')
sm.dice_conditional(d)
b('Example 2: a family has two children. P(both are boys | at least one is a boy)?', 'Sample space {BB, BG, GB, GG}. F = {BB, BG, GB}: 3 outcomes, E ∩ F = {BB}: ' + N('1/3') + '. If instead the elder is known to be a boy the answer is 1/2 (F = {BB, BG})')
b('Example 6 type: a die is thrown twice; P(sum is 4 | numbers are different) etc.', 'Count in the reduced space. Different numbers: 30 outcomes; sum 4 with different numbers: (1,3), (3,1): ' + N('2/30 = 1/15') + ' (Ex 13.1 Q14)')

d.sec('13.2-exercise-13-1')
b('Ex 13.1 Q1: P(E) = 0.6, P(F) = 0.3, P(E ∩ F) = 0.2. Find P(E|F) and P(F|E).', 'P(E|F) = 0.2/0.3 = ' + N(f(Fr(2, 3))) + '; P(F|E) = 0.2/0.6 = ' + N(f(Fr(1, 3))))
b('Ex 13.1 Q2: compute P(A|B) if P(B) = 0.5 and P(A ∩ B) = 0.32.', '0.32/0.5 = 0.64 = ' + N(f(Fr(16, 25))))
pA, pB, pBA = Fr(8, 10), Fr(5, 10), Fr(4, 10)
inter = pA * pBA
b('Ex 13.1 Q3: P(A) = 0.8, P(B) = 0.5, P(B|A) = 0.4. Find (i) P(A ∩ B) (ii) P(A|B) (iii) P(A ∪ B).', '(i) 0.8 × 0.4 = ' + N(dec(inter)) + '. (ii) 0.32/0.5 = ' + N(dec(inter / pB)) + '. (iii) 0.8 + 0.5 − 0.32 = ' + N(dec(pA + pB - inter)))
pAq = Fr(5, 26); pBq = Fr(5, 13); ab = pBq * Fr(2, 5)
ab = pBq * Fr(2, 5)   # P(A|B) = P(A n B)/P(B)  =>  P(A n B) = P(A|B) P(B)
b('Ex 13.1 Q4: evaluate P(A ∪ B) if 2P(A) = P(B) = 5/13 and P(A|B) = 2/5.', 'P(A) = 5/26. P(A ∩ B) = P(A|B)P(B) = (2/5)(5/13) = 2/13. P(A ∪ B) = 5/26 + 5/13 − 2/13 = ' + N(f(pAq + pBq - ab)))
assert pAq + pBq - ab == Fr(11, 26)
pA5, pB5, pU5 = Fr(6, 11), Fr(5, 11), Fr(7, 11)
i5 = pA5 + pB5 - pU5
b('Ex 13.1 Q5: P(A) = 6/11, P(B) = 5/11, P(A ∪ B) = 7/11. Find (i) P(A ∩ B) (ii) P(A|B) (iii) P(B|A).', '(i) 6/11 + 5/11 − 7/11 = ' + N(f(i5)) + '. (ii) (4/11)/(5/11) = ' + N(f(i5 / pB5)) + '. (iii) (4/11)/(6/11) = ' + N(f(i5 / pA5)))
b('Ex 13.1 Q6: a coin is tossed three times. Find P(E|F) for (i) E: head on third toss, F: heads on first two (ii) E: at least two heads, F: at most two heads (iii) E: at most two tails, F: at least one tail.', '(i) F = {HHH, HHT}, E ∩ F = {HHH}: ' + N('1/2') + '. (ii) F has 7 outcomes (all but HHH), E ∩ F = exactly two heads (3): ' + N('3/7') + '. (iii) F has 7 outcomes (all but HHH), E ∩ F = one or two tails (6): ' + N('6/7'))
b('Ex 13.1 Q7: two coins are tossed once. Find P(E|F): (i) E: tail on one coin, F: one coin shows head (ii) E: no tail, F: no head.', '(i) E = {HT, TH, TT}, F = {HT, TH, HH}: E ∩ F = {HT, TH}: ' + N('2/3') + '. (ii) E = {HH}, F = {TT}: E ∩ F = ∅: ' + N('0'))
b('Ex 13.1 Q8: a die is thrown three times. E: 4 on the third throw; F: 6 and 5 on the first two throws. Find P(E|F).', 'The third throw is independent of the first two: ' + N('1/6'))
b('Ex 13.1 Q9: mother, father and son line up at random. E: son at one end; F: father in the middle. Find P(E|F).', 'With father in the middle the son is always at an end: ' + N('1'))
b('Ex 13.1 Q10(a),(b): black and red dice. (a) P(sum > 9 | black die shows 5) (b) P(sum = 8 | red die shows a number < 4).', '(a) ' + N('1/3') + ' (red = 5 or 6). (b) Red ∈ {1, 2, 3} gives 18 outcomes; sum 8 needs (black, red) = (6, 2) or (5, 3): ' + N('2/18 = 1/9'))
b('Ex 13.1 Q11: a die is rolled. E = {1, 3, 5}, F = {2, 3}, G = {2, 3, 4, 5}. Find (i) P(E|F), P(F|E) (ii) P(E|G), P(G|E) (iii) P((E ∪ F)|G), P((E ∩ F)|G).', '(i) ' + N('1/2, 1/3') + '. (ii) E ∩ G = {3, 5}: ' + N('1/2') + ' and ' + N('2/3') + '. (iii) E ∪ F = {1, 2, 3, 5}, ∩ G = {2, 3, 5}: ' + N('3/4') + '; E ∩ F = {3}: ' + N('1/4'))
b('Ex 13.1 Q12: each child is equally likely a boy or a girl. A family has two children. P(both girls) given (i) the youngest is a girl (ii) at least one is a girl.', '(i) ' + N('1/2') + '. (ii) {GG, GB, BG} → ' + N('1/3'))
b('Ex 13.1 Q13: a bank has 300 true/false, 200 difficult true/false, 500 easy MCQs and 400 difficult MCQs. P(easy | it is an MCQ)?', 'MCQs total 900, easy MCQs 500: ' + N(f(Fr(500, 900))))
b('Ex 13.1 Q14: two dice are thrown and the numbers are different. Find P(sum is 4).', '30 outcomes with different numbers; sum 4: (1, 3), (3, 1): ' + N(f(Fr(2, 30))))
b('Ex 13.1 Q15: throw a die; if a multiple of 3 comes up, throw again; otherwise toss a coin. P(the coin shows a tail | at least one die shows 3).', 'The coin is only tossed when the first throw is not a multiple of 3 (no 3 has appeared then), so “at least one die shows 3” and “coin shows tail” cannot happen together: ' + N('0'))
b('Ex 13.1 Q16: if P(A) = ½ and P(B) = 0, then P(A|B) is (A) 0 (B) ½ (C) not defined (D) 1', 'Conditioning on an event of probability 0 is undefined: ' + E('(C) not defined'))
b('Ex 13.1 Q17: if P(A|B) = P(B|A), then (A) A ⊂ B but A ≠ B (B) A = B (C) A ∩ B = ∅ (D) P(A) = P(B)', 'P(A ∩ B)/P(B) = P(A ∩ B)/P(A) ⇒ P(A) = P(B) (when P(A ∩ B) ≠ 0): ' + E('(D)'))

# ---------------------------------------------------------------- 13.3 Multiplication, 13.4 Independence
d.sec('13.3-multiplication-theorem')
b('Multiplication theorem of probability.', T('P(E ∩ F) = P(E) P(F|E) = P(F) P(E|F)') + ' (P(E), P(F) ≠ 0). For three events: P(E ∩ F ∩ G) = P(E) P(F|E) P(G|E ∩ F)')
b('Example 8: an urn has 10 black and 5 white balls. Two balls are drawn without replacement. P(both black)?', 'P(E) = 10/15, P(F|E) = 9/14: ' + N(f(Fr(10, 15) * Fr(9, 14))) + ' = 3/7')
b('Example 9: three cards are drawn successively without replacement from a pack. P(first two kings and third an ace)?', '(4/52)(3/51)(4/50) = ' + N(f(Fr(4, 52) * Fr(3, 51) * Fr(4, 50))))
b('Drawing with vs without replacement.', T('With replacement') + ': draws are independent (same probabilities each time). ' + T('Without replacement') + ': the sample space shrinks, so use conditional probabilities (or combinations)')
d.sec('13.4-independent-events')
sm.independence_area(d)
b('Definition of independent events.', 'E and F are independent if ' + T('P(E ∩ F) = P(E) P(F)') + '. Equivalent (for P(F) ≠ 0): P(E|F) = P(E); (for P(E) ≠ 0): P(F|E) = P(F)')
b('Independent vs mutually exclusive.', X('Different ideas') + ': mutually exclusive means E ∩ F = ∅ (so P(E ∩ F) = 0). Two exclusive events with positive probabilities can never be independent (0 ≠ P(E)P(F))')
b('If E and F are independent, which other pairs are independent?', T('E′ and F') + ', ' + T('E and F′') + ', ' + T('E′ and F′') + ' (Example 13)')
b('Example 14: A, B independent. P(at least one occurs) = ?', T('1 − P(A′)P(B′)') + ' = 1 − (1 − P(A))(1 − P(B))')
b('Independence of three events (pairwise vs mutual).', 'A, B, C are mutually independent if P(A ∩ B ∩ C) = P(A)P(B)P(C) AND every pair is independent. Pairwise independence alone is not enough')
b('Example 10: die thrown. E: multiple of 3; F: even. Independent?', 'P(E) = 2/6 = 1/3, P(F) = 1/2, P(E ∩ F) = P({6}) = 1/6 = (1/3)(1/2): ' + E('independent'))
d.sec('13.4-exercise-13-2')
b('Ex 13.2 Q1: A and B independent, P(A) = 3/5, P(B) = 1/5. Find P(A ∩ B).', f(Fr(3, 5) * Fr(1, 5)) + ' → ' + N('3/25'))
b('Ex 13.2 Q2: two cards are drawn without replacement from a pack of 52. P(both black)?', '(26/52)(25/51) = ' + N(f(Fr(26, 52) * Fr(25, 51))))
b('Ex 13.2 Q3: three oranges are drawn without replacement from a box of 15 with 12 good and 3 bad. P(box approved) = P(all three good)?', '(12/15)(11/14)(10/13) = C(12, 3)/C(15, 3) = ' + N(f(Fr(comb(12, 3), comb(15, 3)))))
b('Ex 13.2 Q4: a fair coin and an unbiased die are tossed. A: head; B: 3 on the die. Independent?', 'P(A ∩ B) = 1/12 = (1/2)(1/6): ' + E('independent'))
b('Ex 13.2 Q5: a die has faces 1, 2, 3 red and 4, 5, 6 green. A: even number; B: red. Independent?', 'P(A) = 1/2, P(B) = 1/2, P(A ∩ B) = P({2}) = 1/6 ≠ 1/4: ' + X('not independent'))
b('Ex 13.2 Q6: P(E) = 3/5, P(F) = 3/10, P(E ∩ F) = 1/5. Independent?', 'P(E)P(F) = 9/50 ≠ 1/5 = 10/50: ' + X('not independent'))
b('Ex 13.2 Q7: P(A) = ½, P(A ∪ B) = 3/5, P(B) = p. Find p if (i) A, B mutually exclusive (ii) independent.', '(i) 3/5 = 1/2 + p: ' + N('p = 1/10') + '. (ii) 3/5 = 1/2 + p − p/2 = 1/2 + p/2: ' + N('p = 1/5'))
b('Ex 13.2 Q8: A and B independent, P(A) = 0.3, P(B) = 0.4. Find (i) P(A ∩ B) (ii) P(A ∪ B) (iii) P(A|B) (iv) P(B|A).', '(i) ' + N('0.12') + ' (ii) 0.3 + 0.4 − 0.12 = ' + N('0.58') + ' (iii) P(A) = ' + N('0.3') + ' (iv) P(B) = ' + N('0.4'))
b('Ex 13.2 Q9: P(A) = ¼, P(B) = ½, P(A ∩ B) = 1/8. Find P(not A and not B).', 'P(A ∪ B) = 1/4 + 1/2 − 1/8 = 5/8; P(A′ ∩ B′) = 1 − 5/8 = ' + N('3/8'))
b('Ex 13.2 Q10: P(A) = ½, P(B) = 7/12, P(not A or not B) = ¼. Independent?', 'P(A′ ∪ B′) = 1 − P(A ∩ B) would give P(A ∩ B) = 3/4, larger than P(A) = ½, so the data as printed are inconsistent. With the intended “neither” reading P(A′ ∩ B′) = 1/4: P(A ∪ B) = 3/4, P(A ∩ B) = ½ + 7/12 − 3/4 = 1/3 ≠ P(A)P(B) = 7/24. Either way the key’s answer is ' + X('not independent'))
b('Ex 13.2 Q11: A, B independent with P(A) = 0.3, P(B) = 0.6. Find (i) P(A and B) (ii) P(A and not B) (iii) P(A or B) (iv) P(neither A nor B).', '(i) ' + N('0.18') + ' (ii) 0.3 × 0.4 = ' + N('0.12') + ' (iii) 0.3 + 0.6 − 0.18 = ' + N('0.72') + ' (iv) 0.7 × 0.4 = ' + N('0.28'))
b('Ex 13.2 Q12: a die is tossed thrice. P(at least one odd number)?', '1 − (1/2)³ = ' + N('7/8'))
b('Ex 13.2 Q13: two balls drawn with replacement from 10 black and 8 red. Find P (i) both red (ii) first black, second red (iii) one black, one red.', '(i) (8/18)² = ' + N('16/81') + ' (ii) (10/18)(8/18) = ' + N('20/81') + ' (iii) 2 × 20/81 = ' + N('40/81'))
b('Ex 13.2 Q14: A and B solve a problem independently with probabilities ½ and ⅓. Find P (i) solved (ii) exactly one solves.', '(i) 1 − (1/2)(2/3) = ' + N('2/3') + '. (ii) (1/2)(2/3) + (1/2)(1/3) = ' + N('1/2'))
b('Ex 13.2 Q15: one card from a deck. In which cases are E and F independent? (i) spade / ace (ii) black / king (iii) king or queen / queen or jack', '(i) 13/52 · 4/52 = 1/52 = P(ace of spades) ✓ independent. (ii) 26/52 · 4/52 = 1/26 = 2/52 ✓ independent. (iii) 8/52 · 8/52 = 1/169 ≠ 4/52: ' + E('(i) and (ii) are independent; (iii) is not'))
b('Ex 13.2 Q16: in a hostel 60% read Hindi, 40% read English, 20% read both. Find (a) P(neither) (b) P(English | Hindi) (c) P(Hindi | English).', '(a) 1 − (0.6 + 0.4 − 0.2) = ' + N('1/5') + '. (b) 0.2/0.6 = ' + N('1/3') + '. (c) 0.2/0.4 = ' + N('1/2'))
b('Ex 13.2 Q17: P(even prime on each die when a pair of dice is rolled) is (A) 0 (B) 1/3 (C) 1/12 (D) 1/36', 'The only even prime is 2: (1/6)(1/6) = ' + E('(D) 1/36'))
b('Ex 13.2 Q18: two events A and B are independent if (A) mutually exclusive (B) P(A′B′) = [1 − P(A)][1 − P(B)] (C) P(A) = P(B) (D) P(A) + P(B) = 1', 'Independence of A and B is equivalent to that of A′ and B′: ' + E('(B)'))

# ---------------------------------------------------------------- 13.5 Bayes
d.sec('13.5-total-probability-and-bayes')
b('Partition of a sample space: definition.', 'Events E₁, ..., Eₙ form a partition if ' + T('Eᵢ ∩ Eⱼ = ∅ (i ≠ j)') + ', each P(Eᵢ) > 0, and ' + T('E₁ ∪ ... ∪ Eₙ = S') + ' (they cover S with no overlap)')
b('Theorem of total probability.', T('P(A) = Σ P(Eᵢ) P(A|Eᵢ)') + ' for a partition {E₁, ..., Eₙ}: the probability of A is the weighted average over the “causes”')
b('Bayes’ theorem.', T('P(Eᵢ|A) = P(Eᵢ) P(A|Eᵢ) / Σⱼ P(Eⱼ) P(A|Eⱼ)') + '. It reverses the conditioning: from P(A|Eⱼ) (effect given cause) to P(Eᵢ|A) (cause given effect)')
b('How to set up a Bayes problem (4 steps).', '1) Name the causes E₁, ..., Eₙ and the observed event A. 2) Write the priors P(Eᵢ). 3) Write the likelihoods P(A|Eᵢ). 4) Compute the total P(A) and then P(Eᵢ|A) = prior × likelihood ÷ total')
sm.total_probability_tree(d)
sm.bayes_frequencies(d)
b('Trap: confusing P(A|B) with P(B|A) (the prosecutor’s fallacy).', 'A test being 99% accurate does not mean a positive result is 99% likely to be right: ' + T('P(disease | +) ≠ P(+ | disease)') + '. The base rate (prior) matters')
d.sec('13.5-exercise-13-3')
b('Ex 13.3 Q1: an urn has 5 red and 5 black balls. A ball is drawn, its colour noted and returned with 2 more balls of the same colour, then a second ball is drawn. P(second is red)?', 'P = (1/2)(7/12) + (1/2)(5/12) = ' + N(f(Fr(1, 2) * Fr(7, 12) + Fr(1, 2) * Fr(5, 12))))
b('Ex 13.3 Q2: bag I has 4 red, 4 black; bag II has 2 red, 6 black. A bag is chosen at random and a red ball is drawn. P(it came from bag I)?', '(1/2 · 1/2)/(1/2 · 1/2 + 1/2 · 1/4) = (1/4)/(3/8) = ' + N(f(Fr(1, 4) / Fr(3, 8))))
pr = Fr(6, 10) * Fr(3, 10) / (Fr(6, 10) * Fr(3, 10) + Fr(4, 10) * Fr(2, 10))
b('Ex 13.3 Q3: 60% of students are hostlers, 40% day scholars. 30% of hostlers and 20% of day scholars get grade A. A random student has grade A. P(hostler)?', '0.6 × 0.3 = 0.18 and 0.4 × 0.2 = 0.08: 0.18/(0.18 + 0.08) = ' + N(f(pr)))
pk = Fr(3, 4) / (Fr(3, 4) + Fr(1, 4) * Fr(1, 4))
b('Ex 13.3 Q4: P(student knows the answer) = 3/4, guesses with probability 1/4; a guess is correct with probability 1/4. P(knows | correct)?', '(3/4)/(3/4 + 1/4 · 1/4) = ' + N(f(pk)))
pd = Fr(99, 100) * Fr(1, 1000) / (Fr(99, 100) * Fr(1, 1000) + Fr(5, 1000) * Fr(999, 1000))
b('Ex 13.3 Q5: a test detects the disease with probability 0.99 but has a 0.5% false positive rate; 0.1% of people have the disease. P(disease | positive)?', N(f(pd)) + ' ≈ 0.165 (see the frequency picture)')
pt = Fr(1, 3) / (Fr(1, 3) * (1 + Fr(3, 4) + Fr(1, 2)))
b('Ex 13.3 Q6: three coins: two-headed, 75%-heads biased, and fair. One is chosen at random and shows heads. P(it is the two-headed coin)?', '(1/3 · 1)/(1/3(1 + 3/4 + 1/2)) = 1/(9/4) = ' + N(f(pt)))
ps = 2000 * Fr(1, 100) / (2000 * Fr(1, 100) + 4000 * Fr(3, 100) + 6000 * Fr(15, 100))
b('Ex 13.3 Q7: 2000 scooter, 4000 car and 6000 truck drivers are insured; accident probabilities 0.01, 0.03, 0.15. An insured person has an accident. P(scooter driver)?', '(2000 × 0.01)/(20 + 120 + 900) = ' + N(f(ps)))
pm = Fr(4, 10) * Fr(1, 100) / (Fr(6, 10) * Fr(2, 100) + Fr(4, 10) * Fr(1, 100))
b('Ex 13.3 Q8: machine A makes 60% of the items (2% defective), B makes 40% (1% defective). A defective item is chosen. P(it came from B)?', '0.004/(0.012 + 0.004) = ' + N(f(pm)))
pg = Fr(4, 10) * Fr(3, 10) / (Fr(6, 10) * Fr(7, 10) + Fr(4, 10) * Fr(3, 10))
b('Ex 13.3 Q9: two groups win a board election with probabilities 0.6 and 0.4. If the first wins, a new product is introduced with probability 0.7; if the second wins, 0.3. Given a new product was introduced, P(the second group introduced it)?', '0.4 × 0.3/(0.6 × 0.7 + 0.4 × 0.3) = 0.12/0.54 = ' + N(f(pg)))
pdie = Fr(2, 3) * Fr(1, 2) / (Fr(2, 3) * Fr(1, 2) + Fr(1, 3) * Fr(3, 8))
b('Ex 13.3 Q10: a girl throws a die. If she gets 5 or 6 she tosses a coin three times; if 1, 2, 3 or 4 she tosses it once. She gets exactly one head. P(she threw 1, 2, 3 or 4)?', 'P(1 head | coin once) = 1/2 and P(1 head | three tosses) = 3/8: (2/3 · 1/2)/(2/3 · 1/2 + 1/3 · 3/8) = ' + N(f(pdie)))
pa = Fr(5, 10) * Fr(1, 100) / (Fr(5, 10) * Fr(1, 100) + Fr(3, 10) * Fr(5, 100) + Fr(2, 10) * Fr(7, 100))
b('Ex 13.3 Q11: operators A (50% of the time), B (30%), C (20%) produce 1%, 5%, 7% defective items. A defective item is produced. P(it was produced by A)?', '0.005/(0.005 + 0.015 + 0.014) = ' + N(f(pa)))
pl = Fr(1, 4) * Fr(comb(12, 2)) / (Fr(1, 4) * comb(12, 2) + Fr(3, 4) * comb(13, 2))
b('Ex 13.3 Q12: a card from a pack of 52 is lost. Two cards drawn from the remaining are both diamonds. P(the lost card was a diamond)?', 'Lost diamond (1/4): remaining 12 diamonds: C(12, 2). Lost non-diamond (3/4): 13 diamonds: C(13, 2). ' + N(f(pl)))
b('Ex 13.3 Q13: A speaks the truth with probability 4/5. A coin is tossed and A reports a head. P(a head actually appeared) is (A) 4/5 (B) 1/2 (C) 1/5 (D) 2/5', '(1/2 · 4/5)/(1/2 · 4/5 + 1/2 · 1/5) = ' + E('(A) 4/5'))
b('Ex 13.3 Q14: if A ⊂ B and P(B) ≠ 0, which is correct? (A) P(A|B) = P(B)/P(A) (B) P(A|B) < P(A) (C) P(A|B) ≥ P(A) (D) none', 'A ∩ B = A, so P(A|B) = P(A)/P(B) ≥ P(A) since P(B) ≤ 1: ' + E('(C)'))

# ---------------------------------------------------------------- Miscellaneous
d.sec('13.6-miscellaneous')
b('Example 22: four boxes hold coloured balls (black counts 3 of 18, 2 of 8, 1 of 7, 4 of 13). A black ball is drawn from a random box. P(it came from box III)?', 'Bayes: (1/7)/(3/18 + 2/8 + 1/7 + 4/13) = ' + N(f(Fr(1, 7) / (Fr(3, 18) + Fr(2, 8) + Fr(1, 7) + Fr(4, 13)))) + ' (the four boxes each have prior 1/4, which cancels)')
b('Example 24: a machine set up correctly gives 90% acceptable items, incorrectly set gives 40%. It is correctly set up 80% of the time. After a set-up it produces 2 acceptable items. P(correct set-up)?', '0.8 × 0.9² / (0.8 × 0.9² + 0.2 × 0.4²) = 648/680 = ' + N('0.95'))
b('Misc Q1: A and B with P(A) ≠ 0. Find P(B|A) if (i) A ⊂ B (ii) A ∩ B = ∅.', '(i) P(A ∩ B) = P(A): ' + N('1') + '. (ii) P(A ∩ B) = 0: ' + N('0'))
b('Misc Q2: a couple has two children. (i) P(both males | at least one male) (ii) P(both females | the elder is female).', '(i) ' + N('1/3') + ' (ii) ' + N('1/2'))
b('Misc Q3: 5% of men and 0.25% of women have grey hair. A grey-haired person is chosen (equal numbers of men and women). P(male)?', '0.5 × 0.05/(0.5 × 0.05 + 0.5 × 0.0025) = 0.05/0.0525 = ' + N(f(Fr(5, 100) / Fr(525, 10000))))
p_at_most_6 = 1 - sum(comb(10, r) * Fr(9, 10) ** r * Fr(1, 10) ** (10 - r) for r in range(7, 11))
b('Misc Q4: 90% of people are right-handed. P(at most 6 of a random sample of 10 are right-handed)?', 'By the binomial law: ' + N('1 − Σ (r = 7 to 10) ¹⁰Cᵣ (0.9)ʳ (0.1)¹⁰⁻ʳ') + ' ≈ ' + N(f'{float(p_at_most_6):.4f}'))
b('Misc Q5: a leap year is selected at random. P(it has 53 Tuesdays)?', 'A leap year has 52 weeks plus 2 extra days; the pair (extra days) is one of 7 equally likely pairs and Tuesday appears in 2 of them: ' + N('2/7'))
b('Misc Q6: boxes A (1 red, 6 white, 3 black), B (6, 2, 2), C (8, 1, 1), D (0, 6, 4). A box is chosen at random and a red marble is drawn. P(box A), P(box B), P(box C)?', 'Red counts 1, 6, 8, 0 out of 10 each; total 15 red-weights: ' + N('1/15, 2/5, 8/15') + ' (box D has no red marble)')
b('Misc Q7: heart-attack chance 40%; meditation and yoga reduce it by 30%, a drug by 25%. A patient chooses either at random and has an attack. P(he followed meditation and yoga)?', 'Attack probabilities 0.4 × 0.7 = 0.28 (meditation) and 0.4 × 0.75 = 0.30 (drug): 0.28/(0.28 + 0.30) = ' + N('14/29'))
b('Misc Q8: each entry of a 2 × 2 determinant is 0 or 1 with probability ½ each. P(the determinant is positive)?', 'ad − bc > 0 needs ad = 1, bc = 0: (1/4)(3/4) = ' + N('3/16'))
b('Misc Q9: P(A fails) = 0.2, P(B fails alone) = 0.15, P(A and B fail) = 0.15. Find (i) P(A fails | B has failed) (ii) P(A fails alone).', 'P(B fails) = 0.15 + 0.15 = 0.30. (i) 0.15/0.30 = ' + N('0.5') + '. (ii) 0.2 − 0.15 = ' + N('0.05'))
pl10 = Fr(4, 7) * Fr(4, 10) / (Fr(4, 7) * Fr(4, 10) + Fr(3, 7) * Fr(5, 10))
b('Misc Q10: bag I has 3 red and 4 black balls; bag II has 4 red and 5 black. A ball is moved from I to II, then a ball is drawn from II and it is red. P(the transferred ball was black)?', 'Transfer black (4/7): bag II has 4 red of 10; transfer red (3/7): 5 red of 10. (4/7 · 4/10)/(4/7 · 4/10 + 3/7 · 5/10) = ' + N(f(pl10)))
b('Misc Q11: if P(A) ≠ 0 and P(B|A) = 1, then (A) A ⊂ B (B) B ⊂ A (C) B = ∅ (D) A = ∅', 'P(A ∩ B) = P(A): all of A lies in B. ' + E('(A)'))
b('Misc Q12: if P(A|B) > P(A), then (A) P(B|A) < P(B) (B) P(A ∩ B) < P(A)P(B) (C) P(B|A) > P(B) (D) P(B|A) = P(B)', 'P(A ∩ B) > P(A)P(B), so P(B|A) = P(A ∩ B)/P(A) > P(B): ' + E('(C)'))
b('Misc Q13: if P(A) + P(B) − P(A ∩ B) = P(A), then (A) P(B|A) = 1 (B) P(A|B) = 1 (C) P(B|A) = 0 (D) P(A|B) = 0', 'P(A ∪ B) = P(A) forces P(B) = P(A ∩ B): ' + E('(B) P(A|B) = 1'))

# ---------------------------------------------------------------- Exam patterns
d.sec('13.z-exam-patterns')
b('Addition rule and its conditional form.', T('P(A ∪ B) = P(A) + P(B) − P(A ∩ B)') + '; for independent events P(A ∪ B) = 1 − P(A′)P(B′)')
b('“At least one” problems.', 'Use the complement: ' + T('P(at least one) = 1 − P(none)') + '. For n independent trials with success p: 1 − (1 − p)ⁿ')
b('Probability of exactly r successes in n independent trials (preview of the binomial law).', T('ⁿCᵣ pʳ (1 − p)ⁿ⁻ʳ') + '. Example: exactly 2 heads in 3 tosses = 3 × (1/2)³ = 3/8')
b('Odds and probability.', 'If the odds in favour of A are a : b then ' + T('P(A) = a/(a + b)') + '. Odds against: b : a')
b('A and B throw a die alternately; the first to get a 6 wins. A starts. P(A wins)?', 'P = 1/6 + (5/6)²(1/6) + ... = (1/6)/(1 − 25/36) = ' + N('6/11') + ' (Example 23 type)')
b('Given P(A) = 0.5, P(B) = 0.3, P(A ∪ B) = 0.65. Are A and B independent?', 'P(A ∩ B) = 0.5 + 0.3 − 0.65 = 0.15 = 0.5 × 0.3: ' + E('independent'))
b('If P(A) = 0.4, P(B) = 0.5 and A, B mutually exclusive, find P(A|B) and P(A ∪ B).', 'P(A|B) = ' + N('0') + ' and P(A ∪ B) = ' + N('0.9'))
b('Two dice: P(sum is 7 | at least one die shows 6)?', 'Outcomes with a 6: 11; those with sum 7: (1,6), (6,1): ' + N('2/11'))
b('A bag has 3 red and 2 blue balls. Two balls are drawn without replacement. P(second is blue | first is red)?', 'After a red is removed: 2 red, 2 blue: ' + N('2/4 = 1/2'))
b('Bayes with two urns: which urn is more likely if a white ball is drawn?', 'Compare the numerators P(urn) × P(white | urn); with equal priors the urn with the larger proportion of white balls is more likely. Divide by the total to get exact probabilities')

# ---------------------------------------------------------------- How it is asked
d.sec('13.z-how-its-asked')
b('MCQ: if P(A) = 0.6, P(B) = 0.5 and P(A ∩ B) = 0.3 then P(A|B) =<br>(a) 0.5 (b) 0.6 (c) 0.3 (d) 0.4', '0.3/0.5 = ' + E('(b) 0.6'))
b('MCQ: two independent events A, B with P(A) = 0.4, P(B) = 0.5 give P(A ∪ B) =<br>(a) 0.9 (b) 0.7 (c) 0.2 (d) 0.5', '0.4 + 0.5 − 0.2 = ' + E('(b) 0.7'))
b('MCQ: a card drawn from a pack; P(king | face card) =<br>(a) 1/3 (b) 4/13 (c) 1/13 (d) 1/12', 'Face cards 12, kings 4: ' + E('(a) 1/3'))
b('MCQ: two dice are thrown. P(sum 8 | doublet) =<br>(a) 1/6 (b) 1/36 (c) 1/12 (d) 1/3', 'Doublets: 6 outcomes; sum 8: (4, 4): ' + E('(a) 1/6'))
b('MCQ: in Bayes’ theorem, the sum of the denominators over all hypotheses equals<br>(a) P(A) (b) 1 (c) P(E) (d) 0', 'Σ P(Eⱼ)P(A|Eⱼ) is the total probability: ' + E('(a) P(A)'))
b('MCQ: A and B are mutually exclusive with P(A), P(B) > 0. Then A and B are<br>(a) independent (b) not independent (c) equal (d) complementary', 'P(A ∩ B) = 0 ≠ P(A)P(B): ' + E('(b)'))
b('MCQ: P(A′|B) =<br>(a) 1 − P(A|B) (b) P(A|B′) (c) 1 − P(A′|B) (d) P(A′)', E('(a)'))
b('MCQ: a fair die is rolled twice. P(second is 6 | first is 6) =<br>(a) 1/6 (b) 1/36 (c) 1 (d) 1/2', 'independent throws: ' + E('(a) 1/6'))
b('MCQ: P(E) = 0.3, P(F) = 0.4, E, F independent. P(E ∩ F′) =<br>(a) 0.18 (b) 0.12 (c) 0.7 (d) 0.42', '0.3 × 0.6 = ' + E('(a) 0.18'))
b('MCQ: three coins are tossed; P(3 heads | at least 2 heads) =<br>(a) 1/4 (b) 1/8 (c) 1/3 (d) 1/2', 'At least 2 heads: 4 outcomes: ' + E('(a) 1/4'))
b('Integer answer (JEE Main): a bag has 4 white and 6 black balls. Two balls are drawn without replacement. If P(both white) = a/b in lowest terms, find a + b.', '(4/10)(3/9) = 2/15: a + b = ' + N('17'))
b('Integer answer: P(A) = 1/2, P(B) = 1/3, A and B independent. Then 12 P(A ∩ B) = ?', N('2') + ' (P(A ∩ B) = 1/6)')
b('Integer answer: a fair coin is tossed 3 times. If P(exactly two heads) = k/8, find k.', 'ⁿCᵣ: 3 outcomes: ' + N('3'))
b('Assertion–Reason.<br><b>A:</b> P(A|B) + P(A′|B) = 1.<br><b>R:</b> conditional probabilities behave like ordinary probabilities on the reduced sample space.<br>(a) Both true, R explains A (b) Both true, R does not (c) A true, R false (d) A false, R true', E('(a)'))
b('Assertion–Reason.<br><b>A:</b> if A and B are mutually exclusive events with positive probabilities, they are independent.<br><b>R:</b> P(A ∩ B) = 0 for mutually exclusive events.<br>(a) Both true, R explains A (b) A false, R true (c) A true, R false (d) Both false', E('(b)') + ': P(A)P(B) > 0 = P(A ∩ B)')
b('True/False: P(A ∩ B) = P(A)P(B|A) always (P(A) ≠ 0).', E('True') + ' (multiplication rule)')
b('True/False: if P(A|B) = P(A) then P(B|A) = P(B) (P(A), P(B) > 0).', E('True') + ': both mean P(A ∩ B) = P(A)P(B)')
b('2-mark: if P(A) = 0.5 and P(B|A) = 0.4, find P(A ∩ B).', N('0.2'))
b('2-mark: two coins are tossed. P(both heads | at least one head)?', '{HH, HT, TH}: ' + N('1/3'))
b('3-mark: two cards are drawn without replacement from 52. P(both are aces)?', '(4/52)(3/51) = ' + N('1/221'))
b('3-mark: A can hit a target with probability 1/4, B with 1/3. Each fires once. P(target is hit)?', '1 − (3/4)(2/3) = ' + N('1/2'))
b('4-mark: a bag contains 4 white and 2 black balls; another has 3 white and 5 black. A bag is chosen at random and a ball drawn: it is white. P(it was from the first bag)?', '(1/2 · 4/6)/(1/2 · 4/6 + 1/2 · 3/8) = (1/3)/(1/3 + 3/16) = ' + N('16/25'))
b('4-mark: 40% of a factory’s bulbs come from plant P (5% defective) and 60% from plant Q (2% defective). A defective bulb is found. P(from P)?', '0.4 × 0.05/(0.4 × 0.05 + 0.6 × 0.02) = 0.02/0.032 = ' + N('5/8'))
b('Case-based: a rapid test has sensitivity 95% and false-positive rate 2%. In a population where 1% are infected, a person tests positive. What is the chance that they are infected?', '0.01 × 0.95/(0.01 × 0.95 + 0.99 × 0.02) = 0.0095/0.0293 = ' + N('95/293 ≈ 32.4%'))
b('Case-based: a student passes physics with probability 0.8 and maths with probability 0.7, independently. P(passes at least one)?', '1 − 0.2 × 0.3 = ' + N('0.94'))

print('cards', len(d.cards))
os.makedirs(OUT, exist_ok=True)
print('notes', d.write(os.path.join(OUT, 'deck.json')))
